### ISSUE TITLE
Ability to install curseforge resource packs like you can with curseforge mods

### ISSUE THREAD

**Issue by sylvesterroos** [gorilla-devs/GDLauncher#1001]
**Describe the solution you'd like**
Search curseforge for resourcepacks the same way like you can search it for mods.

**Describe alternatives you've considered**
Manually downloading resource packs from curseforge

**Comment by TheMarksmanXII** [comment]
Duplicate of Issue #827

**Comment by Eskaan** [comment]
Duplicate of #705
