### ISSUE TITLE
Add jarmods and coremods support

### ISSUE THREAD

**Issue by IceColdTray** [gorilla-devs/GDLauncher#1010]
**Is your feature request related to a problem? Please describe.**
Cannot install OptiFine without needing Forge/Fabric [OptiFabric] so we could add it to Minecraft.jar

**Describe the solution you'd like**
Like MultiMC and ATLauncher, add support for coremods and jarmods (like OptiFine, this way, you could install OptiFIne without needing Forge/Fabric.). You could also add a button for it like the other launchers have (images below).

**Describe alternatives you've considered**
N/A

**Additional context**
MultiMC: 
![image](https://user-images.githubusercontent.com/87967287/127317110-d3559ed9-bbaf-41c0-9aaf-d3e2e946ab0b.png)
ATLauncher:
![image](https://user-images.githubusercontent.com/87967287/127317137-24f46061-1260-4a62-8f12-29f4e4041474.png)

**Comment by Eskaan** [comment]
Duplicate of #616
