### ISSUE TITLE
GDlauncher crashing on start

### ISSUE THREAD

**Issue by jinkhya** [gorilla-devs/GDLauncher#1011]
**Describe the bug**
Hello, I'm having an issue with GDLauncher crashing on launch.
Here's my console log : 
https://gist.github.com/jinkhya/53114834ee7b0584e70dbb053668b04c

I dunno how relevant this is but here's what I did this morning before it wouldn't let me start it
- open GDLauncher
- Download a new pack (pack was Chroma technology 2)
- I didn't keep my eyes on it at all times, but I saw it was near done and next time I checked if the download was finished I noticed GDlauncher was closed and that I couldn't start it anymore.

This happened to me another time a couple of days ago, and restarting the pc fixes it.

**Expected behavior**
To not crash at launch

**Operating System:**
 - OS: Manjaro
 - Version 21.0.6 kernel 5.11.22-2

**Comment by jinkhya** [comment]
Actually it looks like this time restarting the pc doesn't fix this.

**Comment by jinkhya** [comment]
Removing Chroma technology 2 folder from instances let me start GD. Looks like it doesn't like this modpack.

**Comment by jinkhya** [comment]
I tried redownloading the pack, and that still generates a crash when it's done. This might be a good way for you to reproduce and find a fix. :)

**Comment by Eskaan** [comment]
Can you provide us whit some info about the modpack? (Version, Forge/Fabric)

**Comment by Eskaan** [comment]
Also Manjaro is A MacOS version? (or Linux?)

**Comment by huantianad** [comment]
@Code-Ac Manjaro is a Linux distribution based on Arch Linux, I can attempt to reproduce this when I get back to my main pc.
@jinkhya have you tried the AUR version of the package as opposed to the appimage?

**Comment by jinkhya** [comment]
It is Linux indeed, and the modpack is using forge. (all the other 1.16.5 packs I play seem to be fine and I have quite a few installed).

I did try the AUR version and it crashes too. https://gist.github.com/jinkhya/d1e1f70664f5933eaaa18fd353cde613

**Comment by huantianad** [comment]
Just to make sure, which gdlauncher aur package did you try?
The error seems to be due to the inotify watch limit being exceeded.
Edit 2: Perhaps see #617, and try raising your itnofiy watch limit - note [this](https://askubuntu.com/a/1088794) answer on the stackoverflow page linked (the arch linux command should work). I would also note your current limit just in case you need to go back.

It would be nice if this error was better handled by GDLauncher.

**Comment by jinkhya** [comment]
Thanks a lot raising the itnofiy fixed it ! 
And the package I tried was this one : https://aur.archlinux.org/packages/gdlauncher/

**Comment by hypherionmc** [comment]
Closing this as resolved. Feel free to comment if this is still an issue
