### ISSUE TITLE
'/' in mod pack page names prevent packs from installing

### ISSUE THREAD

**Issue by kreezxil** [gorilla-devs/GDLauncher#1015]
![image](https://user-images.githubusercontent.com/3880072/127919841-a09c480c-a54e-446e-8cb2-0108a622fbe0.png)
The slash in the title of this packs name causes it to not install, when I downloaded the zip directly, gdl had no problem installing the pack.

https://www.curseforge.com/minecraft/modpacks/better-minecraft-fabric

gdl 1.1.11

problem happens on windows and linux

**Comment by kreezxil** [comment]
For posterity I messaged the mod author of the pack 
![image](https://user-images.githubusercontent.com/3880072/127920302-256c389f-b755-4abb-aa43-a4925457c4d2.png)

**Comment by urmet** [comment]
nothing to do with that slash, look at #961 
will be fixed next release

**Comment by Eskaan** [comment]
Duplicate of #943, #961 - fixed whit #980.

**Comment by hypherionmc** [comment]
Fixed in release 1.1.12+
