### ISSUE TITLE
Can't add mods on fabric instances.

### ISSUE THREAD

**Issue by lazynessmind** [gorilla-devs/GDLauncher#1021]
**Describe the bug**
When trying to add mods to an Fabric Instance, the page says that "No mods has been found with the current filters"

**To Reproduce**
1. Right Click a Fabric instance
2. Click on Manage
3. Goto mods
4. Add Mod

**Expected behavior**
List of mods for fabric

**Possible solutions**
Remove the filter for fabric only mods, since curse forge doesn't let you filter for Fabric currently.

**Screenshots**
![image](https://user-images.githubusercontent.com/52864251/129443993-73ad95fc-9681-4ce9-adc8-e09766701fd4.png)
![image](https://user-images.githubusercontent.com/52864251/129444005-6e9e580f-b008-4702-a6c6-20d7d3adc700.png)

**Operating System:**
This doesn't matter rn

**Additional context**
hmm

**Comment by Ezzestus** [comment]
I am also having this issue. I believe it is related to this Issue in the console ```electron/js2c/renderer_init.js:13 (electron) The remote module is deprecated. Use https://github.com/electron/remote```

**Comment by AppleMangoOrange** [comment]
Same problem here, even updating mods currently in a fabric instance does not seem to work. The issue does not seem to be there for forge modpacks/instances.
EDIT: The not being able to update mods problem is only there for most mods, some update just fine.

**Comment by lazynessmind** [comment]
Currently we can't access the fabric filter in curse forge. I think that's the reason.

**Comment by Eskaan** [comment]
Yes, that’s the reason. The fix is on the way in #1022

**Comment by hypherionmc** [comment]
Fixed in release 1.1.12+
