### ISSUE TITLE
Modpacks crashing on startup and during world loading

### ISSUE THREAD

**Issue by Parkyy03** [gorilla-devs/GDLauncher#1029]
**Describe the bug**

**To Reproduce**
1. Go to the launcher
2. Load up a modpack
3. Wait for it to go through startup process
4. Crashes before startup completes

**Expected behavior**
I would expect the modpack to load completely fine without a crash.

**Possible solutions**
Identify the problem causing it through error files

**Screenshots**
![image](https://user-images.githubusercontent.com/50531851/129778929-8ae636ca-2f37-4e4e-94b7-831908168484.png)

**Operating System:**
 - OS: Windows
 - Version: 10

**Additional context**
Heres the error file that I was given after the crash, this was whilst trying to load All the mods 6 but it happens on every modpack.
[hs_err_pid8476.log](https://github.com/gorilla-devs/GDLauncher/files/7002163/hs_err_pid8476.log)

**Comment by GamerMine** [comment]
Hello,
It is an error from the Java Virtual Machine (JVM) so it's not caused by GDLauncher.
Are you using the Java shipped with GDLauncher ?

**Comment by Eskaan** [comment]
@Parkyy03 is this fixed whit the last release? Also the JVM complains about access problems. Did you mess whit the access settings? 😅

**Comment by Parkyy03** [comment]
@Code-Ac Sorry for the late reply, I’ve managed to fix the issue it seems. It was due to my msi motherboard having a hidden hardware overclock knob that was turned on one of the highest settings by default. After changing it to it being off, the issue was never seen again so it wasn’t you guys. Oh and to answer your question, no I hadn’t changed any settings within gdlauncher or any access settings.

**Comment by Eskaan** [comment]
Thanks for reporting and telling back :)
