### ISSUE TITLE
file error: C:\Users\[USER]\AppData\Roaming\gdlauncher_next\instances\MC  Eternal\config.json

### ISSUE THREAD

**Issue by Grimm8094** [gorilla-devs/GDLauncher#1031]
I'm attempting to download a modpack for Minecraft so I can play with a few of my friends, but I keep getting this error. I've tried multiple times to fix this on my own, but I simply cannot get it to work.

**To Reproduce**
I'm not sure how to reproduce this error, because I don't know what's wrong. All I know is that every time I attempt to install any sort of modpack through GD Launcher, I get this error, even if I uninstall the launcher and try again.

**Screenshots**
![Screenshot 2021-08-17 145448](https://user-images.githubusercontent.com/89103555/129791967-3fed293c-a035-4308-8f76-1b59e4aacdde.png)
Pasted code for easier viewing:
file error: C:\Users\[USER]\AppData\Roaming\gdlauncher_next\instances\MC  Eternal\config.json

**Operating System:**
 - Windows
 - 10

**Additional context**
I've already done a full wipe of my computer to see if any existing files were interfering with the installation, but it obviously didn't work. I've also gone through multiple forums online to see if any of them could help me solve this, but I found nothing.

**Comment by Ladvace** [comment]
this is a warning so it's not the reason of your problem, could you try sending all the console output here?

**Comment by Grimm8094** [comment]
> this is a warning so it's not the reason of your problem, could you try sending all the console output here?

Sure, though im not sure how much it'll help, this is all i got after a few minutes of waiting:

![Screenshot 2021-08-18 144653](https://user-images.githubusercontent.com/89103555/129962662-ebd23931-977f-4b99-8316-6fc047bafdf7.png)


Edit:
Okay so i tried it again today and actually got some errors this time if it helps:
![Screenshot 2021-08-19 135321](https://user-images.githubusercontent.com/89103555/130127752-570fe807-c622-4033-9ca3-c0d17879e5ce.png)
