### ISSUE TITLE
Can't Update GDLauncher on windows

### ISSUE THREAD

**Issue by CanBoy67** [gorilla-devs/GDLauncher#1050]
**Describe the bug**
GDLauncher has an update from 1.1.11, problem is I'm unable to update it. I click on both the little arrow pointing down in the top and I go to settings and click update, and it closes but never applies the update. I've even tried downloading the file from the download page to no avail it says that gdlauncher is running (when it's not) and a second later after clicking close another notification box pops up saying that gdlauncher can't be closed and needs to be closed manually. So I'm caught between a rock and a hard place.

**To Reproduce**
1. Click update button at top or under settings
2. Program closes but doesn't apply update

**Expected behavior**
GDLauncher closes thus applying the update with now issue

**Possible solutions**
idk

**Screenshots**
n/a

**Operating System:**
 - OS: Windows
 - Version 10

**Additional context**

**Comment by Eskaan** [comment]
Is the process still visible in the taskmanager after clicking update?
If yes, just kill it, it will reboot on its own after that.

**Comment by CanBoy67** [comment]
No, it's not visible on the task manager

**Comment by CanBoy67** [comment]
Managed to update it by uninstalling and reinstalling the new version
