### ISSUE TITLE
[Enhancement] Multi-connection Downloading

### ISSUE THREAD

**Issue by aaronliu0130** [gorilla-devs/GDLauncher#1051]
**Is your feature request related to a problem? Please describe.**
Download speeds may not always be fast enough, especially in the case of large modpacks.

**Describe the solution you'd like**
Download with multiple connections, splitting large targets into chunks, downloading multiple small files at once, like how `aria2c`'s `-x` option works. Also, add a setting to specify the number of concurrent downloads. I recommend it 

**Describe alternatives you've considered**
Using a mirror, but that is against the EULA and risky.

**Additional context**
No other context or screenshots about the feature request here.

**Comment by Eskaan** [comment]
We have a setting for concurrent downloads in Settings>General.
Downloading in chunks in not possible because the Curseforge API does not support that from my knowledge.
