### ISSUE TITLE
Search is bugged / non-optimal

### ISSUE THREAD

**Issue by AntonioNoack** [gorilla-devs/GDLauncher#1052]
**Describe the bug**
I was searching for "ftb infinity evolved skyblock", and "FTB Infinity Evolved Skyblock" was the 6th result. This happens in CurseForge as well. So could you add a post-processing sorting, if you just use their ordering?

**To Reproduce**
1. Add New Instance
2. Use Curseforge
3. Search for "ftb infinity evolved skyblock"

**Expected behavior**
"FTB Infinity Evolved Skyblock" is the 1st result

**Possible solutions**
Sort the entries queried from CurseForge yourself. In my case, an exact match (ignoring case) would be enough

**Screenshots**
![image](https://user-images.githubusercontent.com/20659579/130593257-bf334b37-8c10-4b36-8c9e-39d44a24942d.png)

**Operating System:**
 - OS: Windows
 - Version 10

**Additional context**
Nothing

**Comment by YoYoK3nny** [comment]
Overwolf already have something like this planned for a future update.
https://curseforge-ideas.overwolf.com/ideas/CF-I-14

In the mean time, just use fewer search terms.
e.g: `infinity`
`evolved`
`infinity evolved`

**Comment by Eskaan** [comment]
So, I don’t think Curseforges API is our fault - we can’t sort the searches because we only load about 10 at once to not overload the clients internet connection. Also we can’t require all possible results because The amount of results would be gargantous and the client would have to parse and compute this incredible amount of data.

**Comment by AntonioNoack** [comment]
Mmh, you could improve it. In my case, the best result was the 6th one, so it would have been good enough, to just sort the groups of 10s individually (in those 10, not changing the order of the previous ones).

But yes, maybe it's a rare case. Idk, I don't try that many new packs.
