### ISSUE TITLE
Can't install modpacks with very long instance names....

### ISSUE THREAD

**Issue by guvnor33** [gorilla-devs/GDLauncher#1058]
Trying to add new instance:

"**Roguelike Adventures and Dungeons TiC Edition**"

throws error:

"**Instance name is not valid or too long. Please try another one.**"

**Comment by Eskaan** [comment]
That’s not an issue, it’s just a flaw in the UI.

If you click on the instance name, you can start typing a new name for it. (The shown name is a placeholder, not actual text already in the input field)

**Comment by guvnor33** [comment]
Excellent, thank you, I typed a shorter name and now it's installing. :)

**Comment by Eskaan** [comment]
Duplicate of #912
