### ISSUE TITLE
Launcher crashes on launch on Arch Linux

### ISSUE THREAD

**Issue by huantianad** [gorilla-devs/GDLauncher#1069]
**Describe the bug**
There have been multiple reports of the launcher malfunctioning on Arch and Arch-based systems, where the launcher would crash on launch, only briefly showing a gray window, then crashing. Opening the launcher from command line doesn't seem to yield any useful errors.

**To Reproduce**
1. Install the launcher via the AUR packages gdlauncher, gdlauncher-bin, gdlauncher-beta, or gdlauncher-beta-bin, or from GitHub releases.
2. Launch the launcher either from command line or .desktop shortcut.
3. The launcher loads in a gray box, then crashes.

**Expected behavior**
The launcher launches normally into the main menu.

**Possible solutions**
The launcher was previously working fine; however, many people started to get this problem around the same time, so this could be due to a package/dependency change  from upstream arch packages.

**Screenshots**

**Operating System:**
- OS: Arch Linux and other Arch-based distributions
- Version: Latest? ~~this is a rolling release distro~~
- Java Version: N/A
- Minecraft Version: N/A
- Mod Loader: N/A

**Additional context**
This could be due to the AUR package, but I think this happens on GitHub release as well.

**Comment by BettaGeorge** [comment]
Interestingly, it behaves differently for me. The stable version (1.14) launches, but then hangs at the loading screen forever, while the beta (1.15) works, but cannot install modpacks.
Have you tried the beta again? Maybe the most recent update fixes your issue.

**Comment by huantianad** [comment]
@BettaGeorge The loading thing could be due to a bug that I fixed in the 1.15 version. What is the error you're getting installing modpacks? This could be the forge installer issue, which should've fixed in the binary package, but may not in the compiled package if  your electron version is not latest.

**Comment by huantianad** [comment]
Closing this since it seems to be resolved,
