### ISSUE TITLE
Error on pressing button 'Open ressource pack folder'

### ISSUE THREAD

**Issue by SkyNalix** [gorilla-devs/GDLauncher#1070]
**Describe the bug**
Everytime when i try to open ressource packs folder from the in game ressource packs menu it show me this error (screenshot)
Translation: Windows cannot find '\D:\_gdl\instances\Hypixel SkyBlock\resourcepacks\'. Make sure you entered the correct name, then try again.
The folder exist, with several packs in

**To Reproduce**
1. In game, go to 'options' then 'Resource Packs...'
2. Click on 'Open ressource pack folder'
3. See error

**Expected behavior**
Open the ressource packs folder, but no the one in D:\_gdl but the folder in the User Data path setup in the settings
because the moment when you close your game, the D:\_gdl folder is deleted so you can't modify anything anymore

**Possible solutions**
Fix the path which is used to open ressource packs folder to the one set in the launcher settings

**Screenshots**
![image](https://user-images.githubusercontent.com/56894341/133001280-4090086b-8ab3-4f28-89fa-374677d5f08d.png)

**Operating System:**
- OS: Windows
- Version: 10 20H2
- Java Version: 8
- Minecraft Version: 1.8.9
- Mod Loader: Forge

**Comment by Eskaan** [comment]
Yes and no, I believe you that this folder exists, but GDL added a `\` to the path so it’s invalid.

**Comment by SkyNalix** [comment]
> Yes and no, I believe you that this folder exists, but GDL added a `\` to the path so it’s invalid.

Ok so that where the error is from
But it also open the wrong path
Imagine if someone want to change/update a pack, it open the one in _gdl
but he can't delete packs because they are in use, that why the player close his game
and _gdl folder it opened is automatically deleted...
it should open the folder in the path set in the settings

**Comment by RemagOfficial** [comment]
the reason it trys to open the folder it does is because Minecraft is trying to open the resource pack folder in the folder that Minecraft is running from this being the _gdl folder, there's not really a fix that the launcher can do because it's a Minecraft issue

**Comment by WolfBV** [comment]
Were you able to resolve your issue?

**Comment by Eskaan** [comment]
This is likely a duplicate of #991, closing.
