### ISSUE TITLE
[1.17.1] Stuck on "Downloading Forge Installer"

### ISSUE THREAD

**Issue by grannymc** [gorilla-devs/GDLauncher#1102]
Attempt to update Forge for 1.17.1 past 37.0.73 gets stuck on message "Downloading Forge Installer". Only exit is to kill GDLauncher and relaunch, then reinstall Forge 37.0.73 or older.

Windows 7, AMD A10-7890K, 16GB, 1050TI, HDD with plenty of empty space

ETA: This also fails when creating a new 1.17.1 instance with Forge > 37.0.73

**Comment by huantianad** [comment]
Possibly duplicate of #1086? Or could be caused by differences in forge installer JSON

**Comment by grannymc** [comment]
This may well be a duplicate of #1086 but that was installing a 1.12 modpack (PO3) for the first time, while this was updaing forge for 1.17 on a modpack already installed and running in 1.17. Some important differences there, so this should probably not be closed as a duplicate until someone definitively determines that it's not two different errors that happen to produce the same message.

**Comment by Eskaan** [comment]
> This may well be a duplicate of #1086 but that was installing a 1.12 modpack (PO3) for the first time, while this was updaing forge for 1.17 on a modpack already installed and running in 1.17. Some important differences there, so this should probably not be closed as a duplicate until someone definitively determines that it's not two different errors that happen to produce the same message.

The important difference is not that different since the issue is downloading the forge installer.
Could you please replay if the latest beta works for you?

**Comment by vomaufgang** [comment]
Having the same problem with Forge for 1.16.5, installing modpacks gets stuck at "Installing Forge 0%".

v1.1.15-beta.6 fixes the problem for me.

Can't speak for 1.17 though.

**Comment by elbim** [comment]
Same here for Forge 36.2.6/1.16.5 (tried updating ATM6 to version 1.8.5) and switching to beta 1.1.15-beta.6 fixes the problem for me.

**Comment by Dogvomit** [comment]
I am having the same issue after attempting to update "Enigmatica 6 E6 1 16 5" from version 0.5.11 to 0.5.14.

The update process started off ok until it gets to "Downloading forge installer... 0%" It doesn't get any farther and I have to close GDLauncher.
Now my instance is unplayable as all the mods were removed during the update process.

Installing a fresh instance of "Enigmatica 6 E6 1 16 5" version 0.5.11 works as it should.
Installing a fresh instance of "Enigmatica 6 E6 1 16 5" version 0.5.14 doesn't work.

Enigmatica 6 E6 1 16 5
  Pack v0.5.11 uses Forge-1.16.5-36.2.2  -- Forge download works.
  Pack v0.5.14 uses Forge-1.16.5-36.2.4  -- Forge download doesn't work.

**Comment by Janitor53** [comment]
Got the same error trying to update FTB OceanBlock modpack to the 1.3.0 version. Error in console may contain the origin of error:
![Imgur](https://i.imgur.com/d08z26m.png)
Edit: GDLauncher 1.1.15 beta 6 on Windows 11

**Comment by Eskaan** [comment]
Okay, because there is no feedback, I see this as a duplicate now. @grannymc Reopen it when it doesn’t work :)

**Comment by Eskaan** [comment]
Duplicate of #1086

**Comment by Janitor53** [comment]
But the bug is still present in the latest beta!

**Comment by Eskaan** [comment]
So please explain the bug you encountered :)
Latest Beta is v1.1.15.6, which version do you have?

**Comment by Janitor53** [comment]
Options - General said it is a v1.1.15-beta.6.
I have downloaded latest beta manually to make sure it is exact version. Main exe in archive was a different size than installed one. Looks like internal updater fails an update for some reason :(
After manual update all seems to be fine.
I am sorry for bothering you!

**Comment by Eskaan** [comment]
@Janitor53 on whichever Operating System are you? On some Linux distros and on MacOS the Autoupdater doesn’t work.

**Comment by huantianad** [comment]
They mentioned exe so it's probably windows

**Comment by Janitor53** [comment]
I'm on Windows 11.

**Comment by Eskaan** [comment]
Ah thanks. Was just curious because there are not many Mac users out there who use GDL 😅
*am basically alone out here*
