### ISSUE TITLE
Import/Export modpack option

### ISSUE THREAD

**Issue by Freddo3000** [gorilla-devs/GDLauncher#111]
**Is your feature request related to a problem? Please describe.**
Well, you can currently not create custom packs that can be easily imported from my knowledge, without relying on Curse.

**Describe the solution you'd like**
I'd like a solution similar to that of MultiMC, with export/import functionality, where you can paste a link to a server, E.G https://reconstructionera.duckdns.org/Reconstruction_Era.zip and install it that way.  
Preferably, this should also check if there is difference between the remote file and local one in order to get updates.  
These options could be hidden until you check some "developer" checkbox in settings.

**Describe alternatives you've considered**
The possibility to generate modpacks similar to those hosted on Curse, where they don't contain the .jar files, and this being able to be hosted on your own webserver.

**Additional context**
N/A

**Comment by CrankySupertoonArchive** [comment]
For Import just base it on MultiMC's code or[Frankcyi's CMPDL](https://github.com/Franckyi/CMPDL).
Its really well documented its not hard

For Exporting & You could even go as far into tweaking this code. https://github.com/NillerMedDild/ModpackUploadTool
