### ISSUE TITLE
Forge won´t let me istall

### ISSUE THREAD

**Issue by A009i8** [gorilla-devs/GDLauncher#1120]
hey 
i try many packs and i thinkmy pc or the launcher on the pc is broke.

asyncToGenerator.js:6 Uncaught (in promise) Error: certificate has expired
    at TLSSocket.onConnectSecure (_tls_wrap.js:1497)
    at TLSSocket.emit (events.js:315)
    at TLSSocket._finishInit (_tls_wrap.js:932)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:706)

this is in the console. 
can you help me pls

**Comment by Zetal911** [comment]
I'm having the same issue-- I switched to the Beta branch instead and it works now. Maybe it's an expired cert in the Stable branch or something?

**Comment by A009i8** [comment]
> I'm having the same issue-- I switched to the Beta branch instead and it works now. Maybe it's an expired cert in the Stable branch or something?

How do I switch to beta? And from what do I need to do this ?

**Comment by Zetal911** [comment]
> 
> 
> > I'm having the same issue-- I switched to the Beta branch instead and it works now. Maybe it's an expired cert in the Stable branch or something?
> 
> How do I switch to beta? And from what do I need to do this ?

You can do it in the GDLauncher settings, the gear in the topright. Then restart and click the little green update arrow.

**Comment by A009i8** [comment]
> > > I'm having the same issue-- I switched to the Beta branch instead and it works now. Maybe it's an expired cert in the Stable branch or something?
> > 
> > 
> > How do I switch to beta? And from what do I need to do this ?
> 
> You can do it in the GDLauncher settings, the gear in the topright. Then restart and click the little green update arrow.

Okey thanks I will try

**Comment by Eskaan** [comment]
Duplicate of #1086

**Comment by Eskaan** [comment]
There you will find all information you need
