### ISSUE TITLE
Forge v36.2.8 can not be found

### ISSUE THREAD

**Issue by StanleyMcClister** [gorilla-devs/GDLauncher#1126]
**Describe the bug**
FTB Oceanblock will not start an instance when clicked on. In the attached screenshot the circled uncaught happens each time FTB OceanBlock is clicked. 

**To Reproduce**
I created a new forge instance of 36.2.8 and the installer is stuck at 100%, maybe because the forge install links have changed. My instance of FTB OceanBlock is forge version 36.2.8 as well. That forge version folder doesn't exist on my system at the moment.

**Expected behavior**
A modded minecraft instance to launch. 

**Possible solutions**

**Screenshots**
![image](https://user-images.githubusercontent.com/67228240/138463710-7b3d8d87-b5fb-4006-abd4-66efe2f83a31.png

**Operating System:**
- OS: Windows
- Version: GDlauncher v1.1.14
- Java Version: I use the GDLauncher preset
- Minecraft Version: 1.16.5
- Mod Loader: Forge

**Comment by StanleyMcClister** [comment]
I am closing this out.  Switching to 15 beta-6 and creating a new forge instance of 36.2.8 corrected the issue.  
Thank you to Kreezxil in discord who suggested it to another user.

**Comment by Eskaan** [comment]
I love it if someone closes his issue on its own <3. Thanks

**Comment by kreezxil** [comment]
and he said why too. I love that even more.
