### ISSUE TITLE
Can't Install New Forge Instances

### ISSUE THREAD

**Issue by Divinos** [gorilla-devs/GDLauncher#1129]
Describe the bug
When installing a 1.16.5 forge instance it gets stuck on downloading forge installer at 0%

To Reproduce
1. Go to GDLauncher
2. Click on the plus sign
3. Create any 1.16.5 forge instance

Expected behavior
After creating instance it will download game files and then move onto downloading forge installer where it gets stuck on 0%.

Possible solutions
Restarting GDLauncher which did not work
Reinstalling GDLauncher which did not work
Getting a certificate because the console says it expired which I don't know how to do

Screenshots
![image](https://user-images.githubusercontent.com/88003008/138564715-138e496d-7794-4f37-905d-f955858cba6d.png)
![image](https://user-images.githubusercontent.com/88003008/138564924-9813ee53-1451-45e3-a229-4b3d370dea01.png)

Operating System:
- OS: Windows
- Version: 10
- Java Version: 8
- Minecraft Version: 1.16.5
- Mod Loader: Forge

Additional context
My already downloaded instances work fine, it just won't let me install new ones.

**Comment by Eskaan** [comment]
Duplicate of #1086

**Comment by Eskaan** [comment]
I start memorizing the issue number... @killpowa! Let me pin issues!
