### ISSUE TITLE
Fabric support

### ISSUE THREAD

**Issue by Freddo3000** [gorilla-devs/GDLauncher#113]
**Is your feature request related to a problem? Please describe.**
The launcher currently does not support installing [Fabric](http://fabric.asie.pl/use/).

**Describe the solution you'd like**
Add an option when creating an instance to install Fabric.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by CrankySupertoonArchive** [comment]
This is very similar to the Rift comment i made, but this is superior
