### ISSUE TITLE
when dowloading forge 1.17.1 the forge dowloader does not download 

### ISSUE THREAD

**Issue by Adam123654** [gorilla-devs/GDLauncher#1134]
**Describe the bug**
When I want to dowload forge 1.17.1 everything work fine but then the forge downloader stays at 0% I've waited some minutes and still nothing. How can I fix this
**To Reproduce**

**Expected behavior**

**Possible solutions**
Some ideas of how you would solve this issue, if possible

**Screenshots**

**Operating System:**
- OS: [e.g. Windows]
- Version: [e.g. 10]
- Java Version: [e.g. 8/16]
- Minecraft Version: [e.g. 1.16.5]
- Mod Loader: [e.g. Forge/Fabric]

**Additional context**

**Comment by Eskaan** [comment]
Duplicate of #1086
