### ISSUE TITLE
Option to configure allocated RAM

### ISSUE THREAD

**Issue by Freddo3000** [gorilla-devs/GDLauncher#114]
**Is your feature request related to a problem? Please describe.**
Launching modpacks such as All The Mods require a lot of RAM, more than the 4 GB that are currently allocated by default.

**Describe the solution you'd like**
Add an option to set maximum/minimum RAM and/or an option to the individual instance.  
This should probably be something to be able to edit in initial setup.

**Describe alternatives you've considered**
N/A

**Additional context**
There should be at the very least a field somewhere to configure launch parameters.

**Comment by blarfoon** [comment]
Closing as solved. Feel free to open this issue again if needed.
