### ISSUE TITLE
Curse packs search field is case-sensitive

### ISSUE THREAD

**Issue by Freddo3000** [gorilla-devs/GDLauncher#115]
**Describe the bug**
Searching for a Curse modpack, for example"Peace of Mind", if you enter "peace" it will not yield any results.

**To Reproduce**
1. Go to 'Curse Packs'
2. Search for "peace"
3. Notice there are no results
4. Search for "Peace"
5. Notice there are many results

**Expected behavior**
The search field not being case sensitive.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: v0.9.0

**Additional context**
N/A

**Comment by blarfoon** [comment]
So you're suggesting we should just convert everything to lower-case?

**Comment by Freddo3000** [comment]
Perhaps not display names, but the logic behind it.

**Comment by janagyjr** [comment]
This is still an issue in 0.12.3
http://prntscr.com/pnst4h
