### ISSUE TITLE
Log isn't created, leading to more errors

### ISSUE THREAD

**Issue by Lunar-Dawn** [gorilla-devs/GDLauncher#118]
**Describe the bug**
When launching the application whenever the `~/.config/GDLauncher/GDLauncher/` directory hasn't been created the application fails to open the `GDLauncher_logs.txt` file. This causes an error to show on screen, and any subsequent attempt to log data will throw more errors.

**To Reproduce**
1. Make sure the ~/.config/GDLauncher/GDLauncher directory *doesn't* exist
2. Launch the .AppImage

**Expected behavior**
The log file should be created and written to.

**Screenshots**
The first error:
![The initial error](https://user-images.githubusercontent.com/6073217/50689983-0cbf9b80-102c-11e9-8a47-b4cd052d8580.png)
One of the errors that follow:
![One instance of the following errors](https://user-images.githubusercontent.com/6073217/50690082-61631680-102c-11e9-98e2-74926617b181.png)

**Desktop (please complete the following information):**
 - OS: Debian Buster (x64)
 - Browser: Firefox
 - Version: v0.9.0

**Additional context**
This may be because [this](https://github.com/gorilla-devs/GDLauncher/blob/3879b124aaeb65a0dd84999588ca8d7b483fba1d/app/main.dev.js#L152) line successfully creates the file if it's missing but not the parent directory if it is.

**Comment by blarfoon** [comment]
Closing as solved. Feel free to open this issue again if this error comes back
