### ISSUE TITLE
Install dialog every time

### ISSUE THREAD

**Issue by Benrok** [gorilla-devs/GDLauncher#120]
**Describe the bug**
Every time the launcher is opened the "install" dialog appears on linux (Arch/Antergos atleast)
Pressing yes or no doesn't change this.
furthermore when pressing yes the shortcut doesn't seem to be created

**To Reproduce**
open launcher, press yes/no, repeat

**Expected behavior**
depending on the option chosen, an shortcut should be created, and the dialog should stop appearing

**Desktop (please complete the following information):**
 - OS: Linux (Arch/Antergos
 - Version 0.9.0

**Comment by blarfoon** [comment]
Might be fixed in #122 since I updated a lot of dependancies. Let me know if this is still an issue
