### ISSUE TITLE
GDlauncher will not go past the loading screen.

### ISSUE THREAD

**Issue by PrinceSousuke** [gorilla-devs/GDLauncher#1226]
Same error in 1.1.20 as 1.1.19. 

If you want to use the launcher, you have to use 1.1.18 or below, otherwise the console will say "Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'version_data')" and never let you in.  An option to disable the aggressive auto-update would really help combat issues like this. might as well keep this: https://github.com/gorilla-devs/GDLauncher/releases/tag/v1.1.18 in a text file so I can just paste it in to re-install the launcher every time I want to access the modpacks I'm playing.

**Comment by PrinceSousuke** [comment]
Console

![GDeadconsole](https://user-images.githubusercontent.com/69915077/147376489-366bc917-ad1b-41bf-9a3d-6ac86cbd4c87.png)

Display

![Gdeadloading](https://user-images.githubusercontent.com/69915077/147376494-7dc0636d-532a-4a85-bc12-3ae30fe8c8d1.png)

**Comment by bluebear94** [comment]
Why put a new issue here instead of commenting on #1224?

**Comment by Eskaan** [comment]
Duplicate of #1220
