### ISSUE TITLE
[Feature] Set Default Version Type for Latest Releases of Curse Projects

### ISSUE THREAD

**Issue by Zer0Lyfe** [gorilla-devs/GDLauncher#124]
**Is your feature request related to a problem? Please describe.**
When i press the install latest version you download the release version but I would like to download alpha and beta versions as the mod downloaded is normally outdated.

![2019-01-05 13_31_17-gdlauncher](https://user-images.githubusercontent.com/28994351/50720779-6092b900-10ee-11e9-8e5d-37bf9f2f6bf6.png)

This is the version that GD Launcher installs 
![image](https://user-images.githubusercontent.com/28994351/50720832-c9c6fc00-10ef-11e9-8a44-92b6cf7b6eab.png)

and this is the current version that jei up to date
![2019-01-05 13_35_10-gdlauncher](https://user-images.githubusercontent.com/28994351/50720789-c2ebb980-10ee-11e9-8792-c420367bd5b4.png)

**Describe the solution you'd like**
I would like to download alpha and beta versions. I would like an easier way of downloading them. It could be done the same way as curse where you have to select the preferred release or another way that you may like.

![image](https://user-images.githubusercontent.com/28994351/50720817-879dba80-10ef-11e9-8bbd-33d14df20b49.png)

**Describe alternatives you've considered**
I know that if you go into the explore menu of the mod it allows to download the latest but it is more tedious.

**Additional context**
If you need more infomation or need to me to word it better I can.

**Comment by ghost** [comment]
Is this fully done?
