### ISSUE TITLE
Modpack search results are inconsistent and change

### ISSUE THREAD

**Issue by Funwayguy** [gorilla-devs/GDLauncher#126]
**Description**

While using the search function on the "Curse Packs" tap, the results returned appear to be very inconsistent. Not only does it fail to find some packs at times but some results change when the query is run again without changing anything.

**To Reproduce**

1. Go to "Curse Packs" tab
2. Search for a known pack, ideally using a single word or part of a word
3. Using the enter key, rerun the search
4. Results may or may not change after every press of the enter key
5. Try changing the query text slightly (even so much as adding a trailing space character)
6. Run then rerun again observing any changes or notable differences
7. Change query back to the original text
8. Run and rerun again observing any changes from the first test

(May behave differently depending on length of query and target pack)

**Expected behavior**

The search results displayed should not only match the ones returned by the site (in addition to FTB's own packs) but also be repeatable should the search be rerun. The search terms used should also return predictable results regardless of whether the user used partial words, full words or mixed casing.

**Screenshots**

![yc2ua5l5xp](https://user-images.githubusercontent.com/6048596/50722012-8e8af400-1114-11e9-9aad-f899750cc8bf.gif)

**Desktop**
 - OS: Windows 10
 - Version: v0.9.1

**Comment by Freddo3000** [comment]
May tie into #115 a bit
