### ISSUE TITLE
Launching the instance does not launch the instance

### ISSUE THREAD

**Issue by johnstudent76** [gorilla-devs/GDLauncher#128]
https://pastebin.com/UyNmSK13

I have 8 GB allocated out of 16 on my system, and the Java path is correct, but this error shows up when I try launching an instance I downloaded

**Comment by blarfoon** [comment]
Looks like your ram amount is 'undefined', which is causing the instance to crash. Could you try going in the settings and changing the ram to like 10gb and tell me if that solves your issue?

**Comment by fightmesun** [comment]
I'm having this issue and I slide it to 16g and I still get the same issue


console.js:72 18:44:45.469 › Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

a @ console.js:72
n @ console.js:37
r @ log.js:25
(anonymous) @ instancesManager.js:186
emit @ events.js:194
addChunk @ _stream_readable.js:296
readableAddChunk @ _stream_readable.js:277
Readable.push @ _stream_readable.js:232
onStreamRead @ internal/stream_base_commons.js:165
console.js:72 18:44:45.482 › Invalid maximum heap size: -Xmx16384m
The specified size exceeds the maximum representable size.

**Comment by TOLoneWolf** [comment]
@fightmesun 
https://github.com/gorilla-devs/GDLauncher/wiki/FAQ-Frequently-Asked-Questions#could-not-create-the-java-virtual-machine
