### ISSUE TITLE
Option to display console in separate window

### ISSUE THREAD

**Issue by Freddo3000** [gorilla-devs/GDLauncher#129]
**Is your feature request related to a problem? Please describe.**
Being able to see the console while the game is running wouldn't be too bad.

**Describe the solution you'd like**
A check option in settings to display a console window. Possibly have the possibility to filter different types of error.

**Describe alternatives you've considered**
At least being linked to crash logs when game crashes.

**Additional context**
N/A

**Comment by blarfoon** [comment]
The launcher has a console (click on the button in the top left corner) which displays all the information relative to the launcher. Is that what you mean?

**Comment by Freddo3000** [comment]
@gorilla-devs I rather meant for the game, not the launcher. Sorry for not being clear on that.

**Comment by blarfoon** [comment]
I think it's a good idea. Imma work on that then
