### ISSUE TITLE
Modpack icon as Instance Icon

### ISSUE THREAD

**Issue by Midnex** [gorilla-devs/GDLauncher#132]
**Is your feature request related to a problem? Please describe.**
Pull the modpack icon and set it to the default Instance icon, and/or allow user selected icon.

**Describe the solution you'd like**
User automatically has icon for modpack selected, can select from default, modpack, or custom.

**Comment by Freddo3000** [comment]
Duplicate of #112

**Comment by blarfoon** [comment]
Closing this since duplicate
