### ISSUE TITLE
Fix fucking mod seaching

### ISSUE THREAD

**Issue by JukoiDev** [gorilla-devs/GDLauncher#1323]
**Describe the bug**
GDlauncher doesnt ant to show me mods, searching result in idiotic error

**To Reproduce**
Search 6 or more mc mods

**Expected behavior**
Show mods

**Possible solutions**
Make own APi calls to curseforge mod database, and dont use cf's get call "curseforge.com/minecraft/mc-mods/search?search={SOME MOD}"?

**Comment by JukoiDev** [comment]
![image](https://user-images.githubusercontent.com/79868869/166158840-6cb2f16f-53ea-4698-9a62-79dab58db2ed.png)
![image](https://user-images.githubusercontent.com/79868869/166158857-b331a85b-ea97-4777-9006-e7b6c0cb232c.png)

**Comment by JimSkywalker** [comment]
this is happening to me as well

**Comment by iamrusskikh** [comment]
this happening to all from all custom launchers where cf packs was available, MiltiMC devs found solution in modpack.cn

**Comment by Eskaan** [comment]
Fixed in v1.1.23 f5e7a253bbfa5bfc6674c30c56a42862da6d399e
