### ISSUE TITLE
Warn users if they allocate more than 2gb of RAM when they have 32bit java

### ISSUE THREAD

**Issue by Trikzon** [gorilla-devs/GDLauncher#133]
**Is your feature request related to a problem? Please describe.**
When a user has a 32bit version of java installed and allocates more than 2gb of RAM, instances don't start.

**Describe the solution you'd like**
An error popup that explains to the user that they have a 32bit version of java and can't launch the game because they allocated too much RAM.

**Describe alternatives you've considered**
Prevent users with 32 bit java from selecting more than 2gb of RAM to allocate.

**Additional context**
N/A

**Comment by Midnex** [comment]
Windows 32bit is limited to 3GB in most cases, it can go to 4GB if you know how to configure it. It has to do with not having enough ram available to allocate the 2GB of ram. This isn't an issue with the client, its a user issue. 

Best implementation might be more or less add a warning when launching that available ram is less than maximum heap -Xmx2048 (in this case). Then recommend a new value to the user to accept to launch using. Example user has 1900MB of ram, maybe suggest nearest 256MB increment or 512MB.
