### ISSUE TITLE
Mod(pack) search on CurseForge is not working.

### ISSUE THREAD

**Issue by JukoiDev** [gorilla-devs/GDLauncher#1343]
**Describe the bug**
Mod(pack) search on CurseForge is not working. GDlauncher is throwing error at me.

**To Reproduce**
1. Click on 'Add new Instance' button
2. Try to search for modpacks
3. See error

**Expected behavior**
Show me modpacks

**Possible solutions**
Make own CurseForge search API

**Screenshots**
sure,
![image](https://user-images.githubusercontent.com/79868869/169587870-561bf58c-fc14-4e6a-a72a-e9932afbb16a.png)

**Operating System:**
- OS: Window
- Version: 10
- Java Version: Any
- Minecraft Version: Any
- Mod Loader: Any

**Additional context**
It is annoying...

**Comment by AlexHailstone** [comment]
I ended up downloading the Curseforge app 🤮 to install one of the modpacks. Made me really appreciate everything that GDL has provided. Thanks Devs :)

**Comment by tippf3hlr** [comment]
Is there a solution?

**Comment by lewapro** [comment]
It got fixed in new gdlauncher updates, but since 3rd party api is now banned or something there is no way to install modpacks from either modpack list or zips. Waiting for update on that

**Comment by Eskaan** [comment]
The old CurseForge API got shut down, GDL versions below v1.1.23 won't longer work with CurseForge.
