### ISSUE TITLE
Some Design Problems

### ISSUE THREAD

**Issue by GeorgeWL** [gorilla-devs/GDLauncher#138]
I would suggest that you take heed of these suggestions, they'll make the app look far more polished.

Here is some ideas for improving the design without changing too much: https://s3-us-west-2.amazonaws.com/elasticbeanstalk-us-west-2-868470985522/ShareX/2019/01/Photoshop_2019-01-06_21-18-49.png

Here is a list of changes/reasoning:

Don't let text or icons touch the edge of a box, add a few pixels of padding instead. I added padding to the logo, next to the "favorites" text and a few other places.

You can combine the "Home" button with the gorilla logo and use that space for some extra branding, replacing "home" with "GDLauncher". This would help people remember the brand.

The headers for news like "Hey, did you know about themes?" shouldn't be the same color as buttons. Those headers should have lower contrast so your eyes are attracted to buttons.

The theme buttons should just be links because they aren't important.

The favorites menu could have "add" a button below, "search" as a de-emphasized text box, and sorting can be moved to a menu button

Try not to center text. If a message looks weird being left-aligned then there isn't enough content. Add more useful text, like "Try out the new 1.13.2" has nothing useful about what it is.

Don't ask questions in your news messages like "Wanna try it out?". It's weird to read as a user. Instead phrase things as an action like "Try out the pack below".

You can reduce menu clutter by hiding icons/buttons behind a menu button. This is especially useful for actions that aren't entirely clear in an icon, like the logout button.

Removed the "R" avatar but using the minecraft head for the account would be neat.

If people can change the theme colors it will limit what graphics you can use in your news announcements. Changing the theme is neat as a feature, but not useful as a user. It's pretty dated to let users change the design. It's going to hurt your design consistency and brand recognition and doesn't offer anything to the users. A light/dark version is usually appreciated but beyond that, changing colors isn't as good idea as it seems.

https://www.reddit.com/r/feedthebeast/comments/ad8z2z/gdlauncher_adds_curse_modpack_search/edg8otn?context=3

_Sent from my Pixel 2 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by CrankySupertoonArchive** [comment]
This was already disucced by me and him in the discord server. He likes most of it but the 3 arrow design. I explained its not a step design its just different shaped button, and i dont see a problem with either.

**Comment by GeorgeWL** [comment]
mostly put it here so it's easier to track as an issue/request.
