### ISSUE TITLE
Error: Error occurred while fetching token from Xbox Secure Token Service.

### ISSUE THREAD

**Issue by FilipNone** [gorilla-devs/GDLauncher#1477]
- [ x ] I searched the issue tracker for other issues covering my case
- [ ? ] This is a Launcher issue. (Usually if you can reproduce it with a fresh instance)

I'm just trying to login but the launcher says: "Error: Error occurred while fetching token from Xbox Secure Token Service."

(idk if is useful)
![image](https://user-images.githubusercontent.com/79002362/202024600-89682d7b-81c3-4d14-ad91-9cf5ccdfdfbe.png)

**Operating System:**
- OS: Windows 11 22H2 (OS Build 22621.819)
- Launcher Version: v1.1.29
- Java Version: 8/17

**Comment by Eskaan** [comment]
Dusplicate of #1116
