### ISSUE TITLE
search bar stops being in focus after typing one letter.

### ISSUE THREAD

**Issue by Zer0Lyfe** [gorilla-devs/GDLauncher#149]
**Describe the bug**
The bug makes it so after you type one letter in the search bar it will unfocus the search bar. It will be fine after the first letter if you click the search bar again and type the rest of it. I have reinstalled the launcher and it didn't fix the problem for me. 
**To Reproduce**
1. Go to 'Modpacks'
2. Click on 'search here'
3. try to type anything and only the first the first letter will be there

**Expected behavior**
to not lose focus on the search bar after the typing one letter in

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [chrome]
 - Version [71]

**Comment by blarfoon** [comment]
Closing as solved. Feel free to reopen this issue if the issue persists
