### ISSUE TITLE
Custom Java Arguments

### ISSUE THREAD

**Issue by NeonCarbide** [gorilla-devs/GDLauncher#152]
I'm not really asking for much here. Most, if not all, of the other main launchers support the ability to add in custom java arguments to the game to improve optimization.

**Comment by CrankySupertoonArchive** [comment]
I second this

**Comment by Midnex** [comment]
Third this

**Comment by hron84** [comment]
Guys, there is a voting option in GitHub since months. Let's use it on the OP.

**Comment by blarfoon** [comment]
Coming soon, @Ladvace is working on it hopefully
