### ISSUE TITLE
[Enhancement] Manual Download 

### ISSUE THREAD

**Issue by accessdenied0** [gorilla-devs/GDLauncher#1520]
**Is your feature request related to a problem? Please describe.**
Sometimes If I try to download (older) mod-packs and the GDLauncher is forced to use the external method to download these specifics mods, the GDLauncher gets trapped in a "CurseForge verification" loop:
![GDLauncherIssue](https://user-images.githubusercontent.com/8020013/213493281-b06ad849-d2ad-4d8f-894d-015e3d470c32.gif)
This causes a constant repeating until the launcher declares it as failed:
![GDLauncher_sOVlAUFNyY](https://user-images.githubusercontent.com/8020013/213493636-6d71e913-a234-4fff-b0b5-460b9dad66f0.png)

**Describe the solution you'd like**
An option where you can opt for manual download the mod and path the launcher to it/manual add it.

**Describe alternatives you've considered**
Alternative a button to accept and the pack gets not deleted but left installed as far to this point. Or both options.

**Additional context**
I am unsure what this might causes, but in alot of cases I feel this is very useful.

**Comment by Mr-Oca** [comment]
Hello !
For info, I just had this issue, and downloading the mod manually and adding it in the "mods" folder, fixes the issue (after you click "retry download").
