### ISSUE TITLE
Im not able to download modrinth app and when i did i couldnt run it either

### ISSUE THREAD

**Issue by Mattifytv** [gorilla-devs/GDLauncher#1596]
I tried to use the modrinth app after i installed it yesterday i turned on my computer only to find it dosent let me open it i click on it i wait for several minutes it dosent open so i try to reinstall the app deleating everything including file of the app i then install the app i open the wizard and half way it just stops when i almost shut down i forgot to close it then when windows showed that the wizard was not letting me shut down i clicked on cancel then it showed the app couldnt be installed for some reason i can reproduce the whole thing if you want

**Comment by Mattifytv** [comment]
my discord username: mattifytv if user dosent work mattifytv#2945

**Comment by Eskaan** [comment]
I think you're on the wrong issue tracker here, this isn't the modrinth launcher.

This is the modrinth launcher: https://github.com/modrinth/theseus
And there is a FAQ that sounds similar to your problem on their webpage: https://docs.modrinth.com/faq/app/webview2
If you prefer to talk over Discord, this is their Discord server: https://discord.gg/modrinth ([this channel](https://discord.com/channels/734077874708938864/1120929730863050873))
