### ISSUE TITLE
[FEATURE] Cancel pending tasks

### ISSUE THREAD

**Issue by hron84** [gorilla-devs/GDLauncher#162]
**Is your feature request related to a problem? Please describe.**
Currently, if an import or a creation task is stuck there is no way to cancel it. E.g if importing a modpack is stuck (for me it's an actual problem, importing from ZIP is not working for me at all) there is no way to cancel the task and push the launcher to switch to next task (make a new modpack). 

**Describe the solution you'd like**
You should use either more worker or add an ability to cancel a stuck task. Also, it would be nice if the Launcher could communicate more clearly what happens during it downloads / imports a modpack. A percent counter is not always enough.

**Comment by blarfoon** [comment]
Right now any modpack/forge installation/import is broken due to twitch APIs being down. 
I think adding more info on what the download is doing would be helpful. Task cancellation would be a great feature, planned

**Comment by hron84** [comment]
@CrankySupertoon which version will include task cancellation?

**Comment by furtabs** [comment]
Next
