### ISSUE TITLE
[BUG?] This mod's Curse page makes GDLauncher sad

### ISSUE THREAD

**Issue by hron84** [gorilla-devs/GDLauncher#172]
I tried to customize [Mech & Magic LITE](https://www.curseforge.com/minecraft/modpacks/mech-magic-lite) modpack and checking (not install, just checking) page of [Wireless Crafting Grid](https://minecraft.curseforge.com/projects/wireless-crafting-grid) and GDLauncher dies "blue screen of death", which means the whole window become completely empty. 

No crash, no other things, just simply refuses to load the window. No logs, no further descriptions, because I really have no info what's happening. 

(Yes, I know this mod was replaced by Refined Storage Addons, but I fear this error could affect more mods than this, just nobody reached a page like this)

**Comment by blarfoon** [comment]
Fixed with https://github.com/gorilla-devs/GDLauncher/commit/b509f21fb9610e250b31c14f22c9be8f057e7f1e.
Coming on next release soon
