### ISSUE TITLE
when running Yarn

### ISSUE THREAD

**Issue by BraXon-Devs** [gorilla-devs/GDLauncher#179]
**Describe the bug**
E:\GDLauncher>yarn
yarn install v1.15.2
$ node ./internals/scripts/CheckYarn.js
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.7: The platform "win32" is incompatible with this module.
info "fsevents@1.2.7" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "antd > @ant-design/icons-react@1.1.2" has incorrect peer dependency "@ant-design/icons@~1.1.0".
warning " > connected-react-router@6.3.2" has unmet peer dependency "prop-types@^15.0.0 || ^16.0.0".
warning " > discord-rpc@3.0.1" has unmet peer dependency "register-scheme@github:devsnek/node-register-scheme".
warning " > react-contextmenu@2.10.0" has unmet peer dependency "prop-types@^15.0.0".
warning " > eslint-config-erb@0.0.2" has incorrect peer dependency "eslint-config-prettier@^3.3.0".
warning " > eslint-config-erb@0.0.2" has incorrect peer dependency "eslint-import-resolver-webpack@^0.10.1".
warning " > eslint-config-erb@0.0.2" has incorrect peer dependency "eslint-plugin-compat@^2.6.3".
warning " > eslint-config-erb@0.0.2" has incorrect peer dependency "eslint-plugin-jsx-a11y@6.1.2".
warning " > eslint-plugin-prettier@3.0.1" has unmet peer dependency "prettier@>= 1.13.0".
warning "jest > jest-cli > @jest/core > jest-resolve-dependencies@24.5.0" has unmet peer dependency "jest-resolve@^24.1.0".warning "jest > jest-cli > jest-config > jest-resolve@24.5.0" has unmet peer dependency "jest-haste-map@^24.0.0".
warning " > postcss-syntax@0.36.2" has unmet peer dependency "postcss@>=5.0.0".
error An unexpected error occurred: "ENOENT: no such file or directory, copyfile 'C:\\Users\\nanob\\AppData\\Local\\Yarn\\Cache\\v4\\npm-tapable-1.1.1-4d297923c5a72a42360de2ab52dadfaaec00018e\\node_modules\\tapable\\lib\\__tests__\\AsyncParallelHooks.js' -> 'E:\\GDLauncher\\node_modules\\tapable\\lib\\__tests__\\AsyncParallelHooks.js'".
info If you think this is a bug, please open a bug report with the information provided in "E:\\GDLauncher\\yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

E:\GDLauncher>yarn dev
yarn run v1.15.2
$ yarn build-antd && cross-env START_HOT=1 node -r @babel/register ./internals/scripts/CheckPortInUse.js && cross-env START_HOT=1 yarn start-renderer-dev
$ lessc --js ./antd/index.less ./app/antd.css

WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3

E:\GDLauncher\node_modules\@babel\template\lib\parse.js:81
  if (t().isPlaceholder(node)) {
          ^

TypeError: t(...).isPlaceholder is not a function
    at placeholderVisitorHandler (E:\GDLauncher\node_modules\@babel\template\lib\parse.js:81:11)
    at traverseSimpleImpl (E:\GDLauncher\node_modules\@babel\types\lib\traverse\traverse.js:27:14)
    at Object.traverse (E:\GDLauncher\node_modules\@babel\types\lib\traverse\traverse.js:21:3)
    at parseAndBuildMetadata (E:\GDLauncher\node_modules\@babel\template\lib\parse.js:65:7)
    at buildLiteralData (E:\GDLauncher\node_modules\@babel\template\lib\literal.js:53:35)
    at literalTemplate (E:\GDLauncher\node_modules\@babel\template\lib\literal.js:20:7)
    at Object.assign.args (E:\GDLauncher\node_modules\@babel\template\lib\builder.js:32:40)
    at getTemplateForReexport (E:\GDLauncher\node_modules\@babel\helper-module-transforms\lib\index.js:210:115)
    at buildReexportsFromMeta (E:\GDLauncher\node_modules\@babel\helper-module-transforms\lib\index.js:222:34)
    at buildExportInitializationStatements (E:\GDLauncher\node_modules\@babel\helper-module-transforms\lib\index.js:320:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by blarfoon** [comment]
`warning package-lock.json found` means you either did `npm install` instead of `yarn` or it got created in some other ways. Ensure that you have a clean clone of this repo and just run `yarn`. There's no package-lock in our repo so you have created it in some ways

**Comment by BraXon-Devs** [comment]
Ok, I will check it out again, thanks
