### ISSUE TITLE
Possibility to track directly Mod Updates and update it easy (Link in the twitch App) and more things needed!

### ISSUE THREAD

**Issue by Fireztonez** [gorilla-devs/GDLauncher#184]
Hello,

**My Story:**
I just discover your amazing Launcher in the live of Darphan, I have install and I'M reallu happy to see a good team making a project like that, question to be able to install modpack easily, better, less broken than the twitch app and Multi-Platform!!

I'm a modpack maker, and I really need a better Launcher than the Twitch App, because I loose so mutch time with all bugs with the new Twitch App... I use now the Twitch App to add or update mods SymLink to Multi-MC Instance. This work, but I still have to deal with all the Twitch App Bugs.

**What I need:**
So, question to be able to stop using the Twitch App, I need a good way to track Mods Update (So, using a little icon to show mod having a new update should be cool). When you click on that, it should ask what version you want to install, but important thing, but, this is important to being able to see the Change Logs for that version (Now, I do update from the Twitch App, but before I have to go to on the curse forge page to look the change log...).

**Other things missing, possible with the Twitch App:**
- Having a possibility to see, when clicking on the mod (From the Mod Manager List), the Curse Page description from the mod should be really good
- Being able to downgrade a mod easily if an update caused problem
- Thing's currently impossible with the Twitch App, but should be really Nice; Being able to mask a specific update if we want to see if there have a new update after that broken one easily!

**Feature from MultiMC really usefull for Modpack Dev:**
- Having question to open Console, when I launch a modpack (Like Multi-MC does), and possibly coloring ERROR and FATAL line in red, Orange for WARNING, and things like that!!
- Having a simple shortcut direcly to the Mod Folder
- Having easy access to all the latest Logs Files and Crash-Reports, with a link to Log and Crash Folder on the interface

I think this is here a list of thing how you can possibly added to the app question to have a more complete options for Modpack Dev!

Thank's
Fireztonez

**Comment by kreezxil** [comment]
Ditto!
