### ISSUE TITLE
Project dead in the water? Finding it difficult to contact the devteam.

### ISSUE THREAD

**Issue by Sarioah** [gorilla-devs/GDLauncher#185]
Is this project abandoned? The concept launcher looked like it had so much potential, but the devteam's contact links appear broken. The Discord invite is expired, and when I tried to send an email about this, I was presented with a delivery failed message...

FWIW, the email address I tried was the one on the gdevs.io site; info@gdevs.io.

**Comment by Ladvace** [comment]
In this days we were busy, we are sorry about that.
Here Is the discord invite like: https://discord.gg/Zd7pEuU

**Comment by blarfoon** [comment]
Hi, this project is not dead at all. I was not aware of our email not working, I'll investigate asap! In the meanwhile you can contact us on our discord :)
