### ISSUE TITLE
Java classes not found

### ISSUE THREAD

**Issue by daviewales** [gorilla-devs/GDLauncher#191]
**Describe the bug**
SkyFactory 4 crashes during launch because it can't find `com/mojang/text2speech/NarratorOSX`

It works in the Twitch launcher.

**To Reproduce**
1. Install SkyFactory 4
2. Launch the instance
3. Wait while it loads.
4. When it gets to 6/7 or 7/7, it closes, and nothing happens.

**Expected behavior**
The instance would load.

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - Java Version: 1.8.0_111
 - GDLauncher Version 0.11.6

**Additional context**
Behold a crash report!

[crash-2019-04-26_20.03.23-client.txt](https://github.com/gorilla-devs/GDLauncher/files/3120838/crash-2019-04-26_20.03.23-client.txt)

**Comment by blarfoon** [comment]
You're using an old version of the launcher. Try downloading the latest from our website and confirm if you have the same issue
Sadly on macOS, we are not able to deliver auto-updates at the moment.

**Comment by daviewales** [comment]
I've updated to 0.11.9.
The same crash occurs.

[crash-2019-04-27_09.42.33-client.txt](https://github.com/gorilla-devs/GDLauncher/files/3123265/crash-2019-04-27_09.42.33-client.txt)

Searching Java exception brings up a few results:

I suspect that this is the issue:

https://bugs.mojang.com/browse/MC-118506?focusedCommentId=388824&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-388824

Where does GDLauncher keep the `minecraft/libraries/ca/weblite` directory? In vanilla Minecraft on Mac, there should be a directory `minecraft/libraries/ca/weblite/java-objc-bridge/1.0.0` containing the missing Java class. If you can point me to where that should go, I'll copy it across and see if it fixes the problem.

**Comment by blarfoon** [comment]
Could you please send me the launcher log?

**Comment by daviewales** [comment]
@killpowa What is the path for the launcher log?

Here is `GDLauncher/instances/packs/SkyFactory4/logs/debug.log`:
[debug.log](https://github.com/gorilla-devs/GDLauncher/files/3133533/debug.log)

And `GDLauncher/instances/packs/SkyFactory4/logs/latest.log`:
[latest.log](https://github.com/gorilla-devs/GDLauncher/files/3133540/latest.log)

And `GDLauncher/instances/packs/SkyFactory4/crash-reports/crash-2019-04-29_11.46.42-client.txt`:
[crash-2019-04-29_11.46.42-client.txt](https://github.com/gorilla-devs/GDLauncher/files/3133543/crash-2019-04-29_11.46.42-client.txt)

**Comment by blarfoon** [comment]
You can find the path for the log, depending on your OS, [here](https://github.com/gorilla-devs/GDLauncher/wiki/Troubleshooting)

**Comment by daviewales** [comment]
Thanks @killpowa.
Here is the log:

[log.log](https://github.com/gorilla-devs/GDLauncher/files/3140277/log.log)

I think it contains logs for more than just the latest launch.

**Comment by blarfoon** [comment]
You are using a really old version of the launcher (we don't have auto updates on mac yet). Try manually downloading the latest version from our website

**Comment by daviewales** [comment]
Here is a crash report from the latest version of the launcher (0.11.15.861):

[crash-2019-08-22_17.10.51-client.txt](https://github.com/gorilla-devs/GDLauncher/files/3532372/crash-2019-08-22_17.10.51-client.txt)

**Comment by daviewales** [comment]
Now I'm trying to launch a fresh instance of 1.14.4 Vanilla, and I get this:

[log.log](https://github.com/gorilla-devs/GDLauncher/files/3532629/log.log)
[crash-2019-08-23_12.40.26-client.txt](https://github.com/gorilla-devs/GDLauncher/files/3532631/crash-2019-08-23_12.40.26-client.txt)

**Comment by TOLoneWolf** [comment]
This issue should be fixed as of 0.12.4
Updating the launcher reinstall any instances that do not work should fix any launching problems for missing libraries.

**Comment by daviewales** [comment]
I just tested it, and it works now!
Thanks!
