### ISSUE TITLE
Progress Bar Appears Over Items

### ISSUE THREAD

**Issue by Wibble199** [gorilla-devs/GDLauncher#192]
Minor UI style error. The progress bar shown when downloading a pack shows above the right-click menu of another pack and also the "Manage" modal window.

![image](https://user-images.githubusercontent.com/3984322/56841087-7e458300-6883-11e9-9e9c-a3b11cd0dcf7.png)

**Comment by blarfoon** [comment]
What version of the launcher are you running?

**Comment by Wibble199** [comment]
v0.11.9

**Comment by blarfoon** [comment]
This should be fixed in the latest beta 0.11.10-beta. Closing this issue as solved but I'll reopen it if the issue persists
