### ISSUE TITLE
All instances downloaded are launched in "Silent Mode" and all sound files are missing

### ISSUE THREAD

**Issue by lewhitekid** [gorilla-devs/GDLauncher#193]
[-1556264816559.log](https://github.com/gorilla-devs/GDLauncher/files/3123511/-1556264816559.log)

**Describe the bug**
Any instance I download from the GDLauncher and try to play, in the console it says its missing every sound file and Minecraft is launching in silent mode. This only happens on the GDLauncher

**To Reproduce**
Download any pack.

**Expected behavior**
Minecraft to launch with sound.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Stable release of GDLaucher

**Comment by Ladvace** [comment]
which pack have you tried?

**Comment by lewhitekid** [comment]
1.13.2 vanilla, FTB interactions, Sky Factory 4, and Project Ozone 3, all with with same results

**Comment by extant1** [comment]
I am having the same issue, fresh install of GDLauncher  v0.11.9, tried on 1.12.2 forge and 1.13.2.

I just checked the console and thing I found the issue:
`"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\versions\1.13.2\1.13.2.jar" net.minecraft.client.main.Main --username extant1 --version 1.13.2 --gameDir "C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\packs\1.13.2" --assetsDir C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\assets --assetIndex 1.13.1 --uuid 56b4d25b8fb44a6d8df45e177583de45 --accessToken HIDDEN_ACCESS_TOKEN --userType mojang --versionType release  `

The assetsDir variable isn't wrapped in quotes so the space in my user directory is breaking it off into a separate command and failing it as you can see here.

`Completely ignored arguments: [Maple\AppData\Roaming\GDLauncher\instances\assets]

instancesManager.js:59 [20:52:59] [Client thread/ERROR]: Can't find the resource index file: C:\Users\Whiskey\indexes\1.13.1.json`

**Comment by lewhitekid** [comment]
is there any way to fix this? without having to rename my folders to things without spaces?

**Comment by extant1** [comment]
Renaming your folders would break your account, you'd need to make a new user account without spaces in the name or just wait for an update to the launcher.

**Comment by lewhitekid** [comment]
its weird that they wouldn't add an option to change the directories. thanks you though for at least confirming this isn't something wrong on my end. I had been trouble shooting the past 2 days.

**Comment by extant1** [comment]
The directory isn't anything to do with the launcher or minecraft, it's your username for windows.

Conway's Super PC

The directory path of 
C:\users\Conway's Super PC\

It's not wrapped in quotation marks so the launch command is just mistaking the spaces is all. You don't want to rename your windows user folder otherwise it will bad news for you. You could make a temporary new windows user account without spaces in the meantime but I assume they will fix this quickly now that they know of the issue.

**Comment by extant1** [comment]
3e13200 fails to fix the issue.  I've tried repairing the instances or reinstalling them and repairing again and the assetsDir value is still not wrapped in quotes causing the same behavior.

**Comment by lewhitekid** [comment]
Yeah I'm still having the same issue. When you right click the error in console it says its from renderer.prod.js if that helps
