### ISSUE TITLE
Allow all files of application including folders to be installed anywhere and not force roaming folder.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [gorilla-devs/GDLauncher#194]
**Is your feature request related to a problem? Please describe.**
I only have a 120GB SSD and I avoid using my c drive for none hardware based applications and software. In other words no games or junk on my c drive.

**Describe the solution you'd like**
One thing I really liked about MultMc was the ability to keep files related to launcher in the launcher folder. I am not fond of forced launching or install locations.

**Describe alternatives you've considered**
I came from the Multi-Mc scene because it is no longer receiving updates to things I seek.

**Additional context**
![2019-04-28 00_50_49-Window](https://user-images.githubusercontent.com/10351221/56859402-cb8f2680-694f-11e9-81b2-2194dab6516e.jpg)

**Comment by blarfoon** [comment]
We now allow users to move the instances install location
