### ISSUE TITLE
Invalid maximum heap size: -Xmx{_RAM_}m  (Beta v0.11.10-beta)

### ISSUE THREAD

**Issue by extant1** [gorilla-devs/GDLauncher#195]
`00:04:55.651 › "C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe" -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms256m -Xmx{_RAM_}m -Xmx8192m  -Djava.library.path="C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\packs\1.13.2\natives"  -Dminecraft.client.jar="C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\versions\1.13.2\1.13.2.jar" -cp "C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\com\mojang\patchy\1.1\patchy-1.1.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\oshi-project\oshi-core\1.1\oshi-core-1.1.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\net\java\dev\jna\platform\3.4.0\platform-3.4.0.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\net\sf\jopt-simple\jopt-simple\5.0.3\jopt-simple-5.0.3.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\io\netty\netty-all\4.1.25.Final\netty-all-4.1.25.Final.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\com\google\guava\guava\21.0\guava-21.0.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\org\apache\commons\commons-lang3\3.5\commons-lang3-3.5.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\commons-io\commons-io\2.5\commons-io-2.5.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\commons-codec\commons-codec\1.10\commons-codec-1.10.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\com\mojang\brigadier\1.0.14\brigadier-1.0.14.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\com\mojang\datafixerupper\1.0.19\datafixerupper-1.0.19.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\com\google\code\gson\gson\2.8.0\gson-2.8.0.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\com\mojang\authlib\1.5.25\authlib-1.5.25.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\it\unimi\dsi\fastutil\8.2.1\fastutil-8.2.1.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\org\apache\logging\log4j\log4j-api\2.8.1\log4j-api-2.8.1.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\org\apache\logging\log4j\log4j-core\2.8.1\log4j-core-2.8.1.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\com\mojang\realms\1.13.9\realms-1.13.9.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\org\lwjgl\lwjgl\3.1.6\lwjgl-3.1.6.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\org\lwjgl\lwjgl-jemalloc\3.1.6\lwjgl-jemalloc-3.1.6.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\org\lwjgl\lwjgl-openal\3.1.6\lwjgl-openal-3.1.6.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\org\lwjgl\lwjgl-opengl\3.1.6\lwjgl-opengl-3.1.6.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\org\lwjgl\lwjgl-glfw\3.1.6\lwjgl-glfw-3.1.6.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\org\lwjgl\lwjgl-stb\3.1.6\lwjgl-stb-3.1.6.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\libraries\com\mojang\text2speech\1.10.3\text2speech-1.10.3.jar";"C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\versions\1.13.2\1.13.2.jar" net.minecraft.client.main.Main --username extant1 --version 1.13.2 --gameDir "C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\packs\1.13.2" --assetsDir C:\Users\Whiskey Maple\AppData\Roaming\GDLauncher\instances\assets --assetIndex 1.13.1 --uuid 56b4d25b8fb44a6d8df45e177583de45 --accessToken HIDDEN_ACCESS_TOKEN --userType mojang --versionType release   
console.js:72 00:04:55.784 › Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
console.js:72 00:04:55.785 › Invalid maximum heap size: -Xmx{_RAM_}m`

**Comment by extant1** [comment]
On a side note it looks like the --assetsDir value isn't being wrapped in quote, in reference to #193

**Comment by Ladvace** [comment]
The problem Is that there Is "-Xmx{_RAM_}" in the launch string if you
remove that in the global Java arguments It should work.
We have changed the way we handle the ram so to fix it you have to go in GDLauncher folder > config.json and remove  the "-Xmx{_RAM_}" from the javaArgs string

Il mar 30 apr 2019, 06:08 extant1 <notifications@github.com> ha scritto:

**Comment by SuperSandro2000** [comment]
The format changed when you switch from stable to beta. You just need to reset your java options.

Ps next time use 4 ` to get a scrollbar on the right.

**Comment by extant1** [comment]
Refreshing the Java custom path does fix this issue however that fix isn't directly obvious so I'm leaving closing the issue out up to the developers if they want to leave it open as awareness to the issue an implement automatic updating of the java custom path on a new version of the launcher (or whatever scenario triggered this event).

**Comment by Ladvace** [comment]
This issue has been fixed (if I'm not wrong) right?
