### ISSUE TITLE
MC only launching with 1986MB of RAM

### ISSUE THREAD

**Issue by Vonr** [gorilla-devs/GDLauncher#196]
**Describe the bug**
When launching Minecraft (any pack too), GDLauncher only allocates 1986MB of RAM to it, which is obviously not enough.

**To Reproduce**
1. Go to Settings
2. Set RAM to e.g. 6144MB (the one I use)
3. Use `-XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=20000 -XX:ParallelGCThreads=4` as your Java Arguments (not sure if this affects anything but that's what I ue)
4. Launch any pack.
5. See error

**Expected behavior**
Should allocate full 6144MB of RAM to Minecraft.

**Screenshots**
![image](https://user-images.githubusercontent.com/24369412/57020149-0ac4bc80-6c5b-11e9-8050-716825595a20.png)
![image](https://user-images.githubusercontent.com/24369412/57020182-1b753280-6c5b-11e9-846e-e83ac098e46a.png)

**Desktop (please complete the following information):**
 - OS: Win 10 10.0

**Additional context**
Using Java 1.8.0_201

**Comment by Ladvace** [comment]
I tried and for me it works, the ram was the one I choose. If you write me on discord I can try helping you

**Comment by blarfoon** [comment]
Can you confirm that you have not enabled an override java memory for the specific instance?
Could you also please send us the GDLauncher log? https://github.com/gorilla-devs/GDLauncher/wiki/Troubleshooting

**Comment by blarfoon** [comment]
Closing as solved. Feel free to re-open this issue if it's still happening
