### ISSUE TITLE
Logged out of the launcher every so often

### ISSUE THREAD

**Issue by Dimentive** [gorilla-devs/GDLauncher#203]
#### Describe the bug
Sometimes, after exiting the launcher and launching it again, I am logged out of the launcher, with the error message “Token Not Valid. You Need To Log-In Again :(.” I’m not clicking the log out button, logging out of Minecraft anywhere else manually, or deleting any temporary data or anything of the sort.

#### To reproduce

Exit and re-launch the launcher a few times.

#### Expected behaviour

The expected behaviour is not to be randomly logged out of the launcher.

#### Screenshot

![Token not valid (cropped and colours filled in corners)](https://user-images.githubusercontent.com/34230933/57193009-0cca9c00-6f37-11e9-8bf0-8daa01121cd5.png)

#### Versions

* **Operating system:** Windows 10 Home
* **GDLauncher:** v0.11.11-beta (latest beta version as of writing this)

**Comment by Ladvace** [comment]
Maybe because the token expires

**Comment by Dimentive** [comment]
Ever since I updated to v.0.11.12-beta, this hasn’t happened again yet.

**Comment by blarfoon** [comment]
Yeah, if I'm not mistaken I should have fixed this as of v0.11.12
