### ISSUE TITLE
Multiple versions of the same mods are installed when you install mods that depend on them

### ISSUE THREAD

**Issue by Dimentive** [gorilla-devs/GDLauncher#205]
#### Describe the bug
If a mod requires another mod, GDLauncher will often download an outdated version of that mod. For instance, when downloading a bunch of add-ons to JEI, I ended up with three separate versions of JEI installed in my instance, two of which I, of course, had to remove to be able to launch the game. The same happened with many other mods. I ended up with two versions of Forestry after installing some Forestry add-ons, and so on.

This doesn’t happen because the add-ons I’m installing require a specific, older version of the mods in question. They work fine with the latest version, yet GDLauncher is downloading multiple, different versions of the same mods when I’m installing other mods that depend on them.

I found that this had already been reported (#153), but it was closed by killpowa without a reason given. I’m assuming this was a mistake, so I’m reporting it again. Or, perhaps, a fix to this bug was attempted. I’m not sure what the case is, but either way, this bug still occurs on the latest beta version of GDLauncher.

#### To reproduce

Download multiple mods with the same required dependency.

#### Expected behaviour

The expected behaviour is for any instance to only have one instance of any mod installed at a time. If I’ve installed, say, the latest version of a mod, the launcher shouldn’t download other, outdated versions of the same mod when I’m installing mods that depend on that mod, such as add-ons.

#### Versions

* **Operating system:** Windows 10 Home
* **GDLauncher:** v0.11.12-beta (latest beta version as of writing this)

**Comment by TOLoneWolf** [comment]
As far as I know the current version ( 0.12.4 at this time ) does not have this issue.

If I am wrong we can reopen this issue but I am going to close it for now.
