### ISSUE TITLE
Certain mods in the add a mod search can cause the Launcher to blank

### ISSUE THREAD

**Issue by LunaFolf** [gorilla-devs/GDLauncher#206]
**Describe the bug**
As the title says, when previewing mods from the add mods menu certain mods can blank the app.

**To Reproduce**
I wrote this out once, then GitHub refreshed automatically and wiped what I wrote, so just watch the video below, it's really easy to reproduce tbh.

**Screenshots**
[https://abrm.liamholmes.co.uk/2019-05-11%2019-14-43.mp4](https://abrm.liamholmes.co.uk/2019-05-11%2019-14-43.mp4)

**Desktop (please complete the following information):**
 - OS: Windows 10 Version 1809 (Build 17763.475)

**Comment by Ladvace** [comment]
for some reason, I can't find the mod you have used

**Comment by LunaFolf** [comment]
Interesting.
A mod called 'Photoreal', also by ichun, causes the same problem as well, maybe you can find that one?

**Comment by jackwilsdon** [comment]
Looks like that mod has no support for newer versions of MC, and as such the array of matching mod filed is empty. This crashes the launcher when it tried to access `allFiles[0]`. I'm not sure on a solution to this — is it possible to filter search results by game version or should a check be added to show a message when a mod does not provide any files for the currently selected game version?

**Comment by Dimentive** [comment]
If you change to the beta version of the launcher in the settings, it will only show mods for your instance’s version of Minecraft when searching.

**Comment by LunaFolf** [comment]
@jackwilsdon To fix the preview screen that opens, then a check should be added that index 0 of allFiles array actually exists first, otherwise display a message stating a version of the mod for the MC instance version does not exist.
In addition to this, a small banner on the icons of the search results showing that it's out of date would also be handy, if possible.

**Comment by jackwilsdon** [comment]
It sounds like this is fixed in the beta according to @Dimentive, as it should now be impossible to view mods which don't support your current instance's version anyway

**Comment by Ladvace** [comment]
yeah, indeed you can't see not supported mods

**Comment by LunaFolf** [comment]
Awesome so from comments above it seems this is already fixed in Beta build of application, so I'll close this now.
