### ISSUE TITLE
Modpack listing does not load

### ISSUE THREAD

**Issue by ecatherman** [gorilla-devs/GDLauncher#208]
The Modpacks tab where never loads. It does not help to change the sort by option or to search in the search box.

![image](https://user-images.githubusercontent.com/6530707/58387783-ce2e7b80-7fe2-11e9-98a4-9de60b0439c5.png)

**Comment by furtabs** [comment]
Its not in our Control, please dont bug us, if your going to bug someone, bug Dries on his discord. he made the API which lets our launcher work https://staging_cursemeta.dries007.net/
