### ISSUE TITLE
[FEATURE] Searching by Minecraft Version

### ISSUE THREAD

**Issue by Bigboom243** [gorilla-devs/GDLauncher#216]
**Describe the solution you'd like**
A drop down list (like the one with the featured, popularity, last updated, etc options) to pick a certain minecraft version like 1.7.10, 1.10.2, 1.8, etc. Once you do that it will then show all of the modpacks that use that minecraft version.

**Additional context**
Something like this:
![Feature Idea](https://user-images.githubusercontent.com/44557686/61583292-f55e8080-ab2d-11e9-9ccf-0663617f3c95.png)

**Comment by kreezxil** [comment]
What's the ETA on this, it should be relatively easy to do?

Can you guys add a bounty feature to your github, I would love to place a bounty on this feature request.
