### ISSUE TITLE
Instances won't launch after recent update of GD Launcher

### ISSUE THREAD

**Issue by solarionlunarion** [gorilla-devs/GDLauncher#217]
**Describe the bug**
I updated GD Launcher itself to the latest version (0.11.14). Now none of my instances will launch at all. I tried to download a new modpack to make certain my instances were not corrupted, but that would not launch, either. 

Using the double click or clicking Launch command in the right-click menu results in the "Playing" arrow appearing in the modpack icon for about half a second, then disappearing. Nothing else happens. The launcher doesn't even generate an error report. 

**To Reproduce**
1. Update the launcher to 0.11.14.
2. Attempt to launch any modpack instance by either double clicking or the rightclick menu's Launch command.
3. Notice that it fails to launch at all.

**Expected behavior**
A. Double-clicking an instance should launch the instance.
B. Using the rightclick menu's "Launch" command should launch the instance.

**Comment by Ladvace** [comment]
To Workaround this problem until we fix it,, enable java arguments in right click>manager>settings

**Comment by blarfoon** [comment]
v0.11.14 was a big update and I changed a lot of things in the configs. Try to click "Repair" on the instance, that should fix it

**Comment by EB57PzUhYmQsMm** [comment]
try downloading jdk 8

https://github.com/gorilla-devs/GDLauncher/wiki/FAQ-Frequently-Asked-Questions#java-64-bit-installers

**Comment by NicTanghe** [comment]
repair stuck at 75%
using openjdk
