### ISSUE TITLE
Minecraft 1.14.3 won't launch

### ISSUE THREAD

**Issue by Snow-ctrl-c** [gorilla-devs/GDLauncher#220]
**Describe the bug**
After installing Minecraft 1.14.3 as an instance I tried to laugh the version. There is a play icon that appears on the instance icon for a second. Nothing else happens.

**To Reproduce**
1. Go to GDLauncher
2. Click on Instances tab
3. Scroll down to an instance set up for Minecraft 1.14.3, if not there create one
4. Wont launch

**Desktop**
 - OS: MacOs 10.14.5
 - Launcher: GDLauncher 0.11.9.638

**Additional context**
The default and twitch's launchers both work for me. 
I also noticed that Minecraft 1.8.9 launches on the GDLauncher. Its weird that 1.14.3 doesn't.

**Comment by Ladvace** [comment]
Can you open the console and screenshot the error please?

**Comment by blarfoon** [comment]
Are you trying to run a vanilla 1.14 or forge?

**Comment by Snow-ctrl-c** [comment]
Vanilla

**Comment by blarfoon** [comment]
Oh, you're on macOS. We're having quite some troubles on macOS atm :(

**Comment by meelock** [comment]
I'm having the same issue on windows but with modded, extends to 1.12.2 as well.

**Comment by UnknownMind001** [comment]
I'm having the same issue windows 10. Minecraft version: 1.14.4. Mod pack: Enigmatica 4, version 0.4.1. The play icon flashes up for half a second and then disappears. Nothing else happens

**Comment by kreezxil** [comment]
Look in the issue https://github.com/gorilla-devs/GDLauncher/issues/268.
There are two issues mentioned with two solutions, one each. Both or at
least one will likely apply to you.

**Comment by TOLoneWolf** [comment]
`Launcher: GDLauncher 0.11.9.638`
@Zachary-collins7  ~~is your launcher version 0.12.4 (bottom right)~~ Update your launcher!
What version of java is it using? [Check Java Version](https://github.com/gorilla-devs/GDLauncher/wiki/Check-Java-Version)  
[Java 64-bit Installers](https://github.com/gorilla-devs/GDLauncher/wiki/FAQ-Frequently-Asked-Questions#java-64-bit-installers)  

@UnknownMind001 @meelock   
https://github.com/gorilla-devs/GDLauncher/wiki/FAQ-Frequently-Asked-Questions#not-starting-no-error-in-console

**Comment by TOLoneWolf** [comment]
Going to close this as it should be solved for OSX which this issue was for.
The other 2 are different issues and for a different OS but should also have the solutions to them. If not please open a new issue for them and provide logs.
[View console and logs](https://github.com/gorilla-devs/GDLauncher/wiki/How-to-view-console-and-log-files)
