### ISSUE TITLE
Version numbers mixed

### ISSUE THREAD

**Issue by rocket7642** [gorilla-devs/GDLauncher#223]
Is your feature request related to a problem? Please describe.

When downloading a pack for example stoneblock 2, the version numbers when choosing what you want the instance to be are in a seemingly random order. For example 1.15.0 is the newest but the top version number in the list is 1.3.0 followed by 1.0.1 and then 1.2.0 etc in a random order. (similar problem in other packs such as Skyfactory 4, All the Mods 3, and Rougelite adventures and dungeons)

Describe the solution you'd like

Organize the list when choosing a modpack version from newest uploaded to oldest uploaded.

Describe alternatives you've considered

Put the date the item was uploaded near the item.

**Comment by blarfoon** [comment]
Fixed https://github.com/gorilla-devs/GDLauncher/commit/f975c1199218b7550d30a7b54c295d887e6cc220
