### ISSUE TITLE
Cannot create Forge 1.14.4 (or any version) instance

### ISSUE THREAD

**Issue by FenixFyreX** [gorilla-devs/GDLauncher#229]
**Describe the bug**
I've tried creating a new instance of Minecraft 1.14.4 with Forge 28.0.41. The instance gets almost finished, then hangs and never finishes installing.

**To Reproduce**
Steps to reproduce the behavior (2 for 2, I've done this twice now):
1. Right Click -> Add New Instance
2. Select A Version -> Forge -> 1.14.4 -> 28.0.41
3. Waited literally 24 hours, sleep mode / etc turned off.
4. Still no good, instance is non-interactable, can't do anything because the load bar and circle icon are still whirling away.

**Expected behavior**
The instance finishes installing, and allows me to play.

**Desktop (please complete the following information):**
 - OS: Arch Linux 64 bit (x86_64)
 - Browser: Firefox
 - Version: 0.11.15

**Comment by FenixFyreX** [comment]
I tried this with 0.11.16-beta (1.13 beta support) and still would not work. It is still spinning away, not finishing.
Edit: I've also just tried to create a 1.12 instance, and it is doing the same thing. I closed the application, opened it back up and the instance was "finished" (no loading icon / bar). I tried to play it (1.12 version) and it is complaining about an `UnsatisfiedLinkError`, in regards to lwjgl64.

Any ideas?

**Comment by FenixFyreX** [comment]
I'm gonna close this, because I downloaded Minecraft vanilla launcher, ran it (ran 1.14.4 and 1.12.2), then tried GDLauncher again and it worked in less than 10 seconds. Idk why GDLauncher didn't want to build the instances before, but if anyone encounters this issue, running a vanilla instance in the vanilla launcher fixed it for me.

**Comment by drewbit** [comment]
I'm still encountering this issue but only with Forge installations. Vanilla works as expected.
