### ISSUE TITLE
Uninstalling leaves a mess

### ISSUE THREAD

**Issue by odessadraekavik** [gorilla-devs/GDLauncher#230]
**Describe the bug**
When uninstalling GDLauncher it leaves a GDLauncher folder in %appdata%/Roaming

**To Reproduce**
- Install the latest version of GDLauncher
- Uninstall it through the Windows add/remove software panel

**Expected behavior**
Uninstaller should have a tickbox to keep or remove the leftover files.

**Comment by Lartza** [comment]
Leaving some files isn't uncommon for software, even if bad, but I had no instances left and GDLauncher still left 328MB behind

**Comment by ArushGore** [comment]
How do I go about removing GDlauncher from a linux application. I want to reinstall it but as it isn't loading but using snap again won't work.
