### ISSUE TITLE
[Linux] No forge versions shown

### ISSUE THREAD

**Issue by bluepython508** [gorilla-devs/GDLauncher#231]
**Describe the bug**
When I try to create an instance or add Forge to an instance, no versions of Forge are shown.

**To Reproduce**
Start creating an instance. Choose Forge.
When the instance is created, it is continuously processing and never creates the instance.
Right click a vanilla instance and choose Manage. No Forge versions are listed in the install Forge list.

**Expected behavior**
Forge versions to be available to install.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: XUbuntu 16.04
 - Browser: Chrome
 - Version: 0.11.15

**Smartphone (please complete the following information):**

**Additional context**

**Comment by garpu** [comment]
It worked for me.  (Slackware)  Right click, new instance, forge, 1.14, 28.0.40.
