### ISSUE TITLE
an option to automatically download dependencies like the twitch app does

### ISSUE THREAD

**Issue by lag42** [gorilla-devs/GDLauncher#232]
**Is your feature request related to a problem? Please describe.**
installing mods then going back to get the dependencies they say they need can be a pain, the twitch app already has a solution for this though

**Describe the solution you'd like**
an option that when enabled will make it so that when mods that have required dependencies listed on their curseforge page are installed those required dependencies will be installed if they are not already installed

**Describe alternatives you've considered**
an option that brings up a prompt when you install a mod that has required dependencies that tells you what they are

**Comment by blarfoon** [comment]
Fixed in latest beta (v0.11.17-beta). Coming out as stable later this month
