### ISSUE TITLE
[ENHANCEMENT] Sort pack versions by alphabetic - at least

### ISSUE THREAD

**Issue by hron84** [gorilla-devs/GDLauncher#233]
Version numbers are - i guess - ordered by how Curse API returns with them.

Steps to see the problem:

1. Open the client
2. Try install [TownCraft](https://www.curseforge.com/minecraft/modpacks/towncraft)
3. Drop down version numbers.

This is a whole mess, not even able to guess which is the latest version.

Affected version: 0.11.15

**Comment by blarfoon** [comment]
Fixed in the latest beta (v0.11.17-beta). Coming out as stable later this month
