### ISSUE TITLE
A way to view logs

### ISSUE THREAD

**Issue by Mixu78** [gorilla-devs/GDLauncher#234]
**Is your feature request related to a problem? Please describe.**
A way to view the log output of Minecraft would be nice, so you can see what went wrong when for example doing x and an error saying to check the logs is put into the in-game chat but you have to manually navigate to the instance folder to view latest.log.

**Describe the solution you'd like**
A button to open a log window to be able to view logs, with color coding like yellow = warning, red = error, white = log etc.

**Describe alternatives you've considered**
A button to open the latest.log in the instance folder for the selected pack.

**Additional context**

**Comment by furtabs** [comment]
Already exists, click the top left button in the laumcher then click Console

**Comment by Mixu78** [comment]
Does it exist in Linux?

**Comment by blarfoon** [comment]
It exists on all operating systems. There is a little icon in the top left of the launcher

**Comment by Mixu78** [comment]
I think you misunderstood, I meant the Minecraft logs not launcher logs

**Comment by blarfoon** [comment]
They are all in there

**Comment by Mixu78** [comment]
It opens a chrome developer console window and it looks kinda weird comparing to the launcher

**Comment by Mixu78** [comment]
Being able to directly view them from the instance window would be better

**Comment by kreezxil** [comment]
I agree with this, however, let's add some clarity.

right clicking the instance icon shows a lot of options. why not just add "show console" right there in that context menu. That will have the affect of less people coming to the github to complain about it. In the Microsoft Windows world that little button in the upper left corner doesn't mean squat, it usually only ever means window sizing parameters. In other operating systems it can easily mean other stuff. However, if most people of the alternate systems came from windows it will still mean nothing.

Best solution add "show console" to the right click menu.

**Comment by dhouck** [comment]
The dev console does not give me a link to the actual log file and doesn’t let me copy anything out without adding extra linebreaks and `action.js:2695`.

**Comment by theoparis** [comment]
Any updates on this? It's been 2 years since this was closed and I still don't see a good way to view logs other than to view a JS Console that has non-mc related information.

**Comment by kreezxil** [comment]
right click the pack
open the folder
two folders, logs/ and crash-reports/
enter each to get what you want

GDL itself only has the console log
on the console tab
right click the empty white space
choose saveas

the resulting text will be drastically larger than what you saw on the
console screen. because it will have everything.
