### ISSUE TITLE
Long loading time

### ISSUE THREAD

**Issue by milcondoin** [gorilla-devs/GDLauncher#236]
When starting up the GDLauncher, it takes quite a long time to get into the progran, showing only some bluish stuff, with some effect going from left to right. Nothing can be done until then. This is very frustrating.

Question: Is there anything important loaded from a remote server, without that the launcher is by design unusable? That would sound like a design error.

Suggestion: Simply display the page with the instances directly. Everything here should be already locally available. Then the user can start to load the modpack, which would be the wanted action 99% of the time when the GDLauncher is started.

**Comment by maxetime** [comment]
The font library "https://fontlibrary.org/face/glacial-indifference" is down. I suggest saving the font in the ressources of the app.

Update found out the site is down since githubs announcement : https://twitter.com/fontlibrary/status/1161181858291277824

**Comment by milcondoin** [comment]
Update: Startup speed is back to normal.
