### ISSUE TITLE
GDLauncher not downloading all files

### ISSUE THREAD

**Issue by Mixu78** [gorilla-devs/GDLauncher#238]
**Describe the bug**
GDLauncher downloads part of mods in a modpack, thus leaving modpack incomplete

**To Reproduce**
1. Select a large modpack, like Awakening: Sky of Diamonds
2. Download said modpack
3. Attempt to launch the pack and see it fail due to missing dependencies

**Expected behavior**
GDLauncher downloads the whole modpack

**Desktop (please complete the following information):**
 - OS: Linux/Ubuntu
 - Browser: Firefox
 - Version: 0.11.15

**Smartphone (please complete the following information):**
 - Device: Samsung galaxy Xcover 3
 - OS: Android 6.0.1 Marshmallow
 - Browser: Chrome beta
 - Version: ?
Why do you need this?

**Comment by Meister1593** [comment]
I have constant issues related to this still, was this really fixed?

skyfactory, project ozone, mceternal, all of them constantly download incomplete modpacks and repairing/changing version back and forth doesnt help

**Comment by Eskaan** [comment]
That issue is fixed, look at the pinned one ;)

**Comment by Meister1593** [comment]
> That issue is fixed, look at the pinned one ;)

if this is about 0% download modpack then it isn't the same issue, because entire modpack does supposedly download and report as finished

it just doesnt download entire modpack, some mods are missing and thus i can't join servers (or even launch some modpacks) with same modpack version

**Comment by Eskaan** [comment]
Yes, that is the Curseforge API's fault. Look at your console, it should show the same issues when downloading.

**Comment by Meister1593** [comment]
> Yes, that is the Curseforge API's fault. Look at your console, it should show the same issues when downloading.

Sorry, it probably is really this issue all along.
