### ISSUE TITLE
[FEATURE] Ability to disable "this instance is corrupted"

### ISSUE THREAD

**Issue by Mixu78** [gorilla-devs/GDLauncher#239]
**Is your feature request related to a problem? Please describe.**
It is insanely annoying when GDLauncher starts saying an instance is corrupted. Who cares? Let us launch the instance anyway, as not all mods are on forge and adding some manually makes it "corrupted".

**Describe the solution you'd like**
A way to disable "This instance is corrupted" warnings.

**Describe alternatives you've considered**
Being able to launch the pack even if it is "corrupted".

**Additional context**

**Comment by hron84** [comment]
It could be reworded like: GDLauncher should support adding mods outside from CurseForge.

**Comment by Ladvace** [comment]
we are refactoring the code, we will fix it

**Comment by trevorjd** [comment]
I would like to know WHY it thinks the instance is corrupted! That would help me un-corrupt it!

**Comment by Mixu78** [comment]
Basically GDLauncher keeps track of what files are in your pack, if it notices some file got added/removed manually(not via GFLauncher) it thinks instance is corrupted.

**Comment by mbainter** [comment]
This also breaks when you want to sync between different systems (such as waypoints, map data, etc).
