### ISSUE TITLE
Provide a way to easily install Optifine

### ISSUE THREAD

**Issue by tiago4171** [gorilla-devs/GDLauncher#246]
**Is your feature request related to a problem? Please describe.**

> Yes it is, When I tried to install vanilla instances on Linux, but I think this it is multiplataform problem(not tested yet), I just don't know or can't install Optifine easily. 

**Describe the solution you'd like**

> I'm thinking about a button or something like that to add Optifine to an instance, specially at vanilla instances. I believe that in forge instances or modpacks this is so much easier, because is just drop the "optifine.jar" on mods folder and we are good to go.

**Describe alternatives you've considered**

> An alternative solution is just to provide a documentation explaning step-by-step with pictures how to add optifine on Vanilla and forge instances of Minecraft.

**Additional context**

> Sorry for my english, I'm not a native. I tried my best, with dictionary and stuff to provide a clear text.

Thanks...

**Comment by janagyjr** [comment]
The only way to install optifine is to download the mod and place it in your mods folder manually. The author of OptiFine does not allow for any other method of installing it.

**Comment by tiago4171** [comment]
> The only way to install optifine is to download the mod and place it in your mods folder manually. The author of OptiFine does not allow for any other method of installing it.

But without installing forge, we can not do this way. What's the way to do that on Vanilla Instances?

**Comment by janagyjr** [comment]
Setup the vanilla instance like you would a modded one. Forge won't prevent you from connecting to a vanilla server (I play on some vanilla servers with client-side mods installed such as JourneyMap, Inventory Tweaks, Mouse Tweaks, and Optifine).

**Comment by tiago4171** [comment]
Well, Thank you for the explanations.
