### ISSUE TITLE
GDLauncher Crashes When Opening Settings Menu

### ISSUE THREAD

**Issue by janagyjr** [gorilla-devs/GDLauncher#249]
**Describe the bug**
when I click on the gear icon to open the settings menu it says GDLauncher has crashed and to restart it. Restarting GDLauncher doesn't clear the bug.

**To Reproduce**
1. Go to 'GDLauncher'
2. Click on 'Gear Icon'
3. ???

**Expected behavior**
I expected to see the settings menu.

**Possible solutions**
I dunno.

**Screenshots**
![gdlaunchercrashout](https://user-images.githubusercontent.com/23646259/66721903-0bab6e00-edf7-11e9-8b65-87cdd2eefae8.png)

**Operating System:**
 - OS: Windows 10 Pro
 - Version 1903
- OS Build 18362.356

**Additional context**
Started happening after a recent update to the launcher.

**Comment by Daktyl198** [comment]
The most recent update was centered around fixing a bug with the mojang account logins. You could try logging out and back into your mojang account? It shouldn't help, but computers are weird sometimes. All of your data will remain when logging out and back in.

**Comment by janagyjr** [comment]
That fixed it.
