### ISSUE TITLE
Choose the location the launcher installs.

### ISSUE THREAD

**Issue by Uniform300** [gorilla-devs/GDLauncher#250]
Need the ability to choose what drive the Base GDlauncher installs to during install as alot of user use a ssd as an os drive and it is usually really small but can't figure out how to change where windows installs programs by default(if their is a way).

**Comment by dudeedud4** [comment]
"old" issue I know, but this is still not implemented.

**Comment by Rmdhn1** [comment]
still can't find it

**Comment by Normal69** [comment]
Win10 - still can't choose an installation path.

Presumed solution (seems working, just haven't extensively tested):
After install, exit,
move the whole installation directory to your preferred path,
restart,
set instance dir to your preferred path,
destroy all unneded directories fromRoaming and Local.

Happiness!
(correct me if I'm wrong please)

**Comment by Eskaan** [comment]
You can store the directory all data gets stored in. You can do that right after installation and that is about what we can do without doing some weird workarounds.
