### ISSUE TITLE
[Feature] Modpack version display

### ISSUE THREAD

**Issue by Discomanco** [gorilla-devs/GDLauncher#251]
~~_**Describe the solution you'd like**~~
~~Similar to what Twitch does, show the current version of the installed modpack, either in the info~~ ~~panel or below the name (currently has Forge Ver,~~

~~**Describe alternatives you've considered**~~
~~Naming packs with their version number seems silly~~

~~**Additional context**~~
~~Always nice for Beta testing or pack deving to know which version you're booting up~~

~~Instance overview could hold a lot of additional information regardless, like pack Author name, ~~~~version, last played and who knows what else_~~

Replace the MC Version with the Modpack Version on Instances with Modpacks

**Comment by kreezxil** [comment]
ditto
