### ISSUE TITLE
Settings Screen / settings buttons  Resulting in a crash

### ISSUE THREAD

**Issue by AzureDoom** [gorilla-devs/GDLauncher#258]
Clicking on the Settings button brings up the crashed screen. 

**To Reproduce**
1. Start the launcher
2. Click the settings cog
3. Ssssssorry error

**Expected behavior**
Get the settings screen.

**Screenshots**

**Operating System:**
 - OS: Windows
 - Version 10

**Additional context**
Launcher version 0.12.3

**Comment by garpu** [comment]
Getting the same thing on Linux, gdlauncher 0.12.3. (Slackware-current, 64-bit, OpenJDK 1.8.0.222)

**Comment by lag42** [comment]
Also getting this, same launcher version and on windows 10, reinstalling did not fix it

**Comment by garpu** [comment]
If you log your mojang account out, then log back in, it should resolve.

**Comment by Nanianmichaels** [comment]
Can confirm the issue and the resolution proposed by garpu.

It might have something to do with the Mojang account token not being valid anymore because this issue always happens to me when I've last logged in a while ago (like 2+ weeks), though that's just a wild guess on my part.

**Comment by tarikbir** [comment]
I also have the same issue and can confirm it is a Mojang account bug. I am having a problem with my instance having an account named **undefined**. Settings doesn't open so I can't revert back without uninstalling and redownloading. Hope they fix this issue ASAP.

**Comment by lag42** [comment]
i've found a workaround by just not using remember me and being signed into the vanilla launcher, you can click the button at the bottom and it will sign you in correctly

**Comment by tarikbir** [comment]
> i've found a workaround by just not using remember me and being signed into the vanilla launcher, you can click the button at the bottom and it will sign you in correctly

Wonderful workaround for now. So, remember me option doesn't work. I wonder if the in-game profile is fixed or not because it was showing the name **undefined** before.

**Comment by fabm3n** [comment]
From the logs: https://pastebin.com/YgQEctNL
