### ISSUE TITLE
Make the launcher Skinnable

### ISSUE THREAD

**Issue by kreezxil** [gorilla-devs/GDLauncher#263]
I understand that this might be a back burner project or even one that will never be implemented.

However,

I'd like the option to apply my own custom skin to the launcher and even have some zones in it where I can use my own html to provide click links, etc.

Example:

I have the World of Dragons mod packs. I'd like to be able to reskin (rebrand) the launcher to be dragon-like in feeling and have my packs listed at the top no matter what. And like to have some space on the side to put sponsor links or advertising links.

I'm kind of thinking this can be done already because of that console, how it looks, makes me think i'm in a web browser. however, assets in place to allow me to do it easily would be most excellent.

**Comment by furtabs** [comment]
Been in Old Branch for awhile but just isnt easily user customizable, but you can edit config.json manually
