### ISSUE TITLE
Remember me login issue

### ISSUE THREAD

**Issue by sscards55** [gorilla-devs/GDLauncher#265]
**Describe the bug**
The login bug relating to "Remember Me" not keeping you logged in still exists but in a different form. Now what happens is that your account will not stay logged in, but instead the launcher will set then username to "Undefined", this does still let you launch minecraft, but it does cause issues as you are effectively signing in as a different user. For example Thaumcraft will not remember any of your research.

**To Reproduce**
1. Open the launcher. (maybe it happens)

**Expected behavior**
You stay logged in.

**Possible solutions**
It's a technical issue, so I don't know. Maybe check that the previously logged in user is logged in if the user did not intentionally log out and the "Remember Me" box was ticked.

**Operating System:**
 - OS: Windows
 - Version: 10

**Comment by xynydev** [comment]
Same problem / Mac OS Mojave

**Comment by LindaJuffermans** [comment]
Still an issue; Win10 w/GD Launcher v0.12.4

**Comment by CmdrNorthpaw** [comment]
Can confirm issue on Manjaro Linux with v0.12.4

**Comment by pagameba** [comment]
Also happening for me periodically OSX with v0.12.4
