### ISSUE TITLE
Instances freeze at 99% download

### ISSUE THREAD

**Issue by jengeld4** [gorilla-devs/GDLauncher#268]
Trying to create an instance of a modpack (in this case FTB Unstable 1.14, but all other packs seem the samel). The pack seems to download but right at the end, the install freezes. The rest of the launcher still seems to work, but it won't finish the install, nor will it start downloading other packs.
Screen shots:
[https://gyazo.com/da0ac02d7ae89e552049bf469565ef5c](url)
[https://gyazo.com/c4c3e70d8d2a130e9fcfc614a6cdcfc5](url)

GDLauncher v0.12.3

**Comment by kreezxil** [comment]
# I just installed
this without a problem using explicit 64 bit. Below are some notes for you.

## btw
your images didn't render, when writing an issue, always click the preview tab to make sure that everything you are posting will be rendered, correct them if not

# what is wrong for real
1. Open GDLAUNCHER
1. install the pack again
1. click on the >_ in the upper left 
![image](https://user-images.githubusercontent.com/3880072/70537689-7ee70d00-1b26-11ea-819b-b8eb8b18374c.png)
1. click on console
1. scroll to the bottom and watch it

When the install gets to the hang mark, a nasty error will be displayed there

# likely solution
In all likelihood the GDLauncher is erroneously trying to do something with 32bit java. you need to tell it to use 64bit java explicitly.

1. click on the main cog 
![image](https://user-images.githubusercontent.com/3880072/70537839-bc4b9a80-1b26-11ea-9dee-40daa7dbf1e2.png)
1. click on java on the left and the unslide the autodected so you can entire an explicit path
![image](https://user-images.githubusercontent.com/3880072/70537925-dd13f000-1b26-11ea-86d0-eb7b9097bac9.png)
1. which you can browse for, make sure what you pick is 64 bit
![image](https://user-images.githubusercontent.com/3880072/70537977-f61ca100-1b26-11ea-9a5c-3d19f0849eea.png)

reinstall the pack, everything should be fine at that point.

# send us your pastes
if not, the copy what's in the console and paste it into https://gist.github.com and send the resulting url here.
![image](https://user-images.githubusercontent.com/3880072/70538465-bf935600-1b27-11ea-8f0d-3e506e7f074c.png)

copy either of these and paste them here
![image](https://user-images.githubusercontent.com/3880072/70538520-dafe6100-1b27-11ea-8091-c4dbae9a4494.png)

**Comment by jengeld4** [comment]
Ok, looking at Java in my control panel pointed me to C:\Program Files\Java\jre1.8.0_231\bin\javaw.exe which it says it is x86_64 architecture, so I'm assuming that's the right path. I changed the directory for both the Javaw.exe and Java.exe, both had the same problem.

After further testing, I found that "Life in the Village" (a 1.12 pack) does seem to install correctly, and so far works, so it may just be an issue with the 1.14 packs that I been trying.

Here is the long error that's create at the point of hanging: https://gist.github.com/jengeld4/6e2ec78d4a21971a23bf611e8a37f53a

As a note, Several other errors showed up earlier in the same install process that seem to be related to missing configs. Posted them separately in case this is a separate issue.
https://gist.github.com/jengeld4/aac59129fd6b7f23592d715b02ebb0f5

**Comment by Ommina** [comment]
@jengeld4   That almost looks like it is having a fit because of the space in the username.  I'd be interested in knowing if trying to save the packs to an instance without a space in the path is more successful.

**Comment by jengeld4** [comment]
Well, moving the instance to my secondary drive with no spaces in the file path seems to have worked. The instances are downloading correctly, and don't crash when I start them, though they seem to take forever to load. Thanks for the help guys.

Edit: Can confirm that the JankySkyblock pack installed and ran. Still having issues with FTBUnstable 1.14, but well, unstable is literally in the name...

**Comment by MikaelOre** [comment]
@jengeld4 well, I have the same issue and even though I tried to follow up with your conversation I couldn't get the solution, how do I fix it?
![Anotación 2019-12-13 135106](https://user-images.githubusercontent.com/58832246/70829682-ec5b9d80-1db3-11ea-962b-a3fce2b78f73.png)

**Comment by jengeld4** [comment]
In the options, there is a tab that determines where the instances are saved. I'm not at my computer to take screen shots, but I just changed the instance folder to E:\GDLauncher\instances or something to that effect. As long as there is no space in the file path, it seems to work with 2 out of 3packs I tried.
Well, 3 out of 3 for this particular problem. Like I said, FTB Unstable isn't launching but it does install

**Comment by kreezxil** [comment]
# Changing the Path for all instances

> ## Make sure you are logged on
> ![image](https://user-images.githubusercontent.com/3880072/70849938-a7367a80-1e4a-11ea-8fa9-d81101768022.png)

> ## Enter the master settings (if you get the creeper crash, you're not logged on)
> ![image](https://user-images.githubusercontent.com/3880072/70849949-bf0dfe80-1e4a-11ea-9e72-e99613e5189d.png)

> ## Click on instance
> ![image](https://user-images.githubusercontent.com/3880072/70849959-cf25de00-1e4a-11ea-9faf-eb082cb414de.png)

> ## Activate the path override
> ![image](https://user-images.githubusercontent.com/3880072/70849974-f086ca00-1e4a-11ea-92fe-857012fbdb5d.png)

> ## Enter the new path without spaces that all instances will download to
> ### this will not rejigger your existing installed packs, you'll have to uninstall and reinstall them for that
> ![image](https://user-images.githubusercontent.com/3880072/70849991-1f9d3b80-1e4b-11ea-9654-93bf1ca7be48.png)

**Comment by TOLoneWolf** [comment]
Don't have to uninstall/reinstall packs when moving folders but it is the simplest way to deal with it.
https://imgur.com/a/l63OppM

**Comment by Pixlsaurus** [comment]
Help!!! 
on the GDlauncher hing i cant finish downlading an instance in this case the aether legacy mod it stops on the finalising overrides scren.
I checked the logs and this is what they said
![image](https://user-images.githubusercontent.com/84007619/117779102-b1e48180-b281-11eb-8302-228975d4fa59.png)
I cant play this and I have for a long time so please help
Thanks

**Comment by Pixlsaurus** [comment]
doesn't matter deleted old version and updated - now works
