### ISSUE TITLE
Permit manual import of existing mod files

### ISSUE THREAD

**Issue by trevorjd** [gorilla-devs/GDLauncher#269]
**Is your feature request related to a problem? Please describe.**
I've spent the day troubleshooting in No.1 Piece of Junk "launcher" and have all the files I need already downloaded.  I was glad to find that GDLauncher supports Forge 1.14 but was surprised that it's not simple to just create a new instance and drag my files into the mods folder.

Funny thing is that if I use your built-in downloader to add one mod, it will now display everything that was manually moved into the folder, but if you remove that mod again, it says the folder is empty.

**Describe the solution you'd like**
I'm sure you've got a good reason for maintaining a separate index so it would be helpful if you added the ability to import mod files from a folder.

**Describe alternatives you've considered**

**Additional context**

**Comment by TOLoneWolf** [comment]
#264
