### ISSUE TITLE
[Feature] Detect 64 bit Java

### ISSUE THREAD

**Issue by kreezxil** [gorilla-devs/GDLauncher#270]
Currently GD Launcher erroneously selects 32bit java when 64 bit java is clearly installed.

GD Launcher should autodetect 64 bit java and it's path.

**Comment by TOLoneWolf** [comment]
Going to add this info here as it fits this issue.


Info for identifying java version, brand/vender/JVM, install location, and java arch type.

https://github.com/AdoptOpenJDK/openjdk-build/issues/1188
java -XshowSettings:properties -version
- sun.arch.data.model  <-- java arch
- java.home  <-- installl location
- java.vendor <-- brand/vender name
- java.version
- java.vm.name <-- possible location for hotspot vs other JVM?
