### ISSUE TITLE
[Feature] Grouping certain instances together

### ISSUE THREAD

**Issue by QazCetelic** [gorilla-devs/GDLauncher#271]
**Is your feature request related to a problem? Please describe.**
Yes, the instance tab gets very cluttered.

**Describe the solution you'd like**
Add folders, which can contain instances. So you can sort it.

**Describe alternatives you've considered**
Maybe groups like in MultiMC.

**Additional context**
None

**Comment by irunatbullets** [comment]
Being able to tag instances as favourites (or just making that group yourself) and having the ability to collapse groups would be pretty handy too.  (Please excuse my elite design skillz)

![groups-gdlauncher](https://user-images.githubusercontent.com/344908/105140946-4bfead80-5b5d-11eb-9b3e-5c1b54f7472b.png)

**Comment by Smolax** [comment]
Are there any plans for this feature? Because it would really come in handy
