### ISSUE TITLE
GDLauncher crashes when I press the settings buttons

### ISSUE THREAD

**Issue by QazCetelic** [gorilla-devs/GDLauncher#272]
**Describe the bug**
It crashes when i press the settings button, at the right top, and it says "GDlauncher ran into a creeper", when i press restart it just closes.

**To Reproduce**
1. Open GDLauncher
2. Click the settings icon at the top right
3. See error

**Expected behavior**
It shows the settings

**Possible solutions**
Idk.

**Screenshots**
Won't really help

**Operating System:**
 - OS: Linux (Kubuntu)
 - Version 19.10

**Comment by nurd6** [comment]
I am also having this issue on Windows 10.

**Comment by AzureDoom** [comment]
Dupe of #258 that includes a work around

**Comment by kreezxil** [comment]
@QazCetelic @nurd6 the solution is to login.

![image](https://user-images.githubusercontent.com/3880072/70913289-5bffa180-1fdb-11ea-8bc8-b44e48760c2e.png)

If clicking on 1 crashes the client, then 2 is empty with no name meaning you need to log in by clicking 3.

It's a known bug and being worked on.

**Comment by QazCetelic** [comment]
Thanks,  should i close it because it's a dupe?

**Comment by TOLoneWolf** [comment]
Going to close since it is a duplicate of known bug already on the issue tracker.

**Comment by kreezxil** [comment]
You should link the duplicate report for posterity and to help the original
poster find that thread.

**Comment by TOLoneWolf** [comment]
>  kreezxil
> You should link the duplicate report for posterity and to help the original
> poster find that thread.

Yeah i guess it would be good to have it at the bottom of the issue conversation.

> AzureDoom
> Dupe of #258 that includes a work around
