### ISSUE TITLE
[Feature Request] Ability to filter out Fabric mods

### ISSUE THREAD

**Issue by TheDarkPreacher** [gorilla-devs/GDLauncher#273]
**Is your feature request related to a problem? Please describe.**
Yes, when I try and make a modpack using Forge mods, Fabric mods are mixed in, with no way to filter them out. It's extremely frustrating.

**Describe the solution you'd like**
Add in a filter setting to filter by either Fabric or Forge versions of mods.

**Describe alternatives you've considered**
I considered suggesting this to Curseforge, but they have no way of requesting things, or at least, no obvious way. And even if the suggestion was put into their hands, good luck getting them to actually implement it. Hard enough getting them to approve a modpack without writing a 5 page essay describing it.

**Comment by AzureDoom** [comment]
Wow so hard to find CurseForge feedback system where you do requests **/s** 
![image](https://user-images.githubusercontent.com/7415711/70955919-656f2500-2040-11ea-8df5-16b3513cbf65.png)
This is most likely something that would need done on the CurseForge/mod uploader level. The mod would need tagged with the proper loader for the launcher to even know if it's a Forge or Fabric mod.
![image](https://user-images.githubusercontent.com/7415711/70955552-4a4fe580-203f-11ea-9d9c-38b1cac689dd.png)  
Most mod devs do this but if the dev doesn't, then the launcher has no way telling if it's a forge release or fabric release. 

It's impossible to do a reliable system of selecting the proper release.

**Comment by 23SRLITheGamer** [comment]
The main problem with the current system is that the sorter that does only show forge mods, shows forge mods for ALL VERSIONS, not just for one version.
