### ISSUE TITLE
Forge 1.15 Not Starting

### ISSUE THREAD

**Issue by AzureDoom** [gorilla-devs/GDLauncher#274]
**Describe the bug**
Forge 1.15 does not start on the launcher. 

**To Reproduce**
1. Create a new instance 
2. Choose the latest 1.15 forge release
3. Try to start instance. 

**Expected behavior**
Game would start

**Possible solutions**
Seems a new library that was added isn't being loaded. 

**Screenshots**
![image](https://user-images.githubusercontent.com/7415711/70967895-c6f5ba80-2065-11ea-8f4c-f79cf0d6968b.png)

**Operating System:**
 - OS: [Windows]
 - Version [0]

**Comment by AzureDoom** [comment]
Closing as issue was with Forge. Forge 1.15 is working!

**Comment by kreezxil** [comment]
can we build packs with GD Launcher for 1.15?

**Comment by AzureDoom** [comment]
I am unsure. The modpage doesn't work for me with 1.15/1.15.1
![image](https://user-images.githubusercontent.com/7415711/71126234-9ec9a100-21b6-11ea-9b5a-cd6957556cd8.png)

**Comment by AzureDoom** [comment]
Tested with an empty aka no mods with it export and imported it into a private edited version of GD Launcher I have, it does in fact export fine.
