### ISSUE TITLE
1.15/1.15.1 Mod Manager add new mods page doesn't load

### ISSUE THREAD

**Issue by AzureDoom** [gorilla-devs/GDLauncher#276]
**Describe the bug**
Mod Manager doesn't load the mods page for 1.15/1.15.1 packs.

**To Reproduce**
1. Create a 1.15/1.15.1 instance.
2. Open the Mod Manager for that instance. 
3. Click Add Mods

**Expected behavior**
You would be able to choose mods to add. 
![image](https://user-images.githubusercontent.com/7415711/71126720-8c039c00-21b7-11ea-920c-cd95f6d400f9.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/7415711/71126338-d20c3000-21b6-11ea-88a4-e75a36798a92.png)

**Operating System:**
 - OS: [Windows]
 - Version [10]

**Comment by TOLoneWolf** [comment]
This is a curseforge issue not the launchers fault. Has to do with them not dealing with the new version tag.

Until this page shows mods:
https://www.curseforge.com/minecraft/modpacks?filter-game-version=1738749986%3A68722&filter-sort=4

GDL will also not show any mods.

**Comment by TOLoneWolf** [comment]
This is a cursforge issue to do with their API that the twitchapp uses. GDLauncher gets its mod list from curseforge the same way.

Until this has any content between [] GDL will not list anything.

https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&gameVersion=1.15

Should look similar to this:
https://addons-ecs.forgesvc.net/api/v2/addon/search?categoryId=0&gameId=432&gameVersion=1.14

**Comment by AzureDoom** [comment]
Just closing this as you can now search for 1.15.1 mods.
