### ISSUE TITLE
Any instance with Forge does not launch

### ISSUE THREAD

**Issue by murphyneko** [gorilla-devs/GDLauncher#278]
Every time I try to launch instance with Forge, playing icon appears and dissapears after 1 second, and Minecraft isn't starting. Also, I cannot open folder of instance.

1. Create any instance with Forge
2. Try to launch it
3. Try to open folder of instance
Expected normal launch of instance

![ezgif-7-1af004377a44](https://user-images.githubusercontent.com/47712032/71305246-dec09c00-23e1-11ea-8f2f-ecdd4713c0ed.gif)

OS: Ubuntu 18.04

Also I found that thing while launching GDlauncher through ./:
11:01:34.428 › Config store: /home/ivan/.config/GDLauncher/config.json
11:01:36.465 › Error: Could not connect
    at Socket.o (/tmp/.mount_GDLaunl8ZCze/resources/app.asar/app/webpack:/app/main.prod.js:18829:16)
    at Object.onceWrapper (events.js:282:20)
    at Socket.emit (events.js:194:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
11:01:37.288 › Checking for update
11:01:37.289 › CHECK_FOR_UPDATES
11:01:39.858 › Update for version 0.12.3 is not available (latest version: 0.12.3, downgrade is allowed).

**Comment by murphyneko** [comment]
Just found out about dev tools, so I tried them.
12:59:13.323 › java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by kreezxil** [comment]
Thankfully GDevs created a FAQ recently:
https://gist.github.com/TOLoneWolf/a167b2b0513667a0cbc9579c1adbea3c

I present two solutions to an issue here:
https://github.com/gorilla-devs/GDLauncher/issues/268 (disregard the title
of the issue)

**Comment by LelouBil** [comment]
I just want to add on this since I got the same problem and fixed it.
I had exactly the same error as you but GDLauncher was already using 64 bit Java.
The problem I had was about the java version. I had Java 13 installed and when I put in manually the path to java 8 in the settings it worked.

**Comment by TOLoneWolf** [comment]
Closing this issue as instructions above (Java version change) should fix the issue and since no update from the user has been posted in over 2 weeks.
