### ISSUE TITLE
Forge update button in modpack "Manage" menu.

### ISSUE THREAD

**Issue by Dubl33** [gorilla-devs/GDLauncher#280]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to add a mod to a modpack but the modpack hasn't been updated in ages and the mod requires a newer forge version than the the one the modpack had.

**Describe the solution you'd like**
There should be an option in the "Manage" window of modpacks where you can update the forge version like you're able to do in the twitch launcher.

**Describe alternatives you've considered**
I saw there was an option to uninstall forge and then reinstall any other forge version you wanted but for some reason it didn't work.

**Comment by furtabs** [comment]
#340
