### ISSUE TITLE
Curseforge modpack integration skipping resourcepacks part

### ISSUE THREAD

**Issue by GameBurrow** [gorilla-devs/GDLauncher#281]
**Describe the bug**
Curseforge integration does not download resourcepacks written into the curseforge modpack. 

**To Reproduce**
1. Install our [The Society - Transportcraft](https://www.curseforge.com/minecraft/modpacks/the-society-transportcraft) by GameBurrow
2. Open instance folder and you'll see that resourcepacks folder is empty.

**Expected behavior**
The folder should look like this:
![image](https://user-images.githubusercontent.com/4341091/71563430-12fa2380-2a98-11ea-9573-86e8d1688b1a.png)

**Possible solutions**
N/A. 

> Problably useless to you, but I implemented a solution for this in my own small downloader for our dockerized server (my first java application, so do not judge please ;) ). The API I used provided a object type: mod or resourcepacks and I put stuff into folders according to that type. https://dev.sepaurg.eu/thesociety/minecraft-downloader

**Additional context**
In case of our modpack, this is a critical feature, because we have a mod in our pack that relies on resourcepacks for it's content (Immersive Railroading).

**Comment by trevorjd** [comment]
GDL 0.12.3 under Win10

Tonight, I did a fresh install of Project Ozone 3, pack ver 3.1.45 and after spending the best part of 10 mins waiting for the pack to start up, it crashed.  Tried again with exactly the same error.
https://gist.github.com/trevorjd/393c6cd371b7477282d4ac57c30bbe55

Loading the pack up in Satan's Favourite Launcher, it runs fine.  Immediate difference I spotted was that the GDL instance mods folder had two extra files. One was the GDLreadme.txt but the other was Ozone_Resources_3.zip.jar

Comparing to the SFL instance, that file should be in ~/resourcepacks not ~/mods and _not_ a .jar file!
