### ISSUE TITLE
[FEATURE] Mods Manager

### ISSUE THREAD

**Issue by kreezxil** [gorilla-devs/GDLauncher#282]
Mods Manager should have the option to click a mod entry and goto that mods page. It should also show the mods actual name and not just its file name.

Current GDL mods manager information:
![image](https://user-images.githubusercontent.com/3880072/71605673-6029d400-2b30-11ea-95bc-47dcbe651247.png)

how twitch does it, which i believe would be the ideal layout:
![image](https://user-images.githubusercontent.com/3880072/71605739-ec3bfb80-2b30-11ea-8e14-3c62a2b34481.png)

**Comment by furtabs** [comment]
#123
