### ISSUE TITLE
Links in descriptions for packs don't work, nor in changelogs.

### ISSUE THREAD

**Issue by kreezxil** [gorilla-devs/GDLauncher#285]
**Describe the bug**
Links in descriptions for packs don't work, nor in changelogs.

**To Reproduce**
1. pick a pack that has links in its description or changelog
1. click on links
1. keep clicking on those links like a madman hoping they will work
1. never gonna profit, always gonna get let down.
1. very similar to the Twitch problem with links.

**Expected behavior**
clicking links to open default browser and goto the link clicked.

**Operating System:**
 - OS: Windows 10
- client: 0.12.3

**Comment by TOLoneWolf** [comment]
An example:
https://www.curseforge.com/minecraft/modpacks/rlcraft

Some links are changed to a redirect url which breaks those hyperlinks:
![GDLauncher_WkbPlOLbtc](https://user-images.githubusercontent.com/8376628/71759199-0ba79100-2e6f-11ea-8cd6-cd8abff39ce1.png)

Some links curse leaves alone so they work:
![GDLauncher_xy8qlPQHqX](https://user-images.githubusercontent.com/8376628/71759200-0e09eb00-2e6f-11ea-9001-f1a988512e33.png)

Example URL:
/linkout?remoteUrl=https%253a%252f%252fwww.bonfire.com%252fstore%252fshivaxi%252f

%252f === /
%253a === :

/linkout?remoteUrl=https://www.bonfire.com/store/shivaxi/

**Comment by TOLoneWolf** [comment]
some how when those links are added they are getting double encoded (curseforges side).
/ gets turned into %2F
%2F gets turned into %252F

Another Example url:
https://www.curseforge.com/linkout?remoteUrl=https%253a%252f%252foptifine.net%252fadloadx%253ff%253dOptiFine_1.12.2_HD_U_E3.jar

%252f === /
%253a === :
%253f === ?
%253d === =

https://optifine.net/adloadx?f=OptiFine_1.12.2_HD_U_E3.jar

**Comment by kreezxil** [comment]
aye and Twitch has this problem too. but all their links go to the linkout
profile on Twitch.

**Comment by kreezxil** [comment]
if this can be solved, GD Launcher will have another leg up on Twitch
Launcher.

Already GD Launcher:
* enables Linux users to participate in pack building, exporting, and
maintaining in the way that Windows users have enjoyed from the time of the
first Curse client.
* this second is a huge biggie, Twitch no longer launches old packs, such
as 1.8 and older. Forcing 1.8, 1.7.10 and older pack fans to use other
launchers, not an issue with GDL.
* so resolving this issue with links will give GDL a major plus.

it might seem a little too intensive to add an url scrubber to the code but
I feel it would be worth it. You already know about double encoded slashes.
Now you just have scrub out the linkout portion. From my observation I've
only ever seen a problem with linkout urls.

I think the reason for LINKOUT was that CF and possibly Twitch felt it was
their social duty to provide some modicum of protection to the masses for
perverted or scam related links. However that should be the domain the
security software on ones system. Code complexity on the part of Twitch and
CurseForge can be simplified by removing that. My suggestion is to not go
down the road of being a Link Warrior. I know you're not, but wanted to
make it known that you shouldn't.

Looking forward to a patch that rectifies this

**Comment by TOLoneWolf** [comment]
I know there is one easy way to do it (probably not the right way, idk still learning javascript). I actually already tested doing it and works fine on the links. I would like to make it only check the hyperlink tags but not sure how to do that yet in js.
