### ISSUE TITLE
need help please respond 

### ISSUE THREAD

**Issue by chrisgames4444** [gorilla-devs/GDLauncher#288]
when i download a minecraft mod pack and right click the instance nothing happens and when i right  click and press create shortcut a error appears please help

**Comment by furtabs** [comment]
What OS and Launcher version?

**Comment by kreezxil** [comment]
that's not true, and don't take offense at that.

instead goto https://github.com/gorilla-devs/GDLauncher/issues/268 as there are two issues in that thread. One of which if not both will apply to your given situation. There are solutions presented for both issues there with pictures.

**Comment by TOLoneWolf** [comment]
Take a look at section "Minecraft Doesn't Start Causes" at this link:
https://gist.github.com/TOLoneWolf/a167b2b0513667a0cbc9579c1adbea3c

If those do not solve your issue. please upload the log file from GDL and what OS your using.

**Comment by TOLoneWolf** [comment]
Shortcut error message:
![GDLauncher_owDVEsN5oL](https://user-images.githubusercontent.com/8376628/71948649-53dbf180-3196-11ea-8240-546cbf9bf1b8.png)

```
Error creating instance symlink: 
Error: Command failed: 
powershell 
$s=(New-Object -COM WScript.Shell).CreateShortcut('%userprofile%\Desktop\WyldVanilla-1.0.5.lnk');
$s.TargetPath='C:\Users\User\AppData\Local\Programs\gdlauncher\GDLauncher.exe';
$s.Arguments='-i WyldVanilla-1.0.5';
$s.Save()

Unable to save shortcut "C:\Users\User\Desktop\WyldVanilla-1.0.5.lnk".
At line:1 char:213
+ ... auncher\GDLauncher.exe';$s.Arguments='-i WyldVanilla-1.0.5';$s.Save()
+                                                                 ~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], DirectoryNotFoundException
    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException
```


Changing it from `%userprofile%\Desktop` to `[Environment]::GetFolderPath("Desktop")` Fixes it for me.
Reason for it break is my Desktop folder is not on my `C:\` drive. I have it moved to `D:\` so following my userprofile leads to a dead path. I am assuming something similar might be happening on chrisgames4444 path.

```
$s=(New-Object -COM WScript.Shell).CreateShortcut(([Environment]::GetFolderPath("Desktop") + '\WyldVanilla-1.0.5.lnk'));
$s.TargetPath='C:\Users\User\AppData\Local\Programs\gdlauncher\GDLauncher.exe';
$s.Arguments='-i WyldVanilla-1.0.5';
$s.Save()
```

**Comment by TOLoneWolf** [comment]
What does the log show after trying to launch a pack/instance?
https://github.com/gorilla-devs/GDLauncher/wiki/How-to-view-console-and-log-files

**Comment by TOLoneWolf** [comment]
Maybe this issue: [No error in console](https://github.com/gorilla-devs/GDLauncher/wiki/FAQ-Frequently-Asked-Questions#not-starting-no-error-in-console)  
Please see the other issues: [Minecraft Doesn't Start Causes](https://github.com/gorilla-devs/GDLauncher/wiki/FAQ-Frequently-Asked-Questions)  
And let us know if fixed or still has the issues.

**Comment by TOLoneWolf** [comment]
Closing as user never responded whether or not issue still existed after suggested fix. And now there is a ticket open for the shortcut issue it self so this one longer is needed to be open.
