### ISSUE TITLE
[FEATURE] Dropdown for mods being added need to be wider

### ISSUE THREAD

**Issue by kreezxil** [gorilla-devs/GDLauncher#289]
**Is your feature request related to a problem? Please describe.**
The current drowndown select for which mod version to install is too narrow.

**Describe the solution you'd like**
The dropdown select for which mod version to install needs to be wider. Or at least have a tooltip displaying it's full filename.

the dropdown should be at least as wide as the useable space in the launcher.
![image](https://user-images.githubusercontent.com/3880072/71771057-d052a400-2efa-11ea-8912-290e02492867.png)

**Comment by TOLoneWolf** [comment]
#240
