### ISSUE TITLE
1.14 Forge modpack sometimes won't launch: Could not find or load main class cpw.mods.modlauncher.Launcher

### ISSUE THREAD

**Issue by bluebear94** [gorilla-devs/GDLauncher#293]
**Describe the bug**
1.14 Forge modpacks sometimes won't launch; when I open the console, I get the message `Could not find or load main class cpw.mods.modlauncher.Launcher`.

**To Reproduce**
1. Browse modpacks and select one for 1.14 Forge (such as [Harrowing Adventure](https://www.curseforge.com/minecraft/modpacks/harrowing-adventure))
2. Create an instance of it
3. When done downloading, try to launch it
4. Open the console

**Expected behavior**
The instance should launch.

**Operating System:**
 - OS: Linux (Manjaro)
 - Version 0.12.4 (AppImage version)
 - Java: OpenJDK v8

**Additional context**
Vanilla Minecraft (tested 1.15.1) launches without problems.
Using 'Repair' on the modpack sometimes allows it to launch.

**Comment by TOLoneWolf** [comment]
Please upload the GDL log file after having the issue launching.  
https://github.com/gorilla-devs/GDLauncher/wiki/How-to-view-console-and-log-files
