### ISSUE TITLE
[0.12.4] Export not Twitch Compatible

### ISSUE THREAD

**Issue by kreezxil** [gorilla-devs/GDLauncher#295]
**Describe the bug**
The export doesn't make a compatible file for importing into Twitch.
Yes, the mods import in, but the configs do not.
Apparently Twitch expects something in one of the files it requires for importing, not just a presence in the overrides.

Consistently even in 0.12.3 it Twitch would not import the config folder from the overrides folder. GDL handles the import file just fine. Twitch is expecting something magical that is clearly not exported by GDL.

What other information do you need, let me and I'll gladly provide it.

**Comment by TOLoneWolf** [comment]
the manifest is missing the `"overrides": "overrides"` key value pair that is used by twitch to find the "extra files" to copy to the new instance folder when importing.

https://github.com/gorilla-devs/GDLauncher/blob/master/app/components/ExportPackModal/ThirdStep.js#L63

**Comment by kreezxil** [comment]
nice, that should be an easy fix. I'm really trying to abandon Twitch and
ensuring our exports are 100% compatible with Twitch will help me to do
that. If you're not aware I'm an avid pack developer. I have nearly 55
packs now. I make on average a new pack each month.
https://www.curseforge.com/members/kreezxil/projects
