### ISSUE TITLE
Mac OSX Can't Start Instance

### ISSUE THREAD

**Issue by SpongebobVEVO** [gorilla-devs/GDLauncher#296]
**Describe the bug**
I am simply unable to begin instances when I select launch. It shows launching, then ends with the error "exception in thread main."

**To Reproduce**
1. Install a modpack (I installed ATM4.)
2. Right-click on modpack, click launch.

**Expected behavior**
I expected minecraft to start and the pack to launch.

**Possible solutions**
I have honestly no clue.

**Screenshots**
N/A

**Operating System:**
 - OS: MacOS Catalina
 - Version v0.12.4

**Additional context**
https://hastebin.com/ohoduwutuk.py Issue on line 62.

**Comment by TOLoneWolf** [comment]
Your machine has Java 13.0.1 (line 6 of you hastebin) which is not compatible with minecraftforge the mod loader. You will need to change the Java version gdl is trying to launch.

Gdl and Java location:
https://github.com/gorilla-devs/GDLauncher/wiki/Check-Java-Version#macosx-java-locations

Grab Java 8 from Oracle or adoptopenjdk:
https://github.com/gorilla-devs/GDLauncher/wiki/FAQ-Frequently-Asked-Questions#Java-64-bit-Installers
