### ISSUE TITLE
Add custom screen resolution for instances

### ISSUE THREAD

**Issue by XEJK** [gorilla-devs/GDLauncher#300]
**Is your feature request related to a problem? Please describe.**
I am asking for this feature as I have the problem that some screen elements are messed up in  instances using the standard Minecraft resolution

**Describe the solution you'd like**
Add a Custom screen resolution option on instances similar to MultiMC

**Comment by Teibidh** [comment]
Second this one. I've resorted to using the Vanilla launcher and just using this and Twitch (depending on the scenario) to do my pack management for this very reason.

**Comment by furtabs** [comment]
#259
