### ISSUE TITLE
Export To Twitch Pack - project id wrong json type

### ISSUE THREAD

**Issue by kreezxil** [gorilla-devs/GDLauncher#301]
Using the private build that is suppose to fix the key/pair issues with export files so that Twitch will import them.

Twitch did import them but when I used the export to publish my pack the CurseForge team responded with:

```
Notes: Invalid manifest.json file:
References project ID 353448 (World of Dragons - Player's Choice (wpc)), should be project ID 353448 (World of Dragons - Player's Choice (wpc)).
You must create pack files from scratch using the Twitch Desktop App. You cannot modify an existing pack.
```

clearly the project id's are the same. I wonder what exactly they are complaining about.

**Comment by kreezxil** [comment]
Look at the exports there are clear differences.

Twitch export is in the top (GREEN), GDL export is in the bottom (RED).
Twitch includes a modlist.html, GDL does not. GDL should tho.
Twitch manifest is at least 80% larger than the GDL manifest.

![image](https://user-images.githubusercontent.com/3880072/72936392-bacbdf80-3d2c-11ea-8147-914d20d55176.png)

Notable differences between the manifest.json.

Twitch is on the left, GDL is on the right.
GDL is whitespace removed, can't image that curseforge would have a problem parsing that, but they might. Considering they apparently hired monkeys.
![image](https://user-images.githubusercontent.com/3880072/72936654-3cbc0880-3d2d-11ea-81e3-2075761e0ecc.png)

Interestingly enough GDL has 4 more lines, when you format its json file vs Twitch's.
Twitch is on the left and GDL is on the right.
![image](https://user-images.githubusercontent.com/3880072/72936743-75f47880-3d2d-11ea-8e65-b44b81a595b1.png)

Author line is missing from the GDL manifest, its in the Twitch manifest.
Twitch on the left, GDL on the right.
![image](https://user-images.githubusercontent.com/3880072/72936931-cff53e00-3d2d-11ea-8e3d-e66991d90b43.png)

And this is probably where the problem is. Twitch records the project id as a number, GDL records it as a string.
Twitch on the left, GDL on the right
![image](https://user-images.githubusercontent.com/3880072/72937010-eef3d000-3d2d-11ea-81ea-6f9da166d711.png)

**Comment by TOLoneWolf** [comment]
I haven't uploaded modpacks to twitch before, so how does it get the projectID in the first place?
When I export packs from twitch it does not have that line so it must be added later after exporting from an existing pack?

Do you have to install your own pack after you have submitted it the first time to twitch?

Edit:
Got my answer in discord.
Yes it gets uploaded first without one then after installing it and exporting again it has one to use.

**Comment by kreezxil** [comment]
for the sake of completeness the relevant chat portion:

```
2:45 PM] TOLoneWolf: @Kreezxil how do you setup a new modpack that your going to upload to twitch as a pack?
I know it doesn't have a project id yet at that point in the export file.
I am trying to figure out when that gets added to the manifest the first time.
[2:45 PM] Kreezxil: @TOLoneWolf mixed mode, doesnt that mean she has both?
[2:45 PM] Kreezxil: Twitch handles the nuances for me
[2:46 PM] TOLoneWolf: do you install your pack back into the launcher after it has been created on twitch the first time?
[2:46 PM] Kreezxil: i build a raw pack, and i export, i believe it doesn't generate a project id, so I post that and when it gets approved by cf, the project id gets pushed in somehow.
[2:46 PM] Kreezxil: after that I download the pack and I have a properly generating json afterwards
[2:46 PM] TOLoneWolf: okay
[2:47 PM] TOLoneWolf: thats what i though
[2:47 PM] Kreezxil: then everytime i issue an update we're golden, they don't complain
[2:47 PM] TOLoneWolf: got it.
[2:47 PM] Kreezxil: i think i gave you enough data to fix the export engine
[2:48 PM] TOLoneWolf: yeah it was just making it int instead of string, and getting the author name somehow.
[2:48 PM] Kreezxil: i think it's basicaly how gdl and twitch know to pull the profile image for the pack icon. if there is no pack icon, it's a new custom build.
[2:49 PM] Kreezxil: the author name appears to come from the launcher on export by which mc character is currently logged on
```

**Comment by kreezxil** [comment]
ok, tested it, when you update the FORGE it looks like it knocks out the project id, this doesn't happen when Twitch is managing it.

Also it appears the GDL removes all spaces and decorations from the pack name.

GDL is on the left, and Twitch is on the right
![image](https://user-images.githubusercontent.com/3880072/73208169-95afe600-410b-11ea-8ca0-9e1170411cbc.png)

**Comment by kreezxil** [comment]
I'm going to upload this to CurseForge to see if they accept it. If they do, the missing project ID won't matter too much. Will know for sure in a moment.

**Comment by kreezxil** [comment]
Ok, they excepted it without the project id number. so that is a minor bug to fix.

![image](https://user-images.githubusercontent.com/3880072/73209503-f6402280-410d-11ea-92a2-bd7c69b5da94.png)
