### ISSUE TITLE
TOLONEWOLF incorrect pack icons listed in browse mode

### ISSUE THREAD

**Issue by kreezxil** [gorilla-devs/GDLauncher#307]
@TOLoneWolf in the last copy that you gave me that allows me to make exports that curse accepts, the icons in the master browse for pack are wrong. For example my mod pack **God Block** is showing as this 
![image](https://user-images.githubusercontent.com/3880072/73359045-9197db80-4265-11ea-89f2-4fc2511276a8.png)

which is the original logo for the pack but not the current image.

![image](https://user-images.githubusercontent.com/3880072/73359121-bbe99900-4265-11ea-8b99-9d0bb6ffb6bb.png)

**Comment by furtabs** [comment]
Twitch Launcher had the same issue btw. I removed the asset in my pack in 2015, never knew they still stored it
