### ISSUE TITLE
pack export for twitch - duplicates mod id in manifest

### ISSUE THREAD

**Issue by kreezxil** [gorilla-devs/GDLauncher#310]
The export for the version I have from you that allows exports that CF likes and Twitch will import currently doesn't remove duplicates on export.

a pack I've been working on just got refused with this message, all the ids are just there to show the number of duplicates their bot found
```
Invalid manifest.json file:
Duplicate fileID references: fileID 2871463, fileID 2871246, fileID 2870559, fileID 2859264, fileID 2870411, fileID 2859921, fileID 2871235, fileID 2870496, fileID 2871647, fileID 2871238, fileID 2869194, fileID 2871475, fileID 2871477, fileID 2871414, fileID 2871240, fileID 2869028, fileID 2866352, fileID 2871478, fileID 2868369, fileID 2866285, fileID 2869178, fileID 2870412, fileID 2862435, fileID 2844513, fileID 2868969, fileID 2871717, fileID 2868373, fileID 2869421, fileID 2869117, fileID 2871865, fileID 2871545, fileID 2871351, fileID 2871370, fileID 2869118, fileID 2868347, fileID 2847409, fileID 2870036, fileID 2870786, fileID 2844514, fileID 2869359, fileID 2866509, fileID 2868525, fileID 2871783, fileID 2844695, fileID 2845661, fileID 2871442.
```

**Comment by bluebear94** [comment]
It looks like ~~removing~~ disabling a mod doesn't delete its entry from config.json. Perhaps that's what's causing the bug.

**Comment by bluebear94** [comment]
Was this issue fixed?

**Comment by kreezxil** [comment]
holy smokes, I want to know if it's been fixed too, I don't see a pr hash as to why this was closed? @CrankySupertoon 

Even a reason like you won't be supporting pack exporting would be useful.

**Comment by furtabs** [comment]
We are just closing all old Classic GDLauncher issues since Next when it releases will most likely fix this

**Comment by kreezxil** [comment]
this issue has reappeared in 1.0.9 but not related to deleting, just random happen chance, perhaps it has something to do with the recent patch to fix windows users getting corrupted config.json files.
