### ISSUE TITLE
[Feature Request] Ability to use the vanilla launcher for login

### ISSUE THREAD

**Issue by Tschipp** [gorilla-devs/GDLauncher#311]
I think it would be nice to have the option to login via the official Minecraft Launcher, similarly to how twitch handles it. Twitch just launches the vanilla launcher and let's the user authenticate directly in there, which can provide an extra sense of security.
It could be a preference in the options, even disabled by default, for the people that like having the quick launches etc. This is basically the only feature that I really miss from the Twitch launcher. Everything else that you guys have is sooo much better!

**Comment by AzureDoom** [comment]
You already can, if you have the vanilla launcher and are logged in, the launcher gives you an option to log in without entering your info.

**Comment by Tschipp** [comment]
I see it now when I press the "?". But where can I find the skip login button?

**Comment by AzureDoom** [comment]
https://user-images.githubusercontent.com/8376628/70577629-987a6a00-1ba3-11ea-8daa-192a6158365c.png where the crossed out box is. (Image from guide as Im om mobile)

**Comment by Tschipp** [comment]
Ah okay, so that goes straight to the vanilla launcher?

**Comment by AzureDoom** [comment]
No, it uses the token from the vanilla launcher, allowing you to login without entering your info.

**Comment by Tschipp** [comment]
Very nice, thanks!
