### ISSUE TITLE
Legacy Version Support

### ISSUE THREAD

**Issue by strobili** [gorilla-devs/GDLauncher#319]
One of the only reasons I still sometimes use MultiMC instead of GDLauncher is how it supports legacy versions such as the alpha and beta versions. I quite enjoy this old versions for their nostalgia and simplicity, and it would be wonderful if I could just do that in GDLauncher and have just one program for all my Minecraft needs.

Also, support for things such as custom jars would also be appreciated. (One feature that MultiMC seems to lack)

**Comment by DavidYummy** [comment]
nopr
