### ISSUE TITLE
Turning off/customizing certain UI details and animations.

### ISSUE THREAD

**Issue by strobili** [gorilla-devs/GDLauncher#320]
I enjoy using GDLauncher, but some of the animations and UI elements are not really nice in my opinion. I personally think that there should be an option (or options) to disable several animations or UI elements. This is more of a cosmetic than functional thing, but would be nice regardless.

Customizing UI elements, like moving the sidebar from the right to left would also be a really cool feature that I think would make the program much better visually.

**Comment by TOLoneWolf** [comment]
`but some of the animations and UI elements are not really nice in my opinion`  
What UI/animation parts are you specifically talking about?
