### ISSUE TITLE
[0.12.4] Creating Shortcuts - Error creating instance symlink

### ISSUE THREAD

**Issue by kreezxil** [gorilla-devs/GDLauncher#322]
While researching the **Creating Shortcut** issue as presented by SAJewers

```
[8:31 AM]  SAJewers: Anyone able to help diagnose an odd problem? Launching any instance from within GDLauncher works fine, but doesn't seem to work If I create a shortcut try to launch from that.
[8:38 AM]  SAJewers: Latest stable GDLauncher, latest oracle java 8, Win10
[9:28 AM]  Kreezxil: what do you mean create a shortcut?
[9:29 AM]  SAJewers: when i right-click an instance in gdlaunch and click "create shortcut"
[9:29 AM]  SAJewers: it creates a shortcut fine
[9:29 AM]  SAJewers: but trying to run that shortcut nothing happens
```
I decided to try and create a shortcut on one of my test packs.

![image](https://user-images.githubusercontent.com/3880072/74164414-598b8380-4be9-11ea-9278-fd22af837c1e.png)

title "**1.14.4 Test**" and it said it failed to make the shortcut and gave the following reason in the console.

```
vendor.js:29 09:36:26.967 › Error creating instance symlink: Error: Command failed: powershell $s=(New-Object -COM WScript.Shell).CreateShortcut('%userprofile%\Desktop\1.14.4 Test.lnk');$s.TargetPath='C:\Users\kreez\AppData\Local\Programs\gdlauncher\GDLauncher.exe';$s.Arguments='-i 1.14.4 Test';$s.Save()
Unable to save shortcut "C:\Users\kreez\Desktop\1.14.4 Test.lnk".
At line:1 char:203
+ ... ms\gdlauncher\GDLauncher.exe';$s.Arguments='-i 1.14.4 Test';$s.Save()
+                                                                 ~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], DirectoryNotFoundException
    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException
```
I suspect this is related to the space in a name issue.

but that didn't work out because when I tried in GodBlock which has no spaces in its path that I'm aware of I received what appears to be the same error.

![image](https://user-images.githubusercontent.com/3880072/74164727-c6068280-4be9-11ea-9d5b-eee2753fb99c.png)

```
09:41:31.952 › Error creating instance symlink: Error: Command failed: powershell $s=(New-Object -COM WScript.Shell).CreateShortcut('%userprofile%\Desktop\GodBlock.lnk');$s.TargetPath='C:\Users\kreez\AppData\Local\Programs\gdlauncher\GDLauncher.exe';$s.Arguments='-i GodBlock';$s.Save()
Unable to save shortcut "C:\Users\kreez\Desktop\GodBlock.lnk".
At line:1 char:197
+ ... grams\gdlauncher\GDLauncher.exe';$s.Arguments='-i GodBlock';$s.Save()
+                                                                 ~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], DirectoryNotFoundException
    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException
 ```

**Comment by kreezxil** [comment]
Should be noted that I'm on Windows 10, Java 64 bit, with Hotspot.

**Comment by TOLoneWolf** [comment]
this bug is mentioned a little bit in issue #288   
By chance does your desktop folder not exist on your C drive?  
`C:\Users\kreez\Desktop`

**Comment by kreezxil** [comment]
That's correct it exists elsewhere.

**Comment by kreezxil** [comment]
I'm in favor of removing this feature because a) as Davide pointed out
Linux doesn't have it likely due in part to the extreme customization as to
where a Desktop can be and I suspect that b) apple doesn't have but not for
the Linux reasons. If you drop this feature, coding in the future will be
easier on the team.
