### ISSUE TITLE
Launcher doesn't login account properly on startup

### ISSUE THREAD

**Issue by Archilyte** [gorilla-devs/GDLauncher#324]
**Describe the bug**
Launcher skips login, resulting in no account being logged in
**To Reproduce**
1. Login normally
2. Restart Launcher
3. Launcher skips login

**Expected behavior**
It should either stop me at login menu, or auto login properly

**Possible solutions**
Make it properly auto login, like the original launcher

**Operating System:**
 - Windows
 - 10

note: for now, i can bypass this issue by manually logging in again, but sometimes one may forget and loading an instance that takes 20 mins to load again is just stupid because you can't join multiplayer because your account isn't logged in.

**Comment by TOLoneWolf** [comment]
same bug for issue #256
