### ISSUE TITLE
Forge 1.15 not starting

### ISSUE THREAD

**Issue by Xitoboy9** [gorilla-devs/GDLauncher#335]
**Describe the bug**
Whenever I try to open any forge version of Minecraft that's 1.14 or higher, it shows the little triangle indicating that it is starting up and after a bit the triangle disappears, 1.13 works fine.

**To Reproduce**
1.  Double click on an forge-instance that's 1.14 or more (including 1.15)
2. ????
3. Profit

**Expected behavior**
The game starts up

**Possible solutions**
Not sure, I haven't seen anyone else complain about it. On the official Twitch launcher on Mac, anything that's 1.13 or more won't work, so you guys are doing something right. However, not sure how you would go about fixing this. Don't even know if this is a feature that you guys have yet, but I did see a different issue complaining about the same thing but on Windows.

**Screenshots**
N/A

**Operating System:**
 - OS: Macintosh
 - Version 10.15.2

**Additional context**
Regular 1.14 and such work, but not modded. Even without any mods installed, just forge, it does not work.

**Comment by TOLoneWolf** [comment]
First guess is your java version is 11 and not 8 which modded minecraft needs to work correctly.  
first download java 8 from: https://adoptopenjdk.net/  
And install it.  

Then you will need change GDL to use that new java in the settings.
https://github.com/gorilla-devs/GDLauncher/wiki/Check-Java-Version#macosx-java-locations

if you get a crash when trying to access the settings
https://github.com/gorilla-devs/GDLauncher/wiki/FAQ-Frequently-Asked-Questions#crash-when-opening-settings

If there are any problems after that still, upload a  copy of the log file.
https://github.com/gorilla-devs/GDLauncher/wiki/How-to-view-console-and-log-files

**Comment by Xitoboy9** [comment]
Hey, thanks for the very detailed answer! I downloaded and installed Java 8 from AdoptOpenJDK, changed the settings inside the launcher too. I got the settings crash thing, but I just logged out and logged back in on my own before checking the link you provided for it. Everything seems to be good, but it still does not launch 1.14 or 1.15 forge. 1.13 still works, so I didn't break anything it seems. I looked for the log file, but the GDLauncher map doesn't show up. BUT IGNORE ALL OF THAT, because it did end up working. On the guide on how to change the Java settings, there's a mistake I think. It says "Click the folder icon to the right of "Java custom Path" and nativate to the path: /Library/Java/JavaVirtualMachines/jdk1.8.0_XXX.jdk/Contents/Home/bin/java
XXX= Replace with number from the folder shown above for JavaVirtualMachines." But the file I downloaded from adoptopenjdk is actually in the folder adoptopenjdk-8.jdk not jdk1.8.0_25.jdk like it said. I can now start up 1.15 forge, I'll test it with All the mods 5 later, sorry if this is super messy, hope it all makes sense. I still do have the problem with the GDLauncher Logs folder not showing up, screenshot is attached. Not a problem for now, but might be for someone else so it's worth looking into
![Screenshot 2020-02-29 at 17 49 12](https://user-images.githubusercontent.com/24394706/75611786-cc6b8880-5b1d-11ea-8cbd-f6f76d16a703.jpg)

**Comment by TOLoneWolf** [comment]
Yeah there are a few mistakes here and there. Oracle was the java source it (wiki) was written for but adopt is the source we are trying to use now.

On the Mac Finder Menu > "Go" > "Go to Folder..." (Command + Shift + G) > `~/Library/Logs/GDLauncher/` > Go button will take you to the log folder, it's actually a different path then what you would think in the end it goes to this folder:  
`/Users/<USERNAME>/Library/Logs/GDLauncher/log.log`   

`~` expands to `/Users/<USERNAME>/` on Mac.

**Comment by Xitoboy9** [comment]
Oh my bad, that did indeed work. Thank you for the quick responses!

**Comment by TOLoneWolf** [comment]
Nice, glad it got it working for you.
And thanks for pointing out the confusion on log location and wiki instructions.
