### ISSUE TITLE
GLFW error 65539:invalid key 4

### ISSUE THREAD

**Issue by Shad0wyDr3ams** [gorilla-devs/GDLauncher#336]
**Describe the bug**
error popup of GLFW error 65539:invalid key 4 that pops up when loading any modpack with my computer using the GDlauncher

**To Reproduce**
1. Have this exact Computer https://pcpartpicker.com/list/xWBzPn
2. open GDlauncher 
3. Download any modpack and try to run it 
4. watch error happen and then check logs and take screenshot
5. Download linked file to see logs and captured screenshot =https://drive.google.com/open?id=1ii-ggGrZugvQW9bWDDvVt_eKBRxVBYnV

**Expected behavior**
modpacks are supposed to fully load and be playable 

**Possible solutions**
i have no know solutions for this issue as of current

**Screenshots**
screenshot of issue in zip folder linked above

**Operating System:**
 - OS: Windows10
 - Version: 1909

**Additional context**
And yes i have checked my graphics drivers and they are up to date and the latest as of current time. secondly it only happens when using GDlauncher.
When using original minecraft launcher with forge and mods this issue does not happen

**Comment by Shad0wyDr3ams** [comment]
And yes i have checked my graphics drivers and they are up to date and the lastest as of current time. secondly it only happens when using GDlauncher ,if using original minecraft launcher with forge and mods this issue does not happen

**Comment by kreezxil** [comment]
You've attached the wrong logs and other extraneous data. What you attached
is for debugging a modpack. See
https://github.com/gorilla-devs/GDLauncher/wiki/FAQ-Frequently-Asked-Questions
for what this project actually needs from you in the logs. Our console is
not the same as the one generated by minecraft.

**Comment by TOLoneWolf** [comment]
Try changing java to this in GDL settings.  
`C:\Users\Shado\AppData\Roaming\.Minecraft\runtime\jre-x64\bin\java.exe`  
This is the java version vanilla ships with.

if gdl crashes trying to access setting:  
https://github.com/gorilla-devs/GDLauncher/wiki/FAQ-Frequently-Asked-Questions#crash-when-opening-settings

**Comment by TOLoneWolf** [comment]
where to get right log file for gdl.  
https://github.com/gorilla-devs/GDLauncher/wiki/How-to-view-console-and-log-files
