### ISSUE TITLE
Instance claims that no mods are installed, even though they are

### ISSUE THREAD

**Issue by Archilyte** [gorilla-devs/GDLauncher#338]
**Describe the bug**
When I right click my custom instance to manage mods, it says "No Mod is Installed", even though they are.

**To Reproduce**
1. Mske a custom instance
2. Put mods in manually (I downloaded most mods through the launcher, but mods like Optifine manually"
3. Right click the custom instance on the launcher and go to manage
4. Go to mod manager and see error

**Expected behavior**
All mods loaded should be listed and update icons should be shown

**Possible solutions**
idk honestly

**Screenshots**

**Operating System:**
Windows 10

**Additional context**
When you left click the instance once, it shows the mod count on the sidebar, which I find strange

**Comment by AzureDoom** [comment]
This is a known thing, there is even a txt added to your mods folder telling you not to do this. Should already be fixed in the rewrite branch.

**Comment by Archilyte** [comment]
Where can I access the rewrite branch download? (sry if i sound like an idiot)

or is it the next update?

**Comment by AzureDoom** [comment]
You can compile it from here: https://github.com/gorilla-devs/GDLauncher/tree/next

but yes it will be the next update
