### ISSUE TITLE
After playing a game, you can no longer interact with the launcher

### ISSUE THREAD

**Issue by CmdrNorthpaw** [gorilla-devs/GDLauncher#341]
**Describe the bug**
When you open and close a game of Minecraft, you can't click anywhere in the interface and you have to restart the launcher
**To Reproduce**
1. Play a game of Minecraft
2. Close the game
3. And now you can't click anything
**Expected behavior**
I just need to be able to press buttons.
**Operating System:**
 - OS: Manjaro Linux
 - Version: It's a rolling release, and I'm on the stable channel.

**Comment by furtabs** [comment]
I use manjaro linux and cannot reproduce. Next or Legacy
