### ISSUE TITLE
Expand the Mod selection pull down so that the name of the mod is not cut off

### ISSUE THREAD

**Issue by salasnet** [gorilla-devs/GDLauncher#345]
I would like to see the mod selection pull-down menu be wider so that mods that have really long names do not get their name truncated, making it impossible to see what the version is.

Being able to see the version of the mod you want to install in the mod menu pulldown would be really helpful as you don't always want the latest version of a mod for your pack.

![image](https://user-images.githubusercontent.com/49218803/77231366-c858e680-6b70-11ea-9d47-2b685bd4f5b0.png)

**Comment by TOLoneWolf** [comment]
#240
