### ISSUE TITLE
Add option to disable Discord Rich Presence

### ISSUE THREAD

**Issue by Freddo3000** [gorilla-devs/GDLauncher#347]
**Is your feature request related to a problem? Please describe.**
I'd rather not have it displaying that I'm "Playing GDLauncher". At least make it display which modpack I'm playing, or allow me to disable it.

**Describe the solution you'd like**
A simple toggle.

**Describe alternatives you've considered**
> At least make it display which modpack I'm playing

**Additional context**
N/A

**Comment by CmdrNorthpaw** [comment]
They're adding this in the rewrite, which is coming out soon.

**Comment by TOLoneWolf** [comment]
duplicate of #262

**Comment by Freddo3000** [comment]
Must've been blind when I was looking for duplicates.
