### ISSUE TITLE
[next] Can't paste my password in the login screen

### ISSUE THREAD

**Issue by hvdklauw** [gorilla-devs/GDLauncher#358]
**Describe the bug**
Build the next branch on my laptop, ran it with `yarn start-prod`
Tried to login by copying my password from my password manager, but couldn't paste in the password field.

**To Reproduce**
1. Start GDlauncher next branch
2. Copy some text from somewhere
3. Click the password field
4. Paste 

**Expected behavior**
I expect my copied text to have been filled in the password field.

**Possible solutions**
Handle copy and paste correctly

**Operating System:**
 - OS: MacOs
 - Version: Catalina (10.15.3)

**Comment by hvdklauw** [comment]
Can't paste in dev mode either, not can I paste in the inspector..

**Comment by hvdklauw** [comment]
https://pracucci.com/atom-electron-enable-copy-and-paste.html maybe?

**Comment by hvdklauw** [comment]
Yup, that fixed it

**Comment by hvdklauw** [comment]
in electron.js:
```
Menu.setApplicationMenu(
  Menu.buildFromTemplate([
    {
      label: 'Application',
      submenu: [
        {
          label: 'About Application',
          selector: 'orderFrontStandardAboutPanel:'
        },
        { type: 'separator' },
        {
          label: 'Quit',
          accelerator: 'Command+Q',
          click: () => {
            app.quit();
          }
        }
      ]
    },
    {
      label: 'Edit',
      submenu: [
        { label: 'Undo', accelerator: 'CommandOrControl+Z', selector: 'undo:' },
        {
          label: 'Redo',
          accelerator: 'Shift+CommandOrControl+Z',
          selector: 'redo:'
        },
        { type: 'separator' },
        { label: 'Cut', accelerator: 'CommandOrControl+X', selector: 'cut:' },
        { label: 'Copy', accelerator: 'CommandOrControl+C', selector: 'copy:' },
        {
          label: 'Paste',
          accelerator: 'CommandOrControl+V',
          selector: 'paste:'
        },
        {
          label: 'Select All',
          accelerator: 'CommandOrControl+A',
          selector: 'selectAll:'
        }
      ]
    }
  ])
);
```
instead of 
```
Menu.setApplicationMenu();
```

**Comment by TOLoneWolf** [comment]
You can do a pull request and then davide can easily just accept it into the next branch if its good with him.

**Comment by hvdklauw** [comment]
Yes, will do when I have the time between homeschooling the kids ;-)

**Comment by adveres** [comment]
It appears this was never implemented. I am unable to paste my (long, complex, auto-generated) password. 

- GDLauncher ~1.0.6~ 1.0.8
- OSX Mojave 10.14.6
- MacBook Pro (15 inch, Mid 2015)

-----

Please consider reopening this ticket. This is prohibitive for pasting generated passwords, and things like complex JVM arguments. I'm stuck typing all of it out, leading to typos, etc.

**Comment by MaxLevs** [comment]
I agree with previous speaker. I have 1Password auto-generated password and I can't just login because there aren't neither copy nor paste options into MacOS Big Sur.

**Comment by hypherionmc** [comment]
@killpowa just a reminder. This could be useful

**Comment by blarfoon** [comment]
It was fixed a long time ago I think

**Comment by blarfoon** [comment]
Feel free to reopen if still an issue
