### ISSUE TITLE
Repair stuck at 75 procent

### ISSUE THREAD

**Issue by NicTanghe** [gorilla-devs/GDLauncher#371]
**Describe the bug**
Repair stuck at 75 procent

**To Reproduce**
ad instance valhesia 2
stuck during install at 75% somewhere.
reboot gd launcher.
unable to run the instance?
repair instance.
stuck at 75% again.

**Expected behavior**
doesn't get stuck and completes

**Possible solutions**
Some ideas of how you would solve this issue, if possible

**Screenshots**

**Operating System:**
 - OS: [Windows]
 - Version [10]

**Additional context**

**Comment by TOLoneWolf** [comment]
Do any errors show up in the console(log) when after it gets to  75% ?

https://github.com/gorilla-devs/GDLauncher/wiki/Console-and-Log
