### ISSUE TITLE
Launcher automatically disables cheating in-game.

### ISSUE THREAD

**Issue by tucoqrz** [gorilla-devs/GDLauncher#384]
I have an instance in the latest release of Forge for 1.15.2 and whenever I create a world and enable cheats, they are disabled when I enter the world and I have to do the classic "open to LAN" method to enable them again, I have tried to create new instances on the exact same version, tried to create other worlds and even tried to test each mod to see if they were causing the problem but none of this worked so I started suspecting it was an issue with the launcher.

**Comment by TOLoneWolf** [comment]
Tested with
Minecraft 1.15.2
Forge 31.1.35

I cannot reproduce this result.

@LunaticKing top right in GDL does it show your correct username and not blank?
![image](https://user-images.githubusercontent.com/8376628/78414037-d5012400-75df-11ea-98d8-adda070d5b59.png)

You might need to logout and login again to GDL.

**Comment by tucoqrz** [comment]
Indeed, it was blank, (even though I had previously checked the "Remember me" box when logging in for the first time. Weird) I logged out and then logged in again and the problem was solved, thank you so much!
