### ISSUE TITLE
[Bug] Caching of old mods when updating or clean installing new updates to a pack

### ISSUE THREAD

**Issue by Ranzer1255** [gorilla-devs/GDLauncher#391]
**Describe the bug**
instances seem to be caching old data even on "clean" installs. we discovered this when updating GrimCo's Coop Life 2 mod pack to version 1.0.8, which removed Galaticraft and related mods in this version. when preforming an update or a "clean" install of the mod pack these mods would stay installed despite them not being in the .zip import or the curseforge download

While i use Coop Life 2 as an example here, this may be an issue in other packs as well. it is just known to our team to occur in CL2

**To Reproduce**
1. Install GrimCo's Coop Life 2 mod pack version 1.0.7 or earlier
2. leave pack name default `GrimCosCoopLife2`
3. check the mod manager for Galacticraft mods
4. launch MC to make sure the instance is fully populated
5. delete the instance from the Launcher
6. recreate the instance but at version 1.0.8 with the same default pack name 
7. check for GC mods again in Mod manager

**Expected behavior**
GC mods should *not* be in the pack at version 1.0.8

**Possible solutions**
Work-arrounds we came up with were: 

deleting the `GrimCosCoopLife2` file in the `<appdata>/Roaming/GDLauncher/instances/temp` folder resolves this issue

also, using a unique name for the instance file prevents this issue from happening as it doesn't reference the old `temp` file.

**Operating System:**
 - OS: Windows
 - Version: 10 1909

**Additional context**
when looking in the `temp` file the Jar files for the Galacticraft mod are there. despite them being removed from the mod pack...  you can also see more information in https://github.com/GrimCo/CoopLife2/issues/66 where this issue was first discovered and worked around by our team

**Comment by TOLoneWolf** [comment]
@CrankySupertoon this was an issue with the extraction in the old 0.12.4 version of the launcher not a request for a caching feature.

This was breaking installing new instances and updating old instances to a new modpack version.

**Comment by Ranzer1255** [comment]
so... has this been fixed in an upcoming version?

**Comment by TOLoneWolf** [comment]
Yes it should all be working fine in the next release.

Tested it and currently is working fine as the download cache is removed between installs as it should.
