### ISSUE TITLE
Skip Login Function Issue

### ISSUE THREAD

**Issue by AaronSezar** [gorilla-devs/GDLauncher#394]
when any user want to skip login there is no button in launcher for it
how can we activate skip login function in code because there is so many users that want to play without any mojang ID

**Comment by CmdrNorthpaw** [comment]
GDLauncher is not a cracked launcher. Please close this issue as that feature will never be added.

**Comment by tilda** [comment]
Short answer: No.

Long answer: I'm pretty sure adding a function to be able to skip login would go against the rules that Mojang has put in their terms. They probably wouldn't do anything about it (they've got better things to do, like actually working on the game) but it's best to stay on the safe side and just not do that.

No one will help regarding modifying the launcher to be a cracked version.

Sorry to say, but I think it's best if you set aside some money and put it towards buying an account for the game. It'll work out better for you in the end.
