### ISSUE TITLE
1.15.2 Instance not launching

### ISSUE THREAD

**Issue by Songar87** [gorilla-devs/GDLauncher#396]
When I add a 1.15.2 Forge instance to the Instances section, the play icon appears for split second then stops. 1.14.4 and 1.12.2 instance do not have this problem.

1. Go to 'Add New Instance'
2. Click on '1.15.2'
3. Scroll down to 'Forge (any version)'
4. Run Instance

**Expected behavior**
Forge launches

**Possible solutions**
Tried multiple versions of Forge with no success.

**Operating System:**
 - OS: Windows
 - Version 10

**Additional context**

**Comment by AzureDoom** [comment]
Please provide a log https://github.com/gorilla-devs/GDLauncher/wiki/Console-and-Log

**Comment by Songar87** [comment]
https://hastebin.com/kayetopeba.coffeescript

**Comment by AzureDoom** [comment]
`The command line is too long.`

Sadly the only fix is to love the instance of the modpack to a folder closer to the root of the drive. This is something that should be resolved in the Next update coming next month.

**Comment by Songar87** [comment]
Ok. Thanks!

**Comment by furtabs** [comment]
Im going to close this for now it is fixed in the Next Release. Should be out relatively soon

**Comment by skellitor301** [comment]
I just got this error, launcher version 1.1.25.
Console log: https://gist.github.com/skellitor301/49be45ada5ee349995ac1050ab81d2ae

**Comment by SolarSupremacy** [comment]
Same. Tried the fix posted above (moving the directory closer to root). Doesn't work.

**Comment by Eskaan** [comment]
Also on Mc 1.15?
There is a new issue for Forge 1.19

**Comment by skellitor301** [comment]
> Also on Mc 1.15? There is a new issue for Forge 1.19

1.15 posts are 2 years old, the recent comments are current as this issue has resurfaced in the current launcher version.
