### ISSUE TITLE
Error creating Instance Shortcut when username contains accentualed characters

### ISSUE THREAD

**Issue by jberube** [gorilla-devs/GDLauncher#397]
When trying to create a shortcut, it fails and I get the following error written in the logs:

```
[2020-04-12 19:09:12.192] [error] Error creating instance symlink: Error: Command failed: powershell $s=(New-Object -COM WScript.Shell).CreateShortcut('%userprofile%\Desktop\MineColonies 5.0.lnk');$s.TargetPath='C:\Users\Julien Bérubé\AppData\Local\Programs\gdlauncher\GDLauncher.exe';$s.Arguments='-i MineColonies 5.0';$s.Save()
Unable to save shortcut "C:\Users\Julien B�rub�\Desktop\MineColonies 5.0.lnk".
At line:1 char:229
+ ... launcher\GDLauncher.exe';$s.Arguments='-i MineColonies 5.0';$s.Save()
+                                                                 ~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [], DirectoryNotFoundException
    + FullyQualifiedErrorId : System.IO.DirectoryNotFoundException
```

Notice that my username contains accentuated characters, i.e. "é", which are correctly displayed at some places, but not others (displayed at �).

**To Reproduce**
1. Create a local user with character "é" in it
2. Install and open GDLauncher, add an instance
3. Right-click, Create shortcut
4. See error in the %AppData%/GDLauncher/log.log file

**Expected behavior**
I get a shortcut on my desktop :)

**Possible solutions**
You probably need to define an encoding somewhere in the PowerShell script.

**Operating System:**
 - OS: Windows
 - Version 10 64-bit Pro

**Additional context**

PowerShell version : 

```
PS C:\Users\Julien Bérubé> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      18362  628
```

**Comment by jberube** [comment]
Also : My Desktop is located at the default location, i.e. `C:\Users\Julien Bérubé\Desktop`

**Comment by jberube** [comment]
After investigating the issue a little, I figured out that my Desktop is no longer at `C:\Users\Julien Bérubé\Desktop`, but rather `C:\Users\Julien Bérubé\OneDrive\Desktop`, probably because I installed OneDrive this afternoon.

For a classy solution to handling non-standard Desktop locations on Windows, see : https://stackoverflow.com/a/31747246/309236

**Comment by furtabs** [comment]
This has to do with the username having a space and no quoting the command properally. fixed in next
