### ISSUE TITLE
Add method of selecting Java executable

### ISSUE THREAD

**Issue by 0alpha** [gorilla-devs/GDLauncher#399]
**Is your feature request related to a problem? Please describe.**
I would like to force OpenJ9 as the used JVM.

**Describe the solution you'd like**
Add a method of selecting Java executable.

**Describe alternatives you've considered**
PATH?

**Additional context**
N/A.

**Comment by TOLoneWolf** [comment]
settings > java > disable autodetect > set java custom path to desired java.

if you get a crash message trying to access the settings logout and back in to gdl, top right should display your playername if your account is logged in correctly(main window).

Note OpenJ9 is not recommend for use with forge as some mods will not work with it and 1.14.4 will just not even start.
[Forge Commit Block OpenJ9 Launch](https://github.com/cpw/modlauncher/commit/1f9473a28ad910ef42539f7f789f63afa4cdbf8d)

![OpenJ9 warning](https://raw.githubusercontent.com/wiki/gorilla-devs/GDLauncher/img/java-64-bit-installers/minecraftForgeOpenJ9.png)
