### ISSUE TITLE
[Feature] Custom Instance Paths

### ISSUE THREAD

**Issue by Alareg** [gorilla-devs/GDLauncher#401]
**Operating System used:**  
Windows 10

**Actual behavior:**  
Custom Path for instances is missing in version 0.0.4

**Steps to reproduce the behavior:**  

**Expected behavior:**  

**If applicable, add screenshots/videos to help explain:**  

**Additional context:**

**Comment by Eskaan** [comment]
Is this issue about the Java path or the instance location?
Anyways, this issue is either fixed by cfaea167 or a duplicate of #110

**Comment by Rmdhn1** [comment]
need this on Linux, cause y'know, SSD is precious
