### ISSUE TITLE
[Bug] GDLauncher remains in background processes after being closed, and spawns a new instance when opened again

### ISSUE THREAD

**Issue by Daktyl198** [gorilla-devs/GDLauncher#402]
**Operating System used:**
Windows 10, build 18363

**Actual behavior:**
After closing GDLauncher v0.0.3, the process remains as a zombie in the background processes. Opening GDLauncher again spawns a new process, which will zombie-fy if closed as well, stacking on top of the first, and so on and so forth. Very bad for memory.

**Steps to reproduce the behavior:**
Open GDLauncher.
Optional: Launch a modpack, then close it
Close GDLauncher.

**Expected behavior:**
The GDLauncher process should either be closed completely, or re-use the background process left open after the first close.

**If applicable, add screenshots/videos to help explain:**
![image](https://user-images.githubusercontent.com/2475672/79284563-0358ec00-7e89-11ea-9c60-335a6eea5fa7.png)

**Comment by B-Wilhelm** [comment]
I'm having a similar issue, what exactly happened here?
