### ISSUE TITLE
[Bug]  launcher doesn't seem to realize it's done deleting an instance

### ISSUE THREAD

**Issue by TOLoneWolf** [gorilla-devs/GDLauncher#413]
Submitted by: Discomanco [Win10/High Sierra]

**Operating System used:**
Windows 10

**Actual behavior:**
The launcher doesn't seem to realize when it's done deleting an instance. The folder is gone from Explorer, but it's still deleting

**Steps to reproduce the behavior:**
?

**Expected behavior:**
Remove instance from computer, GDL, and stop showing it being removed in the UI.

**If applicable, add screenshots/vidoes to help explain:**

**Additional context:**

Could be related to the Reload bug I posted further up (which is now back)  in issue: gorilla-devs/GDLauncher-Next-Issues#7

**Comment by Discomanco** [comment]
This was fixed in 005, so should be closed
