### ISSUE TITLE
[Bug] All modpacks disappear when reloading Launcher

### ISSUE THREAD

**Issue by TOLoneWolf** [gorilla-devs/GDLauncher#418]
Submitted by: Discomanco [Win10/High Sierra]

**Operating System used:**
Windows 10

**Actual behavior:**
All modpacks disappear when reloading (Ctrl-R) the Launcher. Need to relaunch to make them appear.

**Steps to reproduce the behavior:**
CTRL+R

**Expected behavior:**
Reload the modpacks

**If applicable, add screenshots/vidoes to help explain:**
https://gyazo.com/de003f6a74c8fce583705691b9e3b390

**Additional context:**

- Details 1: I do have a custom path set. 1 pack with custom name, one with default.
- Detail 2: Works fine on OSX - no changed to Data Path.

**Comment by blarfoon** [comment]
This should no longer be happening, feel free to reopen if this issue still exists
