### ISSUE TITLE
[Feature] FTB Support

### ISSUE THREAD

**Issue by furtabs** [gorilla-devs/GDLauncher#425]
### We are currently only taking Feature Requests for the Upcoming Next Release which will fix most of the legacy build's bugs.
---

**Describe the new feature you are requesting**
Support for FTB Modpacks

**Describe alternatives to this feature if Applicable**

**Additional Inforomation**
**API:** https://modpacksch.docs.apiary.io/
**FTB API Scraper** https://github.com/jamierocks/neptune-ftb-meta
**FTB App** https://github.com/FTBTeam/FTB-App
**FTB Backend** https://github.com/CreeperHost/modpacklauncher

**Comment by jcotton42** [comment]
I'm confused, doesn't GDLauncher already support FTB packs? I've used it to install several of them from Curse

**Comment by TOLoneWolf** [comment]
@jcotton42 FTB left curse/twitch didn't renew contract so they left and are slowly switching back to their own system for new packs.

**Comment by jcotton42** [comment]
Ah I missed the news for that.
In the meantime is there a way for us to manually import FTB packs into GDLauncher? I see an import option but that only has the "Twitch" format, unsure if it's compatible.

**Comment by TOLoneWolf** [comment]
looks like currently all their packs are still on twitch so don't need to atm.

That is why this is a feature request for adding support for FTBs API...

**Comment by furtabs** [comment]
> looks like currently all their packs are still on twitch so don't need to atm.
> 
> That is why this is a feature request for adding support for FTBs API...

That is invalid most of their 1.12 packs have newer updates on the FTB Api. Not to mention Omnia. I would just use the FTB App then copy the folders back

**Comment by rlnt** [comment]
FTB Omnia is exclusive for their launcher afaik.

**Comment by furtabs** [comment]
Not to mention the new Stoneblock update

**Comment by rlnt** [comment]
I mean they also mentioned that they will delete their ftb account on twitch so all modpacks that are currently available there will be gone and only available on the ftb exclusive launcher then.
At least they are transferring the mods to one of their modders to keep them available for everyone which is really honorable.

Here's a reference link if someone wants to read the whole article: https://forum.feed-the-beast.com/threads/on-the-31st-october-2019-the-partnership-between-ftb-and-twitch-will-be-ending.300783/

**Comment by Dragnier** [comment]
The 1.16 Direwolf20 pack is not on Curse. Further, the FTB Launcher itself is now an Overwolf app just like the Curse one so it has ads and all the badness related to Overwolf too. This feature would be much appreciated.

**Comment by Jschmuck2** [comment]
Seconded

**Comment by ozhound** [comment]
Thirded!

**Comment by mkolassa** [comment]
Fourthed.  Now that packs are seeing updates and new releases purely on the FTB Launcher, it would be nice to have the integration in GDLauncher.

**Comment by Ladvace** [comment]
update! we have implemented ftb and probably it will be available in the next release
