### ISSUE TITLE
[Feature] Button to launch packs?

### ISSUE THREAD

**Issue by Seth0067** [gorilla-devs/GDLauncher#437]
### We are currently only taking Feature Requests for the Upcoming Next Release which will fix most of the legacy build's bugs.
---

**Describe the new feature you are requesting**
Launch button after selecting a pack.  While you can right click and select launch, this is not the most frictionless way to launch the pack.   There is no visible way to start a pack, and this may create friction for users.

Currently clicking the pack instance displays three button-ish info fields at the right - this may be a good spot for said button.  As an aside, since these aren't clickable, you may want to consider another text presentation that removes the text from button looking graphics.

**Describe alternatives to this feature if applicable**

**Additional Information**

**Comment by furtabs** [comment]
Can’t you double click the one you want to launch
