### ISSUE TITLE
NONE of the mod packs will launch

### ISSUE THREAD

**Issue by ChickneTurky** [gorilla-devs/GDLauncher#441]
`18:43:28.021 › Parsing json version for libraries
console.js:72 18:43:28.025 › "/usr/bin/java" -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true  -Xms256m -Xmx4096m   -Djava.library.path="/Users/lorimarten/Desktop/GDL/packs/ZooBuildersPack/natives"  -Dminecraft.client.jar="/Users/lorimarten/Desktop/GDL/versions/1.12.2/1.12.2.jar" -cp "/Users/lorimarten/Desktop/GDL/libraries/net/minecraftforge/forge/1.12.2-14.23.5.2847/forge-1.12.2-14.23.5.2847.jar:/Users/lorimarten/Desktop/GDL/libraries/net/minecraft/launchwrapper/1.12/launchwrapper-1.12.jar:/Users/lorimarten/Desktop/GDL/libraries/org/ow2/asm/asm-all/5.2/asm-all-5.2.jar:/Users/lorimarten/Desktop/GDL/libraries/org/jline/jline/3.5.1/jline-3.5.1.jar:/Users/lorimarten/Desktop/GDL/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar:/Users/lorimarten/Desktop/GDL/libraries/com/typesafe/akka/akka-actor_2.11/2.3.3/akka-actor_2.11-2.3.3.jar:/Users/lorimarten/Desktop/GDL/libraries/com/typesafe/config/1.2.1/config-1.2.1.jar:/Users/lorimarten/Desktop/GDL/libraries/org/scala-lang/scala-actors-migration_2.11/1.1.0/scala-actors-migration_2.11-1.1.0.jar:/Users/lorimarten/Desktop/GDL/libraries/org/scala-lang/scala-compiler/2.11.1/scala-compiler-2.11.1.jar:/Users/lorimarten/Desktop/GDL/libraries/org/scala-lang/plugins/scala-continuations-library_2.11/1.0.2/scala-continuations-library_2.11-1.0.2.jar:/Users/lorimarten/Desktop/GDL/libraries/org/scala-lang/plugins/scala-continuations-plugin_2.11.1/1.0.2/scala-continuations-plugin_2.11.1-1.0.2.jar:/Users/lorimarten/Desktop/GDL/libraries/org/scala-lang/scala-library/2.11.1/scala-library-2.11.1.jar:/Users/lorimarten/Desktop/GDL/libraries/org/scala-lang/scala-parser-combinators_2.11/1.0.1/scala-parser-combinators_2.11-1.0.1.jar:/Users/lorimarten/Desktop/GDL/libraries/org/scala-lang/scala-reflect/2.11.1/scala-reflect-2.11.1.jar:/Users/lorimarten/Desktop/GDL/libraries/org/scala-lang/scala-swing_2.11/1.0.1/scala-swing_2.11-1.0.1.jar:/Users/lorimarten/Desktop/GDL/libraries/org/scala-lang/scala-xml_2.11/1.0.2/scala-xml_2.11-1.0.2.jar:/Users/lorimarten/Desktop/GDL/libraries/lzma/lzma/0.0.1/lzma-0.0.1.jar:/Users/lorimarten/Desktop/GDL/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar:/Users/lorimarten/Desktop/GDL/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar:/Users/lorimarten/Desktop/GDL/libraries/net/sf/trove4j/trove4j/3.0.3/trove4j-3.0.3.jar:/Users/lorimarten/Desktop/GDL/libraries/org/apache/maven/maven-artifact/3.5.3/maven-artifact-3.5.3.jar:/Users/lorimarten/Desktop/GDL/libraries/com/mojang/patchy/1.1/patchy-1.1.jar:/Users/lorimarten/Desktop/GDL/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar:/Users/lorimarten/Desktop/GDL/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar:/Users/lorimarten/Desktop/GDL/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar:/Users/lorimarten/Desktop/GDL/libraries/com/paulscode/codecjorbis/20101023/codecjorbis-20101023.jar:/Users/lorimarten/Desktop/GDL/libraries/com/paulscode/codecwav/20101023/codecwav-20101023.jar:/Users/lorimarten/Desktop/GDL/libraries/com/paulscode/libraryjavasound/20101123/libraryjavasound-20101123.jar:/Users/lorimarten/Desktop/GDL/libraries/com/paulscode/librarylwjglopenal/20100824/librarylwjglopenal-20100824.jar:/Users/lorimarten/Desktop/GDL/libraries/com/paulscode/soundsystem/20120107/soundsystem-20120107.jar:/Users/lorimarten/Desktop/GDL/libraries/io/netty/netty-all/4.1.9.Final/netty-all-4.1.9.Final.jar:/Users/lorimarten/Desktop/GDL/libraries/com/google/guava/guava/21.0/guava-21.0.jar:/Users/lorimarten/Desktop/GDL/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:/Users/lorimarten/Desktop/GDL/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar:/Users/lorimarten/Desktop/GDL/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:/Users/lorimarten/Desktop/GDL/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar:/Users/lorimarten/Desktop/GDL/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar:/Users/lorimarten/Desktop/GDL/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar:/Users/lorimarten/Desktop/GDL/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar:/Users/lorimarten/Desktop/GDL/libraries/com/mojang/realms/1.10.22/realms-1.10.22.jar:/Users/lorimarten/Desktop/GDL/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar:/Users/lorimarten/Desktop/GDL/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar:/Users/lorimarten/Desktop/GDL/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:/Users/lorimarten/Desktop/GDL/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar:/Users/lorimarten/Desktop/GDL/libraries/it/unimi/dsi/fastutil/7.1.0/fastutil-7.1.0.jar:/Users/lorimarten/Desktop/GDL/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar:/Users/lorimarten/Desktop/GDL/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar:/Users/lorimarten/Desktop/GDL/libraries/org/lwjgl/lwjgl/lwjgl/2.9.2-nightly-20140822/lwjgl-2.9.2-nightly-20140822.jar:/Users/lorimarten/Desktop/GDL/libraries/org/lwjgl/lwjgl/lwjgl_util/2.9.2-nightly-20140822/lwjgl_util-2.9.2-nightly-20140822.jar:/Users/lorimarten/Desktop/GDL/libraries/com/mojang/text2speech/1.10.3/text2speech-1.10.3.jar:/Users/lorimarten/Desktop/GDL/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar":"/Users/lorimarten/Desktop/GDL/versions/1.12.2/1.12.2.jar" net.minecraft.launchwrapper.Launch --username GodIsWalter --version forge-14.23.5.2847 --gameDir "/Users/lorimarten/Desktop/GDL/packs/ZooBuildersPack" --assetsDir "/Users/lorimarten/Desktop/GDL/assets" --assetIndex 1.12 --uuid 88cab0d5241942e58215b943652316f9 --accessToken HIDDEN_ACCESS_TOKEN --userType mojang --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker --versionType Forge  
console.js:72 18:43:28.744 › Exception in thread "main" 
a @ console.js:72
n @ console.js:37
r @ log.js:25
(anonymous) @ instancesManager.js:186
emit @ events.js:194
addChunk @ _stream_readable.js:296
readableAddChunk @ _stream_readable.js:277
Readable.push @ _stream_readable.js:232
onStreamRead @ internal/stream_base_commons.js:165
console.js:72 18:43:28.745 › java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at net.minecraft.launchwrapper.Launch.<init>(Launch.java:34)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

a @ console.js:72
n @ console.js:37
r @ log.js:25
(anonymous) @ instancesManager.js:186
emit @ events.js:194
addChunk @ _stream_readable.js:296
readableAddChunk @ _stream_readable.js:277
Readable.push @ _stream_readable.js:232
onStreamRead @ internal/stream_base_commons.js:165`
### **I have tried doing a bunch of things. I am using a MacOS. I have tried multiple mod packs, but ZooBuilderPack was the first one I was trying to launch, its in the version 1.12.2. I also tried doing AllTheMods4 and it looked like this in the console...**
`18:53:22.679 › Parsing json version for libraries
console.js:72 18:53:22.690 › "/usr/bin/java" -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true  -Xms256m -Xmx4096m  -XstartOnFirstThread -Djava.library.path="/Users/lorimarten/Desktop/GDL/packs/AlltheMods4ATM4/natives"  -Dminecraft.client.jar="/Users/lorimarten/Desktop/GDL/versions/1.14.4/1.14.4.jar" -cp "/Users/lorimarten/Desktop/GDL/libraries/net/minecraftforge/forge/1.14.4-28.2.4/forge-1.14.4-28.2.4.jar:/Users/lorimarten/Desktop/GDL/libraries/org/ow2/asm/asm/6.2/asm-6.2.jar:/Users/lorimarten/Desktop/GDL/libraries/org/ow2/asm/asm-commons/6.2/asm-commons-6.2.jar:/Users/lorimarten/Desktop/GDL/libraries/org/ow2/asm/asm-tree/6.2/asm-tree-6.2.jar:/Users/lorimarten/Desktop/GDL/libraries/cpw/mods/modlauncher/4.1.0/modlauncher-4.1.0.jar:/Users/lorimarten/Desktop/GDL/libraries/cpw/mods/grossjava9hacks/1.1.0/grossjava9hacks-1.1.0.jar:/Users/lorimarten/Desktop/GDL/libraries/net/minecraftforge/accesstransformers/1.0.5-shadowed/accesstransformers-1.0.5-shadowed.jar:/Users/lorimarten/Desktop/GDL/libraries/net/minecraftforge/eventbus/1.0.0-service/eventbus-1.0.0-service.jar:/Users/lorimarten/Desktop/GDL/libraries/net/minecraftforge/forgespi/1.5.0/forgespi-1.5.0.jar:/Users/lorimarten/Desktop/GDL/libraries/net/minecraftforge/coremods/1.0.0/coremods-1.0.0.jar:/Users/lorimarten/Desktop/GDL/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar:/Users/lorimarten/Desktop/GDL/libraries/com/electronwill/night-config/core/3.6.0/core-3.6.0.jar:/Users/lorimarten/Desktop/GDL/libraries/com/electronwill/night-config/toml/3.6.0/toml-3.6.0.jar:/Users/lorimarten/Desktop/GDL/libraries/org/jline/jline/3.12.1/jline-3.12.1.jar:/Users/lorimarten/Desktop/GDL/libraries/org/apache/maven/maven-artifact/3.6.0/maven-artifact-3.6.0.jar:/Users/lorimarten/Desktop/GDL/libraries/net/jodah/typetools/0.6.0/typetools-0.6.0.jar:/Users/lorimarten/Desktop/GDL/libraries/java3d/vecmath/1.5.2/vecmath-1.5.2.jar:/Users/lorimarten/Desktop/GDL/libraries/org/apache/logging/log4j/log4j-api/2.11.2/log4j-api-2.11.2.jar:/Users/lorimarten/Desktop/GDL/libraries/org/apache/logging/log4j/log4j-core/2.11.2/log4j-core-2.11.2.jar:/Users/lorimarten/Desktop/GDL/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar:/Users/lorimarten/Desktop/GDL/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar:/Users/lorimarten/Desktop/GDL/libraries/com/mojang/patchy/1.1/patchy-1.1.jar:/Users/lorimarten/Desktop/GDL/libraries/oshi-project/oshi-core/1.1/oshi-core-1.1.jar:/Users/lorimarten/Desktop/GDL/libraries/net/java/dev/jna/jna/4.4.0/jna-4.4.0.jar:/Users/lorimarten/Desktop/GDL/libraries/net/java/dev/jna/platform/3.4.0/platform-3.4.0.jar:/Users/lorimarten/Desktop/GDL/libraries/com/ibm/icu/icu4j-core-mojang/51.2/icu4j-core-mojang-51.2.jar:/Users/lorimarten/Desktop/GDL/libraries/com/mojang/javabridge/1.0.22/javabridge-1.0.22.jar:/Users/lorimarten/Desktop/GDL/libraries/net/sf/jopt-simple/jopt-simple/5.0.3/jopt-simple-5.0.3.jar:/Users/lorimarten/Desktop/GDL/libraries/io/netty/netty-all/4.1.25.Final/netty-all-4.1.25.Final.jar:/Users/lorimarten/Desktop/GDL/libraries/com/google/guava/guava/21.0/guava-21.0.jar:/Users/lorimarten/Desktop/GDL/libraries/org/apache/commons/commons-lang3/3.5/commons-lang3-3.5.jar:/Users/lorimarten/Desktop/GDL/libraries/commons-io/commons-io/2.5/commons-io-2.5.jar:/Users/lorimarten/Desktop/GDL/libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar:/Users/lorimarten/Desktop/GDL/libraries/net/java/jinput/jinput/2.0.5/jinput-2.0.5.jar:/Users/lorimarten/Desktop/GDL/libraries/net/java/jutils/jutils/1.0.0/jutils-1.0.0.jar:/Users/lorimarten/Desktop/GDL/libraries/com/mojang/brigadier/1.0.17/brigadier-1.0.17.jar:/Users/lorimarten/Desktop/GDL/libraries/com/mojang/datafixerupper/2.0.24/datafixerupper-2.0.24.jar:/Users/lorimarten/Desktop/GDL/libraries/com/google/code/gson/gson/2.8.0/gson-2.8.0.jar:/Users/lorimarten/Desktop/GDL/libraries/com/mojang/authlib/1.5.25/authlib-1.5.25.jar:/Users/lorimarten/Desktop/GDL/libraries/org/apache/commons/commons-compress/1.8.1/commons-compress-1.8.1.jar:/Users/lorimarten/Desktop/GDL/libraries/org/apache/httpcomponents/httpclient/4.3.3/httpclient-4.3.3.jar:/Users/lorimarten/Desktop/GDL/libraries/commons-logging/commons-logging/1.1.3/commons-logging-1.1.3.jar:/Users/lorimarten/Desktop/GDL/libraries/org/apache/httpcomponents/httpcore/4.3.2/httpcore-4.3.2.jar:/Users/lorimarten/Desktop/GDL/libraries/it/unimi/dsi/fastutil/8.2.1/fastutil-8.2.1.jar:/Users/lorimarten/Desktop/GDL/libraries/org/apache/logging/log4j/log4j-api/2.8.1/log4j-api-2.8.1.jar:/Users/lorimarten/Desktop/GDL/libraries/org/apache/logging/log4j/log4j-core/2.8.1/log4j-core-2.8.1.jar:/Users/lorimarten/Desktop/GDL/libraries/org/lwjgl/lwjgl/3.2.1/lwjgl-3.2.1.jar:/Users/lorimarten/Desktop/GDL/libraries/org/lwjgl/lwjgl-jemalloc/3.2.1/lwjgl-jemalloc-3.2.1.jar:/Users/lorimarten/Desktop/GDL/libraries/org/lwjgl/lwjgl-openal/3.2.1/lwjgl-openal-3.2.1.jar:/Users/lorimarten/Desktop/GDL/libraries/org/lwjgl/lwjgl-opengl/3.2.1/lwjgl-opengl-3.2.1.jar:/Users/lorimarten/Desktop/GDL/libraries/org/lwjgl/lwjgl-glfw/3.2.1/lwjgl-glfw-3.2.1.jar:/Users/lorimarten/Desktop/GDL/libraries/org/lwjgl/lwjgl-stb/3.2.1/lwjgl-stb-3.2.1.jar:/Users/lorimarten/Desktop/GDL/libraries/com/mojang/text2speech/1.11.3/text2speech-1.11.3.jar:/Users/lorimarten/Desktop/GDL/libraries/ca/weblite/java-objc-bridge/1.0.0/java-objc-bridge-1.0.0.jar":"/Users/lorimarten/Desktop/GDL/versions/1.14.4/1.14.4.jar" cpw.mods.modlauncher.Launcher --username GodIsWalter --version forge-28.2.4 --gameDir "/Users/lorimarten/Desktop/GDL/packs/AlltheMods4ATM4" --assetsDir "/Users/lorimarten/Desktop/GDL/assets" --assetIndex 1.14 --uuid 88cab0d5241942e58215b943652316f9 --accessToken HIDDEN_ACCESS_TOKEN --userType mojang --versionType release --launchTarget fmlclient --fml.forgeVersion 28.2.4 --fml.mcVersion 1.14.4 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20190829.143755  
instancesManager.js:182 2020-05-03 18:53:25,425 main WARN Advanced terminal features are not available in this environment

instancesManager.js:182 [18:53:25] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, GodIsWalter, --version, forge-28.2.4, --gameDir, /Users/lorimarten/Desktop/GDL/packs/AlltheMods4ATM4, --assetsDir, /Users/lorimarten/Desktop/GDL/assets, --assetIndex, 1.14, --uuid, 88cab0d5241942e58215b943652316f9, --accessToken, ❄❄❄❄❄❄❄❄, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 28.2.4, --fml.mcVersion, 1.14.4, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20190829.143755][m
instancesManager.js:182 [18:53:25] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 4.1.0+62+5bfa59b starting: java version 13.0.2 by Oracle Corporation[m
instancesManager.js:182 [18:53:26] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust[m
7instancesManager.js:182 [18:53:29] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release[m
57instancesManager.js:182 [18:53:30] [main/INFO] [STDERR/]: [jdk.nashorn.api.scripting.NashornScriptEngine:<init>:143]: Warning: Nashorn engine is planned to be removed from a future JDK release[m
instancesManager.js:182 [18:53:35] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, forge-28.2.4, --gameDir, /Users/lorimarten/Desktop/GDL/packs/AlltheMods4ATM4, --assetsDir, /Users/lorimarten/Desktop/GDL/assets, --uuid, 88cab0d5241942e58215b943652316f9, --username, GodIsWalter, --assetIndex, 1.14, --accessToken, ❄❄❄❄❄❄❄❄, --userType, mojang, --versionType, release][m
console.js:72 18:53:36.524 › Exception in thread "main" 
a @ console.js:72
n @ console.js:37
r @ log.js:25
(anonymous) @ instancesManager.js:186
emit @ events.js:194
addChunk @ _stream_readable.js:296
readableAddChunk @ _stream_readable.js:277
Readable.push @ _stream_readable.js:232
onStreamRead @ internal/stream_base_commons.js:165
instancesManager.js:182 [18:53:36] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1049]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException[m[18:53:36] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1049]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)[m[18:53:36] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1049]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)[m[18:53:36] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1049]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)[m[18:53:36] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1049]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)[m[18:53:36] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1049]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)[m[18:53:36] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1058]: Caused by: java.lang.reflect.InvocationTargetException[m[18:53:36] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1058]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[m[18:53:36] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1058]: 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[m[18:53:36] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1058]: 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[m[18:53:36] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1058]: 	at java.base/java.lang.reflect.Method.invoke(Method.java:567)[m[18:53:36] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1058]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)[m[18:53:36] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1058]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)[m[18:53:36] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1058]: 	... 4 more[m[18:53:36] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]: Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 57[m[18:53:36] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]: 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:176)[m[18:53:36] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]: 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:158)[m[18:53:36] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]: 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:146)[m
instancesManager.js:182 [18:53:36] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]: 	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:273)[m
instancesManager.js:182 [18:53:36] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]: 	at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:82)[m
instancesManager.js:182 [18:53:36] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]: 	at cpw.mods.modlauncher.TransformerClassWriter.access$100(TransformerClassWriter.java:35)[m
instancesManager.js:182 [18:53:36] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]: 	at cpw.mods.modlauncher.TransformerClassWriter$SuperCollectingVisitor.visit(TransformerClassWriter.java:129)[m
instancesManager.js:182 [18:53:36] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]: 	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:368)[m
instancesManager.js:182 [18:53:36] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]: 	at cpw.mods.modlauncher.TransformerClassWriter.computeHierarchy(TransformerClassWriter.java:74)[m
instancesManager.js:182 [18:53:36] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]: 	at cpw.mods.modlauncher.TransformerClassWriter.<init>(TransformerClassWriter.java:48)[m
instancesManager.js:182 [18:53:36] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)[m
instancesManager.js:182 [18:53:36] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:241)[m
instancesManager.js:182 [18:53:36] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:128)[m
instancesManager.js:182 [18:53:36] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)[m
instancesManager.js:182 [18:53:36] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]: 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)[m
instancesManager.js:182 [18:53:36] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]: 	at net.minecraft.client.main.Main.main(SourceFile:126)[m
instancesManager.js:182 [18:53:36] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:658]: 	... 10 more[m`

**Comment by TOLoneWolf** [comment]
https://github.com/gorilla-devs/GDLauncher/wiki/java-64-bit-installers
You may have to re-add any modpacks that where added before you did the above.

**Comment by Xico26** [comment]
I have the same issue with SkyFactory4 :disappointed: I have already done the things that are linked above.

**Comment by TOLoneWolf** [comment]
> I have the same issue with SkyFactory4  I have already done the things that are linked above.

If you did have the same issue the steps above would fix it. Only Java 8 will do. This issue the other user has 13.

Post a log from the console.

**Comment by Xico26** [comment]
Thanks for answering
I'm using Kubuntu 20.04 so I followed the instructions for Linux and installed Java 8 using that command but it still doesn't work. 😔

**Comment by Xico26** [comment]
How do I access the console?

**Comment by DylanBeMe** [comment]
@Xico26 after installing a new java version change the java path in the launcher

**Comment by Xico26** [comment]
Oh thanks!
I'll try it again soon.

**Comment by TOLoneWolf** [comment]
> How do I access the console?

https://github.com/gorilla-devs/GDLauncher/wiki/Console-and-Log

**Comment by Xico26** [comment]
But does the log open immediately or do I need to do something for it to open? I've never seen the log and I've already played vanilla 1.15.2 with no problems.

**Comment by DylanBeMe** [comment]
@Xico26 if you have more than one java you might also want to run 
"sudo update-alternatives --config java"
to update the default java used on your pc

**Comment by TOLoneWolf** [comment]
> But does the log open immediately or do I need to do something for it to open? I've never seen the log and I've already played vanilla 1.15.2 with no problems.

That means it's using newer version of Java above 8

**Comment by Xico26** [comment]
> > How do I access the console?
> 
> https://github.com/gorilla-devs/GDLauncher/wiki/Console-and-Log

Thanks!

**Comment by Xico26** [comment]
When trying to open settings this happens:
![Screenshot_20200504_190341](https://user-images.githubusercontent.com/47830278/80998133-51369380-8e3a-11ea-93e5-98d11b45a089.png)

**Comment by DylanBeMe** [comment]
@Xico26 log out and back in, this is a known bug

**Comment by Xico26** [comment]
Done!

**Comment by Xico26** [comment]
What's the java path?

**Comment by Xico26** [comment]
Is it correct when running?

> java -version

openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-3ubuntu1, mixed mode, sharing)

**Comment by AzureDoom** [comment]
No, that is showing Java 11, you MUST use java 8.

**Comment by TOLoneWolf** [comment]
which java
whereis java
Find java

Should list the path to someplace in side:
/usr/bin/java/
Should have 8 in the folder name not the one marked 11.

**Comment by Xico26** [comment]
When I tried to install using sudo apt install java8 or something like that (IDK 😃) it said that it was already installed. Now I'm trying to install the OpenJDK package using:

> sudo apt-get install adoptopenjdk-8-hotspot

**Comment by Xico26** [comment]
Still the same thing... 😟
I'll try removing all Java's and installing this

**Comment by DylanBeMe** [comment]
run `sudo update-alternatives --config java` and also change the path in the launcher.
that command lets you set the default java and shows the path, but you'll have to change the path in GD manually

**Comment by Xico26** [comment]
Well...

> xicomaia@xicomaia-kubuntu:~$ java -version
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.252-b09, mixed mode)

**Comment by Xico26** [comment]
Working!!! Thanks a lot!! 😁😁

**Comment by TOLoneWolf** [comment]
Closing as answer is provide that will fix the issue.
