### ISSUE TITLE
[Bug] Java memory allocation sliders don't work

### ISSUE THREAD

**Issue by thotbegone** [gorilla-devs/GDLauncher#446]
**Operating System used:**
Windows 10

**Actual behavior:**
Changing the Java memory slider past 4096 doesn't work. Minecraft still displays memory as x/4096mb. This is for global settings and instance specific settings.

**Steps to reproduce the behavior:**
Adjust global/instance Java memory settings, start Minecraft.

**Expected behavior:**
Adjusting the memory settings should change them for Minecraft.

**Additional context:**
This is a fresh install, I haven't done anything besides install a modpack.

**Comment by Ladvace** [comment]
can you check the dev console when you move the slider?

**Comment by thotbegone** [comment]
No new output when I move the slider, but it gave me a few of these when I started up?

> 17:13:01.985 › Error: ENOENT: no such file or directory, open 'C:\Users\j4sp3\AppData\Roaming\.minecraft\launcher_profiles.json'

**Comment by Ladvace** [comment]
you should see something like that, can you see it?
![image](https://user-images.githubusercontent.com/31326058/81042908-79ada480-8eb1-11ea-938a-4398cb59c03d.png)

**Comment by thotbegone** [comment]
Nope, can't see that anywhere unfortunately.

**Comment by Ladvace** [comment]
seems that in production doesn't work, in dev yes

**Comment by Ladvace** [comment]
can u send me the long you recive when u launch minecraft?

**Comment by thotbegone** [comment]
Sorry is that the Minecraft log or the dev console log?

**Comment by Ladvace** [comment]
in the dev console when you launch minecraft it should console all mc args

**Comment by thotbegone** [comment]
19:52:58.283 › Parsing json version for libraries
console.js:72 19:52:58.294 › "C:\Program Files (x86)\Common Files\Oracle\Java\javapath\java.exe" -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms256m -Xmx5120m   -Djava.library.path="C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\packs\test\natives"  -Dminecraft.client.jar="C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\versions\1.15.2\1.15.2.jar" -cp "C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\net\minecraftforge\forge\1.15.2-31.1.74\forge-1.15.2-31.1.74.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\org\ow2\asm\asm\7.2\asm-7.2.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\org\ow2\asm\asm-commons\7.2\asm-commons-7.2.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\org\ow2\asm\asm-tree\7.2\asm-tree-7.2.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\cpw\mods\modlauncher\5.1.0\modlauncher-5.1.0.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\cpw\mods\grossjava9hacks\1.3.0\grossjava9hacks-1.3.0.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\net\minecraftforge\accesstransformers\2.1.1-shadowed\accesstransformers-2.1.1-shadowed.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\net\minecraftforge\eventbus\2.1.0-service\eventbus-2.1.0-service.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\net\minecraftforge\forgespi\2.1.2\forgespi-2.1.2.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\net\minecraftforge\coremods\2.0.3\coremods-2.0.3.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\net\minecraftforge\unsafe\0.2.0\unsafe-0.2.0.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\com\electronwill\night-config\core\3.6.2\core-3.6.2.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\com\electronwill\night-config\toml\3.6.2\toml-3.6.2.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\org\jline\jline\3.12.1\jline-3.12.1.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\org\apache\maven\maven-artifact\3.6.0\maven-artifact-3.6.0.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\net\jodah\typetools\0.6.1\typetools-0.6.1.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\org\apache\logging\log4j\log4j-api\2.11.2\log4j-api-2.11.2.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\org\apache\logging\log4j\log4j-core\2.11.2\log4j-core-2.11.2.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\net\minecrell\terminalconsoleappender\1.2.0\terminalconsoleappender-1.2.0.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\net\sf\jopt-simple\jopt-simple\5.0.4\jopt-simple-5.0.4.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\com\mojang\patchy\1.1\patchy-1.1.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\oshi-project\oshi-core\1.1\oshi-core-1.1.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\net\java\dev\jna\platform\3.4.0\platform-3.4.0.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\com\mojang\javabridge\1.0.22\javabridge-1.0.22.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\net\sf\jopt-simple\jopt-simple\5.0.3\jopt-simple-5.0.3.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\io\netty\netty-all\4.1.25.Final\netty-all-4.1.25.Final.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\com\google\guava\guava\21.0\guava-21.0.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\org\apache\commons\commons-lang3\3.5\commons-lang3-3.5.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\commons-io\commons-io\2.5\commons-io-2.5.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\commons-codec\commons-codec\1.10\commons-codec-1.10.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\com\mojang\brigadier\1.0.17\brigadier-1.0.17.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\com\mojang\datafixerupper\2.0.24\datafixerupper-2.0.24.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\com\google\code\gson\gson\2.8.0\gson-2.8.0.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\com\mojang\authlib\1.5.25\authlib-1.5.25.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\it\unimi\dsi\fastutil\8.2.1\fastutil-8.2.1.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\org\apache\logging\log4j\log4j-api\2.8.1\log4j-api-2.8.1.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\org\apache\logging\log4j\log4j-core\2.8.1\log4j-core-2.8.1.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\org\lwjgl\lwjgl\3.2.2\lwjgl-3.2.2.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\org\lwjgl\lwjgl-jemalloc\3.2.2\lwjgl-jemalloc-3.2.2.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\org\lwjgl\lwjgl-openal\3.2.2\lwjgl-openal-3.2.2.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\org\lwjgl\lwjgl-opengl\3.2.2\lwjgl-opengl-3.2.2.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\org\lwjgl\lwjgl-glfw\3.2.2\lwjgl-glfw-3.2.2.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\org\lwjgl\lwjgl-stb\3.2.2\lwjgl-stb-3.2.2.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\org\lwjgl\lwjgl-tinyfd\3.2.2\lwjgl-tinyfd-3.2.2.jar;C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\libraries\com\mojang\text2speech\1.11.3\text2speech-1.11.3.jar";"C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\versions\1.15.2\1.15.2.jar" cpw.mods.modlauncher.Launcher --username oklistenup --version forge-31.1.74 --gameDir "C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\packs\test" --assetsDir "C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\assets" --assetIndex 1.15 --uuid c62228ee653e4551b3798c167a58add9 --accessToken HIDDEN_ACCESS_TOKEN --userType mojang --versionType release --launchTarget fmlclient --fml.forgeVersion 31.1.74 --fml.mcVersion 1.15.2 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20200414.225201  
instancesManager.js:182 2020-05-05 19:52:59,923 main WARN Advanced terminal features are not available in this environment

instancesManager.js:182 [19:53:00] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, oklistenup, --version, forge-31.1.74, --gameDir, C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\packs\test, --assetsDir, C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\assets, --assetIndex, 1.15, --uuid, c62228ee653e4551b3798c167a58add9, --accessToken, ????????, --userType, mojang, --versionType, release, --launchTarget, fmlclient, --fml.forgeVersion, 31.1.74, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200414.225201]
[m
instancesManager.js:182 [19:53:00] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 5.1.0+69+master.79f13f7 starting: java version 1.8.0_241 by Oracle Corporation
[m
instancesManager.js:182 [19:53:01] [main/INFO] [ne.mi.fm.lo.FixSSL/CORE]: Added Lets Encrypt root certificates as additional trust
[m
instancesManager.js:182 [19:53:03] [main/INFO] [cp.mo.mo.LaunchServiceHandler/MODLAUNCHER]: Launching target 'fmlclient' with arguments [--version, forge-31.1.74, --gameDir, C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\packs\test, --assetsDir, C:\Users\j4sp3\AppData\Roaming\GDLauncher\instances\assets, --uuid, c62228ee653e4551b3798c167a58add9, --username, oklistenup, --assetIndex, 1.15, --accessToken, ????????, --userType, mojang, --versionType, release]
[m
instancesManager.js:182 [19:53:06] [Render thread/INFO] [minecraft/Minecraft]: Setting user: oklistenup
[m
instancesManager.js:182 [19:53:13] [Render thread/INFO] [minecraft/Minecraft]: Backend library: LWJGL version 3.2.2 build 10
[m
instancesManager.js:182 [19:53:15] [modloading-worker-1/INFO] [ne.mi.co.ForgeMod/FORGEMOD]: Forge mod loading, version 31.1.74, for MC 1.15.2 with MCP 20200414.225201
[m
instancesManager.js:182 [19:53:15] [modloading-worker-1/INFO] [ne.mi.co.MinecraftForge/FORGE]: MinecraftForge v31.1.74 Initialized
[m
instancesManager.js:182 [19:53:18] [Render thread/INFO] [mojang/NarratorWindows]: Narrator library for x64 successfully loaded
[m
instancesManager.js:182 [19:53:18] [Render thread/INFO] [minecraft/SimpleReloadableResourceManager]: Reloading ResourceManager: Default, Mod Resources
[m
instancesManager.js:182 [19:53:18] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [forge] Starting version check at https://files.minecraftforge.net/maven/net/minecraftforge/forge/promotions_slim.json
[m
instancesManager.js:182 [19:53:22] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [forge] Found status: AHEAD Current: 31.1.74 Target: null
[m
instancesManager.js:182 [19:53:27] [Render thread/INFO] [minecraft/SoundSystem]: OpenAL initialized.
[m
instancesManager.js:182 [19:53:27] [Render thread/INFO] [minecraft/SoundEngine]: Sound engine started
[m
instancesManager.js:182 [19:53:27] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[m
instancesManager.js:182 [19:53:27] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 128x128x4 minecraft:textures/atlas/signs.png-atlas
[m[19:53:27] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[m[19:53:27] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[m[19:53:27] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[m[19:53:27] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[m
instancesManager.js:182 [19:53:27] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[m
instancesManager.js:182 [19:53:28] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[m
instancesManager.js:182 [19:53:28] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[m
instancesManager.js:182 [19:53:28] [Render thread/INFO] [minecraft/AtlasTexture]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[m
instancesManager.js:182 [19:54:43] [Render thread/INFO] [minecraft/Minecraft]: Stopping!
[m
console.js:72 19:54:43.949 › Picked up _JAVA_OPTIONS: -Xmx4096m

a @ console.js:72
n @ console.js:37
r @ log.js:25
(anonymous) @ instancesManager.js:186
emit @ events.js:194
addChunk @ _stream_readable.js:296
readableAddChunk @ _stream_readable.js:277
Readable.push @ _stream_readable.js:232
onStreamRead @ internal/stream_base_commons.js:165

Sorry couldn't figure out how to hide it.

**Comment by thotbegone** [comment]
deleted my java options variable, reinstalled and it worked fine. tried without reinstalling and it didn't seem to work

**Comment by Ladvace** [comment]
Yeah, this Is a workaround, btw i'm almost finished implementing an
"autofix"

Il mer 6 mag 2020, 03:07 Jasper Heal <notifications@github.com> ha scritto:

**Comment by CrankySupertoon** [comment]
Any chance your running 32bit java?

**Comment by killpowa** [comment]
You have _JAVA_OPTIONS set on your system. We will add a way to fix this directly from the launcher but for now it's not that important, the majority of people don't have this

**Comment by thotbegone** [comment]
definitely not 32bit, yeah I had it set for the mod dev environment, it always worked w/ twitch so I was just confused

**Comment by hypherionmc** [comment]
This should be fixed by now. If not, please leave a comment
