### ISSUE TITLE
[Bug] ScreenShots delete all option path is undefined

### ISSUE THREAD

**Issue by TOLoneWolf** [gorilla-devs/GDLauncher#451]
**Operating System used:**
Linux Ubuntu

**Actual behavior:**
Error path undefined.
![image](https://user-images.githubusercontent.com/8376628/81140683-e8314780-8f2f-11ea-9753-92a6be416b17.png)

**Steps to reproduce the behavior:**
1. Take a screenshot (or add a file into the folder).  
2. right click instance.
3. select manage
4. select screenshots
5. checkmark image.
6. click on the trash can icon on the top menu for removing all selected images.
7. Confirm deletion.
8. ERROR Path undefined.

**Expected behavior:**

**If applicable, add screenshots/videos to help explain:**
![image](https://user-images.githubusercontent.com/8376628/81139874-f9c52000-8f2c-11ea-8f9e-41f3610937fa.png)

**Additional context:**

Does not happen when using the context menu delete option on each individual image.

Running currently latest commit as date 2020/05/06  
https://github.com/gorilla-devs/GDLauncher/commit/01e2add3ba7a21ef2f09be09342e6f5ebdf5ebef

**Comment by Ladvace** [comment]
fixed
