### ISSUE TITLE
[Bug] Screenshots broken image rendering - linux

### ISSUE THREAD

**Issue by TOLoneWolf** [gorilla-devs/GDLauncher#454]
**Operating System used:**
Linux Ubuntu

**Actual behavior:**
Shows broken image icon in both the list and full screen views.

**Steps to reproduce the behavior:**
Take screenshots and open the screenshots manager.
broken image icon.

click on image to view full screen.
broken image icon.

**Expected behavior:**
Render Images.

**If applicable, add screenshots/videos to help explain:**
![image](https://user-images.githubusercontent.com/8376628/81192439-d7a8bd80-8f7f-11ea-9c29-746bb05dd4cd.png)
![image](https://user-images.githubusercontent.com/8376628/81193489-125f2580-8f81-11ea-9545-0638fe2f1a34.png)

**Additional context:**

Somehow windows lets this pass without throwing an error like it should.
Unknown if macOS allows this to pass.

`file:///` should be added to `img src=path.png`

example result:  
`<img src=file:////home/user/.config/gdlauncher/instances/vanilla/screenshots/image.png />`
`<img src=file:///C:\Users\User\AppData\Roaming\gdlauncher\instances\vanilla\screenshots\image.png />`

**Comment by TOLoneWolf** [comment]
Appears that `yarn dev` is where this happens.

**Comment by Ladvace** [comment]
and in production?

**Comment by Ladvace** [comment]
I tested it on linux but just in dev

**Comment by TOLoneWolf** [comment]
going to test as soon as its done building.
DylanH reported he had no issues with it in production only in dev as well.

**Comment by TOLoneWolf** [comment]
It does work fine in production for me as well on linux and windows.

Adding the file protocol still seems like a good idea though.

**Comment by DylanHameleers** [comment]
why would you? it's just more work and it works without it..

**Comment by Ladvace** [comment]
yeah I already added

**Comment by TOLoneWolf** [comment]
nice.

**Comment by TOLoneWolf** [comment]
src/common/modals/Screenshot.js
also needs that applied.
for full screen view.

**Comment by DylanBeMe** [comment]
fixed and should be closed :)
