### ISSUE TITLE
[Bug] some mods can't be installed (GDlauncher 0.0.6)

### ISSUE THREAD

**Issue by jinkhya** [gorilla-devs/GDLauncher#457]
### We are currently only taking Bug Reports for the Upcoming Next Release which will fix most of the legacy build's bugs.
---

**Operating System used:**
Manjaro 5.6.10-1

**Actual behavior:**
Some 1.15 mods can't be installed and show "no data". I believe it might be because they're jars for fabric and forge at the same time and not marked as working for forge. 
As an example : 
https://i.imgur.com/r6Ad0vb.png

**Steps to reproduce the behavior:**
Make a 1.15 forge instance
Try to add Light Overlay mod or Rare Ice

**Expected behavior:**
I dunno if that can be fixed on your end or if it falls on the mod devs not adding some of the possible tags, but ideally I'd like to be able to add those mods without downloading it from curse website :)

**Comment by TOLoneWolf** [comment]
Appears they have no game version set for forge. Which GDL for its filtering system.
They only have it listed as fabric and mc versions. That is for each version of the mod. If they add 'game version: Forge' tag it should be available after that.

**Comment by TOLoneWolf** [comment]
Should be listed as Supported Modloader versions.
https://www.curseforge.com/minecraft/mc-mods/light-overlay/files/2874208
![image](https://user-images.githubusercontent.com/8376628/81223779-32f0a500-8fac-11ea-9db4-04683b8f65ec.png)

**Comment by furtabs** [comment]
You can only have 1 loader though

**Comment by blarfoon** [comment]
This cannot be fixed sadly.
