### ISSUE TITLE
[Bug] not call a crash a “fucky wucky”

### ISSUE THREAD

**Issue by furtabs** [gorilla-devs/GDLauncher#461]
### We are currently only taking Bug Reports for the Upcoming Next Release which will fix most of the legacy build's bugs.
---

**Operating System used:**
Manjaro

**Actual behavior:**
Well I mean this is the actual behavior but idk if it really should be

**Steps to reproduce the behavior:**
Crash the launcher

**Expected behavior:**
Not say “fucky wucky”

**If applicable, add screenshots/videos to help explain:**

**Additional context:**

**Comment by rlnt** [comment]
Would also appreciate the removal of the "Uwu".

**Comment by tilda** [comment]
I can take on this issue if wanted.

**Comment by Ladvace** [comment]
Davide has some mental problem for that kind of sentences

Il mar 12 mag 2020, 12:52 tilda <notifications@github.com> ha scritto:

**Comment by blarfoon** [comment]
Fixed

**Comment by LordMZTE** [comment]
lol wut
