### ISSUE TITLE
[Feature] Show modpack version

### ISSUE THREAD

**Issue by Discomanco** [gorilla-devs/GDLauncher#466]
### We are currently only taking Feature Requests for the Upcoming Next Release which will fix most of the legacy build's bugs.
---

**Describe the new feature you are requesting**
A way to see what version a modpack is currently on. Very helpful when playing on servers, or simply forgetting if you updated or not.
Also highly preferred for it to be shown on the main menu/modpack selection area, perhaps in the bottom right corner

**Describe alternatives to this feature if applicable**
It could be put in the Modpack Overview, if you feel it would clutter too much on the main menu.

**Additional Information**

**Comment by tilda** [comment]
I'm thinking this is a dupe of #251 ?

**Comment by Discomanco** [comment]
And that was even by me as well, so GJ me?

**Comment by fabm3n** [comment]
Yeah, @tilda did a good job. I also think it's a duplicate.

**Comment by tloskpd** [comment]
+1 for me.  In the old UI, it would list installed version right above the dropdown to select version

**Comment by Roversword** [comment]
+1 from my side.
Would love to see some indication that the modpack has a new version available before launching in the instances page (so I can change to new version and update before starting).
Much appreciated for looking into it.

**Comment by ChaseIngebritson** [comment]
Whoops, I created issue #534 before realizing this issue existed.

As I noted in that issue:
> Resolved in pull request #542 (commit [397ba366106bdebd0e67f6b66c1057e9a63a7191](https://github.com/gorilla-devs/GDLauncher/commit/397ba366106bdebd0e67f6b66c1057e9a63a7191)). Made available in release [v1.0.7](https://github.com/gorilla-devs/GDLauncher/releases/tag/v1.0.7)

So this one is probably good to be closed as well.
