### ISSUE TITLE
Instances not imported to new gdlauncher

### ISSUE THREAD

**Issue by garpu** [gorilla-devs/GDLauncher#473]
I'm on Linux, slackware-current, and when I updated to gdlauncher-next, none of my instances were moved to the new installation.  

Also, they were at ~/.config/GDLauncher/GDLauncher/instances/packs, which I'm 99% sure there wasn't a GDLauncher folder within the ~/.config/GDLauncher folder before I updated.

**Comment by hron84** [comment]
It's an issue on Ubuntu too. I just don't understand why you guys did not test the update. 

Also, the previously working Linux update mechanism is not a possibility anymore, which is sad. I expected a better launcher with this upgrade not worse. :disappointed:

**Comment by Harlekin13** [comment]
Importing Instances is not even working correctly on Windows... For me it's stuck at this point for more than the last 24hours or so. It didn't freeze though, the circle is moving, i can go into settings and all.
![Unbenannt](https://user-images.githubusercontent.com/34014817/82690860-46169c80-9c5d-11ea-9103-334401bd213a.png)

**Comment by mindsolve** [comment]
Instance import seems to not at all work in the newest stable release. I just began playing Minecraft again (after some time), and updated GDLauncher from my old version (`0.12.4`) via the "Update available" button. No instance was imported. I really hope that I can do *something* manually...
