### ISSUE TITLE
[Bug] Massive CPU usage on Linux

### ISSUE THREAD

**Issue by CmdrNorthpaw** [gorilla-devs/GDLauncher#474]
**Describe the bug**
GDLauncher 1.0.0 uses a massive amount of CPU on Linux, even when idle. It usually hovers around 45-50% CPU. There is also a second GDLauncher process using around 25% CPU. Keep in mind that I'm not actually using GDLauncher to get these numbers, just leaving a window open.
**To Reproduce**
1. OpenGDLauncher
2. Leave windows open for maybe 2-3 minutes
3. Open a terminal and run the `top` command
4. Notice the high amount

**Expected behavior**
Well I mean, it really shouldn't be using almost 3 quarters of a thread when doing nothing

**Screenshots**
![Screenshot of top while GDLauncher is running](https://user-images.githubusercontent.com/30018896/82188206-6fde6500-98e5-11ea-83fc-15273d537e0f.png)
This is a screenshot of top, a Linux resource monitoring utility, to show the CPU usage. GDLauncher is not doing anything like installing modpacks here, just sitting there.

**Operating System:**
 - OS: Manjaro
 - Version: Latest (Manjaro is a rolling release).

**Additional context**
I don't know if this is a GDLauncher problem or a problem with AppImages. I will test with the AUR version later today. Also, for context, I have an Intel Core i3-5010U, with 2 cores and 4 threads.

**Comment by CmdrNorthpaw** [comment]
Update: Having installed a build from the AUR, I can confirm that this issue is not limited to the AppImage.

**Comment by furtabs** [comment]
Most likely your side I maintain the AUR package and can not duplicate. It does however stall a lot but I think that is my fault

**Comment by CmdrNorthpaw** [comment]
Perhaps it uses less on your CPU because it is more powerful than mine?

**Comment by TOLoneWolf** [comment]
Might have something to do with the migration of instance feature

**Comment by CmdrNorthpaw** [comment]
No, I nuked my instances before upgrading because I wanted to start fresh.

**Comment by blarfoon** [comment]
Is this still an issue?

**Comment by CmdrNorthpaw** [comment]
I think so. Current version only uses around 5% at idle.

**Comment by Shijikori** [comment]
I personnaly have 1% usage (divided by number of cores/threads, should be similar usage shown on Windows) even none when idle. I get up to 25% not divided which is on a scale of 0 to 1200% for my system. When idle, the non-divided value is 1% constatly. I'm using a Ryzen 5 2600X and I am on the beta channel.

**Comment by Eskaan** [comment]
> I think so. Current version only uses around 5% at idle.
> […](#)
> On 8 Jul 2020, at 09:58, Davide Ceschia ***@***.***> wrote: ﻿ Is this still an issue? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

5% from what?
