### ISSUE TITLE
Broken Manifest.json when exporting instances/profiles

### ISSUE THREAD

**Issue by Rensik** [gorilla-devs/GDLauncher#480]
**Describe the bug**

Manifest.json is not receiving proper mod info when exporting a profile/instance.

**To Reproduce**

Export an instance.

**Expected behavior**

When importing exported instance, it should have thenecessary information available to download and install mods properly.

**Possible solutions**
Some ideas of how you would solve this issue, if possible

**Screenshots**

**Operating System:**
 - OS: [e.g. Windows]
 - Version [e.g. 10]

**Additional context**

**Comment by Rensik** [comment]
Extension to Issue: it's not exporting mods at all. I just tried selecting mods as something to be exported manually as an override, and the export failed to include any.

**Comment by TOLoneWolf** [comment]
Cannot reproduce any export problems in version 1.0.0 and 1.0.3

**Comment by TOLoneWolf** [comment]
Everything that is check will be exported.
Any mods that are from CurseForge will be added to the manifest as projectid/fileid only, the jar is never in the export zip. Mods from CurseForge must also have a check mark or they are not added to the export manifest.

**Comment by RnChan408** [comment]
It didn't do that in the old launcher so I can understand how something like this would happen. Before if you had any mod installed, the launcher would not include them in the manifest and instead included the jar files themselves. I guess this was changed but nobody mentioned it since it was such a minor change.
