### ISSUE TITLE
[BUG] Interference with Minecraft

### ISSUE THREAD

**Issue by DariusSG** [gorilla-devs/GDLauncher#482]
**Describe the bug**
Basically, It is Minecraft but you can't move(Forward,Backward,Left,Right) or interact with the world.
It is on modded instances and maybe affect new instances created by the new launcher cos I didn't get past building terrain.

**To Reproduce**
1. Upgrade launcher and import old instance from previous launcher.
2. Play on new launcher
3. Enter your world

**Expected behavior**
Well, I should be able to play.

**Possible solutions**
On reviewing the changes for the new launcher, Launching instance on the new launcher will be via shortcut/symlink on the C:/ to the appdata/roaming/.. folder. Reverting this new launch sequence to the old one might help. maybe that the issue? I doubt it.
 

**Operating System:**
 - OS: Windows 10
 - Version: GD 0.12.4 to 1.0.0

**Additional context**
Well this is weird.
Created a test instance, cannot enter the world even if mods are the same.(Error was on FTB libs which worked on the original instance on GD 0.12.4(same version of ftb libs))
[Orginial Instance ON GD 0.12.4.log](https://github.com/gorilla-devs/GDLauncher/files/4657798/Orginial.Instance.ON.GD.0.12.4.log)
[TEST INSTANCE ON GD 1.0.0.log](https://github.com/gorilla-devs/GDLauncher/files/4657792/TEST.INSTANCE.ON.GD.1.0.0.log)
[Imported orginial instance on GD 1.0.0.log](https://github.com/gorilla-devs/GDLauncher/files/4657794/Imported.orginial.instance.on.GD.1.0.0.log)

**Comment by DariusSG** [comment]
:( Nobody is interested

**Comment by DariusSG** [comment]
Well if anyone is willing to help, Please do. It is not solved

**Comment by tilda** [comment]
This doesn't look like GDLauncher's fault. Possibly something else on your computer.

**Comment by DariusSG** [comment]
Well, Explain how it works on 0.12.4 but not on 1.0.0. It happened when I updated to the new launcher,
