### ISSUE TITLE
Unable to launch any instances.

### ISSUE THREAD

**Issue by Ghordath** [gorilla-devs/GDLauncher#483]
I installed the new launcher (very nice btw!).  It moved my instances from my gaming drive to my windows drive, and i figured out how to change the path for that and i moved the instances back. But I don't have the "modpack" menu item available on the manage page.  So i deleted one of the instances and did a fresh install of it. Now when i hit play I get the "Error: Could not find or load main class net.minecraft.launchwrapper.Launch"

 
 **To Reproduce**
1. Go to 'downloaded instance...'
2. Click on 'Play'
4. See error: 
Error: Uncaught Fatal Exception  Code: 1
Error Log 
Error: Could not find or load main class net.minecraft.launchwrapper.Launch

**Expected behavior**
It should launch the game

**Possible solutions**
Does it not know where my Minecraft game is installed?

**Screenshots**

**Operating System:**
 - OS: Windows 10
 - Version GDLaucher 1.0.3

**Additional context**

**Comment by TOLoneWolf** [comment]
some how when you installed the pack the minecraft jar was corrupted/incomplete. Reinstalling the instance should correct that.

**Comment by Ghordath** [comment]
I deleted and reinstalled the instance and I get the same error.  (MC Eternal 1.3.5.3).  I checked and this is the version I was running on the old launcher

**Comment by TOLoneWolf** [comment]
Go into the folder you changed GDLaunchers "User Data Path" to.
Should be a  "datastore" folder there.
go inside "datastore\libraries\net\minecraft" folders.
Should be a "1.12.2.jar" and "1.12.2json". Remove them. Then inside gdlauncher create a new vanilla instance of 1.12.2.

Then try try launching the vanilla instance, if that starts then try running the modpack.

**Comment by Ghordath** [comment]
Now I get this message when trying to launch 1.12.2 Vanilla.

 Error: Could not find or load main class net.minecraft.client.main.Main

**Comment by TOLoneWolf** [comment]
Grr, it should be replacing the jars...  

alright do it manually i guess.  


Download this with the name "1.12.2.json" in "datastore\libraries\net\minecraft" folder.
https://launchermeta.mojang.com/v1/packages/6e69e85d0f85f4f4b9e12dd99d102092a6e15918/1.12.2.json  
(ctrl+s to save or right click save as)  


Download this with the name "1.12.2.jar" in "datastore\libraries\net\minecraft" folder.
https://launcher.mojang.com/v1/objects/0f275bc1547d01fa5f56ba34bdc87d981ee12daf/client.jar  


Download this with the name "forge-1.12.2-14.23.5.2847.jar" in "datastore\libraries\net\minecraftforge\forge\1.12.2-14.23.5.2847" folder.
https://files.minecraftforge.net/maven/net/minecraftforge/forge/1.12.2-14.23.5.2847/forge-1.12.2-14.23.5.2847-universal.jar

**Comment by Ghordath** [comment]
Still getting the error when loading vanilla 1.12.2

Error: Could not find or load main class net.minecraft.client.main.Main

I even tried deleting all the files and let it repopulate everything but that didn't help.

Not sure if this helps but the MCEternal error is different from the vanilla one 

Error: Could not find or load main class net.minecraft.launchwrapper.Launch

**Comment by Ghordath** [comment]
I can run vanilla 1.12.2 from the Mojang launcher.

**Comment by Eskaan** [comment]
@Ghordath does this issue still persist in this version of the launcher?
