### ISSUE TITLE
Dulication of files, folders, and instances after recent update

### ISSUE THREAD

**Issue by mjhymowitz** [gorilla-devs/GDLauncher#495]
After the recent update to the new launcher format, I noticed that the file path changed for the entire launcher. After a little digging, I noticed the old file path still exists and the instances before the update. It looks like a whole new installation of the GDLauncher was installed and a copy of all my old instances without deleting the old files and launcher data. 

Can I delete the old file path? Will it affect the launcher or my current instance game data if I do? How should I proceed to remove the old files?

I'm running windows 10
currently have GDlauncher V 1.0.5

![duplication error](https://user-images.githubusercontent.com/9580326/82719461-5731ce80-9c9a-11ea-8275-0be5c8881d8f.PNG)

**Comment by mjhymowitz** [comment]
The only reason I figured out because I personally changed the icon of the instance in the folder so it would show the part of the image I wanted for the instance. GDLauncher was the original file path for the instance icon now it's in gdlauncher_next.

**Comment by Harlekin13** [comment]
Thanks, that info could help me get all the stuff (worlddata, settings etc.) back the forced update (i even used the old installer for that reinstall) seemingly deleted/did not import.
Nope, everythings gone, progress of half a year, nothing's left, or better nothing's accessible, as the files are there, but GD launcher ignores them...

**Comment by TOLoneWolf** [comment]
Everything in the old "gdlauncher" folder can safely be removed.
"gdlauncher_next" is where all new data is stored.
"gdlauncher" will get recreated when gdl starts making its log file. This is partly do to a poorly implemented library (its a cross platform for logs and gets a few paths wrong ).
