### ISSUE TITLE
Updating the game results on loosing all the instances of games already saved

### ISSUE THREAD

**Issue by GridCube** [gorilla-devs/GDLauncher#503]
**Describe the bug**
If you update GDLauncher from the "there is an update available" you lose all your games

**To Reproduce**
1. Go to the top of the GDLauncher window
2. Click on There is an update availabre
3. the launcher updates
4. You lose all your games.

**Expected behavior**
not losing all games

**Possible solutions**
warn users that games might be lost
make it so it doesnt loose your games

**Comment by AzureDoom** [comment]
Old instances are not compatible

**Comment by hanleybrand** [comment]
I guess I was lucky but when I downloaded the new version the other day (downloaded a new dmg) and replaced the old app, when I launched it there was a long period of old instance being re-imported and my old saves, etc were all present. 

Is that maybe the better way to update?

**Comment by Eskaan** [comment]
Issue is outdated and a workaround exists *if* it would appear once again. As far as I can see, this issue was caused by the migrator for the instances not working - which is not needed anymore.
EDIT: fixed in 9aa0ad9c, I guess
