### ISSUE TITLE
Sort Packs by Modloader

### ISSUE THREAD

**Issue by Rensik** [gorilla-devs/GDLauncher#505]
**Is your feature request related to a problem? Please describe.**

When Browsing Modpacks, sort available Modpacks by Modloader.

**Describe the solution you'd like**

A Selection Box that sorts out Modpacks for each Modloader.

**Describe alternatives you've considered**

**Additional context**

**Comment by furtabs** [comment]
Curse API Does not support this. Bring it up to Overwolf. We could probally do a hacky check and say if project has [361988](https://www.curseforge.com/minecraft/mc-mods/jumploader) then show fabric packs. If project does not have [361988](https://www.curseforge.com/minecraft/mc-mods/jumploader) then show forge packs. but that will just be too hard at runtime.
