### ISSUE TITLE
Hitting escape closes GUIs

### ISSUE THREAD

**Issue by TheDeviantCrafter** [gorilla-devs/GDLauncher#509]
There are a handful of GUIs that cannot be closed by hitting the escape key:

1. The settings menu

2. The modpack management screen (right click modpack > manage)

3. The mod list page (right click modpack > manage > mods tab > add mod) (this should return to the mods list)

4. Mod descriptions (right click modpack > manage > mods tab > add mod > click mod) (this should return to the mod search results)

5. Browse modpacks (right click plus sign > browse modpacks)

6. Create instance (right click plus sign > create instance)

7. Import instance (right click plus sign > import instance)

8. Export instance (right click modpack > export instance)

**Comment by kreezxil** [comment]
escape doesn't work on Linux either, just tested that. however I have no issue with hitting the little x 
![image](https://user-images.githubusercontent.com/3880072/87310436-9387eb00-c4e3-11ea-9a2b-4da3fdeb8a4e.png)

which is probably besides the point, if ESC is suppose to work on all the screens, it should work for more than just Windows.

**Comment by kreezxil** [comment]
I have all 3 systems btw, and confirmed, ESCAPE does not work on Mac OSX High Sierra

**Comment by kreezxil** [comment]
ok, i tested this on my windows 10 via vm and the escape does not close any of the windows/dialogs listed.

Which version of the launcher are you using @TheDeviantCrafter @sithrebel15 @enrichman I'm using 1.0.8 in all cases.

**Comment by adveres** [comment]
Just remarking this seems to be related to https://github.com/gorilla-devs/GDLauncher/issues/358. Hotkeys don't work quite right on OSX for me.

I'll echo `<ESC>` doesn't work for any of the dialogs I tried on Mojave.

- GDLauncher 1.0.6 1.0.8
- OSX Mojave 10.14.6
- MacBook Pro (15 inch, Mid 2015)

**Comment by TheDeviantCrafter** [comment]
This appears to have been fixed as of update v1.0.1.1
