### ISSUE TITLE
Launching a second instance breaks the running directory of the first instance.

### ISSUE THREAD

**Issue by Darkere** [gorilla-devs/GDLauncher#510]
**Describe the bug**
Launching a second instance breaks the running directory of the first instance. Making it impossible to select a world/server.

**To Reproduce**
1. launch an instance.
2. launch a second instance
3. use resourcepack section to open the current running directory.

**Operating System:**
 - OS: W 10
 - Version 1.0.5

**Comment by Eskaan** [comment]
Since v0.0.11 every instance has its own running directory, no instance will corrupt an other one
