### ISSUE TITLE
turn off or redefine auxillary banners

### ISSUE THREAD

**Issue by kreezxil** [gorilla-devs/GDLauncher#514]
All Lives Matter in my book. If you pay attention to the riots, they're pulling innocent truckers from their cabs and beating them to inch of their lives. Those men and women have nothing to do with George Floyd or the police officers.

Chinese lives matter. Why don't we have solidarity with the Chinese citizens against their oppressive regime. Do you not care about what is happening Hong Kong right now?

And then there is anti-semitism alive well by the NEW BLACK PANTHER PARTY. Oh dear.

Yeah, the banner should go away after being view at least once. It should have X or right arrow to cycle thru your other messages.

**Comment by blarfoon** [comment]
I completely agree with you, we do think that all lives matter and we strongly believe in equality and inclusion.
Our message is not meant to discriminate anyone, but wants to highlight what is happening right now around the world, and let everyone know what side we stand for.
The banner will be removed soon
