### ISSUE TITLE
Unable to create a new instance when another one is running

### ISSUE THREAD

**Issue by rlnt** [gorilla-devs/GDLauncher#516]
**Describe the bug**
When any instance of the GDLauncher is running and you try to create a new one (no matter if you create it from scratch, import it from zip or download from curseforge), it will be stuck at "Downloading game files... 100%" no matter how long you wait.
When you restart the launcher, the folder doesn't have all files. It only contains `natives`, `config.json` and `installing.lock`.

**To Reproduce**
1. Start any instance you have
2. Try to create a new one while the first one is still running

**Expected behavior**
It should be possible to create another instance while any existing instance is running.

**Possible solutions**
Either lock the instance creation if it's not possible to create another instance or solve this issue.

**Screenshots**
![](https://i.imgur.com/0BrPJsK.png)
![](https://i.imgur.com/d8ury2n.png)

**Operating System:**
 - Windows 10 64 bit 2004
 - GDLauncher: v1.0.6

**Comment by Ladvace** [comment]
can you check if you get somethings in the console while downloading the instance?

**Comment by rlnt** [comment]
Here is a [pastebin](https://pastebin.com/2DZ0tLfR) with the full log.
I first started my only instance until it was fully started. Then I tried to create a new one so the interesting lines are all the way at the bottom. I think the problem is this:
```
webpack-internal:///4:7 Uncaught (in promise) Error: EBUSY: resource busy or locked, unlink 'C:\Users\Relentless\AppData\Roaming\gdlauncher_next\datastore\libraries\net\minecraftforge\forge\1.12.2-14.23.5.2847\forge-1.12.2-14.23.5.2847.jar'
```

**Comment by rlnt** [comment]
Still happens with v1.0.8.

**Comment by Eskaan** [comment]
Issue is not persistent in the newer versions.
