### ISSUE TITLE
Unable to launch instances

### ISSUE THREAD

**Issue by Archilyte** [gorilla-devs/GDLauncher#521]
**Describe the bug**
Whenever I try to launch a instance, it loads forever. When I kill it using the launcher, it says
![error](https://user-images.githubusercontent.com/39607601/84507084-491a1100-ac8e-11ea-8539-e39aec006edd.png)

**To Reproduce**
1. Make an instance
2. Try to run the instance
3. It seems to load for forever
4. Try to kill the instance
5. See error

**Expected behavior**
The instance should load properly

**Operating System:**
 - OS: Windows
 - Version: 10

**Additional context**
I have tried reinstalling gdlauncher, and making new instances

**Comment by Eskaan** [comment]
Could you please provide imformation about the modpack?

**Comment by Archilyte** [comment]
this was so long ago i dont even know if i even have the pack on my pc lol

**Comment by Eskaan** [comment]
So is the issue no longer persistent?
