### ISSUE TITLE
Now unable to update Forge in modpacks

### ISSUE THREAD

**Issue by Mordstreich** [gorilla-devs/GDLauncher#522]
Love the new look, but I've found an issue. You use to be able to delete Forge and re-install any version, allowing you to update. This seems to now not be possible. Of course, I find this out after updating a mod to get rid of an annoying bug, only to find it now needs the latest forge, and I cant update or start my game...
 
Is this deliberate or do I have an issue at my end? If it is intended, is it something that is going to be fixed?

**Comment by ChaseIngebritson** [comment]
This was resolved by pull request #504 and made available in release [v1.0.8](https://github.com/gorilla-devs/GDLauncher/releases/tag/v1.0.8).
