### ISSUE TITLE
Error During Installation

### ISSUE THREAD

**Issue by Tkdriverx** [gorilla-devs/GDLauncher#523]
**Describe the bug**
JavaScript exception when installing (see image). When trying to launch the installed program, it still throws the same error.
I checked the installed version of Java, in case that was the issue. Installing the current version did not fix the issue.

**To Reproduce**
1. Run the installer

**Expected behavior**
For it to launch.

**Screenshots**
![image](https://user-images.githubusercontent.com/9004164/84582160-73ff8480-adb6-11ea-8dcc-555ed659f268.png)
(Screenshot taken from within Windows Sandbox, to not ruin my actual installation by accident)

**Operating System:**
 - OS: Windows 10
 - Currently live version on the site (and Next)

**Comment by Eskaan** [comment]
Did you disable the "custom Java" option in the settings as in the instance overwiew?

**Comment by Tkdriverx** [comment]
This is so old, I'm pretty sure its been fixed by now. Also this wasn't related to instances at all, it was the installer not working.

**Comment by Eskaan** [comment]
Thanks
