### ISSUE TITLE
No longer being able to update instances.

### ISSUE THREAD

**Issue by charmchuu** [gorilla-devs/GDLauncher#525]
**Describe the bug**
Previously GDLauncher had the ability to seamlessly update an instance to another version by managing the instance and changing the version. That functionality seems to be gone now. This might be an intentional change, but I decided to post an issue report about it on the off chance that it's not.

**Comment by ogmacwinux** [comment]
I was also wondering about that and saw this on their discord:

![screenshot 1592384667](https://user-images.githubusercontent.com/61723329/84878728-cdb8c500-b0bc-11ea-89e5-c3ed1340234c.png)

If the instance was installed on a previous version, the modpack menu would not appear:

![image](https://user-images.githubusercontent.com/61723329/84878869-05277180-b0bd-11ea-9f38-a1f207f61f0c.png)

However if you add a new instance in the current version, the modpack menu would now appear.

![image](https://user-images.githubusercontent.com/61723329/84878998-3738d380-b0bd-11ea-88d4-34549f6e3ab8.png)

Hope this helps.

**Comment by Eskaan** [comment]
Outdated and because a workaround exists, I would close it. okay? 🥲
