### ISSUE TITLE
Support ReplayMod as part of the "add mod" UI

### ISSUE THREAD

**Issue by LindaJuffermans** [gorilla-devs/GDLauncher#529]
**Is your feature request related to a problem? Please describe.**
ReplayMod is not available on Curse and as a result doesn't show when we add mods from the UI.

**Describe the solution you'd like**
An option to get the latest ReplayMod for the correct Forge (or other modloaders) version.

**Describe alternatives you've considered**
Downloading manually and placing it into the mod folder works, UI would be easier.

**Additional context**
-

**Comment by furtabs** [comment]
1 word

# No
