### ISSUE TITLE
Ignoring updates

### ISSUE THREAD

**Issue by alven-shin** [gorilla-devs/GDLauncher#531]
**Is your feature request related to a problem? Please describe.**
It's frustrating when the update all button updates all mods to the latest version which causes Minecraft to crash.

**Describe the solution you'd like**
I would like a button next to the update button next to the mod to ignore updates for the mod until a new version comes out which could fix the bug,

**Describe alternatives you've considered**
I could just remember to downgrade the mod after clicking update all.

**Comment by DylanBeMe** [comment]
Did you open 2 by accident? (#530 and #531)

**Comment by alven-shin** [comment]
I opened 2 on purpose because they’re similar requests but still different.
