### ISSUE TITLE
Add an indicator for which version of an instance is currently installed

### ISSUE THREAD

**Issue by ChaseIngebritson** [gorilla-devs/GDLauncher#534]
**Is your feature request related to a problem? Please describe.**
When I would like to convey which version of an instance is currently installed to friends or decide whether I need to update the instance, there's no way which version is currently installed.

**Describe the solution you'd like**
An indicator of what version is currently installed either on the launch button of an instance as well as within the manage modal for an instance.

**Describe alternatives you've considered**
Another option would be putting a "currently installed version" indicator within the version select for an instance

**Additional context**
![2020-06-22 12_37_22-GDLauncher](https://user-images.githubusercontent.com/11217065/85318852-4daca980-b486-11ea-8bbe-984d341093f7.png)
![2020-06-22 12_41_00-GDLauncher](https://user-images.githubusercontent.com/11217065/85318848-4be2e600-b486-11ea-81e0-1d445bd7df9e.png)
![2020-06-22 12_45_16-GDLauncher](https://user-images.githubusercontent.com/11217065/85318845-4a192280-b486-11ea-8b58-be5814e911c7.png)

Note that this may not account for additional modifications made to the instance after it's been installed, but it would still be nice to have an indication of what version you started at even if modifications are made.

**Comment by kreezxil** [comment]
This would be great or put it in the title bar, we really need this, why is it an oversight?

![image](https://user-images.githubusercontent.com/3880072/85413249-30341a00-b530-11ea-977c-71bb9b877951.png)

**Comment by ChaseIngebritson** [comment]
Resolved in pull request #542 (commit [397ba366106bdebd0e67f6b66c1057e9a63a7191](https://github.com/gorilla-devs/GDLauncher/commit/397ba366106bdebd0e67f6b66c1057e9a63a7191)). Made available in release [v1.0.7](https://github.com/gorilla-devs/GDLauncher/releases/tag/v1.0.7)
