### ISSUE TITLE
No mods showing for Fabric

### ISSUE THREAD

**Issue by NexusNovaz** [gorilla-devs/GDLauncher#536]
After installing a Fabric MC instance and going to Manage -> Mods -> Add Mod, no mods show up

**Expected behavior**
A list of Fabric mods should appear, however, they dont. 

**Possible solutions**
Updating the API (If available) or another work around? 

**Screenshots**
![image](https://user-images.githubusercontent.com/19374500/85595329-a58f1000-b640-11ea-9975-e51fb5dac820.png)

**Operating System:**
Windows 10.

**Additional context**
GDLauncher: v1.0.6

**Comment by ChaseIngebritson** [comment]
Can you clarify which Minecraft release your Fabric instance is running?

![2020-06-25 01_05_10-GDLauncher](https://user-images.githubusercontent.com/11217065/85664536-fa05b000-b67f-11ea-8d28-a79d52c02664.png)

If you're running 1.16.1, there's a very good chance that the Curse API isn't providing any mods. Here's an example of the corresponding network requests:
* [1.16.1](https://addons-ecs.forgesvc.net/api/v2/addon/search?gameId=432&sectionId=6&categoryId=4780&pageSize=63&sort=Featured&isSortDescending=true&index=0&searchFilter=&gameVersion=1.16.1)
* [1.15.2](https://addons-ecs.forgesvc.net/api/v2/addon/search?gameId=432&sectionId=6&categoryId=4780&pageSize=63&sort=Featured&isSortDescending=true&index=0&searchFilter=&gameVersion=1.15.2)

Someone else may need to chime in with a possible workaround if there is one as my knowledge of the API itself is limited.

**Comment by NexusNovaz** [comment]
> Can you clarify which Minecraft release your Fabric instance is running?
> 
> ![2020-06-25 01_05_10-GDLauncher](https://user-images.githubusercontent.com/11217065/85664536-fa05b000-b67f-11ea-8d28-a79d52c02664.png)
> 
> If you're running 1.16.1, there's a very good chance that the Curse API isn't providing any mods. Here's an example of the corresponding network requests:
> * [1.16.1](https://addons-ecs.forgesvc.net/api/v2/addon/search?gameId=432&sectionId=6&categoryId=4780&pageSize=63&sort=Featured&isSortDescending=true&index=0&searchFilter=&gameVersion=1.16.1)
> * [1.15.2](https://addons-ecs.forgesvc.net/api/v2/addon/search?gameId=432&sectionId=6&categoryId=4780&pageSize=63&sort=Featured&isSortDescending=true&index=0&searchFilter=&gameVersion=1.15.2)
> 
> Someone else may need to chime in with a possible workaround if there is one as my knowledge of the API itself is limited.

Yes, sorry. It is 1.16.1

**Comment by revdave33** [comment]
This is also a bug with the API for the Forge 1.16.1 version. Curses...

**Comment by lag42** [comment]
i bet we'll have to wait for overwolf to come in and figure out what to do with the API before anything can be done about this, the twitch app doesn't even know 1.16 exists

**Comment by revdave33** [comment]
So has anyone made contact with curseforge/twitch/overwolf/whomever to remedy this problem? I've been trying to find a place to report it to them (since this isn't gorilla-devs fault)and am coming up empty.

**Comment by NexusNovaz** [comment]
> So has anyone made contact with curseforge/twitch/overwolf/whomever to remedy this problem? I've been trying to find a place to report it to them (since this isn't gorilla-devs fault)and am coming up empty.

I believe there is a Google doc for this on the trello board. Have a look at overwolfs website/faq.

**Comment by bluebear94** [comment]
The API now works for 1.16.1; I think this issue can be safely closed now.

**Comment by NexusNovaz** [comment]
Curseforge/Twitch fixed the issue
