### ISSUE TITLE
Shutting off news does not remove "BLM" banner.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [gorilla-devs/GDLauncher#537]
**Describe the bug**

**To Reproduce**
https://i.imgur.com/BvVN7vU.gifv

**Expected behavior**

**Possible solutions**
Some ideas of how you would solve this issue, if possible

**Screenshots**

**Operating System:**
 - OS: [e.g. Windows]
 - Version [e.g. 10]

**Additional context**

**Comment by ChaseIngebritson** [comment]
Release [v1.0.8](https://github.com/gorilla-devs/GDLauncher/releases/tag/v1.0.8) (commit #513) removes the banner, so this issue is probably good to be closed.
