### ISSUE TITLE
The OpenJDK included with GDLauncher is incompatible with Minecraft 1.16.

### ISSUE THREAD

**Issue by mtjohnson47** [gorilla-devs/GDLauncher#539]
**Describe the bug**
See [MC-191334](https://bugs.mojang.com/browse/MC-191334)

**To Reproduce**
1. Install Minecraft 1.16 in GDLauncher
2. Follow the instructions in the linked issue

**Expected behavior**
Game should behave as it does on the vanilla launcher

**Possible solutions**
- Use Oracle Java
- Have a warning for 1.16 that it should use the system's installed Java.
- Fix the bug in OpenJDK and use the new version for 1.16.

**Operating System:**
 - OS: Windows
 - Version 10

**Comment by ChaseIngebritson** [comment]
I'm unable to recreate the dialog freezing issue in 1.16 nor 1.16.1 using the OpenJDK Java bundled with GDLauncher. Do you have any other steps other than what's linked to recreate the issue?

If you disable autodetect Java path and point to a different Java binary, do you still encounter the issue?

**Comment by tilda** [comment]
CNR on Minecraft 1.16.1, tried both my own OpenJDK 1.8.0_232 and also the GDLauncher downloaded OpenJDK, Win10 as well

**Comment by Eskaan** [comment]
Issue no longer persistent. (Didn´t find the fix to link, could be a Java update tho)
Also is GDLauncher not responsible in any way for Minecraft related issues
