### ISSUE TITLE
Mod Installer Does Not List Any Mods for Fabric 1.16.1

### ISSUE THREAD

**Issue by CmdrNorthpaw** [gorilla-devs/GDLauncher#549]
**Describe the bug**
When trying to install Fabric mods on 1.161, there are no mods in the mod installer window, just blank. This is despite the fact that many authors (for instance WorldEdit) have already updated to 1.16

**To Reproduce**
1. Install a new Fabric instance for 1.16.1
2. Click on "Manage > Mods"
3. Click "Install mods"

**Expected behavior**
I expected there to be mods available for me to install.
**Possible solutions**
I think the problem could be caused by your Curse handler needing an update? I wouldn't know how to do that though.

**Screenshots**

**Operating System:**
 - OS: Arch Linux
 - Version: Latest (Arch is a rolling release).

**Additional context**
I'm using `gdlauncher-bin` v1.0.8 from the AUR.

**Comment by DylanBeMe** [comment]
Duplicate of #536 
Also not our fault but their api
