### ISSUE TITLE
[Feature] A link to go to modpack/mod web page

### ISSUE THREAD

**Issue by NexusNovaz** [gorilla-devs/GDLauncher#551]
**Is your feature request related to a problem? Please describe.**
Adding a button that will send you to the modpack/mod webpage in the browser.

**Describe the solution you'd like**
A small button just to take you to the webpage

**Describe alternatives you've considered**
Being able to change the size of the gui to display more information in an easier to read format

**Comment by kreezxil** [comment]
Ditto, i want this too.

**Comment by brightshadow74** [comment]
Likewise, the way Twitch launcher allows you to manage mods, review descriptions, change logs and then jumps to the webpage are a must have.

Also different ways to sort the mod list by file name, mod title, size..etc

**Comment by kreezxil** [comment]
@killpowa (woah, github just taught me something) ... anyways, can we please get this connected to BountySource, as this is an issue I wouldn't mind putting a $10 bounty on.

**Comment by Eskaan** [comment]
@Ladvace check this out, someone wants to give you $10 for 246d9694!
