### ISSUE TITLE
Updating twitch instances

### ISSUE THREAD

**Issue by Rosentti** [gorilla-devs/GDLauncher#559]
**Is your feature request related to a problem? Please describe.**
It would be nice if you could update twitch modpacks.

**Describe the solution you'd like**
A small button on the corner of twitch instances that would tell you if updates are available, and when pressed, you could update the instance.

**Describe alternatives you've considered**
You can import a updated version.

**Additional context**

**Comment by bluebear94** [comment]
This is already supported (right click on instance > Manage > Modpack > select newest version).

**Comment by Rosentti** [comment]
There's no modpack option. Downloaded zip from curseforge and installed.

**Comment by Rosentti** [comment]
Also, importing zip from [this](https://media.forgecdn.net/files/2991/344/GPTAE-1.3.zip) link, doesn't work, and has no modpack options.
