### ISSUE TITLE
Modded instance doesn't start

### ISSUE THREAD

**Issue by Xico26** [gorilla-devs/GDLauncher#564]
Hi!

I'm trying to open a modded instance but it doesn't work: Gives error "Uncaught fatal exception, code 1. - Exception in thread 'main'.
 "
I'm using OpenJDK 8 (the one on the wiki).

Thanks for any help. :smile: 

OS: Manjaro KDE 64-bits
Log:
[latest.log](https://github.com/gorilla-devs/GDLauncher/files/4913250/latest.log)

**Comment by Kataiser9** [comment]
Been troubleshooting this same issue (just got this launcher, also using OpenJDK 8). After a bit of sleuthing, I found that disabling Phosphor makes it work (at least for me).

**Comment by Xico26** [comment]
Thank you very much, later I'll try disabling it. But I like that mod :frowning_face:

**Comment by Xico26** [comment]
I disabled phosphor but still nothing... :(

**Comment by DylanBeMe** [comment]
If its a 1.12 modpack and it contains the mod performant disable that

**Comment by Xico26** [comment]
I don't have it.
Yes, it's a 1.12.2 modpack

**Comment by DylanBeMe** [comment]
Mixinbootstrap?

**Comment by Xico26** [comment]
Nop.

On the log I posted says the mod list?

**Comment by DylanBeMe** [comment]
Nope

**Comment by Xico26** [comment]
How can I post it easily?

**Comment by DylanBeMe** [comment]
Just tell me the modpack name

**Comment by Xico26** [comment]
It's a custom made one :slightly_frowning_face:

**Comment by Xico26** [comment]
![image](https://user-images.githubusercontent.com/47830278/87568362-71e25b80-c6bd-11ea-9735-5569398860c1.png)

![image](https://user-images.githubusercontent.com/47830278/87568392-7f97e100-c6bd-11ea-8405-222a6565cfdb.png)

![image](https://user-images.githubusercontent.com/47830278/87568438-8f172a00-c6bd-11ea-9da5-dd64fc1783e1.png)

Don't know if helps

**Comment by Xico26** [comment]
Is it anything wrong with the mods? How can I post a modlist?

**Comment by DylanBeMe** [comment]
I can't really help with this. Making modpacks isn't as easy as people think. Best thing to do it remove a few mods and see if it starts, and keep repeating until you find the mod or mods that cause this. Sorry

**Comment by Xico26** [comment]
No problem.
Thanks anyway 😊

**Comment by Xico26** [comment]
Well, I disabled Vanilla Fix and now it works!

**Comment by DylanBeMe** [comment]
Glad to hear. Could someone please close this issue if its resolved now?
