### ISSUE TITLE
[Feature Request] Mod Changelogs

### ISSUE THREAD

**Issue by whitebear60** [gorilla-devs/GDLauncher#569]
It would be cool if I can see mod changelogs when updating mods im my modpack to a newer version

**Comment by takashi1kun** [comment]
Yes this would be immensely useful to decide if update or not update without the need to visit forge for each mod, i really would want this feature

**Comment by Eskaan** [comment]
Done in 246d9694 - go into the mod overwiew page and click the ℹ️ in the upper left edge
