### ISSUE TITLE
Cannot login even though its the right email and password

### ISSUE THREAD

**Issue by Endy3032** [gorilla-devs/GDLauncher#572]
I have a Minecraft account (haven't bought mc yet) and I can't login

1. Go to the login screen
2. Enter your credentials
3. Hit login
4. Wrong password or email (Even though its right)
It should let me in but i cant

macOS 10.15.6

(Minecraft Trial Account)

**Comment by Ladvace** [comment]
Can you login in the Minecraft official Launcher?

Il ven 17 lug 2020, 10:40 Enderhoang <notifications@github.com> ha scritto:

**Comment by Endy3032** [comment]
Yes i can login in the minecraft.net site

**Comment by blarfoon** [comment]
You need to buy the game to be able to play
