### ISSUE TITLE
Light Overlay will not download on 1.15 Forge

### ISSUE THREAD

**Issue by ghost** [gorilla-devs/GDLauncher#576]
**Describe the bug**
When trying to install Light Overlay on 1.15 Forge, it tells that there isn't a mod avaible 
https://www.curseforge.com/minecraft/mc-mods/light-overlay

**Possible solutions**
Maybe because it is listed as a fabric mod, but the forge jar is the same as the fabric jar

**Comment by TheDeviantCrafter** [comment]
> Maybe because it is listed as a fabric mod, but the forge jar is the same as the fabric jar

This is probably the case. I ran into exactly the same issue with Rare Ice.

This is probably a duplicate of #565.

**Comment by Eskaan** [comment]
This IS a duplicate of #565.
