### ISSUE TITLE
[Bug/Feature Request] Search bars exit menu when attempting to select text with mouse outside of boundary

### ISSUE THREAD

**Issue by acemagex** [gorilla-devs/GDLauncher#580]
When in a search bar, such as "search for modpacks" or "add mod", attempting to click-drag mouse to select the text closes the search window if you drag the cursor beyond the text box. This can be quite frustrating when trying to quickly search for multiple mods, for example.
[Link to gif of occurence](https://gyazo.com/f8198a1e0fabc87e56d96298423cad57)

**Comment by acemagex** [comment]
Correction: Bug is only when releasing the mouse outside the search field, not when moving out of it.

**Comment by Eskaan** [comment]
Is this issue still persistent whit the most recent version og the Launcher?
