### ISSUE TITLE
403 Request blocked by the Twitch API 

### ISSUE THREAD

**Issue by foxwhite25** [gorilla-devs/GDLauncher#581]
![image](https://user-images.githubusercontent.com/39846845/88500007-30757880-cffa-11ea-9a36-146187e308d0.png)
Due to the block , I can no longer browse mod-packs on the app , I dont know if anyone else have the same issues
![image](https://user-images.githubusercontent.com/39846845/88500048-4b47ed00-cffa-11ea-8999-917243b1fa34.png)
Of-cause I can always download the zip manually , but that's just a bummer  
Any workaround?

**Comment by Ladvace** [comment]
we will add some sort of "loadign" or erro to let the user understand better, btw I don't know if it was a twitch api problem but for me it works at the moment
