### ISSUE TITLE
[Feature Request] Show when an update is available for modpack

### ISSUE THREAD

**Issue by NexusNovaz** [gorilla-devs/GDLauncher#583]
**Is your feature request related to a problem? Please describe.**
Show when a mod pack has an update available.

**Describe the solution you'd like**
For the launcher to do a check of the modpacks when the launcher is loaded and display on the instance if there is an update

**Comment by kedamono** [comment]
I would like this feature as well. I know for a fact that a mod pack I use has had an update, but you can't tell from the Manage window and there's no option to update from there as well.

**Comment by McFrugal** [comment]
To update a pack you go into Manage then click the Modpack tab on the left.  You can select a version via the dropdown menu.
Unfortunately this does seem to be the only way to tell if a modpack updated, and only then by comparing the current listed version with the most recent version in the dropdown!

**Comment by kedamono** [comment]
Sounds like you have an older version. I'm looking at mine and have version 1.0.9 which does not have a "Modpack" tab on the left hand side. It has a "Mods" tab, but no Modpack tab. I could go through and update each mod individually, but since I'm on a server, I don' know which mods were updated in the modpack that was recently uploaded to the server.

**Comment by McFrugal** [comment]
My GDLauncher is 1.0.9 as well.  The Modpack tab is directly below the Mods tab.

**Comment by kedamono** [comment]
Mine's the Mac version, and there isn't an extra tab under it. What maybe happening, is that I installed it prior to the latest GUI update, back when it was beta and the fact that it was a modpack didn't carry over in the update to the release version. Sigh, that means I'll have to reinstall it.

**Comment by Eskaan** [comment]
This feature is added whit the newer versions of the Launcher but its not present on the migrated modpacks
