### ISSUE TITLE
Unable to rename instances after creation 

### ISSUE THREAD

**Issue by TheDeviantCrafter** [gorilla-devs/GDLauncher#585]
**Describe the bug**
I am unable to rename an insane after it has been created in the instance management window. 

**To Reproduce**
1. Create an instance or have one pre-installed
2. Right click the instance and select "manage" 
3. In the name field, delete the text and type in a new name
4. Click the "rename" button.
5. Close the management window. The name will not have changed. 

**Expected behavior**
I expect the instance name to change to match the new string of text I entered. 

**Screenshots**
https://imgur.com/a/cCExUja 

**Operating System:**
 - OS: Windows 10
 - Version: 10

**Additional context**
The rename button feels unresponsive. I would expect it to change color or show some indication that the name change was successful. That might be a clue or completely unrelated.

**Comment by Eskaan** [comment]
Any errors / messages in the console when clicking the button? Also we made some kind of a fix in the last release (12de2e8813aa87878adb0f49707d6650697968a8)

**Comment by TheDeviantCrafter** [comment]
The issue appears to be fixed in v1. 1.14. Renaming instances works as intended.

**Comment by LordDeatHunter** [comment]
Bug still exists in 1.1.21 (latest, as of this comment).
I've only had luck with the rename button once or twice in the past.
By default, it gives:
"Uncaught (in promise) Error: EPERM: operation not permitted, rename"
Running GDLauncher as admin doesn't produce anything in the console, but the instance still doesn't get renamed.

**Comment by LordDeatHunter** [comment]
Apparently it still gives the same error, even when running as admin, it just takes a minute or so before anything appears in console.

**Comment by Eskaan** [comment]
@LordDeatHunter on which OS are you?
Thats a permission error, that should not happen.

**Comment by LordDeatHunter** [comment]
Windows 10, oddly enough it persists when running as admin.

**Comment by Jay420blaze** [comment]
same here. cant rename any instance after creation. consale says: Uncaught (in promise) error: EPERM: operation not permitted, rename "instance directory: -> "instance directory with new name" even when ran as admin on windows 10

**Comment by Jjmboni** [comment]
There's a good workaround: Right click on instance, select "Open Folder".  Close GDLauncher.  Now you can rename the instance using Windows Explorer instead.  When you next launch GDLauncher, it will reflect the new name.

**Comment by iT3g4n** [comment]
Had the same issue. A workaround was installing Microsoft PowerToys and using the function that can "reclaim" the folder by ending all running tasks happening out of that folder. 
![image](https://github.com/gorilla-devs/GDLauncher/assets/68778866/83b07241-287e-429f-9d7b-a800b30424a9)
After clearing the menu that popped up I was able to change the name of the folder, which was reflected in GDLauncher.
