### ISSUE TITLE
AppImage does not run on Ubuntu xenial

### ISSUE THREAD

**Issue by probonopd** [gorilla-devs/GDLauncher#587]
**Describe the bug**
AppImage does not run on Ubuntu xenial

**To Reproduce**
1. Run Ubuntu xenial
2. Try to run the GDLauncher AppImage

**Expected behavior**
Works.

**Possible solutions**
Build on a system no newer than the oldest still-supported Ubuntu LTS release, which currently is xenial.

**Operating System:**
 - Ubuntu
 - xenial

**Additional context**
Reference:
https://github.com/AppImage/appimage.github.io/pull/1084

**Comment by DylanBeMe** [comment]
Did you make it executable?
Right click > go to permissions and click the executable box 
Or: open a terminal and type `sudo chmod +x gdlaunchername.appimage`

**Comment by probonopd** [comment]
Yes, thank you, I did this. I get:

```
Error: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.22' not found (required by /tmp/.org.chromium.Chromium.vJZtcB)
```

**Comment by DylanBeMe** [comment]
It looks like you're missing a dependency. You need to install Libstdc++6: `sudo apt-get install libstdc++6` that should do the trick

**Comment by probonopd** [comment]
This is not how AppImages work. Please have a look at https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages/cc2441518975caca23e9ce2dba6f08a22c678d1e#libstdcso6. Thanks a lot!

**Comment by DylanBeMe** [comment]
You are completely right! That's what you get when the dev is a windows normie lol. @killpowa fix pwease?

**Comment by furtabs** [comment]
Ubuntu Xenial is ancient. If they were to link using a super old GLIB it will break newer modern OSes
