### ISSUE TITLE
Can't login to my Mojang account

### ISSUE THREAD

**Issue by KirillUva** [gorilla-devs/GDLauncher#593]
**Problem:** Hi there, if your reading this you may already know the problem by the title. Im using GDlauncher for Windows 10, newest version of the launcher and have made a mojang account. I type it into the GDlauncher email and password section and it just says "Incorrect email or password". Any ideas on what I could do? Im using Tlauncher as an alternative for now.

**OS info:** 
Windows 10 Home
Version 1909
OS type: 64-bit
Intel(R) Pentium(R) CPU N2400
Quad-core Proccessor
4GB ram (3.84GB usable)
Device: GeoBook 3X
Brought on July 5th

**Comment by DylanBeMe** [comment]
Have you purchased minecraft on that mojang account? Going off on what you said about using Tlauncher I'm guessing you didn't. We don't allow you to play cracked using our launcher.

**Comment by KirillUva** [comment]
@DylanHameleers Yes, I have purchased it.

**Comment by DylanBeMe** [comment]
Windows 10 edition or java edition?

**Comment by KirillUva** [comment]
@DylanHameleers I also have PE and PS3 edition. They both work with my mojang account so i dont see whats wrong with Java.

**Comment by KirillUva** [comment]
And i also have win 10

**Comment by KirillUva** [comment]
What should I do?

**Comment by KirillUva** [comment]
> Windows 10 edition or java edition?

Windows 10 edition.

**Comment by KirillUva** [comment]
Any ideas on the problem?

**Comment by DylanBeMe** [comment]
You need to login using your mojang account and you need to have the java edition of the game. I'm sorry but you're gonna have to buy the game again. Windows 10 edition is bedrock edition and lacks many features. Also it doesn't run on java. If you want to use any launcher that isn't cracked you're gonna have to buy the java edition of the game.

**Comment by blarfoon** [comment]
We might need to add additional error messages to make it clearer why it’s not logging in. I’m not sure whether or not mojang provides this info

**Comment by KirillUva** [comment]
@DylanHameleers I just brought it, still nothing.

**Comment by KirillUva** [comment]
@killpowa There are no error messages, just "Incorrect email or password"

**Comment by blarfoon** [comment]
Can you contact me privately on discord?

**Comment by DylanBeMe** [comment]
> We might need to add additional error messages to make it clearer why it’s not logging in. I’m not sure whether or not mojang provides this info

You can't login using windows 10 edition tho

**Comment by KirillUva** [comment]
Sure.

**Comment by KirillUva** [comment]
@killpowa How do i add you on Discord?

**Comment by KirillUva** [comment]
@DylanHameleers I have just said i bought Java and still nothing is happening.

**Comment by KirillUva** [comment]
@killpowa I sent you a friend request on discord. My username is "eek"

**Comment by hukyyy** [comment]
My friend and I are having the same issue, we both have Minecraft: Java Edition, and it just won't let us log in.

![image](https://user-images.githubusercontent.com/57138098/90660037-b07fae80-e245-11ea-86fa-41e80b837cfa.png)

**Comment by RemagOfficial** [comment]
@huky2005 this is because mojang session is down and has nothing to do with this issue

**Comment by hukyyy** [comment]
Oh right, thanks for the info.

**Comment by Kooramah** [comment]
Hi, 

Microsoft now requires you to create a Microsoft account to play Minecraft for Java. 

Currently, they are in the process to migrate Mojang accounts with Microsoft: https://help.minecraft.net/hc/en-us/articles/360050865492-Minecraft-Java-Edition-Account-Migration-FAQ?ref=launcher. 

![image](https://user-images.githubusercontent.com/5595669/102145044-71402380-3e1b-11eb-95d2-b929e832d837.png)

New players will need to create a Microsoft account and when they purchase Minecraft for Java and login with the Microsoft Account using the login page on the GD Launcher. GD Launcher will return Invalid Password. I've seen this first hand.

![image](https://user-images.githubusercontent.com/5595669/102145053-756c4100-3e1b-11eb-90f6-57af744a078b.png)

That being said, here is what I've seen:
- Player Logs into Minecraft.net using a Microsoft Account - works as intended
- Player logs into the Minecraft Launcher using Microsoft Account - works as intended
- Player logs into the GD Launcher using Microsoft Account - returns an invalid password

**Comment by jplourenco1** [comment]
I'm having the same issue here, I have a Microsoft account, not a Mojang one, and cant create a Mojang account right now. Is there something we can do to fix this?

**Comment by Kooramah** [comment]
> Hi,
> 
> Microsoft now requires you to create a Microsoft account to play Minecraft for Java.
> 
> Currently, they are in the process to migrate Mojang accounts with Microsoft: https://help.minecraft.net/hc/en-us/articles/360050865492-Minecraft-Java-Edition-Account-Migration-FAQ?ref=launcher.
> 
> ![image](https://user-images.githubusercontent.com/5595669/102145044-71402380-3e1b-11eb-95d2-b929e832d837.png)
> 
> New players will need to create a Microsoft account and when they purchase Minecraft for Java and login with the Microsoft Account using the login page on the GD Launcher. GD Launcher will return Invalid Password. I've seen this first hand.
> 
> ![image](https://user-images.githubusercontent.com/5595669/102145053-756c4100-3e1b-11eb-90f6-57af744a078b.png)
> 
> That being said, here is what I've seen:
> 
> * Player Logs into Minecraft.net using a Microsoft Account - works as intended
> * Player logs into the Minecraft Launcher using Microsoft Account - works as intended
> * Player logs into the GD Launcher using Microsoft Account - returns an invalid password

Not sure why this post is marked off topic when its clearly related to any user that purchased Minecraft Java using a Microsoft Account. ATLauncher just updated their launcher 5 days ago to support players who bought Minecraft Java using a Microsoft Account

**Comment by Kooramah** [comment]
Maybe just post on here: #710

**Comment by MaxLevs** [comment]
I have the same problem. I usual play with official MC launcher (java edition). But I still can't login into this launcher. 
And why can't I just copy-paste my credentials if I store it in 1Password service? There are no neither copy nor paste function in MacOS version of GDLauncher.

> I'm guessing you didn't.

It looks like a very strange reaction, dude.

**Comment by MaxLevs** [comment]
> @huky2005 this is because mojang session is down and has nothing to do with this issue

Does it mean this launcher doesn't work anymore?

**Comment by RemagOfficial** [comment]
@MaxLevs no that was months ago

**Comment by Eskaan** [comment]
This Issue is resolved and the resulting feature is continued in #710
