### ISSUE TITLE
Custom themes

### ISSUE THREAD

**Issue by TheDeviantCrafter** [gorilla-devs/GDLauncher#597]
The ability to edit colors, replace images, and make similar graphical tweaks to the launcher might be worthwhile. I would personally consider paying a pretty penny for a true dark mode.

Bonus points if people can share their stylesheets and browse those made by others.

This is something that may be viable as a premium feature. The default client could support only white, dark and the default blue, while paid users get access to more extensive appearance tweaks.

**Comment by SephirothWS** [comment]
What is there to stop people fluent enough to write their own custom css from forking this repository, making their style changes and compiling it themselves? This repository even spells out from A to Z how to compile it.

Also, how would the GDLauncher devs differentiate who is "premium" versus "non-premium" if their logins are Mojang directly? https://github.com/gorilla-devs/GDLauncher/blob/ed83487ed3a1f52e2f3bb036baf37a0143bece1c/src/common/utils/constants.js#L7
https://github.com/gorilla-devs/GDLauncher/blob/ed83487ed3a1f52e2f3bb036baf37a0143bece1c/src/common/api.js#L14-L29

**Comment by TheDeviantCrafter** [comment]
It could be done, but for some people it simply won't be worth the hassle. Plus people might pay for the service simply to support the devs. I probably would if it was reasonably priced.

Realistically there is nothing we can do to stop the technically experienced from getting this feature for free. It's open source and there's a dev console.

As for authentication, it could be tied to the Mojang account. A server would store a list of Minecraft accounts with premium features unlocked and any client logged into said accounts gains access. This would be sufficient for skins, but if we also add world backups or other more sensitive premium features a separate login may be required.

**Comment by furtabs** [comment]
Dup of #409
