### ISSUE TITLE
Paid tech support

### ISSUE THREAD

**Issue by TheDeviantCrafter** [gorilla-devs/GDLauncher#598]
Paying someone to troubleshoot your CraftTweaker scripts would be an invaluable resource for newer pack developers. Paying a staff that can do this is likely to be a massive hassle however.

**Comment by furtabs** [comment]
I mean I don't mind helping helping you but this isn't directly related to GDLauncher. None of the Staff really know CrT but me and even if I'm paid I don't want to help on a minute's notice. Have you tried Linting your Script yet?
