### ISSUE TITLE
GDLauncher checks for mod updates very slowly

### ISSUE THREAD

**Issue by whitebear60** [gorilla-devs/GDLauncher#600]
**Describe the bug**
I have updated my modpack core mod on curseforge about a hour ago and in GDLauncher I didn't see the update

**Possible solutions**
Make launcher check for updates for mods in instance each time I open "Manage" window in the instance

**Video Demonstration**
[Video demonstration is avialable here](https://imgur.com/a/ufLQu4L)

**Operating System:**
 - OS: MacOS
 - Version Yosemite 10.10

**Comment by TOLoneWolf** [comment]
gdl uses curseforges api, the update process for that api can take up to 2 or more hours for an update to be processed after a file is approved. This same limitation exist for the twitchapp it self. The website of curseforge does not use this api and has access to the new files almost instantly. This is not a problem on gdl side of the fence.

**Comment by whitebear60** [comment]
Okay, will know. Thanks

**Comment by whitebear60** [comment]
17 hours later... update is still unavialable in GDLauncher

**Comment by TOLoneWolf** [comment]
This is the twitch api response. Which still does not show your update. Could be because they where being ddos its take them longer to update then normal. You might need to put a ticket in with them.

https://addons-ecs.forgesvc.net/api/v2/addon/381611/files
