### ISSUE TITLE
 my download sometimes disappear

### ISSUE THREAD

**Issue by Story4everXD** [gorilla-devs/GDLauncher#603]
sometimes when i open up the app thing i downloaded they just disappear idk why this happens but it does

go to the main menu
download anything
exit the app then
downloads be gone

**Operating System:**
 - OS: Windows
 - Version 10

**Comment by Vexsanity** [comment]
Did you update the launcher to 1.0.9?

**Comment by Story4everXD** [comment]
yes

**Comment by mcdonaldshoopa** [comment]
This happens to me too, so it's not on you

**Comment by TripleKiller666** [comment]
Just had that happen for me with "All of Fabric 3" Modpack...
On 1.0.8 I never experienced this bug, but now on 1.0.9 it happened to me too.

Weirdly enough, the other 2 Instances that I have are still there (Vanilla Minecraft and Valhelsia 2)
So maybe it has to do with what you last played?

**Comment by furtabs** [comment]
#579

**Comment by blarfoon** [comment]
Hopefully fixed by https://github.com/gorilla-devs/GDLauncher/commit/c5c3c6ad4c263bb19f74e332598d444be3ff6c04
