### ISSUE TITLE
AutoUpdater on macOS?

### ISSUE THREAD

**Issue by whitebear60** [gorilla-devs/GDLauncher#604]
**Is your feature request related to a problem? Please describe.**
When I hit the update button, the launcher shows me that autoupdater is not avialable on macOS. Will this be fixed in the future?

**Additional context**
*My system*

Prozessor: Intel Core i5 2.4GHz
RAM 16 GB 1600GHz DD3
MacOS: 10.10 Yosemite

**Comment by furtabs** [comment]
Not a Bug

**Comment by whitebear60** [comment]
I know that this is not a bug. This issue is feature request.

**Comment by Oct0bass** [comment]
I'm also on macOS, and for me the auto updater shows up and says it's updating, but it's stuck at 0 %.  I'm not sure if it's related or a different issue.

**Comment by Eskaan** [comment]
The problem is, that we would need to sign the app, which Apple takes about $100 for. Sadly, we cannot afford this.


See  [autoUpdater | Electron docs](https://www.electronjs.org/docs/api/auto-updater#macos)
 > Note: Your application must be signed for automatic updates on macOS. This is a requirement of Squirrel.Mac.
