### ISSUE TITLE
Small padding-right in status bar

### ISSUE THREAD

**Issue by whitebear60** [gorilla-devs/GDLauncher#605]
**Describe the bug**
It looks like GDLauncher button, which opens GDLauncher website, must move some pixels left

**To Reproduce**
1. Open GDLauncher
4. See error in top-right corner

**Possible solutions**
Increase padding-right for this image

**Screenshots**
https://i.ibb.co/ykTs9hb/image.png

**Operating System:**
 - OS: MacOS
 - Version 10.10

**Comment by Eskaan** [comment]
Just fixed whit 5a245c99 🙂
Thanks for telling
