### ISSUE TITLE
Integrate custom version j-son files

### ISSUE THREAD

**Issue by QtKaii** [gorilla-devs/GDLauncher#607]
**Is your feature request related to a problem? Please describe.**
As someone who plays on 2b2t and 9b9t I use utility clients like Impact and optifine, some of these utilities are not offered as forge mods, Which frustrates me and many others as I have to switch launchers to open one of these custom versions.

**Describe the solution you'd like**
A simple way to add minecraft version jsons and jars, Therefore allowing custom minecraft clients to be added.
Maybe allowing the user to navigate and select a custom .json file to fetch dependencies and to install the version would be a good solution.

**Describe alternatives you've considered**
Having hand selected clients added to the launcher would be nice, but not a full substitute. 
Currently my alternative is using the OG launcher

**Additional context**
An example is Impact, An utility client for anarchy servers. In the OG launcher it installs under the versions list like so.
![Screenshot_36](https://user-images.githubusercontent.com/15091327/90324474-39a59580-df67-11ea-8739-ba2db61cf1e1.png)

Thank you.

**Comment by furtabs** [comment]
I know you were OP but #616 has more heat. Going to flag this as duplicate but be aware you were the OP
