### ISSUE TITLE
Can't login to my Mojang account.

### ISSUE THREAD

**Issue by RedR2D2** [gorilla-devs/GDLauncher#612]
As the title suggests, I can no longer log in. Of course I bought Minecraft and I've been using the launcher for a few months. Now nothing works anymore.

**Comment by RemagOfficial** [comment]
https://freshcoal.com/mcstatus

**Comment by coiledmocha** [comment]
Why does everything work on the vanilla launcher and not on gd? I still can't login on gd, but if I launch vanilla I can login and join servers, everything works just fine.

**Comment by coiledmocha** [comment]
On the discord server they say you need to spam your login. I've tried like seven times to login and it worked for me. Seems as though this is a temporary fix.

**Comment by RedR2D2** [comment]
I just started the launcher to test it and was logged in. ^^

Yesterday I was able to log into the Vanilla Launcher and play, all without any problems.
Only the GD Launcher was affected.

But now it seems to be working again for now. :)
