### ISSUE TITLE
unable to launch instances from external drives

### ISSUE THREAD

**Issue by RemagOfficial** [gorilla-devs/GDLauncher#614]
**Describe the bug**
When trying to play an instance that its stored on an external drive the instance doesn't launch 

**To Reproduce**
1. Change user data path to an external drive location
2. Restart GDlauncher
3. Click play on any instance 
4. The console shows this [1599308935187.log](https://github.com/gorilla-devs/GDLauncher/files/5178063/1599308935187.log)

**Expected behavior**
The instance launches like its on the internal drive 

**Possible solutions**
Unknown

**Screenshots**
Shouldn't be needed

**Operating System:**
 - OS: Windows
 - Version: 10

**Additional context**
Shouldn't be needed

**Comment by Eskaan** [comment]
The Launcher has no rights to write to the external drive or (less likely) tries to create a new drive at `D:\`
Is this issue still persistent?

**Comment by Eskaan** [comment]
@RemagOfficial
