### ISSUE TITLE
Updating Notification

### ISSUE THREAD

**Issue by kreezxil** [gorilla-devs/GDLauncher#615]
**Is your feature request related to a problem? Please describe.**
When in the mod view, you know there is updates, but none show until about 2 to 3 minutes later. 

**Describe the solution you'd like**
if a mod update check is in progress, i would like to see a mention of that somewhere on the screen

**Describe alternatives you've considered**
waiting 2 to 3 minutes in frustration

**Comment by Eskaan** [comment]
2-3 Minutes are not a real problem, and we wont fix this since you can go into the mod information ant select "switch version" to instantly get an information which is the most recent one
EDIT: I guess you can restart GDLauncher to get an full update

**Comment by kreezxil** [comment]
So a QOL feature like "checking for updates" is out of question?

**Comment by kreezxil** [comment]
Also interesting you classified it as a fix as if you know it's a bug, when I posted this as a feature request.

**Comment by Eskaan** [comment]
I marked it as `wont fix`, tho I dont think we will be adding this.
