### ISSUE TITLE
Launcher closes on loding screen as you open it.

### ISSUE THREAD

**Issue by BillBodkin** [gorilla-devs/GDLauncher#617]
**Describe the bug**

Seemingly overnight the GD launcher no longer works on my system. When opening the launcher the loading text appears for a second or two and then the program closes.

I am using Ubuntu.

`./GDLauncher-linux-setup.AppImage`
`11:45:13.218 › setup`
`(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397`
`11:45:15.079 › Trying to start listener`
`11:45:15.081 › Started listener`
`terminate called after throwing an instance of 'Napi::Error'`
`  what():  Inotify limit reached`
`Aborted (core dumped)`

**To Reproduce**
Opening launcher on Ubuntu?

**Expected behavior**
Not crash

**Possible solutions**
?

**Screenshots**
n/a

**Operating System:**
Ubuntu 20.04 using KDE 5.18.5
Node v10.19.0

**Additional context**
n/a

**Comment by BillBodkin** [comment]
I was able to solve this by following this link: [https://askubuntu.com/questions/770374/user-limit-of-inotify-watches-reached-on-ubuntu-16-04](url) not sure if this is a problem with my system, or the software. Please feel free to remove if the former, Thanks.

**Comment by Eskaan** [comment]
since the duplicate is resolved, I will close this now
