### ISSUE TITLE
[BUG > Resolved] [Feature request]

### ISSUE THREAD

**Issue by Icebluewolf** [gorilla-devs/GDLauncher#618]
The add mod menu in instance manager dose not show mods on a fabric 1.16.2 instance.

**To Reproduce**
1. make a fabric 1.16.2 instance
2. click on manage instance
3. go to mods menu
4. Click add mod at the top of the menu

**Expected behavior**
There should be a list of mods that you can get.

**Possible solutions**
1.16.2 might have not been marked an available version wherever you get the mods from

**Screenshots**
![image](https://user-images.githubusercontent.com/44532864/90988960-7de2f800-e55c-11ea-8113-f5aaac7ceecd.png)

**Operating System:**
 - OS: Windows
 - Version 10

**Additional context**
I know of 1 other person who has had this problem.

**Comment by TOLoneWolf** [comment]
This is not a bug. Curseforge API does not distribute mods for 1.16.2 because of forge not being released as stable yet. (API was made for forge not fabric).

**Comment by Icebluewolf** [comment]
This should be posted somewhere then as it seems like a bug.

**Comment by emberquill** [comment]
This isn't something that can be fixed by GDLauncher. It's an issue with the Curseforge API itself, and it happens every time a Minecraft update is released. Until Forge releases a stable version for 1.16.2, the API won't list any mods.

**Comment by Icebluewolf** [comment]
This now makes sense but than GDlauncher should put a message on the empty mods page that says "The new version of forage API for this version of minecraft is not out. Please install all your mods manually via instance folder > Mods."

**Comment by furtabs** [comment]
>>> This isn't something that can be fixed by GDLauncher. It's an issue with the Curseforge API itself, and it happens every time a Minecraft update is released. Until Forge releases a stable version for 1.16.2, the API won't list any mods.

Twitch even has the same issue
