### ISSUE TITLE
Unable to switch versions...

### ISSUE THREAD

**Issue by Nidaelie** [gorilla-devs/GDLauncher#631]
Im unable to swithc to newer versions, but i can download the file and create the instance for it. Every modpacks has same issue

**Comment by blarfoon** [comment]
Can you explain your issue more in details?

**Comment by davidromrell** [comment]
Mod Options: updatefixerupper, config/autoconfig , multiconnect, modupdater, "Future". There are more options I just cant find them right now.

**Comment by Nidaelie** [comment]
if u think i ll be waiting for 1 month to get some help...

**Comment by davidromrell** [comment]
you can just add modupdater, multiconnect, updatefixerupper and be done with the issue.

**Comment by davidromrell** [comment]
They serious made you wait a month, tip keep bugging them(latest comments are prioritized on places like this)

**Comment by Eskaan** [comment]
> They serious made you wait a month, tip keep bugging them(latest comments are prioritized on places like this)

No they are not. Taking a look at this issue, I was more attempted to just let it because of how toxic you are

Edit: Also, learn to write. its called `seriously` in this context and ther should be a space before the bracket.

**Comment by Eskaan** [comment]
> Im unable to swithc to newer versions, but i can download the file and create the instance for it. Every modpacks has same issue

To get back to your report. Is this issue still persistent?
If yes, please reopen the issue and tell us more details (Launcher version, Minecraft version, Modpack, errors in console)
