### ISSUE TITLE
Can't install murmur2-calulator

### ISSUE THREAD

**Issue by Xhale1** [gorilla-devs/GDLauncher#634]
**Describe the bug**
When installing the codebase and running npm install for the first time, I run into an issue with murmur2-calulator

**To Reproduce**
1. Download GDLauncher Code
2. Run NPM install in the main directory

**Expected behavior**
Node modules successfully install themselves.

**Possible solutions**
None

**Screenshots**
None

**Operating System:**
 - OS: MacOS
 - Version 10.15.6

**Additional context**
Relavent error:
`Failed at the murmur2-calculator@git+https://github.com/gorilla-devs/murmur2-calculator.git#be77da227c28fd502e2b5f05b6daef085c22ecc3 install script.`

**Comment by Ladvace** [comment]
I don't know if did that but you need rust and a  c++ compiler (g++ or windows build tools)

**Comment by blarfoon** [comment]
Is this still an issue for you?

**Comment by furtabs** [comment]
Do you have XCode tools installed?

**Comment by Xhale1** [comment]
I did have xcode tools installed but I didn't have rust setup properly. Closing this :)
