### ISSUE TITLE
NSIS Web Installation Folder Selection

### ISSUE THREAD

**Issue by CapoFantasma97** [gorilla-devs/GDLauncher#635]
**Is your feature request related to a problem? Please describe.**
I think it's almost unnecessary to say how much of a bad practice is to automatically install software on the C:\ drive of windows without user consent, especially for those that run a small SSD for the OS only.

**Describe the solution you'd like**
I'd like to install the launcher where I want through a prompt at the beginning like 99.9% of Windows software does. Even the Twitch Launcher does it, you select where to install Twitch, and where to put Minecraft files, and not just instances/userdata.

**Comment by Eskaan** [comment]
If you want to switch this, go into the settings. After transfering you can delete all the data in the folder except a few files.
But this problem does affect that few users, that I will mark that as `wontfix` and close.
