### ISSUE TITLE
Instances Disappearance in App

### ISSUE THREAD

**Issue by Birphon** [gorilla-devs/GDLauncher#638]
**Describe the bug**
Opened the GDLauncher (installed on my D Drive) and saw all my instances weren't there. Had a look in the Instance folder an everything was still sitting there.

**To Reproduce**
Unsure. Possible update bugged it out

**Possible solutions**
EITHER
1. Zip the instances and import ZIP them (Sadly only works 1 at a time)
2. Create blank instances of the version of Minecraft and just copy and paste everything over

**Screenshots**
![Recreating the Instances:](https://user-images.githubusercontent.com/61985658/93730969-21d4c780-fc1f-11ea-95c9-a85d17024039.png)
![Instances in Instance Folder + Zips of Instances when Importing them (Stopped due to above)](https://user-images.githubusercontent.com/61985658/93730974-25684e80-fc1f-11ea-850b-5bd46ae57d10.png)

**Operating System:**
Windows 10

**Comment by Birphon** [comment]
Screenshot 1: Recreating Blank instances
Screenshot 2: Instances in Instance Folder - Zips are there to Zip Import but this process is 1 zip at a time, quicker to make blank instances and copy over

Found a Fix:
Going into settings and manually Changing User Path Data to the correct path (it was D:\GDLauncher and Manually changed it to D:\GDLauncher) picked up all my instances

**Comment by furtabs** [comment]
#603 #579
