### ISSUE TITLE
Mouse button reassignment breaks launcher

### ISSUE THREAD

**Issue by dalysierre** [gorilla-devs/GDLauncher#639]
**Describe the bug**
When attempting to play Valhelsia 2, the loader stops responding if keys are reassigned to mouse buttons (specifically in my case, Mouse 4). If the keys are not assigned, the game loads just fine. If the game is loaded and then the mouse is reassigned, it works as long as the client isn't closed. How to temporarily fix it: open Options.txt and delete the line assigning mouse button, load game, success.

**To Reproduce**
1. Open GDL and load Valhelsia 2.
2. Open a game and reassign a key to mouse button (I reassigned sneak to Mouse 4).
2. Close and open GDLauncher.
3. Attempt to run Valhelsia 2.
4. Stare at Task Manager process "Not Responding" status in sadness.

**Possible solutions**
Sorry, but I'm not a programmer...

**Screenshots**
![1](https://user-images.githubusercontent.com/71741657/93955455-6cd10680-fd15-11ea-89d4-93c6c925a021.PNG)

**Operating System:**
 - Windows 10

**Additional context**
I have not tried this with another mod. I also have no problem running the mod aside from this problem.

**Comment by Eskaan** [comment]
First, this problem is not cause of the Launcher, I would rather recommend you opening an issue at the modpacks page.
Second, I cant realy help you whit this problem. It seems like one of the mods is having trouble whit the Key Names
