### ISSUE TITLE
Make it the only launcher you would need, for real.

### ISSUE THREAD

**Issue by SlayDigger** [gorilla-devs/GDLauncher#641]
I personally find it very irritating to have to use 5 different launchers to play the modpacks I like. I use Badlion, GDLauncher, Technic, ATLauncher (Rarely) and Voidswrath. Like really. 

I Would really like for the GDLauncher to offer support for the Technic, Voidswrath, and ATLauncher modpacks (In launcher to download) and also to be able to add .exe launchers to the modpack list, so I can open badlion from gdlauncher. I don't know how this would work legally, but I would really like to be able to have the only launcher I would ever need truly.

I think this is quite necessary, because like I said, I NEED 5 LAUNCHERS AWDIAIWDIWADWAI

**Comment by furtabs** [comment]
Technic: #109 
Voidswrath: [Piracy](https://stopmodreposts.org/)
ATLauncher: Fine
Badlion: Badlion Network closed 2 years ago. Also EXE Launchers lul.

**Comment by furtabs** [comment]
ATlauncher, move to #655  
Adding EXE Files will never happen
