### ISSUE TITLE
1.16.3 mods not displayed in the mod browser nor can they be updated

### ISSUE THREAD

**Issue by TehKAMI** [gorilla-devs/GDLauncher#642]
**Describe the bug**
Mods for Forge and Fabric for Minecraft 1.16.3 are not displaying when trying to browse for them via "Add Mod" feature. If added manually by the user, they are displayed in the list of active mods, however can not be updated as each of their pages return a "Mod Not Available" in the dropdown menu.

**To Reproduce**
1. Setup a Forge (v34.1.0) or Fabric (v0.9.3+build.207) instance for Minecraft 1.16.3
2. Navigate to "Mods" section within the Instance Manager
3. Depending on the issue 
a. Click "Add Mod" and try to search for any mod whatsoever, or
b. Manually install a Curseforge mod by drag'n'dropping it onto the Instance Manager and click it's name

**Expected behavior**
When clicking the "Add Mod" button and entering a search query, it should return mods fitting the searched query. When clicking the manually imported mod that's recognized by the launcher as being from Curseforge, it should be able to be updated/it's version switched if there's more than one file available.

**Screenshots**
[Screenshots of both issues](https://imgur.com/a/atNWcYn)

**Operating System:**
 - OS: Windows
 - Version: 10

**Comment by shattyyt** [comment]
Still having this issue in 1.16.5 forge version 36.0.43 for mods like astral and thermal

**Comment by ItsNovaAndCrap** [comment]
I still have this issue with GDLauncher 1.1.21 with 1.16.5 (Forge 36.2.23)
