### ISSUE TITLE
When exporting profiles, GDL should remember the last location I selected for exporting.

### ISSUE THREAD

**Issue by Rensik** [gorilla-devs/GDLauncher#648]
**Is your feature request related to a problem? Please describe.**

Currently, the export menu does not remember the last folder I selected for exporting profiles and I have to choose where to export every time.

**Describe the solution you'd like**

When exporting profiles, GDL should remember the last location I selected for exporting.

**Comment by RemagOfficial** [comment]
please fill in the whole report or delete unused parts

**Comment by Rensik** [comment]
Edited

**Comment by Eskaan** [comment]
Duplicate of #588
