### ISSUE TITLE
Ability to choose install location

### ISSUE THREAD

**Issue by finalsliver** [gorilla-devs/GDLauncher#65]
At the moment GDL installs to:

``` C:\Users\_____\AppData\Roaming\GorillaDevs ```

This doesn't seem to be changeable.

Further, we don't seem to be able to choose the install location of downloaded/Created packs/Servers. 

As someone with a small SSD C:\ that I've only allowed Windows to install on this becomes rather limiting. I may not be alone in this practice. 

TL;DR

• Choose GDL install location
• Choose instance and Server installation locations

**Comment by blarfoon** [comment]
We are currently completely rebuilding the project from scratch and we will address this feature for sure :)

**Comment by finalsliver** [comment]
Thanks guys. Good to know it's on the roadmap :smiley:

**Comment by IceflowRE** [comment]
Small bump, as it was not adressed yet.
