### ISSUE TITLE
Cannot Save Userdata

### ISSUE THREAD

**Issue by hax0r31337** [gorilla-devs/GDLauncher#651]
**Describe the bug**
cannot save my data when i restart the launcher

**To Reproduce**
download "GDLauncher-linux-setup.zip"
unzip it and mkdir "data" at launcher folder
open the launcher and choose my java "/usr/lib/jvm/java-8-openjdk/bin/java"
login and close it use "X"
restart the launcher and it init and my data was gone!

**Operating System:**
 - OS: Manjaro 20.1 Mikah
 - Kernel : x86_64 Linux 5.4.64-1-MANJARO

**Additional context**
lanuncher version: v1.0.11

**Comment by furtabs** [comment]
> OS: Manjaro 20.1 Mikah

use AUR Package

**Comment by furtabs** [comment]
#638 #603 #579
