### ISSUE TITLE
Hitting escape while searching for mods brings me back to the main menu instead of closing only the top window

### ISSUE THREAD

**Issue by TheDeviantCrafter** [gorilla-devs/GDLauncher#656]
**Describe the bug**
Tapping escape closes any windows open inside of GDLauncher, such as settings or the pack management window. When inside a subwindow, such as the mod search screen, tapping escape once closes every active window instead of just the top one.

**To Reproduce**
1. Right click an instance and select "manage" to open the management window.
2. Click the mods tab and select "add mod" to open the mod search window.
3. Click one of the mods to open the mod description window.
4. Tab escape. Instead of closing just the top window, it closes all three windows mentioned in previous steps and brings me all the way back to the main menu.

**Expected behavior**
I expect hitting escape to close only the top window, meaning that I would need to hit escape 3 times to go from the mod description window all the way to the main menu.

**Operating System:**
 - OS: Windows 10 Pro 64-bit
 - Version: 10.0.18363 Build 18363 
- GDLauncher version: v1.0.1.1

**Comment by Eskaan** [comment]
Duplicate of #647
