### ISSUE TITLE
Autocreate default pack name for existing Modpacks

### ISSUE THREAD

**Issue by finalsliver** [gorilla-devs/GDLauncher#66]
Currently when downloading a new modpack from curse or other prebuilt packs the name field is blank by default. Generating a default name based on the packs name would be more convenient for players. 

Blank field bellow is default at this time. 
![](https://i.imgur.com/IC4yokQ.png)

**Comment by blarfoon** [comment]
Do you think this is a useful idea? I mean, it can be useful from time to time but for the most part users want to use their custom names. What do you think?

**Comment by zabi94** [comment]
Personally I never give a name to my packs, I just go with the default pack
name, so this would honestly be useful to me

Il 07 mar 2018 15:32, "Davide Ceschia" <notifications@github.com> ha
scritto:

**Comment by blarfoon** [comment]
I suppose we will add this feature then :)

**Comment by Freddo3000** [comment]
Can this issue be reopened, seeing as this was seemingly never implemented.

**Comment by blarfoon** [comment]
Yup
