### ISSUE TITLE
Confirmation button for "Delete shared data"

### ISSUE THREAD

**Issue by Gullpt** [gorilla-devs/GDLauncher#663]
**Is your feature request related to a problem? Please describe.**
Yes, i accidentally clicked the button without reading the description, thinking it was just a delete cache button, i realized quickly what i did and closed it, probably stopping my world from being erased.

**Describe the solution you'd like**
As you said, put a confirmation button, maybe with graphic signs of danger, alongside a more detailed description.
**Describe alternatives you've considered**
Well just saying, when i opened it back, no instance would launch, this got solved by reinstalling each instance one by one.

**Additional context**
Well not much to put here so i guess thank you for your time :) 

🐝  happy !

**Comment by Ladvace** [comment]
I think I already made it but I don't remember if we already merged it

**Comment by Ladvace** [comment]
ok just made a pr, we need just to merge it
