### ISSUE TITLE
Add button to go to modpack project page

### ISSUE THREAD

**Issue by rlnt** [gorilla-devs/GDLauncher#667]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It would be nice if there was a button somewhere that you can directly access a modpack's project page.
Let's say you install a modpack from CurseForge and you want to join its Discord. The Discord server
is usually linked on their project page. To easier access it, it would be cool if you had a button in the
modpack overview or somewhere else to go directly to that page.

**Describe alternatives you've considered**
An alternative would be to add this to the context menu when you rightclick the pack in the modpack
overview.

**Additional context**
The button should only appear if the pack was actually downloaded from somewhere. Maybe hide
it for self-created packs or make it grayed out.

**Comment by TOLoneWolf** [comment]
2 ways to currently get to it.  

1.  
![image](https://user-images.githubusercontent.com/8376628/95797753-eaa18580-0cb5-11eb-9068-7773b36df445.png)  
![image](https://user-images.githubusercontent.com/8376628/95797764-f12ffd00-0cb5-11eb-9c3e-14031f07dde7.png)  
![image](https://user-images.githubusercontent.com/8376628/95797779-fab96500-0cb5-11eb-9320-88a5e86ece33.png)  
![image](https://user-images.githubusercontent.com/8376628/95797792-0016af80-0cb6-11eb-95ec-90e98d6e2d71.png)  

2.  
![image](https://user-images.githubusercontent.com/8376628/95797844-21779b80-0cb6-11eb-95ab-a7e61556075e.png)  
![image](https://user-images.githubusercontent.com/8376628/95797854-263c4f80-0cb6-11eb-8ad5-80935fd06f9e.png)  
![image](https://user-images.githubusercontent.com/8376628/95797865-2c323080-0cb6-11eb-9abf-93b9f3db7732.png)  
![image](https://user-images.githubusercontent.com/8376628/95797878-318f7b00-0cb6-11eb-881a-b8ebc8be9cfa.png)  

having the same ![image](https://user-images.githubusercontent.com/8376628/95797971-6a2f5480-0cb6-11eb-855b-2da908b05b9a.png) button in the modpack menu would be good adition for it.

**Comment by rlnt** [comment]
I am aware of these ways.
The feature request serves more as a quality of life improvement making it easier to access this option. :)

**Comment by RemagOfficial** [comment]
how would you make that easier?

**Comment by rlnt** [comment]
You should read the issue.

You could place an "open project page" button in the overview window or add an additional option in the context menu.

**Comment by Eskaan** [comment]
Duplicate of #551

Also, its fixed by now in 246d969
