### ISSUE TITLE
Modpack Thumbnail causing crash

### ISSUE THREAD

**Issue by whirlwind0204** [gorilla-devs/GDLauncher#669]
**Describe the bug**
If you scroll past a certain modpack it crashes the launcher.
I sorted by Quests and scrolled down

**To Reproduce**
1. Go to 'add a modpack'
2. Click on 'categories'
3. Scroll down to 'pack'

**Expected behavior**
Crashes launcher with an Error
I cant check which pack it is because it crashes before i can see
**Possible solutions**
Ladvace: Add a fallback

**Screenshots**
![image](https://user-images.githubusercontent.com/60035310/96047514-292d7080-0e6d-11eb-865c-2337f481b3ac.png)

**Operating System:**
 - OS: Windows 10 Home
 - Version: 10.0.18363 Build 18363

**Comment by Ladvace** [comment]
this issues has been solved
