### ISSUE TITLE
Bug when looking at modpacks. Why only me

### ISSUE THREAD

**Issue by CrankySupertoonArchive** [gorilla-devs/GDLauncher#67]
Getting this error when opening  I click the log to desktop button but nothing. Also, it happens when the instance + is clicked on. Hope to find it fixed soon.

I click the get log but nothing happens. Any ideas?
![untitled](https://user-images.githubusercontent.com/26016256/37119088-596c7346-2224-11e8-867f-5dda29279d9d.png)

**Comment by blarfoon** [comment]
This is a known error and we are working on it right now.. It's caused by a service we use which is currently not working
we will release a temporary fix in a few hours
