### ISSUE TITLE
Java Accounts migration

### ISSUE THREAD

**Issue by burtek** [gorilla-devs/GDLauncher#675]
Just to let you guys know, MS will be migrating MC Java Accounts to MS Accounts - this might change authorization process

https://help.minecraft.net/hc/en-us/articles/360050865492

**Comment by TheEpicProgrammer** [comment]
Yes Please!!, when migration starts, this is probably the only thing that will stop me from migrating.

**Comment by Eskaan** [comment]
Fixed by Ladvace in #730
