### ISSUE TITLE
"Please select java.exe binary" even while running naively on Linux.

### ISSUE THREAD

**Issue by nebula8830** [gorilla-devs/GDLauncher#676]
**Describe the bug**
"Please select java.exe binary" even while running naively on Linux.

**To Reproduce**
1. Go to Settings > Java

**Expected behavior**
OS agnostic wording.

**Possible solutions**
"Please select java binary" instead of "Please select java.exe binary"
That would make sense no matter what OS you are using.

**Operating System:**
 - OS: Fedora
 - Version 33

**Additional context**
Not a issue at all, just small wording change. I don't know where the files are to change or I would submit my own PR.

**Comment by Eskaan** [comment]
Done in the recent #993 pr
