### ISSUE TITLE
Download needs restarting after network reset

### ISSUE THREAD

**Issue by largenumberhere** [gorilla-devs/GDLauncher#678]
When downloading a pack, if the **internet connection drops out** for a moment, the **download stalls indefinitely**.
The pack needs to be deleted and the download needs to be restarted from scratch.

**To reproduce** (if it needs to be said) start downloading a pack then disconnect and reconnect to a network.

There appears to **not even be a timeout** to alert the user that this has happened and the launcher will be stuck attempting to download a single file for over 20 minutes.

Proposed **sample solution** outlines (simplest first):
1.) If after 10 minutes a pack has not finished downloading, alert the user that they may need to delete the new instance and try downloading again if no progress is being made
2.) If a single file is not making any download progress after 2 minutes, alert the user that they may need to delete the new instance and try downloading again if no progress is being made.
3.) If a single file is not making any download progress after 2 minutes, restart the install and notify the user.
4.) Create an index of the files to be downloaded and If the network connection has been reset, delete the current file being downloaded, compare the files downloaded to the file index, and download remaining files.

**Comment by Ladvace** [comment]
we are already working on a refactor that should fix this problem

**Comment by largenumberhere** [comment]
Wonderful thank you

**Comment by vdh** [comment]
@Ladvace Is this still being addressed? Because having no error handling on the download and having it hang the entire app is a bit of a showstopper.

**Comment by Ladvace** [comment]
Actually probably we can make some optimization but this problem should be due to their servers (curseforge)

**Comment by Eskaan** [comment]
Duplicate of #658
