### ISSUE TITLE
Weird directory path of gdlauncher and gdlauncher_next on linux

### ISSUE THREAD

**Issue by ghost** [gorilla-devs/GDLauncher#680]
On linux, in my .config directory I have `~/.config/gdlauncher` and `~/.config/gdlauncher_next` however they don't seem to contain configuration files (except for `~/.config/gdlauncher_next/Preferences`).

Their localization is misleading so maybe it would be better to consider relocating them.
A lot of programs store their non configuration files in `~/.PROGRAMNAME` or in `~/.local/share/PROGRAMNAME`.

If you have reasons for it, could you share them, why you left it as it is?

**Comment by Eskaan** [comment]
I think, the problem is that electron defaults to this Path as the program data Path. could you please create an issue [Electrons Github](https://github.com/electron/electron) ?

**Comment by Eskaan** [comment]
External Issue. We use ~/.config/gdlauncher_next as our config directory, the rest is up to Electron.
