### ISSUE TITLE
Error while build.

### ISSUE THREAD

**Issue by rafucuk** [gorilla-devs/GDLauncher#681]
**Describe the bug**
Getting error while building.

**To Reproduce**

Just run: npm run release and got:

`⨯ Get "https://service.electron.build/find-build-agent?no-cache=1fpiusd": dial tcp 51.15.76.176:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.`

**Operating System:**
Windows

**Comment by MicrolemurDev** [comment]
I do not have this issue but on Linux I do get an error after running npm i. More details can be posted if requested.

**Comment by Ladvace** [comment]
try using `npm run build`
