### ISSUE TITLE
Resetting Windows 10 deletes GDLauncher Instances

### ISSUE THREAD

**Issue by thedarkcolour** [gorilla-devs/GDLauncher#687]
**Describe the bug**
When resetting Windows with personal files kept GDLauncher does not put instances in a safe location and so they get reset.

**To Reproduce**
1. Reset Windows and select "keep personal files"
2. Open the new installation of Windows
3. Go to the %Appdata%\Roaming\gdlauncher_next\instances and everything is gone. All the worlds, modpacks, and mod files.

**Expected behavior**
Resetting Windows with personal files should keep the instances because Minecraft worlds are personal files.

**Possible solutions**
Change the default location to the root of C:\ similar to how Twitch does it

**Screenshots**
None

**Operating System:**
 - OS: Windows
 - Version 10

**Additional context**
My computer had just broken down and I had to reset Windows and I couldn't back up my files beforehand. I lost several dozen hours of gameplay and worlds, several mod files that are no longer hosted on the internet, and lots of memories. I'm not mad because it was an oversight and a really specific problem but it would be nice to have this fixed so that it doesn't happen to other users.

**Comment by Ladvace** [comment]
resetting win10 you mean wiping it?

**Comment by thedarkcolour** [comment]
Reinstalling windows but not deleting your personal files. It deletes all the programs but keeps stuff like photos, downloads, and desktop files. It also kept my Twitch launcher instances but GDLauncher instances were gone.

**Comment by Ladvace** [comment]
are in the instances in the original folder? need to check tthat
