### ISSUE TITLE
FTB Packs

### ISSUE THREAD

**Issue by Hi-ImKyle** [gorilla-devs/GDLauncher#693]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Similar to the tabs when adding a new instance like Vanilla/Twitch/Import but for FTB to list all official FTB packs from their site.

**Describe alternatives you've considered**
Using their modpack launcher, but it's annoying having several launchers for different packs, hoping GD will become a hub of sorts for all packs.

**Additional context**
Something like this, but functional of course.![](https://user-images.githubusercontent.com/25551312/99739753-5fda5480-2ac5-11eb-8dbd-5f55d2b00b85.png)

**Comment by Tedris** [comment]
It looks like FTB has a public API found here: https://modpacksch.docs.apiary.io/ and that is what MultiMC is using in their implementation, maybe GDLauncher could use something similar.

**Comment by furtabs** [comment]
Duplicate of #425
