### ISSUE TITLE
Cant download modpacks from curse with a name longer then allowed limit 

### ISSUE THREAD

**Issue by maxybaer123** [gorilla-devs/GDLauncher#696]
**Describe the bug**
On Macos so im not sure if this is also on windows. But whenever I try to download 
Decimation - Realistic Zombie Apocalypse Modpack
https://www.curseforge.com/minecraft/modpacks/decimation-realistic-zombie-apocalypse-modpack

It says "Instance name is not valid or too long. Please try another one"

I cant delete the name or change it cant select it or cmd a basicaly. What I can do is hover over the text and get the text input blinker "|" while my cursour turns to the text cursor but I cant move the blinker and it stays stuck at start I cant even forward delete.  Im assuming this is because it is auto inputed as the pack name and something about it being over the allowed limit prevents the name from being updated.

**To Reproduce**
1. Go to 'Curse packs(on the launcher) and find "Decimation - Realistic Zombie Apocalypse Modpack" 
2. then try to download it through download latest. 
3. no arrow appears no ability to download

**Expected behavior**
A download error apears or I can edit the name so it is in allowed bounds
**Possible solutions**
have names over limit or that use invalid sintax that are on curseforge packs automaticaly shorten to be within allowed limit.

Expand limit.

Simply allow people to edit the names of packs over limit
**Screenshots**
<img width="988" alt="Screen Shot 2020-11-22 at 10 21 29 PM" src="https://user-images.githubusercontent.com/22107254/99933889-27c75180-2d11-11eb-8048-0d3250d00392.png">

**Operating System:**
 - OS: [Macos (intel 16 inch)]
 - Version [10.15.7 (19H2)]

**Comment by TOLoneWolf** [comment]
just start typing after you get the blinking cursor icon. There is no text there so you can not edit it that is why delete and movement do not work. 

It just displays the suggested name from the pack name.

**Comment by RemagOfficial** [comment]
that pack is just one mod you can just make a forge instance and add the mod

**Comment by pagameba** [comment]
Had the same problem, UX here is not great - the way it is shown it looks like you should be able to enter a name. I'd recommend either not showing the pack name at all then its obvious you have to type one in, or actually populate the input with the suggested name from the pack so that it can be selected and modified (or used as is)

**Comment by Eskaan** [comment]
Duplicate of #552
