### ISSUE TITLE
My computer says its harmful

### ISSUE THREAD

**Issue by WaitWhyAmIHere** [gorilla-devs/GDLauncher#698]
I decided to install it but my antivirus said it's harmful. Should I worry or is it a false one?

OS: Microsoft Windows 10 Home 
Version: 10.0.18363
System: Gigabyte Technology. Co. ltd

This is a simple thing but I need a answer

**Comment by WaitWhyAmIHere** [comment]
I GOT A WORST PROBLEM IT SAYS THE POWER USEAGE IS VERY HIGH!

**Comment by TOLoneWolf** [comment]
As long as you got it from gdevs.io or this github repo it is safe to run.

Windows telling you it's high power usage means absolutely nothing, that just means it's doing stuff.
