### ISSUE TITLE
[LWJGL] GLFW_API_UNAVAILABLE error Exception in thread "main"

### ISSUE THREAD

**Issue by thegame4craft** [gorilla-devs/GDLauncher#700]
**Describe the bug**
I can't start my profile ifi click on a installed profile on start. this is my error code: `[LWJGL] GLFW_API_UNAVAILABLE error Exception in thread "main" `

**Operating System:**
 - OS: windows 10 pro 1909

**Comment by ursacascadia** [comment]
bump, Linux 20.04 with NVIDIA gfx card and AMD ryzen 5

**Comment by ursacascadia** [comment]
reboot fixed it nvm lol
