### ISSUE TITLE
[Feature] : Modlist file added to pack export archive.

### ISSUE THREAD

**Issue by JoelZBub** [gorilla-devs/GDLauncher#703]
When exporting a modpack instance, I'd like to be able to pass a list of installed mods to others. The former Twitch launcher used to include a modlist.html file with the pack export that made this possible. (This was also good for having a hyperlinked list for including with the modpack that included links back to the included mods for attribution, though it's not necessary for this request.)

**Describe the solution you'd like**
Include a modlist in the archive (whether HTML or even a simple text file) that lists the mods that will be included when installing the export.

Alternative is manually compiling this list which is prohibitively time-consuming

**Additional context**
I consider this a missing feature from the Twitch Launcher that would improve the GDLauncher user experience for pack developers.

**Comment by Eskaan** [comment]
Fixed by a30a6153

**Comment by JoelZBub** [comment]
Thank You
