### ISSUE TITLE
Adding New Instances loading infinite

### ISSUE THREAD

**Issue by KinteshiAT** [gorilla-devs/GDLauncher#704]
**Describe the bug**
When I go to the "Add a new Instance" and go to the twitch Section, choose any Pack there. After the Name giving Pop-Up I get the loading Screen infinitely with no download.

**To Reproduce**
1. Go to 'Add a new Instance'
2. Click on 'Twitch'
3. Scroll down to 'Any Pack'
4. Click Download (any), choose a Name, see infinite Loading screen

**Expected behavior**
Getting a Loading screen into the Download thingy

**Possible solutions**
I don't know I tried reinstalling several Times restarted my PC multiple times.

**Screenshots**
![image](https://user-images.githubusercontent.com/75277689/100662698-8a45d080-3355-11eb-9b76-4f2fe6b48829.png)

**Operating System:**
 - Windows
 - 10

**Additional context**
I had problems with installing java to if that helps, I have it running now since I played some vanilla Packs already to see if that worked.

**Comment by thebloxxer11** [comment]
I think this is because of CurseForge's transition from Twitch to Overwolf.

**Comment by KinteshiAT** [comment]
Duplicate of #

> I think this is because of CurseForge's transition from Twitch to Overwolf.

So basically patience is the key ?

**Comment by KinteshiAT** [comment]
> I think this is because of CurseForge's transition from Twitch to Overwolf.

So ur telling me to have patience or what ?

**Comment by thebloxxer11** [comment]
> > I think this is because of CurseForge's transition from Twitch to Overwolf.
> 
> So ur telling me to have patience or what ?

Another probable reason, and temp fix, is it isn't installing Forge correctly. On that screen, reboot the launcher. Then RMB on that instance, Manage, and select the Forge version manually. I've had this issue a couple times with MC1.4.7 instances, but I didn't bother to report it.

**Comment by KinteshiAT** [comment]
> > > I think this is because of CurseForge's transition from Twitch to Overwolf.
> > 
> > 
> > So ur telling me to have patience or what ?
> 
> Another probable reason, and temp fix, is it isn't installing Forge correctly. On that screen, reboot the launcher. Then RMB on that instance, Manage, and select the Forge version manually. I've had this issue a couple times with MC1.4.7 instances, but I didn't bother to report it.

First of all sorry for the late response but I haven't had time yet. It would be something worth doing but I don't even get an instance icon in the starting menu so you fix doesn't work in this case

**Comment by AwwShoot** [comment]
I have a similar Issue. I tried importing a zip of a pack (This specifically https://www.curseforge.com/minecraft/modpacks/the-cosmic-tree-1-16-4/files/3152477) and got an infinite loading screen and never got the instance icon.

**Comment by Eskaan** [comment]
Curseforge imports fixed in 6f7d3a31 - should have resolved the issue
