### ISSUE TITLE
Status Code 500 when trying to Login

### ISSUE THREAD

**Issue by abishaieth** [gorilla-devs/GDLauncher#706]
Hi All,

I opened the application and it prompt me to the login page. 
When I enter my details it's giving me a status code 500 error. 
I can see that the API is on red, but I don't know if that affects the login or not. 

Error is attached.
![image](https://user-images.githubusercontent.com/36078286/101166452-9b822c00-3638-11eb-8591-f0f99faa7490.png)

**Comment by Ladvace** [comment]
It's not our fault, it's Mojang problem
