### ISSUE TITLE
[Feature] A different Java executable for each instance

### ISSUE THREAD

**Issue by AnErrupTion** [gorilla-devs/GDLauncher#707]
**Is your feature request related to a problem? Please describe.**
I have a 1.16.4 instance and I have a 1.8.9. Each time I have to switch from Java 15 (1.16.4) to Java 8 (1.8.9) because Java 9+ is incompatible with 1.8.9.

**Describe the solution you'd like**
I would like to be able to have a separate Java executable for each instance I have.

**Describe alternatives you've considered**
MultiMC 5 has that option, even the official Minecraft Launcher has it.

**Additional context**
None.

**Comment by TOLoneWolf** [comment]
dup #400
