### ISSUE TITLE
Microsoft account login

### ISSUE THREAD

**Issue by Polsaker** [gorilla-devs/GDLauncher#710]
**Is your feature request related to a problem? Please describe.**
New Minecraft accounts are already getting created with Microsoft account, it would be nice if GDLauncher supported that

**Describe the solution you'd like**
A user in MultiMC/MultiMC5#3475 did some research and documented the process

**Comment by EnzoAlbornoz** [comment]
I've made a workaround, but the code is messy. I'll make some improvements then I'll send a PR

**Comment by EnzoAlbornoz** [comment]
Now, I need to improve the CI config, because GDLauncher will need an client id from Azure Apps. I've registered one in my personal account and used it to test the code.

https://user-images.githubusercontent.com/39244167/103158379-d42aa680-479b-11eb-86a2-e76343cdca71.mp4

**Comment by mpfaff** [comment]
I tried the release from that PR and it doesn't seem to renew the session when it expires.

**Comment by blarfoon** [comment]
We released this officially as beta. Could you try that?
https://github.com/gorilla-devs/GDLauncher/releases/download/v1.1.0-beta.2/GDLauncher-win-setup.exe
https://github.com/gorilla-devs/GDLauncher/releases/download/v1.1.0-beta.2/GDLauncher-mac-setup.dmg
https://github.com/gorilla-devs/GDLauncher/releases/download/v1.1.0-beta.2/GDLauncher-linux-setup.AppImage

**Comment by EnzoAlbornoz** [comment]
> I tried the release from that PR and it doesn't seem to renew the session when it expires.

Could you send a network log or print from Dev Tools? You can open it by click in the console button in the upper left of the launcher. Then, after open Dev Tools, select the network tab.

**Comment by BarryBonkers** [comment]
> We released this officially as beta. Could you try that?
> https://github.com/gorilla-devs/GDLauncher/releases/download/v1.1.0-beta.2/GDLauncher-win-setup.exe
> https://github.com/gorilla-devs/GDLauncher/releases/download/v1.1.0-beta.2/GDLauncher-mac-setup.dmg
> https://github.com/gorilla-devs/GDLauncher/releases/download/v1.1.0-beta.2/GDLauncher-linux-setup.AppImage

works well, no problems encountered.

**Comment by Kore-Development** [comment]
A friend of mine tried logging in using a new Java account which uses a Microsoft account and they get an error related to being unable to get the token from Secure Token Service or something like that.

**Comment by EnzoAlbornoz** [comment]
Could you send a network log? 
- Open the GDL Dev Tools on the upper left corner (An icon like **>_**) .
- Open the Network Tab
- Try Login
- Find a line that has a red "authorize" and right click it.
- Send us (Discord DM) the content of the "Response" tab

**Comment by ericmedinax** [comment]
I've been having the same problem as the person above: I try to log in using my microsoft account and I receive a message in red saying "error: error occured while fetching token from Xbox Secure Token Service." Not really sure what I can do.

**Comment by EnzoAlbornoz** [comment]
> I've been having the same problem as the person above: I try to log in using my microsoft account and I receive a message in red saying "error: error occured while fetching token from Xbox Secure Token Service." Not really sure what I can do.

Your account is a child/under 18 account? Some people reported that this account "type" is related to this issue.

**Comment by khrj** [comment]
> I tried the release from that PR and it doesn't seem to renew the session when it expires.

Yep, it just logs me out once every few days

**Comment by EnzoAlbornoz** [comment]
> > I tried the release from that PR and it doesn't seem to renew the session when it expires.
> 
> Yep, it just logs me out once every few days

Did you built from source (master branch) or you are using the beta channel release?

**Comment by khrj** [comment]
@EnzoAlbornoz I'm using the beta channel release. Does master fix it? If so, lmk when it reaches beta!

**Comment by EnzoAlbornoz** [comment]
> @EnzoAlbornoz I'm using the beta channel release. Does master fix it? If so, lmk when it reaches beta!

In master we changed the authentication category of GDLauncher to a "desktop application" mode. With this change the time to renew is longer. I've managed to renew the token more times too.
At the time that I'm writing this, I don't know when it will comes to beta.

**Comment by TheEpicProgrammer** [comment]
I have a friend who just got a brand new account and he gets the xbox token error thingy

**Comment by jcotton42** [comment]
> 
> 
> I have a friend who just got a brand new account and he gets the xbox token error thingy

Are they under 18? That seems to cause issues based on comments earlier in the thread.

**Comment by TheEpicProgrammer** [comment]
> Are they under 18? That seems to cause issues based on comments earlier in the thread.
Used to be, but he changed his age back higher than 18 since I was helping him.

**Comment by Acrivec** [comment]
> 
> 
> > I tried the release from that PR and it doesn't seem to renew the session when it expires.
> 
> Yep, it just logs me out once every few days

My boyfriend gets logged out every time he closes the app, which additionaly keeps updating to release instead of beta. He used beta installer and in config the channel is set to beta.

**Comment by TheWolfGamer75** [comment]
When I try to sign in with microsoft I just get a network error.

**Comment by NEXUS2345** [comment]
@killpowa is it possible to get a new beta version with Microsoft account support including the fixes for #841?

Thanks!

EDIT: Nevermind, sorry for the ping, just saw it got added in the latest release. Thanks!

**Comment by AwesomeKalin** [comment]
![image](https://user-images.githubusercontent.com/47223207/115965574-d15d7980-a521-11eb-85fb-c7f72778a2c5.png)
![image](https://user-images.githubusercontent.com/47223207/115965597-e76b3a00-a521-11eb-8910-56f6ea5baac5.png)
I get this when I try to log in to the latest version. Any way to fix this?

**Comment by urmet** [comment]
from discord faq 
> - MS accounts under 18 will get "Error occurred while fetching token from Xbox Secure Token Service" when trying to login on 3rd party launchers atm with the current login system being used by them.
> Possible workaround is having an adult setup family group (unconfirmed) https://account.microsoft.com/family/about

**Comment by AwesomeKalin** [comment]
Thanks

**Comment by christabone** [comment]
Adding the MS account of someone under 18 to my family group worked, thanks!

**Comment by Eskaan** [comment]
Fixed by 3b1bdc88

**Comment by EricBuist** [comment]
Hi, it's been a couple of months Mojang is switching to Microsoft. Why was nothing done to adapt the launcher until things break? What can we use as an alternative? Twitch is completely out for me because of DPI scaling, 90% of the UI is unusable.

**Comment by jcotton42** [comment]
> Hi, it's been a couple of months Mojang is switching to Microsoft. Why was nothing done to adapt the launcher until things break? What can we use as an alternative? Twitch is completely out for me because of DPI scaling, 90% of the UI is unusable.

GD has supported Microsoft accounts for several months now. If you don't have that option you might just need to manually update the launcher by rerunning the installer from the site.
