### ISSUE TITLE
Cant copy paste JVM arguments on mac making them almost unusable

### ISSUE THREAD

**Issue by maxybaer123** [gorilla-devs/GDLauncher#711]
**Describe the bug**
When I go to options and custom java arguments
**To Reproduce**
1. Go to 'options'
2. Click on 'java'
3. Scroll down to 'java custom arguments'
4. Select text and try to press command v like normal for copy and paste
5. See error
Note I also tried to paste them using control v which sometimes work when command v does not on macs
I also tested with just copy and pasting a single letter to see if that was the issue it was not
note this also works if you go into the manage section of a modpack and click override jvms then try and copy and paste them there
**Expected behavior**
the pasted text appears in the java arguments section

**Possible solutions**
add full text editing capability to the jvm bar (i think somethings limiting it)
add a text file that sets jvms with a open text file button next to the jvms so we can edit them more robustly.

**Operating System:**
 - OS: [MacOS]
 - Version [10.15.7 (19H2)]

**Comment by TemperedFool** [comment]
I've experienced the same thing. I've had no luck actually putting in JVM arguments because of this.

As a short-term workaround, is there somewhere in disk where the arguments are stored in a config file? Then I could at least put them in there!

**Comment by Ladvace** [comment]
this issues has been solved but not released, I try to realease it today

**Comment by maxybaer123** [comment]
As a temporary fix I have found that selecting text and click dragging it into the argument bar it will paste them in. That being said I recommend deleting anything you have in the argument bar beforehand so you dont accidentaly paste in the middle of a word.

**Comment by Ladvace** [comment]
This fix Will be released in next release, at the Moment we are working on
the Microsoft login

Il gio 17 dic 2020, 04:14 maxybaer123 <notifications@github.com> ha scritto:

**Comment by TemperedFool** [comment]
For the record, this is definitely fixed in the beta that includes MS account logins. TYVM!!

**Comment by GrumpyChunks** [comment]
Possibly related, but I have the same problem with the password field when entering my Mojang Account details. The work around suggested above (select, drag and drop the text) does work. (Mac OS Big Sur)

**Comment by blarfoon** [comment]
This should be fixed. I will reopen if it's still an issue
