### ISSUE TITLE
[Question] Parsing client json launch arguments

### ISSUE THREAD

**Issue by yonderbread** [gorilla-devs/GDLauncher#713]
Hello! I'm trying to make a simple CLI based Minecraft launcher and was wondering how you guys went about parsing out the launch arguments from the Minecraft client json files. I'm struggling to write a parser that works for any version of the game.

**Comment by yonderbread** [comment]
Also where would I find the code for this in the repo?

**Comment by TOLoneWolf** [comment]
Decides if newer or older mc args parse.  
https://github.com/gorilla-devs/GDLauncher/blob/master/src/common/reducers/actions.js#L2057  

newer mc  
https://github.com/gorilla-devs/GDLauncher/blob/master/src/app/desktop/utils/index.js#L460  

older mc  
https://github.com/gorilla-devs/GDLauncher/blob/master/src/app/desktop/utils/index.js#L363

**Comment by yonderbread** [comment]
> Decides if newer or older mc args parse.
> https://github.com/gorilla-devs/GDLauncher/blob/master/src/common/reducers/actions.js#L2057
> 
> newer mc
> https://github.com/gorilla-devs/GDLauncher/blob/master/src/app/desktop/utils/index.js#L460
> 
> older mc
> https://github.com/gorilla-devs/GDLauncher/blob/master/src/app/desktop/utils/index.js#L363

Thank you so much! This is exactly what I needed, appreciate it :100:
