### ISSUE TITLE
[feat request] launch instances form tray icon

### ISSUE THREAD

**Issue by rmobis** [gorilla-devs/GDLauncher#717]
**Is your feature request related to a problem? Please describe.**
No. It's more like a quality of life thing.

**Describe the solution you'd like**
When you right-click the tray icon for GDLauncher, it displays a list of my instances (maybe only the most recent?) which I can click to instantly launch it, without having to open the main interface.

**Describe alternatives you've considered**
The alternative already exists, all you have to do is double-click the tray icon and it opens the main interface from which you can start any instance. Having it directly on the tray icon is, to me, considerably better experience.

**Additional context**
If this is a feature you'd like to have, I'd probably be willing to draft a PR.

**Comment by rmobis** [comment]
Would you be willing to accept a PR adding this?

**Comment by Ladvace** [comment]
> 
> 
> Would you be willing to accept a PR adding this?

if the pr it's valid yes
