### ISSUE TITLE
Duplicated news in News section

### ISSUE THREAD

**Issue by whitebear60** [gorilla-devs/GDLauncher#723]
**Describe the bug**
All news in News slider are duplicated. (first and second slides shows the same news, third and fourth slides shows the same news etc)

**To Reproduce**
1. Open GDLauncher
2. Look at News slider on top

**Operating System:**
 - OS: macOS
 - Version 10.10

**Comment by Ladvace** [comment]
the problem is from minecraft api, they send duplicates news, quite funny
