### ISSUE TITLE
Unclear error message if out of inotify watches

### ISSUE THREAD

**Issue by JacobRoth** [gorilla-devs/GDLauncher#725]
**Describe the bug**
On Linux systems, if the user is out of inotify watches, you will see "Node Sentinel File Watcher could not be initialized" with no indication of how to fix this. Modpacks will not launch due to this error.

**To Reproduce**
1. Be out of inotify watches
2. Start GDLauncher

**Expected behavior**
Error message should clarify for the user what to do. 

**Possible solutions**
For example, Syncthing is a completely different piece of software that can also suffer from running out of inotify watches. When this happens, the user is pointed towards [this Syncthing FAQ page](https://docs.syncthing.net/users/faq.html#inotify-limits) to learn how to increase the inotify watch limit. 

**Operating System:**
 - OS: Debian 10
 - GDLauncher v1.0.11

**Comment by Eskaan** [comment]
Duplicate of #617
