### ISSUE TITLE
Unable to download after reinstall of windows

### ISSUE THREAD

**Issue by KaiRoman** [gorilla-devs/GDLauncher#726]
**Describe the bug**
(title)
**To Reproduce**
Dont know if you guys wanna get a new ssd install windows on it then switch it to the new sdd form a smaller ssd, then once in intsall and try to download stuff im having problem downloading gog galaxy too

[Consle]

> A cookie associated with a cross-site resource at http://minecraft.net/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.
> webpack-internal:///1028:264 setup
> webpack-internal:///33:207 [RTS] REMOVING INSTANCE Pog
> webpack-internal:///33:207 Error: ENOENT: no such file or directory, open 'C:\Users\Ander\AppData\Roaming\gdlauncher_next\instances\The Clientside Overhaul\config.json'
> webpack-internal:///4:7 Uncaught (in promise) TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
>     at validateString (internal/validators.js:112)
>     at Object.join (path.js:375)
>     at _callee28$ (webpack-internal:///33:198)
>     at tryCatch (webpack-internal:///482:64)
>     at Generator.invoke [as _invoke] (webpack-internal:///482:281)
>     at Generator.eval [as next] (webpack-internal:///482:117)
>     at asyncGeneratorStep (webpack-internal:///4:4)
>     at _next (webpack-internal:///4:26)
>     at eval (webpack-internal:///4:33)
>     at new Promise (<anonymous>)
> DevTools failed to parse SourceMap: file:///C:/Users/Ander/AppData/Local/Programs/gdlauncher/resources/app.asar/build/static/css/5.7828baa1.chunk.css.map
> ﻿
> 

[screenshot] 
https://i.imgur.com/DarqyNI.png

**Comment by Eskaan** [comment]
I think this is resolved whit 199f0454.
If this issue still persists, please reopen it and ping me
