### ISSUE TITLE
List of useful projects to use

### ISSUE THREAD

**Issue by blarfoon** [gorilla-devs/GDLauncher#73]
This is a list to keep track of every useful project we find that may be useful to our launcher.
If you found a project that may be useful, comment it down below and we'll discuss about it.

### Projects List

- [mc-launch](https://github.com/mkg20001/mc-launch): it's kinda old (2016) but it could help figuring some things out
- [node-minecraft-wrap](https://github.com/PrismarineJS/node-minecraft-wrap): It could be very useful, should see if it fits our needs. It could allow us to skip a significant part of the development
- [minecraft-launcher](https://www.jsdelivr.com/package/npm/minecraft-launcher): A chinese simplified launcher.
- [launcher-api](https://www.jsdelivr.com/package/npm/@bauxite/launcher-api): High level Minecraft API for managing instances.
- [minecraft-chunk-viewer](https://github.com/Pessimistress/minecraft-chunk-viewer): A chunk viewer
- [skinview3d](https://github.com/to2mbn/skinview3d): A skin viewer
- [MinecraftLaunchCoreUI](https://github.com/Srar/MinecraftLaunchCoreUI): A launcher (?). Chinese
- [threex.minecraft](https://github.com/jeromeetienne/threex.minecraft): Skin viewer (with animations)
- [aws-minecraft](https://github.com/positron/aws-minecraft): AWS minecraft server automatic deploy
- [minecraft-character-configurator](https://github.com/tweedegolf/minecraft-character-configurator): A skin configurator
- [node-minecraft-runner](https://github.com/dominicbarnes/node-minecraft-runner): Servers api for nodejs
- [skinpreview.js](https://github.com/Hacksore/skinpreview.js): Skin viewer
- [skinpreview3d.js](https://github.com/bs-community/skinview3d): Skin viewer. **THIS COULD BE VERY USEFUL!**
- [ILauncher](https://github.com/InfinityStudio/ILauncher): A MC launcher written in vuejs/electron. **Reall cool project!**
- [OMPM-Launcher](https://github.com/orblazer/OMPM-Launcher): A launcher for custom modpacks
- [voxel-visualization](https://github.com/FlorianFe/voxel-visualization): MC schematics viewer. **Really cool project!**
- [MinecraftLeagueOfLegends](https://github.com/JoshBollar/MinecraftLeagueOfLegends): League of legends implementation using scriptcraft
- [Skinviewer](https://github.com/keupoz/Skinviewer): (kinda) cool skin viewer
- [next](https://github.com/ATLauncher/next): ATLauncher next version written in nw.js. To keep track of!
- [MinecraftLaunchCoreUI](https://github.com/Srar/MinecraftLaunchCoreUI): MC launch wrapper

**Comment by furtabs** [comment]
- [Twitch Minecraft Modpack Exporter](https://github.com/Gaz492/twitch-export-builder) Exporter for Twitch Packs
- [Curse Changelog Generator](https://github.com/TheRandomLabs/ChangelogGenerator) Parses 2 Curse manifest.json files for Changelog Generation
- [Modpack Uploader](https://github.com/NillerMedDild/ModpackUploader) A Script that uses the 2 above projects and automatically uploads to curse. Maybe look at the CURL arguments
