### ISSUE TITLE
Replace Minecraft Jar/Import jar/json file

### ISSUE THREAD

**Issue by AstroOrbis** [gorilla-devs/GDLauncher#731]
**Is your feature request related to a problem? Please describe.**
It should be possible to replace the minecraft jar file, like when you import a folder with a jar and a json file into your .../minecraft/versions folder.

**Describe the solution you'd like**
Maybe an "import alternative version" file in the zip/modpack/vanilla-forge-fabric menu?

**Describe alternatives you've considered**
Alternative: Use vanilla launcher
**Additional context**

**Comment by AshtakaOOf** [comment]
i also want this feature !!!

**Comment by Winter** [comment]
Definitely would be great to be able to use a custom forge jar.

**Comment by VeraSimon** [comment]
This would also be a useful feature for testing the new 1.18 experimental snapshot that was just released
https://www.minecraftforum.net/news/60856-java-edition-1-18-experimental-snapshot-1

**Comment by AstroOrbis** [comment]
I'm learning JS right now, so I could try taking a crack at solving this myself!
(Okay fine I admit that GitHub Copilot is doing most of the work for me-)

**Comment by Eskaan** [comment]
Duplicate of #616
