### ISSUE TITLE
Swap Twitch icon and name with Curseforge

### ISSUE THREAD

**Issue by Madis0** [gorilla-devs/GDLauncher#737]
**Is your feature request related to a problem? Please describe.**
Curseforge is no longer owned by Twitch, so it doesn't make sense to keep that naming.

**Describe the solution you'd like**
Replace all references of "Twitch" with "Curseforge"

**Describe alternatives you've considered**
N/A

**Additional context**
![Screenshot](https://user-images.githubusercontent.com/8611110/103557326-afc97b00-4ebb-11eb-8fc6-d13f48353015.png)

**Comment by Eskaan** [comment]
Done in 461443c1.
