### ISSUE TITLE
Unscrollable account screen

### ISSUE THREAD

**Issue by LUKISO2** [gorilla-devs/GDLauncher#747]
**Describe the bug**
When you will add too many accounts to your accounts selection screen, you won't be able to select any account that doesn't fit in that presized box (It's not possible to scroll there)

**To Reproduce**
1. go to "Accounts" (Down, right).
2. Add enough accounts to fill up the box.
3. Try scrolling or getting to the one's below that box
(TIP: You can make the required account number smaller, by making the app window smaller)

**Expected behavior**
You won't be able to reach the accounts, that are down.

**Possible solutions**
Just add a scroll bar.

**Screenshots**
Attached!
![BugReport](https://user-images.githubusercontent.com/75501566/104132922-983d3700-5380-11eb-9db2-d86136e6bf37.png)

**Operating System:**
 - OS: Windows
 - Version: 10

**Additional context**
There is a bug with the "add account" button, but by solving this problem, it will get solved too, probably.

**Comment by Eskaan** [comment]
I fixed it for you whit d57ea3c3 #959.
