### ISSUE TITLE
game crashes

### ISSUE THREAD

**Issue by dalandis** [gorilla-devs/GDLauncher#749]
**Describe the bug**
crash every time you click disconnect from the server

**To Reproduce**
1. connect to any server
2. disconnect from server

**Expected behavior**
disconnect without crashes

**Possible solutions**
this happens exactly when you press disconnect

**Operating System:**
 - OS: Windows
 - Version 10 20H2

**Additional context**
error in console - https://pastebin.com/5sQp1GzP

**Comment by RemagOfficial** [comment]
you have mods installed its probably one of those not the launcher

**Comment by RemagOfficial** [comment]
you have mods installed its probably one of those not the launcher

**Comment by dalandis** [comment]
the problem was VoxelMap and lambdynlights. replaced VoxelMap until it crashes
