### ISSUE TITLE
OptiFine

### ISSUE THREAD

**Issue by Gunga426** [gorilla-devs/GDLauncher#750]
**Is your feature request related to a problem? Please describe.**
Yes, it is very annoying when I am trying to add OptiFine to GDLauncher, as you need to import a .zip file rather than a .jar file, which OptiFine is

**Describe the solution you'd like**
Add a way to simply install OptiFine from the launcher, like you would a modpack.

**Describe alternatives you've considered**
Add a way to import .jar files

**Additional context**
No

**Comment by Linguardium** [comment]
have you tried just dragging the jar into the mods window before you click Add Mods (or even manually into the mods folder)? It does take jar files just fine. You would have to use a Forge instance for this though

Perhaps this should be listed as Allow the Optifine loader to be used separate from forge and fabric installs (as it wraps the launch of the game similar to forge or fabric mod loaders)

**Comment by RemagOfficial** [comment]
@Linguardium Optifine doesnt allow redistribution so adding OF as a launcher type wouldnt really do anything
and @Gunga426 optifine is a jar like all other mods, just drop it in the mods folder

**Comment by Linguardium** [comment]
Fair enough, from the problem report it appeared as though the user wanted to install optifine without using a modlauncher rather than install it as a mod. Forgot about the redistribution issue though, thanks :)

**Comment by Siuolplex** [comment]
> Linguardium Optifine doesnt allow redistribution so adding OF as a launcher type wouldnt really do anything
> and Gunga426 optifine is a jar like all other mods, just drop it in the mods folder

Optifine is allowed to be downloaded from Optifine servers at runtime, as long as its not downloaded from Non-Optifine servers or bundled with the launcher you should be good with getting it in. (Besides any possible issues code wise)

**Comment by ftzi** [comment]
The GDLauncher team could contact the OptiFine team to see if it's alright to add a built-in way to add it. As this is already a big project (>400 stars), I really think they would allow it (if it is needed), maybe by adding a "Donate to OptiFine" button.

That would be really good. OptiFine is a really needed mod for Vanilla / Forge packs

**Comment by Siuolplex** [comment]
> The GDLauncher team could contact the OptiFine team to see if it's alright to add a built-in way to add it. As this is already a big project (>400 stars), I really think they would allow it (if it is needed), maybe by adding a "Donate to OptiFine" button.
> 
> That would be really good. OptiFine is a really needed mod for Vanilla / Forge packs

Sp614x, the sole dev of Optifine, would most likely not allow it to be downloaded from the GD Servers.

Again, the approved work around is to instead download it from Optifine servers at runtime.

**Comment by Ecorous** [comment]
Optifine should never be used to improve performance. It does more bad than good. Try using a fabric modpack with sodium and lithium for vanilla, and for forge, you'll have to find other alternatives for that

**Comment by rautamiekka** [comment]
> Optifine should never be used to improve performance. It does more bad than good. Try using a fabric modpack with sodium and lithium for vanilla, and for forge, you'll have to find other alternatives for that

If you've an actual point, make it. Just "does more bad than good" doesn't qualify.

**Comment by ghost** [comment]
@RemagOfficial 
> Optifine doesnt allow redistribution so adding OF as a launcher type wouldnt really do anything

OptiFine may not allow redistribution, as it is an all rights reserved license, but that doesn't mean that download links aren't.

**Comment by Eskaan** [comment]
Duplicate of #616

**Comment by JonLit** [comment]
I made an Installer for Optifine for GDLauncher/OptiForge, it copies the OptiFine.jar File to the required locations

ONLY! tested configuration: Linux, GDLauncher v.1.1.14, Minecraft 1.17.1, Forge 37.0.51, OptiFine 1.17.1_HD_U_G9 and OptiForge-MC1.17.1-0.1.0

it should work with other versions too, but it's not (yet) tested

OptiForge Issue Thread: https://github.com/ZekerZhayard/OptiForge/issues/87
My Installer: https://github.com/JonLit/GDLauncherOptiFineInstaller

**Comment by ghost** [comment]
> I made an Installer for Optifine for GDLauncher/OptiForge, it copies the OptiFine.jar File to the required locations
> 
> ONLY! tested configuration: Linux, GDLauncher v.1.1.14, Minecraft 1.17.1, Forge 37.0.51, OptiFine 1.17.1_HD_U_G9 and OptiForge-MC1.17.1-0.1.0
> 
> it should work with other versions too, but it's not (yet) tested
> 
> OptiForge Issue Thread: [ZekerZhayard/OptiForge#87](https://github.com/ZekerZhayard/OptiForge/issues/87)
> My Installer: https://github.com/JonLit/GDLauncherOptiFineInstaller

@JonLit GDLauncher is JavaScript-based, not Java. It wouldn't be the ***best*** thing to mix languages like that.

**Comment by JonLit** [comment]
> > I made an Installer for Optifine for GDLauncher/OptiForge, it copies the OptiFine.jar File to the required locations
> > 
> > ONLY! tested configuration: Linux, GDLauncher v.1.1.14, Minecraft 1.17.1, Forge 37.0.51, OptiFine 1.17.1_HD_U_G9 and OptiForge-MC1.17.1-0.1.0
> > 
> > it should work with other versions too, but it's not (yet) tested
> > 
> > OptiForge Issue Thread: [ZekerZhayard/OptiForge#87](https://github.com/ZekerZhayard/OptiForge/issues/87)
> > My Installer: https://github.com/JonLit/GDLauncherOptiFineInstaller
> 
> @JonLit GDLauncher is JavaScript-based, not Java. It wouldn't be the ***best*** thing to mix languages like that. 

It is a separate program, so I don't see a problem, also, I'm not good at js

**Comment by ghost** [comment]
> > > I made an Installer for Optifine for GDLauncher/OptiForge, it copies the OptiFine.jar File to the required locations
> > > ONLY! tested configuration: Linux, GDLauncher v.1.1.14, Minecraft 1.17.1, Forge 37.0.51, OptiFine 1.17.1_HD_U_G9 and OptiForge-MC1.17.1-0.1.0
> > > it should work with other versions too, but it's not (yet) tested
> > > OptiForge Issue Thread: [ZekerZhayard/OptiForge#87](https://github.com/ZekerZhayard/OptiForge/issues/87)
> > > My Installer: https://github.com/JonLit/GDLauncherOptiFineInstaller
> > 
> > 
> > @JonLit GDLauncher is JavaScript-based, not Java. It wouldn't be the _**best**_ thing to mix languages like that.
> 
> It is a separate program, so I don't see a problem, also, I'm not good at js

I am sorry if this sounds rude, but wouldn't it be easier to just download OptiFine and drop it into the GDLauncher window? 

I guess you could say that it's a start, so good job!

**Comment by JonLit** [comment]
> > > > I made an Installer for Optifine for GDLauncher/OptiForge, it copies the OptiFine.jar File to the required locations
> > > > ONLY! tested configuration: Linux, GDLauncher v.1.1.14, Minecraft 1.17.1, Forge 37.0.51, OptiFine 1.17.1_HD_U_G9 and OptiForge-MC1.17.1-0.1.0
> > > > it should work with other versions too, but it's not (yet) tested
> > > > OptiForge Issue Thread: [ZekerZhayard/OptiForge#87](https://github.com/ZekerZhayard/OptiForge/issues/87)
> > > > My Installer: https://github.com/JonLit/GDLauncherOptiFineInstaller
> > > 
> > > 
> > > @JonLit GDLauncher is JavaScript-based, not Java. It wouldn't be the _**best**_ thing to mix languages like that.
> > 
> > It is a separate program, so I don't see a problem, also, I'm not good at js
> 
> I am sorry if this sounds rude, but wouldn't it be easier to just download OptiFine and drop it into the GDLauncher window? 
> 
> I guess you could say that it's a start, so good job!

I haven't tried just dropping it into gdlauncher' s window, but I don't think it would work, because then you would also somewhere have a button to install optifine in GDLauncher. As far as I know, GDLauncher does not have a way to install optifine automatically

**Comment by ghost** [comment]
> > > > > I made an Installer for Optifine for GDLauncher/OptiForge, it copies the OptiFine.jar File to the required locations
> > > > > ONLY! tested configuration: Linux, GDLauncher v.1.1.14, Minecraft 1.17.1, Forge 37.0.51, OptiFine 1.17.1_HD_U_G9 and OptiForge-MC1.17.1-0.1.0
> > > > > it should work with other versions too, but it's not (yet) tested
> > > > > OptiForge Issue Thread: [ZekerZhayard/OptiForge#87](https://github.com/ZekerZhayard/OptiForge/issues/87)
> > > > > My Installer: https://github.com/JonLit/GDLauncherOptiFineInstaller
> > > > 
> > > > 
> > > > @JonLit GDLauncher is JavaScript-based, not Java. It wouldn't be the _**best**_ thing to mix languages like that.
> > > 
> > > 
> > > It is a separate program, so I don't see a problem, also, I'm not good at js
> > 
> > 
> > I am sorry if this sounds rude, but wouldn't it be easier to just download OptiFine and drop it into the GDLauncher window?
> > I guess you could say that it's a start, so good job!
> 
> I haven't tried just dropping it into gdlauncher' s window, but I don't think it would work, because then you would also somewhere have a button to install optifine in GDLauncher. As far as I know, GDLauncher does not have a way to install optifine automatically

No, GDLauncher has a built in function to allow you to drag & drop `.jar`s into your mods. You can download OptiFine and drop the `.jar`.

**Comment by JonLit** [comment]
> > > > > > I made an Installer for Optifine for GDLauncher/OptiForge, it copies the OptiFine.jar File to the required locations
> > > > > > ONLY! tested configuration: Linux, GDLauncher v.1.1.14, Minecraft 1.17.1, Forge 37.0.51, OptiFine 1.17.1_HD_U_G9 and OptiForge-MC1.17.1-0.1.0
> > > > > > it should work with other versions too, but it's not (yet) tested
> > > > > > OptiForge Issue Thread: [ZekerZhayard/OptiForge#87](https://github.com/ZekerZhayard/OptiForge/issues/87)
> > > > > > My Installer: https://github.com/JonLit/GDLauncherOptiFineInstaller
> > > > > 
> > > > > 
> > > > > @JonLit GDLauncher is JavaScript-based, not Java. It wouldn't be the _**best**_ thing to mix languages like that.
> > > > 
> > > > 
> > > > It is a separate program, so I don't see a problem, also, I'm not good at js
> > > 
> > > 
> > > I am sorry if this sounds rude, but wouldn't it be easier to just download OptiFine and drop it into the GDLauncher window?
> > > I guess you could say that it's a start, so good job!
> > 
> > I haven't tried just dropping it into gdlauncher' s window, but I don't think it would work, because then you would also somewhere have a button to install optifine in GDLauncher. As far as I know, GDLauncher does not have a way to install optifine automatically
> 
> No, GDLauncher has a built in function to allow you to drag & drop `.jar`s into your mods. You can download OptiFine and drop the `.jar`. 

That won't work, you need to extract and copy optifine to the minecraft library folder and to gdlauncher library folder, in the mods folder you need OptiForge, which is also available through gdlauncher's built-in mod manager. In old versions I read that you could just drop optifine into the mods folder, I think since 1.12 or 1.14 this doesn't work anymore

**Comment by JonLit** [comment]
> > > > > > I made an Installer for Optifine for GDLauncher/OptiForge, it copies the OptiFine.jar File to the required locations
> > > > > > ONLY! tested configuration: Linux, GDLauncher v.1.1.14, Minecraft 1.17.1, Forge 37.0.51, OptiFine 1.17.1_HD_U_G9 and OptiForge-MC1.17.1-0.1.0
> > > > > > it should work with other versions too, but it's not (yet) tested
> > > > > > OptiForge Issue Thread: [ZekerZhayard/OptiForge#87](https://github.com/ZekerZhayard/OptiForge/issues/87)
> > > > > > My Installer: https://github.com/JonLit/GDLauncherOptiFineInstaller
> > > > > 
> > > > > 
> > > > > @JonLit GDLauncher is JavaScript-based, not Java. It wouldn't be the _**best**_ thing to mix languages like that.
> > > > 
> > > > 
> > > > It is a separate program, so I don't see a problem, also, I'm not good at js
> > > 
> > > 
> > > I am sorry if this sounds rude, but wouldn't it be easier to just download OptiFine and drop it into the GDLauncher window?
> > > I guess you could say that it's a start, so good job!
> > 
> > I haven't tried just dropping it into gdlauncher' s window, but I don't think it would work, because then you would also somewhere have a button to install optifine in GDLauncher. As far as I know, GDLauncher does not have a way to install optifine automatically
> 
> No, GDLauncher has a built in function to allow you to drag & drop `.jar`s into your mods. You can download OptiFine and drop the `.jar`. 

That won't work, you need to extract and copy optifine to the minecraft library folder and to gdlauncher library folder, in the mods folder you need OptiForge, which is also available through gdlauncher's built-in mod manager. In old versions I read that you could just drop optifine into the mods folder, I think since 1.12 or 1.14 this doesn't work anymore

**Comment by ghost** [comment]
> > > > > > > I made an Installer for Optifine for GDLauncher/OptiForge, it copies the OptiFine.jar File to the required locations
> > > > > > > ONLY! tested configuration: Linux, GDLauncher v.1.1.14, Minecraft 1.17.1, Forge 37.0.51, OptiFine 1.17.1_HD_U_G9 and OptiForge-MC1.17.1-0.1.0
> > > > > > > it should work with other versions too, but it's not (yet) tested
> > > > > > > OptiForge Issue Thread: [ZekerZhayard/OptiForge#87](https://github.com/ZekerZhayard/OptiForge/issues/87)
> > > > > > > My Installer: https://github.com/JonLit/GDLauncherOptiFineInstaller
> > > > > > 
> > > > > > 
> > > > > > @JonLit GDLauncher is JavaScript-based, not Java. It wouldn't be the _**best**_ thing to mix languages like that.
> > > > > 
> > > > > 
> > > > > It is a separate program, so I don't see a problem, also, I'm not good at js
> > > > 
> > > > 
> > > > I am sorry if this sounds rude, but wouldn't it be easier to just download OptiFine and drop it into the GDLauncher window?
> > > > I guess you could say that it's a start, so good job!
> > > 
> > > 
> > > I haven't tried just dropping it into gdlauncher' s window, but I don't think it would work, because then you would also somewhere have a button to install optifine in GDLauncher. As far as I know, GDLauncher does not have a way to install optifine automatically
> > 
> > 
> > No, GDLauncher has a built in function to allow you to drag & drop `.jar`s into your mods. You can download OptiFine and drop the `.jar`.
> 
> That won't work, you need to extract and copy optifine to the minecraft library folder and to gdlauncher library folder, in the mods folder you need OptiForge, which is also available through gdlauncher's built-in mod manager. In old versions I read that you could just drop optifine into the mods folder, I think since 1.12 or 1.14 this doesn't work anymore

I don't think you understand what I am trying to say... 😒 
Also @JonLit please don't repeat the same message!

**Comment by Blackout03** [comment]
> > > > > > > > I made an Installer for Optifine for GDLauncher/OptiForge, it copies the OptiFine.jar File to the required locations
> > > > > > > > ONLY! tested configuration: Linux, GDLauncher v.1.1.14, Minecraft 1.17.1, Forge 37.0.51, OptiFine 1.17.1_HD_U_G9 and OptiForge-MC1.17.1-0.1.0
> > > > > > > > it should work with other versions too, but it's not (yet) tested
> > > > > > > > OptiForge Issue Thread: [ZekerZhayard/OptiForge#87](https://github.com/ZekerZhayard/OptiForge/issues/87)
> > > > > > > > My Installer: https://github.com/JonLit/GDLauncherOptiFineInstaller
> > > > > > > 
> > > > > > > 
> > > > > > > @JonLit GDLauncher is JavaScript-based, not Java. It wouldn't be the _**best**_ thing to mix languages like that.
> > > > > > 
> > > > > > 
> > > > > > It is a separate program, so I don't see a problem, also, I'm not good at js
> > > > > 
> > > > > 
> > > > > I am sorry if this sounds rude, but wouldn't it be easier to just download OptiFine and drop it into the GDLauncher window?
> > > > > I guess you could say that it's a start, so good job!
> > > > 
> > > > 
> > > > I haven't tried just dropping it into gdlauncher' s window, but I don't think it would work, because then you would also somewhere have a button to install optifine in GDLauncher. As far as I know, GDLauncher does not have a way to install optifine automatically
> > > 
> > > 
> > > No, GDLauncher has a built in function to allow you to drag & drop `.jar`s into your mods. You can download OptiFine and drop the `.jar`.
> > 
> > 
> > That won't work, you need to extract and copy optifine to the minecraft library folder and to gdlauncher library folder, in the mods folder you need OptiForge, which is also available through gdlauncher's built-in mod manager. In old versions I read that you could just drop optifine into the mods folder, I think since 1.12 or 1.14 this doesn't work anymore
> 
> I don't think you understand what I am trying to say... 😒
> Also @JonLit please don't repeat the same message!

so what @JonLit means is that with specifically the 1.17.1 optifine it is currently not compatible with forge so you need optiforge but optiforge changed how it works so in newer versions of optiforge, optifine doesn't just get placed in the mods folder.

**Comment by int11** [comment]
> > > > > > > > I made an Installer for Optifine for GDLauncher/OptiForge, it copies the OptiFine.jar File to the required locations
> > > > > > > > ONLY! tested configuration: Linux, GDLauncher v.1.1.14, Minecraft 1.17.1, Forge 37.0.51, OptiFine 1.17.1_HD_U_G9 and OptiForge-MC1.17.1-0.1.0
> > > > > > > > it should work with other versions too, but it's not (yet) tested
> > > > > > > > OptiForge Issue Thread: [ZekerZhayard/OptiForge#87](https://github.com/ZekerZhayard/OptiForge/issues/87)
> > > > > > > > My Installer: https://github.com/JonLit/GDLauncherOptiFineInstaller
> > > > > > > 
> > > > > > > 
> > > > > > > @JonLit GDLauncher is JavaScript-based, not Java. It wouldn't be the _**best**_ thing to mix languages like that.
> > > > > > 
> > > > > > 
> > > > > > It is a separate program, so I don't see a problem, also, I'm not good at js
> > > > > 
> > > > > 
> > > > > I am sorry if this sounds rude, but wouldn't it be easier to just download OptiFine and drop it into the GDLauncher window?
> > > > > I guess you could say that it's a start, so good job!
> > > > 
> > > > 
> > > > I haven't tried just dropping it into gdlauncher' s window, but I don't think it would work, because then you would also somewhere have a button to install optifine in GDLauncher. As far as I know, GDLauncher does not have a way to install optifine automatically
> > > 
> > > 
> > > No, GDLauncher has a built in function to allow you to drag & drop `.jar`s into your mods. You can download OptiFine and drop the `.jar`.
> > 
> > 
> > That won't work, you need to extract and copy optifine to the minecraft library folder and to gdlauncher library folder, in the mods folder you need OptiForge, which is also available through gdlauncher's built-in mod manager. In old versions I read that you could just drop optifine into the mods folder, I think since 1.12 or 1.14 this doesn't work anymore
> 
> I don't think you understand what I am trying to say... 😒
> Also @JonLit please don't repeat the same message!

PLZ JUST try to install forge and optifine in 1.17.1 version.
As far as i know it's impossible. because OPTIFINE DOESN'T officially compatible
if install both YOU MUST HAVE TO INSTALL Optiforge.

https://www.curseforge.com/minecraft/mc-mods/optiforge

and then there is way why JonLit make GDLauncherOptiFineInstaller
the website say

**OptiForge-MC1.17.1: DO NOT PUT OPTIFINE INTO MODS FOLDER. You should install OptiFine via OptiFine installer (double-click the OptiFine jar).
OptiForge-MC1.17.1: DO NOT PUT OPTIFINE INTO MODS FOLDER. You should install OptiFine via OptiFine installer (double-click the OptiFine jar).
OptiForge-MC1.17.1: DO NOT PUT OPTIFINE INTO MODS FOLDER. You should install OptiFine via OptiFine installer (double-click the OptiFine jar).
OptiForge-MC1.17.1: DO NOT PUT OPTIFINE INTO MODS FOLDER. You should install OptiFine via OptiFine installer (double-click the OptiFine jar).**

**Comment by blarfoon** [comment]
> The GDLauncher team could contact the OptiFine team to see if it's alright to add a built-in way to add it. As this is already a big project (>400 stars), I really think they would allow it (if it is needed), maybe by adding a "Donate to OptiFine" button.
> 
> That would be really good. OptiFine is a really needed mod for Vanilla / Forge packs

I did try to contact him multiple times over the last couple of years but he hasn't answered once so far.

**Comment by Rmdhn1** [comment]
i'm looking to just run on optifine, no Forge in betweens

**Comment by TheKodeToad** [comment]
Perhaps optifine.net could be opened in a web browser, and GDLauncher could wait for a new file in Downloads.

Alternatively, since this is an Electron app, there is no issue with simply opening the site inside the app.

OptiFine could also be scraped off the site, but that means that the adverts are not shown, even if the OptiFine site does not explicitly state that is is disallowed.

**Comment by rautamiekka** [comment]
What about the `(Mirror)` one ? https://optifine.net/downloads -> `https://optifine.net/adloadx?f=OptiFine_1.17.1_HD_U_H1.jar` -> `https://optifine.net/downloadx?f=OptiFine_1.17.1_HD_U_H1.jar&x=64877f4b58cd781d33423429426ee04e`

The `x` param changes every time, but that doesn't hurt anything. Scraping the page couldn't get simpler cuz once you got that `/download?f=` link, you can use even just wget to download it without headers or anything.
