### ISSUE TITLE
Loading Forever

### ISSUE THREAD

**Issue by yokisniff** [gorilla-devs/GDLauncher#758]
Hello, I am new to GDLauncher. when I downloaded the app, it just keeps loading. See:
![image](https://user-images.githubusercontent.com/75645436/105056626-6c861500-5a42-11eb-8e3b-5a2ce78f3ada.png)
I downloaded all the versions, the 7-zip version, the portable version, and the original. BUT IT NO WORK
Pls help I just wanna play minecraft

**Comment by slinkouswasalreadytaken** [comment]
Exact same issue on Arch Linux
```
   Applications ./GDLauncher-linux-setup_7f3fbd5f2222df32f280c5cbe7d0686d.AppImage
17:50:58.485 › setup 1.0.11
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
17:51:01.204 › Trying to start listener
17:51:01.207 › Started listener
Checking for update
Update for version 1.0.11 is not available (latest version: 1.0.11, downgrade is allowed).

```

it shows that same screen, with the animation, but will not load. Waiting does not help.

**Comment by tiecia** [comment]
Same issue on Windows. Let me know if you need any diagnostic data.

**Comment by rdezwart** [comment]
Also experiencing this issue on Windows. Console mentions the following: 

![image](https://user-images.githubusercontent.com/40707409/113501140-1882bc80-94d8-11eb-998a-d7e3ecf22e70.png)

**Comment by Denirvan** [comment]
Hello, I have the same problem in Windows, how can it be solved?

**Comment by Nich-Maia** [comment]
I got the same issue. Opening up the dev tools shows this

![image](https://user-images.githubusercontent.com/29356742/118263392-926d7480-b48c-11eb-8b5f-2b9e8d104561.png)

**Comment by Eskaan** [comment]
Does this issue persist in the newer versions?

**Comment by tiecia** [comment]
> Does this issue persist in the newer versions?

I no longer have access to the machine where the issue first occurred but it seems to be working fine now on a different machine with the newest version.

**Comment by Eskaan** [comment]
So can we close this issue?

**Comment by tiecia** [comment]
I guess so, it's now working fine for me.

**Comment by yokisniff** [comment]
ok so is it solved? i tried again and it did the same thing.

**Comment by Eskaan** [comment]
Did it work? Otherwise reopen the issue and provide logs please :)

**Comment by yokisniff** [comment]
no it doesnt :( have any suggestions?

**Comment by lubbermouse** [comment]
I am having this issue and the console says GET file:///C:/Users/lubbe/AppData/Local/Programs/gdlauncher/resources/app.asar/build/manifest.json net::ERR_FILE_NOT_FOUND
