### ISSUE TITLE
Be able to drag zips into the launcher to quickly install them

### ISSUE THREAD

**Issue by colebob9** [gorilla-devs/GDLauncher#762]
**Is your feature request related to a problem? Please describe.**
GDLauncher does not currently allow for adding custom .zip file via dragging them into the "Add New Instance" menu. The only way to select a local .zip file currently is to use the browse button. Currently, direct download links can be dragged into the import text box this way.

**Describe the solution you'd like**
I think it should be possible to drag a zip into GDLauncher, and have it automatically go to the instance setup menu.

**Describe alternatives you've considered**
I would prefer to be able to drag in from anywhere in the launcher, as it would be almost the only context for doing so (excluding what I said in Additional context), but it would make sense if this only worked inside of the "Add New Instance" menu.

**Additional context**
Personally, I would like to see this kind of interaction throughout the launcher (ex: resource packs, individual mods, etc.), but importing an instance is the larger priority. I think this change would make the launcher more intuitive and faster to use.

**Comment by chlorinezorine** [comment]
Apologies, this is a duplicate of #735. Closing.
