### ISSUE TITLE
Cannot acces JRE when installed through snap

### ISSUE THREAD

**Issue by QazCetelic** [gorilla-devs/GDLauncher#763]
**Describe the bug**
I installed it through snap but GDLauncher doesn't seem to be able to acces /usr where the JRE is located. Autodetect fails too.

**To Reproduce**
1. Settings > Java
2. Turn off 'Autodetect Java Path'
3. Put path in text field
4. Click file button that should bring you to the folder
5. Nothing happens
6. Attempt to manually navigate to /usr
7. "Error opening directory '/usr': Permission denied"

**Expected behavior**
That it has acces to the JRE

**Possible solutions**
Use snap classic mode, this provides full acces to the system. [Explaination video](https://www.youtube.com/watch?v=GZhbJ44q4Lk)

**Operating System:**
 - OS: Linux (KDE Neon)
 - Version 5.20

**Comment by Eskaan** [comment]
Duplicate of #727

**Comment by Eskaan** [comment]
Same cause of the problem
