### ISSUE TITLE
Including modlist.html file in export.zip

### ISSUE THREAD

**Issue by Shorepion** [gorilla-devs/GDLauncher#767]
**Is your feature request related to a problem? Please describe.**
Nl, its just something nice to have.

**Describe the solution you'd like**
Basically the feature the CF Launcher offers to add a modlist.html which opens a webpage with all the contained mods + cf pepject links.

**Describe alternatives you've considered**
-

**Additional context**

**Comment by Eskaan** [comment]
Duplicate of #703

**Comment by Eskaan** [comment]
Fixed by a30a615
