### ISSUE TITLE
Maximize button functionality broken on smaller screens

### ISSUE THREAD

**Issue by zabi94** [gorilla-devs/GDLauncher#77]
**Describe the bug**
On smaller screens the launcher exceeds the height of mouse-reachable space, making it impossible to resize vertically. This also seems to break the maximize button on the title bar.
The problem fixes itself when enough space becomes available (eg, moving the dock on the left side of the screen leaves enough space for the launcher to fully display vertically. Maximize button starts working again)

**To Reproduce**
Get Linux and a short screen, launch, try and maximize

**Expected behavior**
The launcher should check for the screen size at launch and resize properly depending on it

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Chrome 67.0.3396.99 (Build ufficiale) (a 64 bit)

**Comment by blarfoon** [comment]
Is it fixed now?
