### ISSUE TITLE
Preset Small Pack of Icons for Custom Instances

### ISSUE THREAD

**Issue by CapoFantasma97** [gorilla-devs/GDLauncher#773]
Vanilla Minecraft Launcher has a selection of icons of various blocks in order to help customize and distinguish the various instances and versions graphically.

In GDLauncher there is only one preset icon for custom instances: a stylized grass block.
To have more of them, the user has to create them on their own in the form of images.

Just like the vanilla launcher, it would be nice to have a few icons to choose from to quickly and easily distinguish and customize the instances graphically, for the average user that doesn't need or can make them on their own.

**Comment by Ladvace** [comment]
maybe in the future we can add that feature, add the moment you can  upload your custom image
