### ISSUE TITLE
Forge download stuck at 2%

### ISSUE THREAD

**Issue by pjc21** [gorilla-devs/GDLauncher#776]
Not able to download any version of forge, gets stuck around 2% 

**To Reproduce**
1. Create a new instance any MC version and any forge version
2. Downloading forge installer - stuck at 2%

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/4660190/106593034-63e62080-65a4-11eb-8213-712f1b1a6ce8.png)

**Operating System:**
- Windows 10
- Also same on windows 8.1 

**Additional context**
Have been using launcher for a little while now & was talking a new user through the process of using this launcher, they responded that it was stuck at 2%. Attempted to create several test instances using different versions of forge I have not previously installed and had the same issue with all tests.  

I have checked the forge website and can manually download fine
Also tested with MultiMC and can download forge fine.

**Comment by takashi1kun** [comment]
I also have this issue, also w10.

**Comment by Summonsays** [comment]
Also having this issue Windows 7.

**Comment by FuzzyFoxe** [comment]
I was about to say that I was having the same issue, but it seems to have worked itself out?

**Comment by pjc21** [comment]
> I was about to say that I was having the same issue, but it seems to have worked itself out?

Yes can confirm it is now working ok again.
