### ISSUE TITLE
microsoft account token not persistent

### ISSUE THREAD

**Issue by the-ashh** [gorilla-devs/GDLauncher#779]
**Describe the bug**
when signing in with a microsoft account, every day or so i have to reenter in my microsoft account login details, as GDL says that my token has expired. this problem does not happen with my mojang account. 

**To Reproduce**
1. sign in with microsoft account in the beta build
2. wait a day or so
3. ?????
4. ~~profit~~ have to relog into microsoft account

**Expected behavior**
not having to log in every day.

**Possible solutions**
either see if there is a way to make that login token persistent, or make the in-app browser accept cookies so one doesn't have to keep entering in their login information

**Operating System:**
- arch linux using appimage build
- windows 10 20h2 19042.746

**Additional context**
this is on the beta branch, as that is the only branch that you can sign in with a microsoft account.

**Comment by EnzoAlbornoz** [comment]
I think the master branch (build from source) fixed it, but it wasn't released in beta branch yet. I changed the login method from "spa" to "native". "SPA" tokens can't live longer than 24 hours, but "Native" tokens do.

**Comment by mridulganga** [comment]
Might be slightly out of context, but is there any planned beta releases soon?
Would really like this fix - it is a bit annoying to login to Microsoft account everyday.

Is there a easy way to apply a patch to an existing installation?

**Comment by Eskaan** [comment]
Fixed whit #741 e4e6fc7a - (aedff4d0)
