### ISSUE TITLE
Snapshots are shown first

### ISSUE THREAD

**Issue by zabi94** [gorilla-devs/GDLauncher#78]
**Is your feature request related to a problem? Please describe.**
When creating a new vanilla instance, the first available versions in the drop-down menu are snapshots.

**Describe the solution you'd like**
Ideally only release-type versions should be displayed by default. Snapshots should be enabled in some setting, and only shown *after* the releases anyways

**Additional context**
Tried on Ubuntu 18.04

**Comment by blarfoon** [comment]
Shapshots are now hidden by default. To show them, users need to check a checkbox while creating the instance.
