### ISSUE TITLE
Duplicate Instance Option

### ISSUE THREAD

**Issue by yonderbread** [gorilla-devs/GDLauncher#780]
**Is your feature request related to a problem? Please describe.**
In a way, it would make things easier and faster.

**Describe the solution you'd like**
A context menu option when right clicking a Minecraft instance to be able to duplicate it.

**Describe alternatives you've considered**
Just copying and pasting the instance folder.

**Comment by Eskaan** [comment]
Done in #1002 e6397e28

**Comment by yonderbread** [comment]
> Done in #1002 [e6397e2](https://github.com/gorilla-devs/GDLauncher/commit/e6397e280a0b31ab829e70052510304a50da4e7f)

Thank you for your contribution, I will definitely be using this feature :)

**Comment by Eskaan** [comment]
Not mine ;)

**Comment by yonderbread** [comment]
Ah whoops, shoulda read the commit info. Thanks @hypherionmc and @killpowa!
