### ISSUE TITLE
Sorting options

### ISSUE THREAD

**Issue by iam-cult** [gorilla-devs/GDLauncher#781]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
An option to change the order your instances are listed in, between alphabetically, time played, and most recent

**Describe alternatives you've considered**
N/A

**Additional context**
This is low priority, but I think it would be helpful

**Comment by zediious** [comment]
I stand heavily by this. #1 feature needed in my mind.

**Comment by Eskaan** [comment]
Duplicate of #636
