### ISSUE TITLE
Client automatically updating / getting rid of Microsoft Login

### ISSUE THREAD

**Issue by Kry0hh** [gorilla-devs/GDLauncher#782]
Not sure if this is know, and I know it's a beta feature, but just wanted to report it just in case. I play with a Microsoft account so I'm using the beta version that was posted awhile ago which includes a Microsoft login feature. For some reason, every 1-2 days I get an authentication error trying to connect to my Minecraft server, and I have to relaunch to re authenticate. When I relaunch, the microsoft login feature is gone, and I have to remove the appimage, go back to the page, and download it. It happens consistently nearly every day. 

**Steps to reproduce the behavior:**
1) Play game regularly until you need to restart to reAuth
2) Microsoft login feature gone on relaunch

**Expected behavior**
Microsoft login remains available on relaunch.

**Possible solutions**
Not quite sure, it seems like it's force-updating though? Since my appimage is renamed from the beta version (1.0.10 Beta 2), into the newest version (1.0.11) every time it happens. Although, I never get any sort of update prompt, and I'm never shown any sort of updating process.

 - OS: Manjaro Linux (Arch-based)
 - Version: 20.2.1 Release

**Comment by Lennster1** [comment]
You need to change your release channel to beta. That should help.

**Comment by Kry0hh** [comment]
@Lennster1 My god I can't believe I didn't see that in the options... Literally the first thing too lol thanks a ton!

**Comment by Lennster1** [comment]
> @Lennster1 My god I can't believe I didn't see that in the options... Literally the first thing too lol thanks a ton!

No problem

**Comment by Lennster1** [comment]
Lol im actually new to coding but I know some stuff

**Comment by Eskaan** [comment]
Duplicate of #952

**Comment by Eskaan** [comment]
Fixed whit #741 e4e6fc7a - (aedff4d0)
