### ISSUE TITLE
Modpacks not launching 

### ISSUE THREAD

**Issue by mlggamer17** [gorilla-devs/GDLauncher#783]
I click play on R.A.D modpack and it shows a green play button and then just nothing happens

**Comment by TheMarksmanXII** [comment]
It might take a sec, I know RAD is Forge, but sometimes Fabric instances take a sec to open, so maybe it's the same with large Forge instances? Just wait. It can take up to 2 min if I had to guess.

**Comment by Eskaan** [comment]
1) More information please
2) Does the issue still persist

**Comment by Eskaan** [comment]
@mlggamer17
