### ISSUE TITLE
Fixed missing instances, but now crashing when loading world or just sartying up a modpack

### ISSUE THREAD

**Issue by chikenjoe117** [gorilla-devs/GDLauncher#787]
So first my game froze and I had to hard reset my PC.
When I started GDLaucher again the modpack wasn't there, fixed that by replacing the config.json file with one from a fresh install
(The on in the modpack that crashed was full of "null")

But now the game is crashing when either the game is loading the world, or when the launcher is starting a modpack

The error I'm getting is

Error: signal exits  Code: 4294967295

Error Log:
Feb 15, 2021 10:52:44 PM goblinbob.mobends.core.bender.EntityBenderRegistry registerBender
INFO: Registering mobends-player
Feb 15, 2021 10:52:44 PM goblinbob.mobends.core.bender.EntityBenderRegistry registerBender
INFO: Registering mobends-minecraft:zombie
Feb 15, 2021 10:52:44 PM goblinbob.mobends.core.bender.EntityBenderRegistry registerBender
INFO: Registering mobends-minecraft:skeleton
Feb 15, 2021 10:52:44 PM goblinbob.mobends.core.bender.EntityBenderRegistry registerBender
INFO: Registering mobends-minecraft:zombie_pigman
Feb 15, 2021 10:52:44 PM goblinbob.mobends.core.bender.EntityBenderRegistry registerBender
INFO: Registering mobends-minecraft:spider
Feb 15, 2021 10:52:44 PM goblinbob.mobends.core.bender.EntityBenderRegistry registerBender
INFO: Registering mobends-minecraft:squid
Feb 15, 2021 10:52:44 PM goblinbob.mobends.core.bender.EntityBenderRegistry registerBender
INFO: Registering mobends-minecraft:wolf
AL lib: (EE) alc_cleanup: 1 device not closed

I've looked around for a solution but couldn't find anything to help.
This may be because I don't know much about coding and could've read the solution and not understood it

**Comment by huantianad** [comment]
I'm currently getting the same error when joining a world in GreedyCraft.

**Comment by Eskaan** [comment]
Does this issue still persist and if yes, is it Minecraft or Launcher related?

**Comment by chikenjoe117** [comment]
No, I don't remember what I did to fix it, but I got it fixed.

Sent from Yahoo Mail on Android 
 
  On Tue, Apr 27, 2021 at 8:41 AM, ***@***.***> wrote:   


I'm currently getting the same error when joining a world in GreedyCraft.

**Comment by huantianad** [comment]
I can perhaps try it with GreedyCraft to see if I can reproduce it again, but it would help to know if the problem is due to the pack and not GDLauncher

**Comment by Eskaan** [comment]
@huantianad tried?
If it worked I would close this

**Comment by Eskaan** [comment]
Thanks
