### ISSUE TITLE
Clear downloads button

### ISSUE THREAD

**Issue by zabi94** [gorilla-devs/GDLauncher#79]
**Is your feature request related to a problem? Please describe.**
When creating a new instance, the download progress is shown as a download notification on the left. There is no way of clearing the notifications for completed downloads.

**Describe the solution you'd like**
"Dismiss" and "Dismiss all" buttons (maybe as a cross near the download?)

**Comment by blarfoon** [comment]
The download list has been removed. Now all downloads are only shown in the "Instances" page.
