### ISSUE TITLE
Only 1gb of ram being allocated no matter how high the slider is

### ISSUE THREAD

**Issue by Twigglestick** [gorilla-devs/GDLauncher#797]
Hi Everyone

not sure what im going to get out of this but my mate and i want to play valhelsia 3 together but his game is only allocating 1gb of ram, no matter how much you allocate in the GDlauncher. would just like to know if anyone has any fixes to this issue.

i've tried for hours to fix it myself over a call but no luck, even installed the launcher myself to see if it was a client thing but apears not to be. would much appreciate any help, thanks :D

**Comment by TOLoneWolf** [comment]
How to remove _JAVA_OPTIONS environment variable for windows

windows key+R (opens the run window)
type in: sysdm.cpl
click ok
click the advanced tab on the top.
click the environment variables button.
remove the _JAVA_OPTIONS environment from the user and system environment  variables if they exist.
restart gdl if it was open.

that should fix your memory value not changing in gdl or any other java program.

**Comment by Twigglestick** [comment]
that worked...but when he updated it went back to 1gb, any suggestions

**Comment by Twigglestick** [comment]
> Hi Everyone
> 
> not sure what im going to get out of this but my mate and i want to play valhelsia 3 together but his game is only allocating 1gb of ram, no matter how much you allocate in the GDlauncher. would just like to know if anyone has any fixes to this issue.
> 
> i've tried for hours to fix it myself over a call but no luck, even installed the launcher myself to see if it was a client thing but apears not to be. would much appreciate any help, thanks :D

that worked but now when he updated it went back to 1gb and there is now no _JAVA_OPTIONS in enviroment variable, help please?

**Comment by TOLoneWolf** [comment]
Check the settings to make sure the increased ram setting is still there.
Restart computer and recheck if it still has the issue and no _JAVA_OPTIONS exists.

Copy the log after attempting to launch and post it.
