### ISSUE TITLE
Console dark theme removes console from use

### ISSUE THREAD

**Issue by TheWerdOfRa** [gorilla-devs/GDLauncher#798]
**Describe the bug**
Hi, I'm using 1.0.11 on Linux/Ubuntu from the official AppImage. 

I was poking around the console ( >_ ) settings and found that there was a theme for the console. I set it to "dark" and then the console disappeared. I clicked the console button again, nothing. I closed and re-opened GDLauncher, nothing. It is as if the console viewer is no longer functional at all. 

**Expected behavior**
Console is visible and intractable 

**Screenshots**
N/A

**Operating System:**
 - OS: Pop_OS! 
 - Version: 20.10

**Additional context**
I was trying to troubleshoot a mod-pack that kept having an unexpected shutdown causing this error:
AL lib: (EE) alc_cleanup: 1 device not closed

I do not think it is related to the issue, but it is the context in which I was poking around the console in the first place.

**Comment by TheWerdOfRa** [comment]
After multiple reboots it functioned again. Not sure what that means. I will monitor and close this if it remains stable.

**Comment by TheWerdOfRa** [comment]
Issue has not reproduced itself. Assume it was an issue outside of GDLauncher.

**Comment by BeetMacol** [comment]
I experienced it yesterday, except after a restart it works again, with dark theme.
