### ISSUE TITLE
Forge 1.7.10 and Fabric 1.16.5 crash

### ISSUE THREAD

**Issue by TheMarksmanXII** [gorilla-devs/GDLauncher#799]
**Describe the bug**
Some instances crash after the window opens, and sometimes the instance crashes immediately after start-up.

**To Reproduce**
1. Use GDLauncher v1.0.11
2. Create a Forge 1.7.10 instance or Fabric 1.16.5
2. Launch the instance
3. View the error code (Exception in thread "Render thread")

**Expected behavior**
The instance should have launched and ran. This did not used to happen with my Fabric 1.16.5 instances, but now it does with one, and with all of my Forge 1.7.10 instances.

**Screenshots**
![a](https://user-images.githubusercontent.com/72309481/109811436-d45e7c80-7bf8-11eb-883c-a9994cd42d58.png)

![e](https://user-images.githubusercontent.com/72309481/109811459-dc1e2100-7bf8-11eb-998c-26cff4c5a324.png)

Log: https://pastebin.com/brn7gw6b

**Operating System:**
 - OS: Windows
 - Version: 10

**Additional context**
I do not remember if the Forge 1.7.10 instance crashed with a different error code, but it might've. Please also tell me if this may be occurring because of a mod. Finally, I am using the automatic Java setup in GDLauncher.

**Comment by RemagOfficial** [comment]
we need a log, those screenshots dont mean anything

**Comment by TheMarksmanXII** [comment]
I added the log's Pastebin, it's under the screenshots.

**Comment by TheMarksmanXII** [comment]
Nvm, found it

**Comment by TheMarksmanXII** [comment]
OMG I'm so sorry this is because of roughly enough resources and not enough resources.
