### ISSUE TITLE
Can't import a previously exported pack

### ISSUE THREAD

**Issue by Asveste** [gorilla-devs/GDLauncher#808]
**Describe the bug**
I made a modpack for 1.7.10 and then exported it. A friend tried to import it but it stopped at 100%. The console gave the following log: https://pastebin.com/vxJFMRDR

**To Reproduce**
1. Download the attached .zip
2. Go to GDLauncher and import the .zip
3. Wait.
4. I don't know look in the console or something.

**Expected behavior**
I expected the modpack to successfully import itself with all the mods.

**Possible solutions**
I asked a friend and he said it PROBABLY has something to do with a wrong parameter, maybe missing quotation marks. He's not sure though, because he doesn't know a lot about minecraft, especially modded.

**Screenshots**
![Screenshot 2021-03-12 221519](https://user-images.githubusercontent.com/23436647/110999314-79f3b780-8380-11eb-99bb-24df438aa9c5.png)

**Operating System:**
 - OS: Windows
 - Version 10 (20H2)

**Additional context**
[Anthurium-2.2.zip](https://github.com/gorilla-devs/GDLauncher/files/6133001/Anthurium-2.2.zip)
This is the exported modpack file.

**Comment by Mattyb21** [comment]
Also having this problem.

Just for clarity sake, the import hangs right on your screenshot (Downloading game files 100%)

**Comment by Mattyb21** [comment]
@Asveste it seems like this is related to https://github.com/gorilla-devs/GDLauncher/issues/721 - fix is inside (correcting the forge version inside the manifest.json)

This workaround corrected this for me and the pack was able to get past the above screenshot

**Comment by Asveste** [comment]
> @Asveste it seems like this is related to #721 - fix is inside (correcting the forge version inside the manifest.json)
> 
> This workaround corrected this for me and the pack was able to get past the above screenshot

Yep, after doing this I was able to import it successfully. Thank you.
