### ISSUE TITLE
Turn off "time played" feature.

### ISSUE THREAD

**Issue by TheMarksmanXII** [gorilla-devs/GDLauncher#809]
**Is your feature request related to a problem? Please describe.**
I don't like the "time played" feature on GDLauncher, I don't want people to see how much I play something.

**Describe the solution you'd like**
I would like it if there was a setting to turn off how much time you've played an instance.

**Describe alternatives you've considered**
MultiMC is another modded Minecraft launcher that allows you to turn the feature off.

**Additional context**
![image](https://user-images.githubusercontent.com/72309481/111205915-22cb2e00-859e-11eb-9572-5be87fcfb6f7.png)

**Comment by ghost** [comment]
Who else sees your time played

**Comment by blarfoon** [comment]
You can manually change it from the config file, we won't support this feature as it is a really specific use case and not many people need this.
