### ISSUE TITLE
thumbnailUrl Issue

### ISSUE THREAD

**Issue by Waldleufer** [gorilla-devs/GDLauncher#810]
**Describe the bug**
Installation of some modpacks is impossible.

**To Reproduce**
Go to the latest Beta Version of GDLauncher (v 1.1.0-beta.2)
Add a new instance:
-> Twitch Tab 
Search for: "Life in the village 2"
-> click on Explore / Versions
CRASH!

(And if trying to directly install the latest version directly: Infinite Looping Loading icon.)

**Expected behavior**
The launcher to install the modpack.

**Operating System**
Windows 10

**Corresponding Error Log**
https://pastebin.com/4HpyakQc

**Comment by Gunner76th** [comment]
I am one of the admin/moderators for the modpack in question, and following the steps given above, using the launcher version specified, I am unable to recreate the claimed issue. Additionally, as the user is not running the launcher from the User Data Path that we have specified that users should use to avoid issues with our modpacks, I am recommending that this issue be marked as invalid and closed.

**Comment by Waldleufer** [comment]
The problem was actually originating from the invalid User Path, as the pathname did contain White Spaces and was too nested. 

Thank you for your support!
