### ISSUE TITLE
Can't start dev environment

### ISSUE THREAD

**Issue by whitebear60** [gorilla-devs/GDLauncher#813]
**Describe the bug**
After `npm i` I see an error. The terminal log can be found in `output.log` attached.

**To Reproduce**
1. Go to Clone GDLauncher repository
2. Run npm i
3. See error

**Expected behavior**
GDLauncher will build and be ready for development

**Operating System:**
 - OS: macOS
 - Version 10.10.0
 - Specs:
![PC Specs](https://i.ibb.co/KKbJ18X/Screen-Shot-2021-02-13-at-20-43-30.png)

Attachments:
[output.log](https://github.com/gorilla-devs/GDLauncher/files/6172814/output.log)
[2021-03-19T16_06_50_278Z-debug.log](https://github.com/gorilla-devs/GDLauncher/files/6172815/2021-03-19T16_06_50_278Z-debug.log)
[2021-03-19T16_06_50_471Z-debug.log](https://github.com/gorilla-devs/GDLauncher/files/6172813/2021-03-19T16_06_50_471Z-debug.log)

**Comment by Ladvace** [comment]
did you install rust?

**Comment by whitebear60** [comment]
> did you install rust?

Yes

**Comment by whitebear60** [comment]
rustc --version
rustc 1.50.0 (cb75ad5db 2021-02-10)

**Comment by whitebear60** [comment]
Maybe it is because I'm running macOS 10.10, which is not supported by new versions of Chromium and Electron?
