### ISSUE TITLE
Joining a Beta 1.7.3 server with a microsoft account sets username to "--width"

### ISSUE THREAD

**Issue by Necklaces** [gorilla-devs/GDLauncher#822]
**Describe the bug**
Joining a Beta 1.7.3 server with a microsoft account sets username to "--width"

**To Reproduce**
1. Have one of the new microsoft account for java edition, log in with that
2. Add new instance, select old beta -> b1.7.3
3. Try joining public server
4. Get kicked out with "Invalid characters in name"
5. Set up own beta server on localhost
6. Join localhost server
7. Type in chat
8. Name is now "--width"

**Expected behavior**
Name should be set to minecraft username

**Possible solutions**
Haven't researched enough, but assuming "--width" is the minecraft window width resolution, this might simply be fixable by adjusting the commandline parameters.

**Operating System:**
 - OS: GNU/Linux 

**Additional context**
Using v1.1.0-beta.2

**Comment by RemagOfficial** [comment]
that's a Minecraft bug, we cant fix that

**Comment by Necklaces** [comment]
Hm, well surely we can make the user experience a little better. MultiMC is somehow able to set the username when it launches the instance, I'm not sure how it does this though. I'd expect GDLauncher to at least set the username to the current account, like MultiMC does by default.

Edit: the same happens for non-microsoft accounts.

Edit 2: possibly fixed in #804

**Comment by TOLoneWolf** [comment]
This is not a minecraft issue and has to do with the launch parameters the launch is sending to older versions is invalid.

**Comment by Necklaces** [comment]
Fixed with the merging of #804
