### ISSUE TITLE
GDlauncher doesn't open

### ISSUE THREAD

**Issue by TurtleMeds** [gorilla-devs/GDLauncher#823]
**Describe the bug**
When I open gdlauncher, an error shows up

**To Reproduce**
1. try to open gdlauncher
2. see error

**Expected behavior**
I expected GDlauncher to open

**Possible solutions**
idk

**Screenshots**
![Screenshot 2021-03-26 131129](https://user-images.githubusercontent.com/76972146/112692092-9b9e7580-8e3b-11eb-861e-f22972c139a7.png)

**Operating System:**
 - OS: Windows
 - Version: 10

**Additional context**
I already downloaded and ran VC_redist.x86.exe and VC_redist.x64.exe
(and restarted my computer many times)

**Comment by Ladvace** [comment]
are you trying to opening the installed version or in dev?

**Comment by blarfoon** [comment]
You probably have an antivirus which is blocking our native workers. Can you try to disable it and see if that works?

**Comment by TurtleMeds** [comment]
I don't know what was happening but it was a problem with my computer and not GDlauncher
