### ISSUE TITLE
Install Resource Packs from Curseforge in GDLauncher

### ISSUE THREAD

**Issue by TheMarksmanXII** [gorilla-devs/GDLauncher#827]
**Describe the solution you'd like**
I'd like it if you could add a feature to browse and install resource packs as well as mods/modpacks from Curseforge.

**Describe alternatives you've considered**
Downloading a resource pack directly from Curseforge and using a shortcut to access the instances folder of GDLauncher to install the resource pack.

**Additional context**
I have a resource pack on Curseforge, I'd like to see it in GDLauncher.

**Comment by zachsai** [comment]
I agree, I have a modpack on curseforge and I would like to add resourcepacks to it. I cannot add resourcepacks through the overrides because it is not allowed. Adding this option would download the resourcepacks through the manifest, which would be wayyyy better!

**Comment by Eskaan** [comment]
Duplicate of #705
