### ISSUE TITLE
export override options

### ISSUE THREAD

**Issue by lublak** [gorilla-devs/GDLauncher#829]
**Is your feature request related to a problem? Please describe.**

Currently, the overwritten options are not exported.
Especially if your modpack has a minimum requirement, it can be useful to export these options.
- Override Game Resolution
- Override Java Memory
- Override Java Arguments

**Describe the solution you'd like**

I would like these to be included in the manifest.json and also read back into the launcher.

**Describe alternatives you've considered**

Currently I have a readme that describes how much it needs at least, and still often have to say: Please set the java flags like this and the memory like this.

**Comment by tristanpoland** [comment]
I would love to ee this feature added as well!

**Comment by RemagOfficial** [comment]
this would break curseforge compatibility
