### ISSUE TITLE
[v1.1.0-beta.2] There is an update button that downgrades to 1.0.11

### ISSUE THREAD

**Issue by ftzi** [gorilla-devs/GDLauncher#832]
**Describe the bug**
Downloaded the 1.1.0 beta to use the Microsoft account. There was a green update button, clicked it, launcher gets downgraded to LTS.

**To Reproduce**
1. Login in 1.1.0-beta.2 (linux .AppImage)
2. Create the MC instance
3. There will be a green update button.
4. It will downgrade to the 1.0.11 version. I had to download again the 1.1.0 beta.

**Expected behavior**
No update button to previous versions

**Possible solutions**
Looks like there is a comparison that if the current version don't match the LTS one, the update button will pop. There are npm semvar comparison packages that could be used, so the update button will only appear if the current version is older than the LTS one, to work with beta versions.

**Screenshots**

**Operating System:**
 - OS: Ubuntu
 - Version 20.10

**Additional context**

**Comment by ftzi** [comment]
And btw, really nice launcher! Bought Minecraft today to create my Modpack i've been doing for some days, and this launcher is not only the best one i've found, but the only one that works with Microsoft account. (also, the Twitch doesn't support linux. Really fuck it)

Congrats and thanks!

**Comment by blarfoon** [comment]
It should be fixed with the new release (1.1.1). Feel free to reopen if the issue persists
