### ISSUE TITLE
Manifest layout

### ISSUE THREAD

**Issue by zachsai** [gorilla-devs/GDLauncher#837]
**Is your feature request related to a problem? Please describe.**
The manifest produced by GDLauncher is much harder and uglier to read
**Describe the solution you'd like**
Produce a cleaner and easier to read manifest
**Describe alternatives you've considered**
This is what Curseforge's manifest looks like
![image](https://user-images.githubusercontent.com/63996164/114964535-eb6dcc80-9e3c-11eb-92f8-dcabc5713ba3.png)
and here is what GD's manifest looks like
![image](https://user-images.githubusercontent.com/63996164/114964570-00e2f680-9e3d-11eb-8cc5-0b2b13a90b5c.png)

**Additional context**

**Comment by RemagOfficial** [comment]
gdl just flattens the JSON, just unflatten it

**Comment by zachsai** [comment]
> gdl just flattens the JSON, just unflatten it

how would I do that?

Also wished we could download resourcepacks through GDLauncher so they show up in the manifest

**Comment by blarfoon** [comment]
Visual studio code can do that. We're not gonna prettify it
