### ISSUE TITLE
Can't Make a New Instance

### ISSUE THREAD

**Issue by slenderknight1** [gorilla-devs/GDLauncher#841]
Hello, lately there was is a bug in the launcher that stops the user from creating new instances and I don't really know why because it's also happening to my friends as well.

**Comment by TrueCP6** [comment]
I'm experiencing a similar issue when clicking the add instance button in the bottom left.
![image](https://user-images.githubusercontent.com/39642832/115342671-e6957980-a1aa-11eb-8ffb-fe1d8196ec34.png)
This issue is present on the latest stable release and the latest beta release.

**Comment by TOLoneWolf** [comment]
https://github.com/gorilla-devs/GDLauncher/blob/master/src/app/desktop/utils/index.js#L220

![image](https://user-images.githubusercontent.com/8376628/115348865-c6e55d80-a178-11eb-95b9-fe5b8ad30617.png)

**Comment by TOLoneWolf** [comment]
fix should be deployed later today ish.

**Comment by slenderknight1** [comment]
That's good to know thanks

**Comment by PlatinumPlanet** [comment]
> 
> 
> fix should be deployed later today ish.

Thanks

**Comment by JoniHoffi** [comment]
When is this fixed?

**Comment by blarfoon** [comment]
Release candidate is in testing, the update should come in 8h or so

**Comment by blarfoon** [comment]
It should be fixed with the new release (1.1.1). Feel free to reopen if the issue persists
