### ISSUE TITLE
I can't create a new Instance

### ISSUE THREAD

**Issue by LordM4x** [gorilla-devs/GDLauncher#844]
When i click create new instance i get this error
![image](https://user-images.githubusercontent.com/82895323/115426161-90532580-a200-11eb-9f60-690b36c836d9.png)

1. Click the create new instance button
2. NO

**Operating System:**
im using win10 and the newest version of GDlauncher

I saw another thread just load in with answers already

**Comment by AshtakaOOf** [comment]
the devs are aware of that and there will be an update in no time

**Comment by TOLoneWolf** [comment]
Duplicate of #841
