### ISSUE TITLE
Instance won't launch, nor can new instances be created.

### ISSUE THREAD

**Issue by protoelectric** [gorilla-devs/GDLauncher#846]
**Describe the bug**
When trying to launch an instance, upon clicking play, nothing happens, When you try to add a new instance, it just shows the error screen.

**To Reproduce**
1. Open GDLauncher
2. Click on Click on any instance
3. Nothing happens

**Expected behavior**
The instance would be launched.

**Possible solutions**
I don't
**Screenshots**
N/A

**Operating System:**
 - OS: Windows 10
 - Version: Latest

**Additional context**
None

**Comment by TOLoneWolf** [comment]
new instance issue is duplicate of #841

running preexisting instances idk if that is because of missing forge manifest data that is causeing that to fail as well.

**Comment by blarfoon** [comment]
It should be fixed with the new release (1.1.1). Feel free to reopen if the issue persists
