### ISSUE TITLE
Impossible to see "installed version" ...

### ISSUE THREAD

**Issue by Uginsecond** [gorilla-devs/GDLauncher#847]
**To Reproduce**
1. Go to any installed modpack
2. Right click on him
3. Choose "manage" and next - "modpack"
4. ![GDLauncher_210421133535](https://user-images.githubusercontent.com/34199861/115540335-a9161680-a2a6-11eb-9d80-d3f8bcc6f9dd.png)
5. ![GDLauncher_2](https://user-images.githubusercontent.com/34199861/115540739-fd20fb00-a2a6-11eb-89dc-cbf4987f3c35.png)

**Comment by Bass2style** [comment]
in addition : 

when you want to "switch version", mods, configs, etc are deleted to "update", and nothing is downloaded. folders are empty.

there is also an issue when you try to update Forge, forge is downloading, seems patching, and then nothing happens. it stay on the previous version of Forge.

**Comment by Uginsecond** [comment]
Now, after 1.1.2 update - all ok.
