### ISSUE TITLE
Version 1.1.1 isn't importing mods from the manifest

### ISSUE THREAD

**Issue by judicius** [gorilla-devs/GDLauncher#849]
**Describe the bug**
Exporting a pack from GDLauncher, which creates a manifest file with project id's listed. Upon importing the zip, GD Launcher is not actually reading or using the manifest as the instances are being created without any mods.

**To Reproduce**
1. Go to any instance and export the instance
2. Import that new export to a new instance.

**Expected behavior**
Imported zip to drive GD Launcher to download and install the mods listed in manifest

**Possible solutions**
n/a

**Screenshots**

**Operating System:**
 - OS: Windows
 - Version 10

**Additional context**
Update version 1.1.1 of GD Launcher. Was working without issue under older version.
Downloading a pack from Curseforge seems to work perfectly fine.
Importing old custom exports that worked, no longer works. It seems to be an issue with the import.
Export Test attached.
[Builder Delight 2 for 1.16.5-1.9.2.zip](https://github.com/gorilla-devs/GDLauncher/files/6351969/Builder.Delight.2.for.1.16.5-1.9.2.zip)

**Comment by balloonhead** [comment]
having the same problem here. Cannot import a pack with mods.

**Comment by Spaig** [comment]
Same problem, same symptoms, same versions.

**Comment by Ladvace** [comment]
I just fixed that in a PR

**Comment by Mysticpasta1** [comment]
Just had this problem too.

Windows 10
Version v1.1.1
