### ISSUE TITLE
Updating Forge version in existing instance not working.

### ISSUE THREAD

**Issue by KajesLorian** [gorilla-devs/GDLauncher#850]
Every time I attempt to update my instance from 1.16.4 to 1.16.5 it will attempt to do so but will not succeed. It downloads the game files and says it patching Forge, but when it's complete nothing has changed.

**To Reproduce**
1. Right-click Instance
2. Click Manage
3. Click the gear for either Minecraft version or Modloader version
4. Change version from 1.16.4 35.1.36 to 1.16.5 36.1.0
5. Click arrow in bottom right to apply

**Expected behavior**
That my 1.16.4 instance will update to 1.16.5, modloader version 36.1.0

**Operating System:**
Windows 10

**Additional context**
Using GDLauncher v1.1.1

**Comment by therealeric** [comment]
I am having the same issue.  Trying to go to Forge 36.1.4 from 36.1.4.

Windows 7
GDLauncher v1.1.1

**Comment by ghost** [comment]
Same issue here on Linux using v1.1.1

**Comment by leyxcx** [comment]
having the same issue trying to go from 36.1.0 to 36.1.6

windows 10
v 1.1.1

**Comment by M3RGeo** [comment]
Having same issue trying to update from forge 36.1.4 to 36.1.6.

**Comment by Ladvace** [comment]
I just pushed a fix yesterday for that

**Comment by ghost** [comment]
Now it no longer displays any Forge versions, only the installed Minecraft version:

![image](https://user-images.githubusercontent.com/51542538/115897455-0edadd80-a422-11eb-8fc0-6121503fc575.png)

**Comment by Elfinlocks** [comment]
Reaffirming that this exact issue is present for me as well, as of this morning with the latest update available. This is occurring on Forge 36.1.2, in case that is relevant information.
