### ISSUE TITLE
GDlauncher crashes on create / cannot update modpack or app

### ISSUE THREAD

**Issue by swardhagen** [gorilla-devs/GDLauncher#859]
**Describe the bug**
I am on Macbook Pro running Big Sur. When I click "create instance" the app crashes and leaves the "ran into a creeper and blew up"-message, and when I try to update a pack it gets stuck on 100% forever, see screenshots
<img width="1093" alt="Screenshot 2021-04-22 at 11 29 56" src="https://user-images.githubusercontent.com/33746229/115693430-336e8100-a360-11eb-90cd-157e0b3e974b.png">
<img width="188" alt="Screenshot 2021-04-22 at 12 37 07" src="https://user-images.githubusercontent.com/33746229/115701026-a0394980-a367-11eb-9eac-1be8c2e2d565.png">

The downloading gets stuck forever and if I force quit the app and load it upp again I can't play the modpack, nothing happens when I press play. I have no idea how to fix this. I've had no issues with GDlauncher until I tried to install the Parasites-modpack from ForgeLabs and that wouldn't start so I deleted the instance and since then I can't create a new instance. Don't know if those things are related. Can I re-install the launcher without losing my current instances?

**To Reproduce**
1. Click the "plus"-icon in the bottom left corner. 
2. Click "Create Instance"
3. The app crashes with the following message:
https://ibb.co/9Gz5JWX

1. Update a modpack
2. The update gets stuck on "Downloading new files" forever
3. If I restart the pack it looks like it's done but nothing happens when I press play

1. Go into settings
2. Press "Update" at the bottom
3. The window closes but the app stays open, I have to manually exit the app and it has not been updated

**Operating System:**
 - Macbook Pro running Big Sur 11.2.3

**Comment by Ladvace** [comment]
issue fixed in the 1.1.1 version

**Comment by swardhagen** [comment]
So I backup the save files and remove the app to download it again, then?

**Comment by swardhagen** [comment]
I backed up the save files, removed the app via app cleaner and reinstalled GDlauncher, now it lets me update the packs, thanks!
