### ISSUE TITLE
How do I update the Forge Modloader version?

### ISSUE THREAD

**Issue by therealeric** [gorilla-devs/GDLauncher#864]
The Minecraft Version button, the Modloader and the modloader version button all take you to the Minecraft version screen.

How do I update the Forge Modloader to a newer version, 36.1.4 to 36.1.6?  The choice to go to a different Forge modloader version number is now gone.

Minecraft 1.16.5
Forge 36.1.4
Windows 7 Pro

**Comment by ghost** [comment]
the minecraft version screen is where you change the modloader version, also have you read the discord announcement?

**Comment by therealeric** [comment]
Yea!  It's back!

Working perfectly...

Thank you.

**Comment by pleasehugme** [comment]
I have encountered an error: I am unable to update Forge to a version a mod requires. Do I downgrade the mod and all of its derivative addons?
