### ISSUE TITLE
Download instance stuck at 100%

### ISSUE THREAD

**Issue by elrepeposo** [gorilla-devs/GDLauncher#865]
Basically what says in the title, heres the log:

Error: ENOENT: no such file or directory, open 'E:\Games\Minecraft\instances\MC Eternal\config.json'
(anonymous) @ actions.js:2141
asyncToGenerator.js:6 Uncaught (in promise) TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124)
    at Object.join (path.js:375)
    at actions.js:1122
    at l (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at n (asyncToGenerator.js:3)
    at s (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)

![image](https://user-images.githubusercontent.com/60124018/115893120-3b94f200-a42e-11eb-968d-cc0477ea677c.png)

**Comment by Kylatia** [comment]
I've gotten the same error from several different mod packs.  My version of GD launcher is 1.1.1

**Comment by NightHammer1000** [comment]
Same

**Comment by therealeric** [comment]
I appear to have joined your group of "being stuck at 100%".

I am attempting to install an "exported instance" that I created myself in GDLauncher.

GDLauncher v1.1.1
Windows 7 Pro

**Comment by srnyx** [comment]
Everyone who sees this thread, please read `#announcements` in GorillaDevs' Discord: https://discord.gg/ZxRxPqn

**Comment by therealeric** [comment]
Please just post the announcement in this thread.  The Discord will not let me in.

**Comment by srnyx** [comment]
> Please just post the announcement in this thread. The Discord will not let me in.

![image](https://user-images.githubusercontent.com/25808801/115917246-eebc1600-a443-11eb-83ed-03539f6510b0.png)

**Comment by therealeric** [comment]
Thank you.

________________________________

**Comment by hron84** [comment]
@killpowa @jrester thank you very much the really fast fix. I never experienced this kind of support from an opensource project. I'm really appreciate it. Being a part of this kind of community is a honor.
