### ISSUE TITLE
Launcher not downloading required libraries/mods automatically

### ISSUE THREAD

**Issue by maicol07** [gorilla-devs/GDLauncher#869]
**Describe the bug**
GDLauncher doesn't download automatically a required lib or mod 

**To Reproduce**
1. Create a new modpack (Forge 1.16.5 last version)
2. Add a mod that requires a lib (for example minecolonies)
3. Try to start the pack
4. Forge error where requires its lib (structurize)

**Expected behavior**
Downloading a mod that requires a library also downloads that library

**Operating System:**
 - OS: Windows
 - Version 10

**Comment by blarfoon** [comment]
Fixed and will be released soon
