### ISSUE TITLE
Instance suddenly missing from GUI; the rest are still there.

### ISSUE THREAD

**Issue by emkirsh** [gorilla-devs/GDLauncher#885]
**Describe the bug**
My instance that I was using just earlier today seems to have disappeared from the launcher. It is still in the gdlauncher_next/instances folder. I tried restarting GDLauncher multiple times, and I moved the folder out of the instances folder, turned GDLauncher off and on, moved it back and turned it off and on again. 

It also seems to recognize it to an extent, because I tried making a new instance with the same name and it said "an instance with this name already exists." Then why doesn't it show up in the GUI?!?!?!?

**To Reproduce**
To be perfectly honest, I don't think there's a clear-cut method to causing it to happen. GDLauncher has been working fine for months, and suddenly it's broken. But for the sake of following the template,
1. Use GDLauncher normally
2. update GDLauncher
3. it works normally
4. the one instance you wanted to use (and that you used earlier today) is suddenly gone from the gui; the rest are still there.
5. restart gdlauncher
6. move folder out of instances folder
7. restart gdlauncher again
8. move folder back to gdlauncher instances folder
9. restart again
10. ~~throw computer out the window~~
11. make bug report

**Expected behavior**
It works normally and I click on my instance and start playing.

**Possible solutions**
Well, I already mentioned having tried moving it out of the instances folder and back, but it not working.

**Screenshots**
[Here is a screen recording of the issue and my failed attempts at troubleshooting it.](https://gyazo.com/c93e68287599d744b353b4517a3dd4a8)

**Operating System:**
 - OS: Windows 10
 - Version 20H2

**Additional context**
No files seem to be missing; it just appears to be invisible or something.

**Comment by blarfoon** [comment]
Hopefully fixed by https://github.com/gorilla-devs/GDLauncher/commit/c5c3c6ad4c263bb19f74e332598d444be3ff6c04
