### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'C:\Users\[NAME]\AppData\Roaming\gdlauncher_next\datastore\libraries\net\minecraft\1.16.5.json'

### ISSUE THREAD

**Issue by Errorcrafter** [gorilla-devs/GDLauncher#892]
**Describe the bug**
i cant open the game anymore. whenever i do, it gives me this error:
```
Error: ENOENT: no such file or directory, open 'C:\Users\[NAME]\AppData\Roaming\gdlauncher_next\datastore\libraries\net\minecraft\1.16.5.json'
```

**To Reproduce**
1. open gddlauncher
2. have a 1.16 fabric installation
3. no matter how many times you click play nothing happens

**Expected behavior**
the game actually works

**Possible solutions**
idfk, there s a 1.12.json in the folder path in the error but no 1.16.5.json. i just started getting this error today so im really confused

**Screenshots**
![image](https://user-images.githubusercontent.com/69189354/117255264-0354d100-ae7c-11eb-9fc6-f4903ada12cd.png)
![image](https://cdn.discordapp.com/attachments/795837316639621120/839754102308732938/unknown.png)

**Operating System:**
 - windows 10
 
**Additional context**

**Comment by Errorcrafter** [comment]
@gorilla-devs

**Comment by steilerDev** [comment]
Can confirm this behaviour.
