### ISSUE TITLE
Required Mod Dependency is no longer installed automatically

### ISSUE THREAD

**Issue by Charismara** [gorilla-devs/GDLauncher#893]
**Describe the bug**
Before the last GDLauncher update all required mod dependencies has been downloaded when downloading a mod. (for example Thermal Foundation has been downloaded if you download Thermal Expansion). This is no longer the case.

**To Reproduce**
1. Create a Forge 1.16.5 Profile
2. Download a Mod with a required dependency (for example Thermal Expansion)
3. No required dependency has been downloaded

**Expected behavior**
The required dependency should be downloaded too.

**Operating System:**
 - OS: Windows
 - Version 1.1.5

**Comment by Pikabyte** [comment]
Same here, it's really frustrating...it only happened on a recent update. How do I switch to an older version?

**Comment by Pikabyte** [comment]
Did some testing. The dependency downloading broke on version 1.1.2. It works fine in 1.1.1.

This is an error given in console:

Failed to load resource: the server responded with a status of 404 ()
createError.js:16 Uncaught (in promise) Error: Request failed with status code 404
    at e.exports (createError.js:16)
    at e.exports (settle.js:17)
    at XMLHttpRequest.d.onreadystatechange (xhr.js:62)

**Comment by rlnt** [comment]
This is actually software-breaking. That's some of the main reasons people are using this launcher and it doesn't work anymore or is even acknowledged by the devs.

**Comment by blarfoon** [comment]
Fixed and will be released soon
