### ISSUE TITLE
Download Fabric mod pack from FTB failed

### ISSUE THREAD

**Issue by Liguma** [gorilla-devs/GDLauncher#894]
**Describe the bug**
Downloading a fabric mod pack form FTP sticks on "Downloading fabric files ... 0%"

**To Reproduce**
1. Go to '+'
2. Click on 'FTB'
3. Select the "Cotton" mod pack
4. install

**Expected behavior**
install the mod pack

**Screenshots**
![image](https://user-images.githubusercontent.com/24432099/117457522-94de4480-af49-11eb-80e9-19966228242e.png)

![image](https://user-images.githubusercontent.com/24432099/117457844-ef77a080-af49-11eb-9fe1-a2d42abf15f4.png)

**Operating System:**
 - OS: windows 10
 - Version 1.1.5

**Comment by blarfoon** [comment]
Fixed and will be released soon
