### ISSUE TITLE
Importing fabric modpacks getting stuck

### ISSUE THREAD

**Issue by jakeismyname** [gorilla-devs/GDLauncher#895]
Currently importing fabric modpacks is broken due to GDLauncher failing to create a config.json for the new instance.

**To Reproduce**
1. Create a fabric modpack to export
2. Export the modpack
3. Import the modpack
4. GDLauncher will get stuck on the add new instance screen ![addnewinstance](https://user-images.githubusercontent.com/79329173/117546321-e2b18600-aff7-11eb-977a-858cce62e6fa.jpg)
these two errors will also be in the console ![uhoh](https://user-images.githubusercontent.com/79329173/117546198-3d96ad80-aff7-11eb-851c-9a5735b04278.jpg)

Tested importing packs in earlier version (1.0.11) and it worked perfectly, not sure what version the bug came up in.
Edit: after about 2 seconds more of testing it turns out only importing fabric modpacks is broken.

**Operating System:**
 - OS: Windows 10
 - Version: 20H2

**Comment by steilerDev** [comment]
Can confirm this issue.

**Comment by papuSpartan** [comment]
Getting the same issue on Arch Linux with the same error and steps of reproduction

**Comment by RemagOfficial** [comment]
this is most likely because the export format doesn't support fabric

**Comment by blarfoon** [comment]
Fixed and will be released soon
