### ISSUE TITLE
GDLauncher Mac version does not close when using the button to close a window or Command + Q

### ISSUE THREAD

**Issue by t-vee** [gorilla-devs/GDLauncher#898]
The process for GDLauncher remains running when the window is closed through the "x" button in the upper left and pressing Command + Q while using GDLauncher does not appear to do anything, either visually or in the backend. 

Closing the window and keeping the app running may be a feature, but closing the app when using the quit function would be appreciated. 

Using Big Sur version 11.2.3 with M1 chip
Launcher version v 1.1.5, no custom install

**Comment by swardhagen** [comment]
Same here, also on a mac with Big Sur.
