### ISSUE TITLE
Unable to QUIT on MacOS (v1.1.5)

### ISSUE THREAD

**Issue by icanhasjonas** [gorilla-devs/GDLauncher#899]
**Describe the bug**
Quit Menu Button is missing on MacOS (Possibly also the reason why `CMD` + `Q` is not working, and `CMD` + `H` for hiding the app)

**To Reproduce (A)**
1. Go to Menu
2. Click on (nope, quit is missing)

**To Reproduce (B)**
1. Hit `CMD` + `Q`

**Expected behavior**
On MacOS you're supposed to be able to quit from the menu or CMD+Q (as the menu shortcut). In the latest version this option is gone, and the only way to quit is to forcefully close the window.

**Possible solutions**
Reintroduce the QUIT menu

**Operating System:**
 - OS: MacOS
 - Version: 11.2.3

**Comment by Eskaan** [comment]
Having the Same Problem on MacOS 11.2.3, whitout M1 Chipset

**Comment by t-vee** [comment]
I don't know if I am supposed to comment but I have the same problem

**Comment by ArcusMG** [comment]
Also having this problem, Mac OS 11.3.1, intel CPU.

**Comment by dstoliker** [comment]
I'm only able to quit if I right click on the icon in the dock, but doing so results in a "GDLauncher quit unexpectedly" message.

**Comment by Eskaan** [comment]
Jes, on the Icon in the Dock you can close it, nur this Button is the Same than killing it in the taskmanager

**Comment by djcmike** [comment]
This issue persists on 1.1.7

**Comment by jcotton42** [comment]
Issue still present on 1.1.7 on macOS Big Sur 11.4

**Comment by dstoliker** [comment]
This is partially resolved in version 1.1.10.  The menu option to quit is now present, and CMD-Q quits, but doing so still results in a "GDLauncher quit unexpectedly" error.

**Comment by Eskaan** [comment]
This Issue is already resolved, Cmd + Q is added. Any other MacOS default shortcuts will be added whit this Pull request: #944

**Comment by Eskaan** [comment]
This is a duplicate of #898 
They were both opened on the same day.
