### ISSUE TITLE
Curse Modpack?

### ISSUE THREAD

**Issue by therealeric** [gorilla-devs/GDLauncher#905]
Why does the Launcher tell me that my Modpack is a Curse Modpack?

I'm not even a member of Curse to make a ModPack.

Windows 7 Pro
GDLauncher 1.1.5
Minecraft 1.16.5

**Comment by RemagOfficial** [comment]
please explain more

**Comment by therealeric** [comment]
[cid:afeca54d-f6a7-4f65-99c2-656644f64191]

________________________________

**Comment by therealeric** [comment]
https://imgur.com/a/OiiZ3Fx

**Comment by YoYoK3nny** [comment]
This happens to any pack that was either imported or installed via the "Add Instance" dialog.

**Comment by therealeric** [comment]
I see, thank you for explaining.
