### ISSUE TITLE
In discord rich presence, GD launcher only shows that I am idle, even though I have a modpack launched

### ISSUE THREAD

**Issue by xentipod** [gorilla-devs/GDLauncher#914]
**Describe the bug**
When Discord rich presence is enabled in GD launcher it only shows "Idle," even when you have a modpack launched.

**To Reproduce**
Go to GD launcher settings and enable Discord Rich Presence. Launch an instance. Open discord and click on your profile, see how it shows that you playing GD launcher. Then see how it shows that you are idle, even though you're playing a modpack.

**Expected behavior**
It should show that you're playing a certain modpack. 

**Possible solutions**
I do not know

**Screenshots**
![image](https://user-images.githubusercontent.com/70001656/119178105-e3eca500-ba32-11eb-880c-4327d28a6223.png)

**Operating System:**
 - OS: Pop OS
 - Version 20.04 LTS

**Comment by Duckyz95** [comment]
I think this might be a bug added in one of the recent updates. Discord used to detect the modpack I'm playing but that is no longer the case and just shows GDLauncher with the status being idle

**Comment by xentipod** [comment]
> I think this might be a bug added in one of the recent updates. Discord used to detect the modpack I'm playing but that is no longer the case and just shows GDLauncher with the status being idle

Perhaps, though it never worked for me in the first place.

**Comment by Nezarn** [comment]
it never worked for me either (I'm on windows)

**Comment by Mahlarian** [comment]
I use Ubuntu 20.04.2, and I have this issue where none of my instances are shown and that GDlauncher is always idling.

**Comment by hypherionmc** [comment]
Added in the latest releases :)
