### ISSUE TITLE
Can't Download FTB modpacks

### ISSUE THREAD

**Issue by PassiveLemon** [gorilla-devs/GDLauncher#921]
**Describe the bug**
You cant download FTB modpacks.

**To reproduce**
1. Click the add modpack button
2. Click on FTB
3. Download FTB modpack
4. Watch as it gets stuck at 100%

**Expected behavior**
It should just download like other modpacks.

**Actual behavior**
It just doesn't ever complete.

**Possible solutions**
I don't know

**Screenshots**
![stuck](https://user-images.githubusercontent.com/72527881/119909484-faa76600-bf22-11eb-9021-d0d494e19c15.PNG)

**Operating system**
 - OS: Windows x64
 - Version 20H2

**Additional context**
I have tested this with Stoneblock 2, Skyfactory 3 and Revelation but they all do the same. Curseforge and custom modpacks work just fine. If you make a FTB modpack in curseforge and then export it to GDL, it has the same result where it gets stuck.

**Comment by PassiveLemon** [comment]
I found a work around. Download these modpacks through the curseforge option rather than FTB.

**Comment by Irgendwer01** [comment]
@PassiveLemon This isn't a real workaround since FTB Packs **not** get updated anymore on Curseforge, only FTB Launcher
