### ISSUE TITLE
[1.1.7] Can't unfocus "update all mods"

### ISSUE THREAD

**Issue by ocram9** [gorilla-devs/GDLauncher#926]
**Describe the bug**
A very small UI bug, when you click on the three dots in the mods tab you get the "update all mods" option. However you can't unfocus it by clicking somewhere else.

**To Reproduce**
1. Go to the mods tab of an instance
2. Click on the small dots next to the folder icon
3. Try to click on the dots or anywhere else that doesn't close the mods list

**Screenshot**
![Screenshot_33](https://user-images.githubusercontent.com/49008532/120251222-27d87900-c281-11eb-8c35-915ffb4a3f1b.png)

**Operating System:**
 - OS: Windows
 - Version 10

**Comment by ghost** [comment]
I'm also seeing this minor bug using 1.1.7 on Linux.
