### ISSUE TITLE
Error on launcher startup

### ISSUE THREAD

**Issue by KnewOne** [gorilla-devs/GDLauncher#929]
**Describe the bug**
Error on launcher start.

**To Reproduce**
1. You wouldn't believe

**Expected behavior**
A good day and absolutely no errors

**Possible solutions**
We can take the error, and just move it elsewhere

**Screenshots**
![Безымянный](https://user-images.githubusercontent.com/41551327/120706618-fef2f680-c4c1-11eb-8956-c2af71a649d3.png)

**Operating System:**
 - OS: Window 10

**Additional context**
The error doens't stop from using the launcher.

**Comment by paper5375** [comment]
I also have this issue, also on Windows. I also stopped being able to manage packs about the time this issue came up. If I right click an instance and click "Manage", a blue screen is all I get. Not sure if it's related.

**Comment by snsangston** [comment]
I am having this exact issue starting same time frame.  trying installing an older version of gdlauncher and still the same issue.  was liking this new launcher but may abandon it due to obvious issue and it doesn't look like any fixes have been mentioned for it.

and with mine, the issue makes the launcher inoperable, it force closes the launcher as soon as it fully opens.

**Comment by paper5375** [comment]
This is probably an upstream [Electron](https://github.com/electron/electron) issue that will be fixed on their end.

**Comment by snsangston** [comment]
> This is probably an upstream [Electron](https://github.com/electron/electron) issue that will be fixed on their end.

Maybe I'll put my save back in this launcher after it's fixed, or maybe I'll leave it in the more reliable launcher.  Hmmm

**Comment by blarfoon** [comment]
This issue is related to nodeJS. Did you try to reinstall the latest 1.1.8 version?

**Comment by KnewOne** [comment]
Reinstalled again and it seems that the issue is no more. For me, at least
