### ISSUE TITLE
Please add Modrinth support. 

### ISSUE THREAD

**Issue by toErIpNid** [gorilla-devs/GDLauncher#931]
**Is your feature request related to a problem? Please describe.**
GDLauncher is incapable of both browsing and pulling mods from the Modrinth site, an opensource mod hosting service which has exclusive mods unavailable anywhere else. It would be nice if there was support for it. 

**Describe the solution you'd like**
Adding support for the browsing and downloading of Modrinth mods. 

**Describe alternatives you've considered**
Without support, people would have to use technic to make their packs for other people due to them not downloading the required mods from Modrinth.

**Additional context**

**Comment by Mari023** [comment]
somewhat related to this: #768 #862

**Comment by Eskaan** [comment]
Duplicate of #768
