### ISSUE TITLE
Java 16 installation for versions that support or require java 16.

### ISSUE THREAD

**Issue by sagorigithub** [gorilla-devs/GDLauncher#932]
**Is your feature request related to a problem? Please describe.**
When you try to launch a 1.17 snapshot through Gdlauncher it fails to launch due to Gdlauncher using java 8 and 1.17 using java 16
**Describe the solution you'd like**
Automatically install java 16 for 1.17 and add an option to use java 16 for versions that support it.
**Describe alternatives you've considered**
Gdlauncher could automatically install java 16 through the automatic java setup but this would cause some issues for older versions of forge that require java 8.
**Additional context**

**Comment by hypherionmc** [comment]
Support has now been added in 1.1.12+
