### ISSUE TITLE
Magiculture 1 is broken.

### ISSUE THREAD

**Issue by SerketTheScorpion** [gorilla-devs/GDLauncher#936]
I created a server running the Magiculture modpack, but when I downloaded and attempted to run Magiculture via GD Launcher, it gave some odd errors. First, it said that I needed to add Baubles 1.7.10 - 1.0.1.10.jar to the mods folder. After closing the window the telling me to get Baubles, I receive "Uncaught Fatal Exception code: 1."  I didn't think too much of it, and added Baubles to the mods folder. I attempted to launch the pack again, and was met with the same error code. "Uncaught Fatal Exception code: 1" "Exception in thread "main"

After that, I checked the instances info through the launcher, and discovered that it was on version 2.0.2. I clicked Download Latest, and it gave me the wrong version. So, I updated the instance to version 2.0.3. The instance remained at version 2.0.2 after the update. I attempted to launch it, and was met with the same error code, even after Baubles was removed by the update. 

There's no crash log or anything. No info I can get from the launcher or my files. At this point, with everybody in my Discord wanting to play the pack, and everybody receiving the same error code, the pack and server are unplayable. 

The error should be as simple to replicate as, downloading the latest version of Magiculture. It will download a version below latest, and it will tell you to add Baubles to the pack upon launch. After that, it'll just give you "Uncaught Fatal Exception code: 1" until the end of time.

**Comment by RemagOfficial** [comment]
its a pack issue, the curseforge launcher has the exact same issue

**Comment by SerketTheScorpion** [comment]
Dang. Thank you for knowing what was wrong at least.
