### ISSUE TITLE
Version 1.17 unsupported. Wrong java version

### ISSUE THREAD

**Issue by balloonhead** [gorilla-devs/GDLauncher#940]
**Describe the bug**
Cannot launch MC Version 1.17 because it says java version is to old. 

**To Reproduce**
1. Install MC Vanilla 1.17
2. try to start it with
3. Error: Uncaugth Fatal Exception code 1

**Expected behavior**
Starting MC 

**Possible solutions**
Add an option to install the correct (newer) Java version for MC 1.17

**Screenshots**
![2021-06-13 08_58_41-GDLauncher](https://user-images.githubusercontent.com/37435752/121798439-a8ef2300-cc26-11eb-9edd-6dda9fce3049.png)

**Operating System:**
 - OS: [e.g. Windows]
 - Version [e.g. 10]

**Additional context**

**Comment by AwesomeKalin** [comment]
There is a way around this. Manually install it for now.

**Comment by AshtakaOOf** [comment]
right click the instance < custom java path < and go find java 16 in your system file (good luck)

**Comment by ghost** [comment]
Here is JDK 16: https://www.oracle.com/java/technologies/javase-jdk16-downloads.html
After you install it the Java Path should be `C:\Program Files\Java\jdk-16.0.1\bin\java.exe` on Windows.

**Comment by SaltSouls** [comment]
I'm getting the same problem on Linux, though after switching to Java 16 I get `Exception in thread "Render thread"` error.

**Comment by reburke** [comment]
The problem with this work around is that all the old (pre 1.17) pack throw this error


<img width="371" alt="gdl_java8onjava16" src="https://user-images.githubusercontent.com/10173582/125010956-c4323000-e024-11eb-888e-d74b6b00d4ef.png">

So its one or the other, not both

**Comment by ghost** [comment]
You need to set it in the instance settings, not the global config menu.

**Comment by reburke** [comment]
oops my bad

**Comment by balloonhead** [comment]
You dont have to use Oracle. Just use OpenJDK instead.
[https://jdk.java.net/16/](https://jdk.java.net/16/)

**Comment by balloonhead** [comment]
It would be good if GDLauncher could install the OpenJDK package for the users.

**Comment by ghost** [comment]
> It would be good if GDLauncher could install the OpenJDK package for the users.

It already does, and I thought that I saw talks of plans to support 1.17 too... 

> You dont have to use Oracle. Just use OpenJDK instead.
> https://jdk.java.net/16/

Let's be honest OpenJDK is just JDK with an *Open* in the name to make it look like a big company is doing the right thing.

**Comment by urmet** [comment]
> Let's be honest OpenJDK is just JDK with an Open in the name to make it look like a big company is doing the right thing.

java was "given away" to the community a while ago and OpenJDK is now the reference implementation. so if Oracle's java and openjdk behaved differently, that means oracle java has a bug. there are many different big companies shipping their own special versions. openjdk is the most vanillaest version there is

best place to get java nowdays is actually https://adoptopenjdk.net/ not Oracle's jdk.java.net
[/offtopic]

and yes, I've seen the plans about autmatically installing java 16 as well to make using 1.17 packs less effort

**Comment by ghost** [comment]
@urmet I was just saying that they function in the same way and that it doesn't really matter where you get it. The worst issue with Java is memory management on Windows, in my experience OpenJDK has the same issues. It's not like OpenJDK is going to magically fix the issues with Java subprocess either. 
  
  In my eyes they are one and the same, I'll keep programming with JDK.  

Also some people don't know how to use OpenJDK.

**Comment by TheMarksmanXII** [comment]
> 
> 
> right click the instance < custom java path < and go find java 16 in your system file (good luck)

For Windows, the Java Path is: C:\Program Files (x86)\Minecraft Launcher\runtime\java-runtime-alpha\windows-x64\java-runtime-alpha\bin\java.exe

**Comment by ghost** [comment]
> > right click the instance < custom java path < and go find java 16 in your system file (good luck)
> 
> For Windows, the Java Path is: C:\Program Files (x86)\Minecraft Launcher\runtime\java-runtime-alpha\windows-x64\java-runtime-alpha\bin\java.exe

The path very well depends on your Java version. It seems you are using an alpha build, of sorts, in most cases it will be `C:\Program Files\Java\jdk-16.0.1\bin\java.exe`, unless (like in your case) you are using a different build (other then JDK 16.0.1). 

As of now, with the release of JDK 16.0.2 it should be `C:\Program Files\Java\jdk-16.0.2\bin\java.exe`.

**Comment by hypherionmc** [comment]
We added support for both Java 8 and 16 in the new releases
