### ISSUE TITLE
Microsoft login issue

### ISSUE THREAD

**Issue by ghost** [gorilla-devs/GDLauncher#952]
**Describe the bug**
When logging in with my Microsoft account I was met with an error code saying Error: network error

I'm unable to find the reason but a method to fix this would be greatly appreciated.
![image](https://user-images.githubusercontent.com/86176994/122663124-1500e800-d14d-11eb-8958-6fb09e2291df.png)

![image](https://user-images.githubusercontent.com/86176994/122663136-277b2180-d14d-11eb-9860-8f9947e398c3.png)

I'm unaware if this is a launcher problem or an internet problem

**Comment by Eskaan** [comment]
Duplicate of #759
