### ISSUE TITLE
ForgeSVC API limit change breaking built-in mod browser

### ISSUE THREAD

**Issue by Vonr** [gorilla-devs/GDLauncher#953]
**Describe the bug**
A supposedly recent change in the ForgeSVC API limit for their pageSize from 63 to 50 breaks GDLauncher's built-in mod browser by returning no data when the new limit is exceeded. This causes the GET request to return Error 400 Bad Request.

**To Reproduce**
1. Right click any instance
2. Click on Manage
3. Switch to the Mods tab
4. Click on Add Mod
5. Notice that no mods are shown and typing anything in the search bar causes GDLauncher to crash immediately.

**Expected behavior**
Mods should be able to be shown and searched.

**Possible solutions**
Decrease the limit from 63 to 50, potentially making a setting in the event of future breaking changes.

**Screenshots**
![image](https://user-images.githubusercontent.com/24369412/122779925-eca9f280-d2e0-11eb-8731-4292a6183405.png)
![image](https://user-images.githubusercontent.com/24369412/122779972-f7fd1e00-d2e0-11eb-81f6-f2a840e9e993.png)

**Operating System:**
 - OS: [e.g. Linux Mint]
 - Version [e.g. 20.1]

**Additional context**
This is likely an issue caused by CurseForge; however, GDLauncher should still aim to address this so as to fix key functionality.

**Comment by natrow** [comment]
I'm also having this exact issue, also happens when switching from "Featured" mods to anything else.

Edit: I'm on windows 10, most recent version btw

**Comment by natrow** [comment]
Your solution worked, changing
```const itemsNumber = 63; ```
to
```const itemsNumber = 50;```

in `src/common/modals/ModsBrowser.js` fixed the issue for me.

**Comment by Vonr** [comment]
Good to know!

**Comment by Vonr** [comment]
It appears that the issue has been fixed by Ladvace. As such, I will close the issue for now.
