### ISSUE TITLE
Crashing when searching for mods

### ISSUE THREAD

**Issue by PassiveLemon** [gorilla-devs/GDLauncher#956]
**Describe the bug**
1. It fails to find any mods.
2. If you search for anything, it crashes.

**To Reproduce**
1. Click 'manage' on your modpack
2. Click 'mods' and then 'add mods'
3. See first error.
4. Type anything into the search and then see the crash.

**Expected behavior**
It finds the supported mods and doesn't crash

**Possible solutions**
Some ideas of how you would solve this issue, if possible
No idea.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/72527881/122799247-7d57e280-d28f-11eb-9527-9e80a3173e2e.PNG)
![Capture1](https://user-images.githubusercontent.com/72527881/122799249-7f21a600-d28f-11eb-93e2-fa647c506256.PNG)

**Operating System:**
 - OS: Windows
 - Version 20H2

**Additional context**
It only happened today. Ive reinstalled the launcher and the prepackaged Java but that didn't work.
I can circumvent this by just downloading the mods from curseforge and then adding them to the modpack folder but i shouldn't have to do that.

**Comment by Sar4h-3** [comment]
Can confirm with the latest Stable version of GD (1.1.10)

**Comment by Charcadet** [comment]
Duplicate of: https://github.com/gorilla-devs/GDLauncher/issues/953

Existing pull request to fix this issue: https://github.com/gorilla-devs/GDLauncher/pull/955

**Comment by GlitchSlayed** [comment]
fixed
