### ISSUE TITLE
Crash on Ubuntu 18.04

### ISSUE THREAD

**Issue by zabi94** [gorilla-devs/GDLauncher#96]
**Describe the bug**
App won't launch. Launching from console shows the attached error output

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Version 0.7.2

**Additional context**
[error.log](https://github.com/gorilla-devs/GDLauncher/files/2512194/error.log)

**Comment by blarfoon** [comment]
I think it's fixed by [this](https://github.com/gorilla-devs/GDLauncher/commit/6b68cef6c1ff684fd210b4a281aa22e5e0d1bb67).
 If this didn't solve your issue, I'll reopen this.
