### ISSUE TITLE
Fabric modpacks will not download from Curseforge

### ISSUE THREAD

**Issue by Madis0** [gorilla-devs/GDLauncher#961]
**Describe the bug**
Fabric modpacks still don't download properly from Curseforge, despite #949. 

**To Reproduce**
1. Click on +
2. Go to CurseForge tab
3. Search for "Fabulously Optimized"
4. Install 2.0.0b3 or newer
5. The install screen will loop indefinitely and only `background.png` and `manifest.json` will download.

**Expected behavior**
Expected the pack to fully download 

**Possible solutions**
Check for more issues with the Fabric format of Curseforge modpacks

**Screenshots**
N/A

**Operating System:**
 - OS: Manjaro 21.0.7
 - Version: GDL v1.1.11

**Additional context**
Manually created Fabric instances work fine as I have Java 16.

**Workaround: download the pack from Curseforge as a ZIP, in GDLauncher press + -> Import Zip -> Browse.**

**Comment by Eskaan** [comment]
> despite 949

As far as I know, we are suporting forge Modpacks fine through jumploader.
The mentioned Merge was only a fix for the latest changes in the fabric `yarn` property. Just tested a random Fabric modpack and it installed and started properly whitout any issues.

**Comment by Madis0** [comment]
Well, what about 1.17? Jumploader will not port to 1.17 because Curseforge added official support.

**Comment by Eskaan** [comment]
What? I dont understand. 
When curseforge **dindn´t** added support we cant help you, thats curseforges fault but thats not what you said right?

**Comment by Madis0** [comment]
Curseforge added support for proper Fabric modpacks, therefore Jumploader has dropped support for the mod and will not update to 1.17.
So if GDLauncher wants to support Fabric modpacks at all in the near future, it will have to support the new format for it (instead of just expecting Jumploader).

**Comment by Eskaan** [comment]
Console at creating the Instance:
 https://gist.github.com/Code-Ac/fbc36cd8835ec25cc25471c6acb8cb12

**Comment by alorg** [comment]
Hi I am having the same issue as Madis0 but I am on Windows 10, I am having the exact results only getting the same 2 files downloaded and an infinite loop install screen. Any and all assistance would be much appreciated. Thanks in advance

**Comment by urmet** [comment]
strange thing is that downloading the pack zip from curseforge and doing "import zip" on it works just fine. it's only direct curseforge install that's broken.

**Comment by localzuk** [comment]
Can confirm I'm seeing this too with all 1.17 fabric packs - the launcher simply shows the animation of the modpack name, only downloads a png file and manifest file and doesn't get any further. 

If I download the zip file from the Curseforge site and then import it into GD Launcher, it installs it correctly.

**Comment by Szum123321** [comment]
Can confirm the same issue

**Comment by SiongSng** [comment]
I also encountered this issue

**Comment by Madis0** [comment]
I've found a workaround for the time being: download the CF pack as a zip and import it as a new instance.
Edit: oops, missed the existing comments stating that

**Comment by urmet** [comment]
just like I said 4 comments/more than a week ago

**Comment by kevinoconnor7** [comment]
I added support for importing Fabric-based zip files in #949, however, when importing via the curseforge browser it just assumes all modpacks are forge based: https://github.com/gorilla-devs/GDLauncher/blob/67e61cc76c36d4e17caf61346ef641f013870448/src/common/modals/AddInstance/CurseForgeModpacks/ModpacksListWrapper.js#L89

I'll throw together something that will detect the loader type based on the manifest instead.
