### ISSUE TITLE
Game uses integrated GPU instead of the dedicated GPU.

### ISSUE THREAD

**Issue by arjuns500** [gorilla-devs/GDLauncher#969]
**Describe the bug**
When Minecraft starts with NVIDIA Optimus enabled, the laptop uses the integrated GPU instead of the NVIDIA 
GPU..

**To Reproduce**
1. Start any instance

**Expected behavior**
Game runs with the dedicated graphics unit.

**Actual behavior**
Game uses the integrated GPU, leading to less performance.

**Operating System:**
 - OS: Windows
 - Version 10

**Additional context**
Laptop has NVIDIA GTX 1650.
NVIDIA Optimus can be toggled, but without it, laptop has worse battery

**Comment by AshtakaOOf** [comment]
My laptop has dedicated gpu used for everything but you can make use of nvidia control panel to choose which graphics card you want to use

**Comment by randomguyingithub** [comment]
> 
> 
> My laptop has dedicated gpu used for everything but you can make use of nvidia control panel to choose which graphics card you want to use

The problem is if you manual switch as Original Poster said it would has worse battery if you forgot to switch back.

> NVIDIA Optimus can be toggled, but without it, laptop has worse battery

**Comment by arjuns500** [comment]
@randomguyingithub I belive that @AshtakaOOf is talking about the fact that you can configure executables to run with a specific gpu.

However, I have not been able to find the correct executable.
Executables I have tried: `GDLauncher.exe` `javaw.exe`

**Comment by randomguyingithub** [comment]
> 
> 
> @randomguyingithub I belive that @AshtakaOOf is talking about the fact that you can configure executables to run with a specific gpu.
> 
> However, I have not been able to find the correct executable.
> Executables I have tried: `GDLauncher.exe` `javaw.exe`

just in case, do you point to right java.exe? since it seems gdlauncher use the java.exe (not javaw.exe) inside the gdlauncher folder
you can check by toggle custom java path in instance.
in my case:
{gd launcher path}\java\8u242-b08\bin\java.exe

**Comment by arjuns500** [comment]
Yes, I have just tried it, and it does not work.

**Comment by AshtakaOOf** [comment]
i also tried but the only way i can use my dedicated gpu with minecraft is to activate the dedicated gpu in nvidia control panel and deactivate it after playing

**Comment by TOLoneWolf** [comment]
From discord.  
gdl on windows creates its temp path on launch of mc and the removes it after it closes.  
If using a different java not installed by gdl the path should be the normal file path and not this messed up symlinked one.  
![image](https://user-images.githubusercontent.com/8376628/123547429-5c2b4200-d726-11eb-90e7-2a1ad94519e7.png)

**Comment by arjuns500** [comment]
> From discord.
> gdl on windows creates its temp path on launch of mc and the removes it after it closes.
> If using a different java not installed by gdl the path should be the normal file path and not this messed up symlinked one.
> ![image](https://user-images.githubusercontent.com/8376628/123547429-5c2b4200-d726-11eb-90e7-2a1ad94519e7.png)

Thanks, it worked!
Could this be clarified in any documentation?
