### ISSUE TITLE
Problem With Engineer's Life 2

### ISSUE THREAD

**Issue by MasterNoLife** [gorilla-devs/GDLauncher#979]
Recently started this modpack was having fun but I've had this happen twice now. Ill save and quit when im done playing perfectly fine go to work come back home and open the GDLauncher then the mod pack which again all works perfectly, eceot noe when i try to load into the world I get a single frame of being in my house then BAM im slapped with this error From GDL 
"Error: signal exits Code:4294967295
AL lib: (EE) alc_cleanup: 1 Device not closed"
Heres the crash reports from my game, I'd really appriciate any help, really i have no idea anything about coding or fixing modpacks normally id just stop playing but ive put a couple hours into this world and id really like to continue it lol.
[crash-2021-07-05_11.55.29-server.txt](https://github.com/gorilla-devs/GDLauncher/files/6765698/crash-2021-07-05_11.55.29-server.txt)
[crash-2021-07-05_11.59.30-server.txt](https://github.com/gorilla-devs/GDLauncher/files/6765699/crash-2021-07-05_11.59.30-server.txt)
[crash-2021-07-05_12.04.33-server.txt](https://github.com/gorilla-devs/GDLauncher/files/6765700/crash-2021-07-05_12.04.33-server.txt)
[crash-2021-07-05_12.09.14-server.txt](https://github.com/gorilla-devs/GDLauncher/files/6765701/crash-2021-07-05_12.09.14-server.txt)
[crash-2021-07-05_12.18.09-server.txt](https://github.com/gorilla-devs/GDLauncher/files/6765702/crash-2021-07-05_12.18.09-server.txt)

**Comment by MasterNoLife** [comment]
the only thing ive done to this pack was add optifine but ive been playing with it for two days with no issues, other then that its the base modpack.

**Comment by CmdrNorthpaw** [comment]
Those crashes mean a corrupt world. This isn't an issue with GDLauncher.

**Comment by hypherionmc** [comment]
Yeah this isn't an issue with GDLauncher. It's an issue with a mod/corrupt world
