### ISSUE TITLE
Exporting Remembers Last Chosen Location (Request)

### ISSUE THREAD

**Issue by Rensik** [gorilla-devs/GDLauncher#981]
**Is your feature request related to a problem? Please describe.**
When exporting profiles/packs, GDL does not remember the last choice of export location.

**Describe the solution you'd like**
When exporting a profile or pack, GDL remembers which folder location one last used.

**Describe alternatives you've considered**
A default export location is decided by GDL upon exporting a profile or pack instead of requiring the user to choose a location.

**Additional context**
N/A

**Comment by huantianad** [comment]
Duplicate of #588.

**Comment by Rensik** [comment]
They say in #588 that the Instance Folder is chosen by default. This is still not the case. We still have to manually choose a location for every export. I would at least like a default location chosen.

**Comment by Eskaan** [comment]
Read it.
 > Make the launcher remember my previous export location.

**Comment by Eskaan** [comment]
Duplicate of #588
