### ISSUE TITLE
Option to launch JARs with automatically downloaded Java

### ISSUE THREAD

**Issue by brawaru** [gorilla-devs/GDLauncher#982]
**Is your feature request related to a problem? Please describe.**

Non-technical users have a very difficult time understanding what they have to do to obtain mods like OptiFine. When talking to my friends, I found that Java is one of the biggest issues for them, since they don't know how to install it (and scared of doing it — rightfully so, nobody wants to deal with adware) or sometimes they can't just do that (managed PCs without admin access).

**Describe the solution you'd like**

GDLauncher installs locally without requiring admin access and so does the Java it downloads. It'd be convenient if there was a small shortcut that allowed to launch JAR files right from the launcher. This can be a single button that prompts the open file dialog and after the file is selected, it doesn't do much, just executes `javaw -jar {selectedFile}`. Warning can be made that running arbitrary JAR files might be dangerous.

**Describe alternatives you've considered**

- Guide users to where the launcher's downloaded Java is located, how to make a `javaw -jar` shortcut and drop JAR file to launch it. This is proven to be difficult, non-tech users are by some reason overcomplicate everything — not to blame them; so even navigating to that directory could be a huge pain already (‘what's directory?’).
- Guide users to install Forge / Fabric and then also how to install OptiFine and OptiFabric mods. Doing so can result in overhead and loss of possibly gained performance. Again, this involves complex steps like downloading mod files, creating `mods` in some profile directory, aaand we lost them.
- Ask for auto-install of OptiFine. This technically can be done by observing how OptiFine installs itself, but might be discouraged by the OF developer. Plus there seems to be no reliable way to automate its download (?). Active issue: #750.

**Additional context**

This issue is not just about OptiFine (although that it benefits from this the most) but any tools for Minecraft (and not only) that might require Java to run.

**Comment by Eskaan** [comment]
Duplicate of #616

**Comment by Eskaan** [comment]
But thanks for telling us ❤️
