### ISSUE TITLE
1.17 crashes

### ISSUE THREAD

**Issue by GameTec-live** [gorilla-devs/GDLauncher#984]
**Describe the bug**
The launcher crashes, when installing a vanilla version of 1.17

**To Reproduce**
1. create a vanilla 1.17 instance
2. Click on play
3. See error

**Expected behavior**
It just starts up like with every other version

**Possible solutions**
no idea

**Operating System:**
 - OS: WIndows
 - Version 10

**Comment by urmet** [comment]
you have given almost zero useful information, but it looks like a duplicate of #940

**Comment by GameTec-live** [comment]
Sry didnt see issue #940
