### ISSUE TITLE
Launcher will not let me change release channel

### ISSUE THREAD

**Issue by reburke** [gorilla-devs/GDLauncher#987]
**Describe the bug**
When I try to change the release channel for the launcher is will not save the change

**To Reproduce**
Click Settings "Gear"
Change Release channel "First setting from stable to beta 
exit out of settings
go back into settings and you will see it has revered to stable

**Expected behavior**
The setting will save and the launcher will update to the beta if there is one

**Possible solutions**
Logs show a type missmatch

Uncaught (in promise) TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (1)

**Screenshots**
full log entry
asyncToGenerator.js:6 Uncaught (in promise) TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received type number (1)
    at writeFile (fs.js:1436)
    at e (graceful-fs.js:139)
    at Object.e.writeFile (graceful-fs.js:136)
    at index.js:8
    at new Promise (<anonymous>)
    at Object.writeFile (index.js:7)
    at General.js:391
    at l (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)

**Operating System:**
 - OS: Windows 10 
 - Version 21H1

**Additional context**

**Comment by reburke** [comment]
[release channel.log](https://github.com/gorilla-devs/GDLauncher/files/6827911/release.channel.log)

**Comment by MacaylaMarvelous81** [comment]
Same thing happening to me.

**Comment by hypherionmc** [comment]
Fixed in release 1.1.12+
