### ISSUE TITLE
GDLauncher not finding file paths correctly.

### ISSUE THREAD

**Issue by Splitzen** [gorilla-devs/GDLauncher#991]
**Describe the bug**
"Windows cannot find '\C:\_gdl\instances\\*any vanilla or mod instance*\resourcepacks\'. Make sure you typed the name correctly, and then try again."
File error across all instances when trying to open resource pack folder or shader folder from inside minecraft while using GDLauncher. I can check the file path manually and do find the files.

**To Reproduce**
1. Launch any instance using GDLauncher
2. Go to options then resource packs
3. Click "Open resource pack folder"

**Expected behavior**
Resource Pack should open normally.

**Operating System:**
 - OS: Windows
 - Version [10 Pro - 20H2 - 19042.1110]

**Comment by c-sig** [comment]
`\C:_gdl\instances\any vanilla or mod instance\resourcepacks`

Is \C:_gdl\ intentional? If yes, this is your problem.

**Comment by WolfBV** [comment]
Were you able to resolve your issue?

**Comment by Eskaan** [comment]
I don't think this issue is fixed yet. I would guess this is an issue with the symlink option in the settings. It might be worth a try toggling this setting and trying again.

This will likely not be resolved in the near future, as I (the only one at least maintaining this project atm) am using Linux as OS.

**Comment by WolfBV** [comment]
Uninstalled gdlauncher after using the Windows .exe setup of 1.1.30, tried the Windows portable zip and the issue no longer occurs.

Edit: Issue returned, will just have to work around it by opening the instance folder and putting resource packs into the resourcepacks folder.
