### ISSUE TITLE
Linux: Game opens as a GDLauncher window

### ISSUE THREAD

**Issue by pm065** [gorilla-devs/GDLauncher#992]
**Note: Apologies if this has already been reported. I'm not sure how to phrase this in search, so I can't find any other similar issues.**

Essentially, when I launch the game through GDL, it opens Minecraft as a GDL window.
Screenshot:
![image](https://user-images.githubusercontent.com/81559564/126143416-85c1ad00-722c-40c0-a81e-4a22b93a3f04.png)
Note how there are two GD windows; one is the launcher, one is the game.

This is slightly annoying when I click out of the game to e.g. access VSCode to edit my KubeJS files (I prefer not playing in fullscreen) as I have to click twice to access it again. I admit this complaint is possibly the most lazy in the universe. Also, my custom modpack icon doesn't display :(

I can't really remember when this started to happen, but it definitely wasn't from the beginning, so I must have done something somewhere to cause this. I think it started after restarting following an Ubuntu update?

It's worth noting that this is the unofficial Snap version. Could that be the issue?

Reproduction:
1. ??? something ???
2. Open GDLauncher for Linux
3. Run any instance
4. Note how the game opens as if it was another GDLauncher window

OS:
Ubuntu 21.04 (Hirsuite) with GNOME Desktop

Other than this and a few other issues already reported, I'm 100% happy with GDLauncher. I switched from MultiMC after finding out this could download mods straight from the launcher, which I feel is one of MMC's shortcomings...

**Comment by Mari023** [comment]
are you using the appimage or the .deb?

**Comment by pm065** [comment]
The unofficial Snap from the Snap Store, which is likely the issue. I
should probably change to the .deb, will I be able to easily transfer my
data? Thanks for the quick response :)

**Comment by Mari023** [comment]
unless snaps do something completely stupid to store data, yes.
it should be stored in ~/.config/gdlauncher_next
if it is stored there, the .deb should just find it 
I am not sure if uninstalling the snap would delete your data, so better make a backup :)

**Comment by pm065** [comment]
Alright, thanks. If using the .deb fixes the issue, I'll close this.

EDIT: Apparently, snaps DO do something stupid. It's stored in ~/.var/app/io.gdevs.GDLauncher/config/gdlauncher_next. I'll just move it into ~/.config/gdlauncher_next.

**Comment by pm065** [comment]
Okay, I got the .deb, and the issue is resolved. Although this isn't related, I have another issue; two actually. One is an instance of #411 in the package version, the other is that the package is marked as proprietery when I know it isn't:

![image](https://user-images.githubusercontent.com/81559564/126287460-f3c1e44f-ce4a-42bb-b0ce-f3cc31f69370.png)
