### ISSUE TITLE
None of the 1.17 Fabric modpacks can be installed

### ISSUE THREAD

**Issue by Hancapo** [gorilla-devs/GDLauncher#997]
Whenever I try to download any CurseForge 1.17 Fabric ModPack the instance creation never ends; infinite loop.

GDLauncher version: 1.1.11

**To Reproduce**
1. Go to 'Add New Instance'
2. Click on CurseForge tab
3. Download any 1.17 Fabric Modpack.

**Expected behavior**
Install it as any modpack prior to 1.17

**Operating System:**
 - OS: Windows 10
 - Version: 10
 - Java version: OpenJDK 16.0.2_windows-x64
 - RAM: 16GB DDR4
 - Processor: R5 3600

**Comment by Eskaan** [comment]
- Please rename the issue, this name is very confusing 
 - This is a known issue whit Fabric as whit 1.17.
 - Please provide error logs next time
 - This is a duplicate of #997 and #940, will be fixed whit the next version and this pull: #993 - please close.

**Comment by Hancapo** [comment]
> * Please rename the issue, this name is very confusing
> * This is a known issue whit Fabric as whit 1.17.
> * Please provide error logs next time
> * This is a duplicate of [None of the 1.17 Fabric modpacks can be installed #997](https://github.com/gorilla-devs/GDLauncher/issues/997) and [Version 1.17 unsupported. Wrong java version #940](https://github.com/gorilla-devs/GDLauncher/issues/940), will be fixed whit the next version and this pull: [Java 16 support #993](https://github.com/gorilla-devs/GDLauncher/pull/993) - please close.

I changed the name for a better understanding.

This issue is not a duplicate of the known problem with Java 16, as I said it has to do with downloading any available 1.17 modpack.

**Comment by Eskaan** [comment]
But it’s well known on our Discord server. Also I have to correct me, I showed the wrong one, I mean #961

**Comment by Eskaan** [comment]
You can leave a comment there, but we are aware of this issue and I think we already fixed it - you just have to wait for the latest update or download the latest build artifact

**Comment by Eskaan** [comment]
The update will be there whit the end of the week, if you want it now go there: https://github.com/gorilla-devs/GDLauncher/pull/980/checks?check_run_id=3037462927 click on artifacts and download it for your os

**Comment by Eskaan** [comment]
Whit the update will also be the 1.17 support

**Comment by Dax911** [comment]
Can confirm. Having no issues in 1.17 or 1.17.1 on cpu or gpu simulated hardware. (Fedora 34) 

Thanks for this super cool launcher. Can't believe I've never heard of it before. I stumbled across it in my package manager. ❤️

**Comment by Memeologisty** [comment]
When is the GDLauncher update that fixes this coming out?
